tracing-attributes/src/lib.rs, tracing-attributes/tests/err.rs, tracing-attributes/tests/instrument.rs
This backports PR #1233 to v0.1.x. This isn't *just* a simple cherry-pick
because the new tests in that branch use the v0.2.x module names, so
that had to be fixed. Otherwise, though, it's the same change, and I'll go
ahead and merge it when CI passes, since it was approved on `master`.
Currently, using `#[instrument(err)]` on a function returning a `Result`
with an `impl Trait` in it results in a compiler error. This is because
we generate a type annotation on the closure in the function body that
contains the user function's actual body, and `impl Trait` isn't allowed
on types in local bindings, only on function parameters and return
types.
This branch fixes the issue by simply removing the return type
annotation from the closure. I've also added tests that break on master
for functions …
=> attributes: fix `#[instrument(err)]` with `impl Trait` return types

tracing-futures/CHANGELOG.md, tracing-futures/Cargo.toml, tracing-futures/README.md, tracing-futures/src/lib.rs
- Updated `pin-project` dependency to 1.0 ([#1038])
- Several documentation fixes and improvements ([#832], [#911], [#913],
[#941], [#953], [#981])
[#1038]: https://github.com/tokio-rs/tracing/pulls/1038
[#832]: https://github.com/tokio-rs/tracing/pulls/832
[#911]: https://github.com/tokio-rs/tracing/pulls/911
[#913]: https://github.com/tokio-rs/tracing/pulls/913
[#941]: https://github.com/tokio-rs/tracing/pulls/941
[#953]: https://github.com/tokio-rs/tracing/pulls/953
[#981]: https://github.com/tokio-rs/tracing/pulls/981
=> futures: prepare to release 0.2.5

tracing/src/macros.rs, tracing/tests/macros.rs
This pr fixes the logging macros to accept syntax like
`info!(target: "test", ?value)`. While this works without the explicit
`target`, it did not worked with the `target` up to now. Besides that
the macros also used from wrong levels in certain branches.
=> Fix logging macros

tracing-attributes/src/lib.rs, tracing/src/lib.rs
The `instrument` macro does not explain the syntax that can be used and
the main tracing docs only say that this syntax is valid for `span` and
`event` macros.
=> Fixes a typo and adds a note about the supported field syntax

tracing/src/macros.rs, tracing/tests/macros.rs
This backports #1239 from `master`.
This PR fixes the event macros to accept syntax like
`info!(target: "test", ?value)`. While this works without the explicit
`target`, it did not worked with the `target` up to now. Besides that
the macros also used from wrong levels in certain branches.
=> tracing: fix broken match arms in event macros (#1239)

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs, tracing/Cargo.toml
- Compiler error when using `#[instrument(err)]` on functions which
return `impl Trait` ([#1236])
[#1236]: https://github.com/tokio-rs/tracing/pull/1236
=> attributes: prepare to release v0.1.13

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
- **attributes**: Compiler error when using `#[instrument(err)]` on
functions which return `impl Trait` ([#1236])
- Fixed broken match arms in event macros ([#1239])
- Documentation improvements ([#1232])
Thanks to @bkchr and @lfranke for contributing to this release!
[#1236]: https://github.com/tokio-rs/tracing/pull/1236
[#1239]: https://github.com/tokio-rs/tracing/pull/1239
[#1232]: https://github.com/tokio-rs/tracing/pull/1232
=> tracing: prepare to release v0.1.24

tracing-log/src/lib.rs, tracing-log/src/log_tracer.rs
This branch adds a check against the current value of the max global
`LevelFilter` hint in `tracing_log`'s `LogTracer::enabled` method. This
should prevent `log::${LEVEL}_enabled!` from always returning `true`
when `tracing` is in use, fixing a performance issue when consuming
`log` records from tracing (see bytecodealliance/wasmtime#2662).
This does, however, mean `LogTracer::enabled` will always be called if
the max `log` level is not set. We can't determine whether we can set
`log`'s max level in `tracing_log`, since we don't know if subscribers
will change (resulting in the current max `tracing` level filter
changing), or if the current subscriber is set as the global default.
Higher-level code in `tracing_subscriber` can do this, though, in
`init()`, because it _does_ know that it's …
=> log: compare `log` record `Level`s against the max level

tracing-log/src/lib.rs, tracing-subscriber/src/subscribe.rs
Seems like we forgot to remove this? Since `TraceLogger` has been removed in `tracing-log`'s v0.1.1. Otherwise, this could bring confusion to those new to `tracing-rs`.
=> chore: remove legacy `TraceLogger` in docs

tracing-log/src/lib.rs, tracing-log/src/log_tracer.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/util.rs
Depends on #1247.
Since `tracing-subscriber`'s `init` and `try_init` functions set the
global default collector, we can use the collector's max-level hint as
the max level for the log crate, as well. This should significantly
improve performance for skipping `log` records that fall below the
collector's max level, as they will not have to call the
`LogTracer::enabled` method.
This will prevent issues like bytecodealliance/wasmtime#2662
from occurring in the future. See also #1249.
In order to implement this, I also changed the `FmtCollector`'s
`try_init` to just use `util::SubscriberInitExt`'s `try_init` function,
so that the same code isn't duplicated in multiple places. I also
added `AsLog` and `AsTrace` conversions for `LevelFilter`s in
the `tracing-log` crate. …
=> subscriber: set the max `log` `LevelFilter` in `init`

tracing-log/Cargo.toml, tracing-log/src/lib.rs, tracing-log/src/log_tracer.rs, tracing-subscriber/Cargo.toml, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/util.rs
This backports #1247 and #1248 to `v0.1.x`. Since this has already been approved, I'll just go ahead and rebase-merge this pending CI.
=> backport `tracing-log` fixes

tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/tests/fmt_max_level_hint.rs, tracing-subscriber/tests/registry_max_level_hint.rs
The `FmtCollector` type is missing a `Collect::max_level_hint`
method that forwards the inner stack's max level hint.
This fixes that, and adds tests.
=> subscriber: fix FmtCollector not forwarding max level 

tracing-log/src/lib.rs, tracing-subscriber/src/subscribe.rs
1. I believe we forgot to rename Context's generic type to `C`. 
2. Some docs look kind of messed up according to PR #1245.
So, this PR simply resolves those trivial issues.
=> chore: rectify Context's generic type name to “C”

tracing-log/src/lib.rs, tracing-log/src/log_tracer.rs, tracing-log/tests/log_tracer.rs, tracing-subscriber/tests/filter_log.rs
PRs #1247, #1248, and #1251 improve `tracing`'s behavior for the `log`
crate's `log_enabled!` macro when a max-level hint is set. However, this
*doesn't* get us correct behavior when a particular target is not
enabled but the level is permitted by the max-level filter. In this
case, `log_enabled!` will still return `true` when using `LogTracer`,
because it doesn't currently call `Collect::enabled` on the current
collector in its `Log::enabled` method. Instead, `Collect::enabled` is
only checked when actually recording an event.
This means that when a target is disabled by a target-specific filter
but it's below the max level, `log::log_enabled!` will erroneously
return `true`. This also means that skipping disabled `log` records in
similar cases will construct the `log::Record` struct …
=> log: forward `LogTracer::enabled` to the collector 

tracing/src/span.rs, tracing/tests/span.rs
This PR allows the following API:
```
let _guard = tracing::span!("foo").entered();
```
See https://github.com/tokio-rs/tracing/issues/zc for an extended
discussion.
This probably needs better docs, so that the people know that this API exists, but I would prefer to avoid further polishing the docs myself :)
Closes #1246
Closes #192
Closes #79
=> Simplify common case of immediately entering the span

tracing-log/src/lib.rs, tracing-log/src/log_tracer.rs, tracing-log/tests/log_tracer.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/tests/filter_log.rs, tracing-subscriber/tests/fmt_max_level_hint.rs, tracing-subscriber/tests/registry_max_level_hint.rs
This backports #1251 and #1254.
=> backport more log fixes from master

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
- **env-filter**: Fixed directives where the level is in mixed case
(such as `Info`) failing to parse ([#1126])
- **fmt**: Fixed `fmt::Subscriber` not providing a max-level hint
([#1251])
- `tracing-subscriber` no longer enables `tracing` and `tracing-core`'s
default features ([#1144])
- **chrono**: Updated `chrono` dependency to 0.4.16 ([#1189])
- **log**: Updated `tracing-log` dependency to 0.1.2
Thanks to @salewski, @taiki-e, @davidpdrsn and @markdingram for
[#1126]: https://github.com/tokio-rs/tracing/pull/1126
[#1251]: https://github.com/tokio-rs/tracing/pull/1251
[#1144]: https://github.com/tokio-rs/tracing/pull/1144
[#1189]: https://github.com/tokio-rs/tracing/pull/1189
Closes #1249
=> subscriber: prepare to release v0.2.16

tracing/src/span.rs, tracing/tests/span.rs
This backports PR #1252 from `master`. I'll go ahead and merge this 
pending CI.
* Simplify common case of immediately entering the span
This PR allows the following API:
```
let _guard = tracing::span!("foo").entered();
```
See https://github.com/tokio-rs/tracing/issues/1246 for an extended
discussion.
* Add missing inlines
This fns are monomorphic, so an `#[inline]` is necessary to alow
cross-crate inlining at all.
* improve method documentation
Co-authored-by: Eliza Weisman <eliza@buoyant.io>
=> tracing: simplify common case of immediately entering the span (#1252)

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs, tracing/src/span.rs
- `Span::entered` method for entering a span and moving it into a guard by value
rather than borrowing it ([#1252])
Thanks to @matklad for contributing to this release!
[#1252]: https://github.com/tokio-rs/tracing/pull/1252
=> tracing: prepare to release v0.1.25

tracing-subscriber/src/registry/extensions.rs, tracing-subscriber/src/registry/mod.rs, tracing-subscriber/src/registry/sharded.rs
There still a lot of docs and variables in the registry module that need to be rectified. This PR simply rename all old `layers` to `subscribers`.
=> subscriber: rename `layers` to `subscribers` in registry module

tracing-attributes/src/lib.rs
Since we bumped the **MSRV** to v1.42 already, it's time to remove `#![allow(unused)]`.
=> attributes: clean unused imports and variables

tracing-core/src/collect.rs, tracing-error/src/layer.rs, tracing-opentelemetry/src/layer.rs, tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/subscribe.rs
Resolves #1073, quoting from there:
> If we changed this to Option<NonNull<()>> we could benefit from niche optimization, saving us the option discriminant and making this return a single word pointer. That may in turn let us benefit from additional optimizations. This could make downcasting slightly faster.
I've made the change to the function signature and let rustc guide me through the process of fixing all callers. This was mostly straightforward but it is `unsafe` code so I'm not sure the changes here are correct.
=> downcast_raw returns NonNull

tracing-subscriber/Cargo.toml, tracing-subscriber/src/filter/env/field.rs
This commit changes `EnvFilter`'s field filters to use regexes which are
anchored at the beginning of the field's `fmt::Display` output, rather
than matching patterns which begin anywhere in the output. Essentially,
the field matching filters previously behaved as though all patterns
began with `.*?`, which is not the desired behavior.
This required an update to `matchers` v0.1.0, which adds an API for
constructing this type of pattern.
Fixes #1234
Closes #1269
=> subscriber: change `EnvFilter` to use anchored regexes

tracing-subscriber/src/reload.rs, tracing-subscriber/tests/reload_max_log_level.rs
This modifies the `tracing_subscriber::reload` layer to also set the
`log` crate's max level with the current max `tracing` level filter
after reloading. If reloading the subscriber caused the max `tracing`
level to change, this ensures that the change is propagated to the `log`
crate as well. In the case where the max level was made more verbose,
this will ensure that `log` records which were previously disabled are
enabled correctly; in the case where it was made less verbose, this
improve performance by not having to perfrom more costly filtering for
those `log` records.
The `log` max level is set only after rebuilding the callsite interest
cache, which is what sets the max `tracing` level filter. This ensures
that we pass the latest state to the `log` crate. …
=> subscriber: set `log` max level when reloading

examples/examples/opentelemetry-remote-context.rs, examples/examples/opentelemetry.rs, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/span_ext.rs, tracing-opentelemetry/src/subscriber.rs, tracing-opentelemetry/tests/trace_state_propagation.rs
This PR renames the following:
`tracing_opetelemetry::layer` to `tracing_opetelemetry::subscriber`
`tracing_opetelemetry::layer::layer()` to `tracing_opetelemetry::subscriber::subscriber()`
`tracing_opetelemetry::layer::OpenTelemetryLayer` to `tracing_opetelemetry::subscriber::OpenTelemetrySubscriber`
Related PR: #1015
=> opentelemetry: rename Layer to Subscriber

tracing-attributes/Cargo.toml, tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs
This draft PR aims to resolve #1219.
Tell me what you think ;)
It works with both the old and new version of `async-trait` (except for one doc test that failed previously, and that works with the new version). One nice thing is that the code is simpler (e.g.g no `self` renaming to `_self`, which will enable some simplifications in the future).
A minor nitpick is that I disliked the deeply nested pattern matching in `get_async_trait_kind` (previously: `get_async_trait_function`), so I "flattened" that a bit.
=> [tracing-attributes] future-proof the #[instrument] integration with async-trait

tracing-attributes/Cargo.toml, tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs
This backports #1228 from `master` to `v0.1.x`.
It works with both the old and new version of async-trait (except for
one doc test that failed previously, and that works with the new
version). One nice thing is that the code is simpler (e.g.g no self
renaming to _self, which will enable some simplifications in the
future).
A minor nitpick is that I disliked the deeply nested pattern matching in
get_async_trait_kind (previously: get_async_trait_function), so I
"flattened" that a bit.
Fixes  #1219.
=> attributes: update `#[instrument]` to support `async-trait` 0.1.43+

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs, tracing/Cargo.toml
- Compatibility between `#[instrument]` and `async-trait` v0.1.43 and
newer ([#1228])
Thanks to @nightmared for lots of hard work on this fix!
[#1228]: https://github.com/tokio-rs/tracing/pull/1228
=> attributes: prepare to release v0.1.14

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/mod.rs
This PR aims to remove a lot of construct boilerplate codes by adopting the `struct update syntax`.  If the [RFC 2528](https://github.com/rust-lang/rfcs/pull/2528)  gets merged and implemented, we can remove more. 😸
=> subscriber: change to `struct update syntax` when construct from self

tracing-subscriber/src/fmt/format/mod.rs
As far as I can tell, we are not relying on transparency anywhere, so
using this rather refined feature here is confusing.
=> Remove unnecessary transparent attribute

tracing-subscriber/src/fmt/fmt_subscriber.rs
The downstream crate is very restricted to do some format thing related to the current span. Because the `ctx` field of `FmtContext` provided by `FormatEvent::format_event()` is non-public to the third crates and we have no public method to get the current span.
Add a new public method called `current_span()` to delegate the method call to inner `ctx`.
Make two fields of `FmtContext` complete public rather than only public in the crate? Or don't this.
=> Add a public `current_span()` method for `FmtContext`

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/mod.rs
Fixes #1136.
Allows arbitrarily combining different FmtSpan events to listen to.
The idea is to allow any combination of `FmtSpan` options, such as the currently unachievable combination of `FmtSpan::NEW | FmtSpan::CLOSE`.
Make `FmtSpan` behave like a bitflag that can be combined using the bitwise or operator ( `|` ) while maintaining backward compatibility by keeping the same names for all existing presets and keeping the implementation details hidden.
=> Switch FmtSpan To a Combinable Bitflag

tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs
Fixes #1296.
I had forgotten to use all the input statements in #1228, so we would delete nearly all the statement of sync functions that return a boxed future :/
=> attributes: fix `#[instrument]` skipping code when returning pinned futures

tracing-subscriber/src/fmt/format/pretty.rs
This fixes #1212, where extra padding was written when logging with the
pretty formatter.
With this change we only write padding when we actually decide to write
a value but not when skipping a metadata value such as `log.file` or
`log.line`
=> subscriber: fix extra padding in pretty format

tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs
Currently, when the `Pretty` event formatter is being used, it does not change
its output when the `with_ansi` flag is set to false by the `CollectorBuilder`.
While this formatter is generally used in situations such as local development,
where ANSI escape codes are more often acceptable, there are some situations in
which this can lead to mangled output.
This commit makes some minor changes to account for this `ansi` flag when
formatting events using `Pretty`.
Becuase ANSI codes were previously used to imply the event level using colors,
this commit additionally modifies `Pretty` so that it respects `display_level`
when formatting an event.
Now, installing a subscriber like so...
```rust
tracing_subscriber::fmt()
.pretty()
.with_thread_names(true)
.with_ansi(false)
.with_level(true) …
```
=> subscriber: update pretty formatter for no ansi

tracing-subscriber/src/fmt/time/mod.rs
This backports #1103 to `v0.1.x`
I reckon this is a bug, and @samschlegel fixed this for ChronoUtc,
but not for ChronoLocal.
Closes #1271
=> subscriber: remove trailing space from ChronoLocal time formatter

tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs, tracing-subscriber/src/fmt/fmt_layer.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs, tracing-subscriber/src/fmt/mod.rs
This backports PRs #1289, #1282, #1290, #1297, #1275, #1277, and #1240 from the `master` branch to v0.1.x. This will let us publish new releases of `tracing-attributes` (with a fix for #1296) and `tracing-subscriber` (with several fixes & API additions).
I'll go ahead and rebase-merge this when CI passes
=> backport recent subscriber and attributes changes

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs, tracing/Cargo.toml
- `#[instrument]` on functions returning `Box::pin`ned futures incorrectly
skipping function bodies prior to returning a future ([#1297])
Thanks to @nightmared for contributing to this release!
[#1297]: https://github.com/tokio-rs/tracing/pull/1297
=> attributes: prepare to release v0.1.15

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
- **fmt**: `Pretty` formatter now honors `with_ansi(false)` to disable
ANSI terminal formatting ([#1240])
- **fmt**: Fixed extra padding when using `Pretty` formatter ([#1275])
- **chrono**: Removed extra trailing space with `ChronoLocal` time
formatter ([#1103])
- **fmt**: Added `FmtContext::current_span()` method, returning the
current span
([#1290])
- **fmt**: `FmtSpan` variants may now be combined using the `|` operator
for more granular control over what span events are generated
([#1277])
Thanks to new contributors @cratelyn, @dignati, and @zicklag, as well as
@Folyd, @matklad, and @najamelan, for contributing to this release!
=> subscriber: prepare to release 0.2.17

tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/benches/trace.rs
Understand the overhead added by recording OpenTelemetry data so that it can be minimized.
Add criterion benchmarks, initially tracking request/response style workloads (1 main span with 99 children).
This patch adds benchmarks for standard `tracing-opentelemetry` usage, as well as baselines for understanding the overhead specific to the usage of the otel tracer, and registry span access patterns.
=> opentelemetry: add preliminary benchmarks

tracing/README.md
This is a simple typo fix, where `tracing_subscriber` was written as `tracing_subscruber`.
=> docs: fix typo in README.md

tracing-core/src/field.rs, tracing-core/src/metadata.rs, tracing-core/src/span.rs, tracing-subscriber/src/fmt/mod.rs, tracing/src/span.rs, tracing/tests/support/field.rs, tracing/tests/support/span.rs
Clippy now warns about implementing `Into` rather than `From`, since
`From` automatically provides `Into` but `Into` does not provide `From`.
This commit fixes the direction of those conversions, placating Clippy.
Additionally, it fixes a redundant use of slice syntax that Clippy also
complained about.
=> chore: reverse the polarity of conversions, fix clippy

tracing-subscriber/tests/field_filter.rs
This branch changes the `field_filter_events` and `field_filter_spans`
tests in `tracing-subscriber` to be ignored by default, as they often
fail spuriously on CI.
The tests can still be run using
```shell
$ RUSTFLAGS="--cfg flaky_tests" cargo test
```
or similar.
=> chore: ignore flaky field filter tests

README.md
Fix a broken link for `#[instrument]`. Also, fix a minor typo (`initalized` -> `initialized`).
=> docs: fix a broken link (and minor typo) on README

tracing/src/span.rs
This was not fixed in #1335 because the `Into<Id> for Span` conversion
was removed in v0.2.x.
This should make clippy happy on v0.1.x.
=> tracing: reverse one more conversion

tracing-serde/src/fields.rs, tracing-subscriber/src/fmt/format/json.rs
Serializing a spans `on_ACTION` events, when no `fields` are set on the span, results in invalid JSON. This is because `serializier_map` was getting a size hint for `self.0.metadata().fields().len()` then serializing `self.0.fields.field_set()` instead. This resulted in the `fields` key being set to an empty object, then Serde serializes the k/v pairs from `field_set()`. This was causing an erroneous closing brace `}` to be added after the serialized fields.
This is discussed here: https://github.com/tokio-rs/tracing/issues/829#issuecomment-661984255
``` toml
[dependencies]
tracing = "=0.1.25"
tracing-serde = "=0.1.2"
tracing-subscriber = "=0.2.17"
```
``` rust
use tracing_subscriber::fmt::format::FmtSpan;
fn main() {
tracing_subscriber::fmt()
.json()
.with_span_events(FmtSpan::FULL) …
```
=> subscriber: fix `on_event` serialization when no fields set on span

README.md, tracing-opentelemetry/src/layer.rs, tracing-serde/src/fields.rs, tracing-subscriber/src/fmt/format/json.rs
This backports PRs #1314, #1337, and #1333 to `v0.1.x`.
The tests in #1333 had to be modified a bit because the test implementation has changed on v0.2.x
=> backport #1314, #1337, and #1333 to v0.1.x

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
=> opentelemetry: backport prepare for v0.12.0 release

tracing-subscriber/src/fmt/format/json.rs
@hawkw Thanks for the feedback in #1333. I've been AFK for the last week but I've updated the test based on your comments from the review. It allows better coverage of the span life cycle and is easier to read.
Ref: https://github.com/tokio-rs/tracing/pull/1333#pullrequestreview-623737828
=> subscriber: improve test for #1333

tracing/src/macros.rs
The following two patterns for the `event!()` are identical to each other, and the second one swapped the order of `$lvl` and `parent: $parent` which I don't think is correct.
```rust
(parent: $parent:expr, $lvl:expr, { $($fields:tt)* }, $($arg:tt)+ ) => (
$crate::event!(
target: module_path!(),
parent: $parent,
$lvl,
{ message = format_args!($($arg)+), $($fields)* }
)
);
(parent: $parent:expr, $lvl:expr, { $($fields:tt)* }, $($arg:tt)+ ) => (
$crate::event!(
target: module_path!(),
$lvl,
parent: $parent,
{ message = format_args!($($arg)+), $($fields)* }
)
);
```
I found the duplicated via [macro_railraod](https://github.com/lukaslueg/macro_railroad). Here is the diagram:
=> tracing: remove duplicated `event!()` macro pattern

tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/subscriber.rs, tracing-opentelemetry/src/tracer.rs
Allow users to set custom span status codes and messages to follow opentelemetry semantic conventions.
Support the status code and status message fields in `OpenTelemetrySubscriber`
Proposal to close #1346
=> subscriber: add span status fields

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs, tracing-subscriber/src/fmt/time/mod.rs
Currently, the default `Compact` and `Full` formatters in
`tracing-subscriber` will prefix log lines with a single space when
timestamps are disabled. The space is emitted in order to pad the
timestamp from the rest of the log line, but it shouldn't be emitted
when timestamps are turned off. This should be fixed.
This branch fixes the issue by skipping `time::write` entirely when
timestamps are disabled. This is done by tracking an additional boolean
flag for disabling timestamps.
Incidentally, this now means that span lifecycle timing can be enabled
even if event timestamps are disabled, like this:
```rust
use tracing_subscriber::fmt;
let subscriber = fmt::subscriber()
.without_time()
.with_timer(SystemTime::now)
.with_span_events(fmt::FmtSpan::FULL);
```
or similar.
I also added a new …
=> subscriber: remove space when timestamps are disabled 

tracing-core/src/span.rs, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/benches/trace.rs, tracing-opentelemetry/src/layer.rs, tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/tracer.rs, tracing-subscriber/src/fmt/fmt_layer.rs, tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/fmt/time/mod.rs, tracing/README.md, tracing/src/macros.rs
This cherry-picks a number of recent commits from `master` to v0.1.x:
* 14eee0a1 core: expose an accessor for the `FieldSet` on `Attributes` (#1331)
* 3b52afc5 subscriber: remove space when timestamps are disabled  (#1355)
* 466221c0 subscriber: add span status fields (#1351)
* d43f0e75 tracing: remove duplicated event macro pattern (#1352)
* 9db56141 subscriber: fix span data for new, exit, and close events (#1334)
* 2ae9f99c docs: fix typo in tracing/README.md (#1305)
* 1038d6db opentelemetry: add preliminary benchmarks (#1303)
=> misc. backports

tracing-core/src/dispatch.rs, tracing-subscriber/src/fmt/format/mod.rs
This PR simply fixes some cargo docs warnings.
=> chore: fix cargo docs warnings

tracing-subscriber/src/filter/env/directive.rs
Filtering log events using the `target[span{field=value}]=level` syntax doesn't work when the span name contains a special char.
This PR closes #1367 by adding dash support in span names.
=> subscriber: support special chars in span names

tracing-core/src/collect.rs
In some cases, users may wish to erase the type of a `Colelct`
implementation, such as when it is dynamically constructed from a
complex parameterized type. When doing so, it's important to ensure that
all trait methods with default implementations are properly forwarded to
the inner erased type. For example, if the type does not implement
`try_close`, but the inner erased collector does, then the the
collector will not be notified when spans close — which could result in
a memory leak.
To avoid potential footguns resulting from users implementing
type-erased collectors incorrectly, this branch adds a new `impl Collect
for Box<dyn Collect + Send + Sync + 'static>` in `tracing-core`, when
the `alloc` feature flag is enabled. This is also somewhat more
ergonomic than any solution in another …
=> core: add `Collect` impl for `Box<dyn Collect + ...>`

examples/examples/panic_hook.rs
It turns out that when using the global dispatcher, emitting tracing
events in a panic hook will capture the span in which the program
panicked. This is very handy for debugging panics! Thanks a lot to
@natemara for pointing this out to me on twitter --- I hadn't even
thought of it!
Since it isn't necessarily immediately obvious that this works, I
thought it would be nice to add an example.
=> tracing: add an example of `tracing` in a panic hook

tracing-core/src/collect.rs, tracing/tests/collector.rs
Users may wish to erase the type of a `Collect`
implementation, such as when it is dynamically constructed from a
complex parameterized type. PR #1358 added a `Collect` implementation
for `Box<dyn Collect + Send + Sync + 'static>`, allowing the use of
type-erased trait objects. In some cases, it may also be useful to share
a type-erased collector, _without_ using `Dispatch` --- such as when
different sets of `tracing-subscriber` subscribers are layered on one
shared collector.
This branch builds on #1358 by adding an `impl Collect for Arc<dyn
Collect + Send + Sync + 'static>`. I also added quick tests for both
`Arc`ed and `Box`ed collectors.
=> core: add `Collect` impl for `Arc<dyn Collect + ...>`

tracing/src/span.rs
The following code compiles failed:
```rust
use tracing;
fn main() {
let span = tracing::info_span!("my_span").entered();
tracing::info!(parent: &span, "test span");
}
```
```log
Compiling playground v0.0.1 (/playground)
error[E0277]: the trait bound `Option<Id>: From<&EnteredSpan>` is not satisfied
--> src/main.rs:6:5
|
6  |     tracing::info!(parent: &span, "test span");
|     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ the trait `From<&EnteredSpan>` is not implemented for `Option<Id>`
```
- `impl<'a> From<&'a EnteredSpan> for Option<&'a Id>`.
- `impl<'a> From<&'a EnteredSpan> for Option<Id>`
- Add `id()` method into `EnteredSpan`.
=> tracing: impl `From<EnteredSpan>` for `Option<Id>`

tracing-subscriber/src/lib.rs
The `tracing-subscriber::CurrentSpan` should be deprectead in `v0.2.x`.
Related PR #1320.
=> subscriber: deprecate `CurrentSpan`

examples/examples/panic_hook.rs, tracing-core/src/dispatcher.rs, tracing-core/src/subscriber.rs, tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing/src/lib.rs, tracing/src/span.rs, tracing/tests/subscriber.rs
This backports the following commits to `v0.1.x`:
* d4493a81 (HEAD -> eliza/backport-1368) docs: document span.in_scope() at top-level (#1344)
* 49461236 tracing: impl `From<EnteredSpan>` for `Option<Id>` (#1325)
* 5f68c71a core: add support for `Arc<dyn Subscriber + ...>`
* a94767a7 tracing: add an example of `tracing` in a panic hook (#1375)
* 1316eaf4 core: add `Subscriber` impl for `Box<dyn Subscriber + ...>` (#1358)
* e2eb1893 subscriber: support special chars in span names (#1368)
* 3c581270 chore: fix cargo docs warnings (#1362)
I'm gonna merge this when CI passes & then hopefully do some releases.
=> a bunch more backports

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md, tracing-core/src/lib.rs
- `Subscriber` impl for `Box<dyn Subscriber + Send + Sync + 'static>`
([#1358])
- `Subscriber` impl for `Arc<dyn Subscriber + Send + Sync + 'static>`
([#1374])
- Symmetric `From` impls for existing `Into` impls on `Current` and
`Option<Id>` ([#1335])
- `Attributes::fields` accessor that returns the set of fields defined
on a span's `Attributes` ([#1331])
Thanks to @Folyd for contributing to this release!
[#1358]: https://github.com/tokio-rs/tracing/pull/1358
[#1374]: https://github.com/tokio-rs/tracing/pull/1374
[#1335]: https://github.com/tokio-rs/tracing/pull/1335
[#1331]: https://github.com/tokio-rs/tracing/pull/1331
=> core: prepare to release v0.1.18

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
- **attributes**: Compatibility between `#[instrument]` and `async-trait`
v0.1.43 and newer ([#1228])
- Several documentation fixes ([#1305], [#1344])
- `Subscriber` impl for `Box<dyn Subscriber + Send + Sync + 'static>`
([#1358])
- `Subscriber` impl for `Arc<dyn Subscriber + Send + Sync + 'static>`
([#1374])
- Symmetric `From` impls for existing `Into` impls on `span::Current`,
`Span`, and `Option<Id>` ([#1335], [#1338])
- `From<EnteredSpan>` implementation for `Option<Id>`, allowing
`EnteredSpan` to be used in a `span!` macro's `parent:` field ([#1325])
- `Attributes::fields` accessor that returns the set of fields defined
on a span's `Attributes` ([#1331])
Thanks to @Folyd, @nightmared, and new contributors @rmsc and @Fishrock123 for
[#1227]: …
=> tracing: prepare to release 0.1.26

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
- Deprecated the `CurrentSpan` type, which is inefficient and largely
superseded by the `registry` API ([#1321])
- **json**: Invalid JSON emitted for events in spans with no fields
([#1333])
- **json**: Missing span data for synthesized new span, exit, and close
events ([#1334])
- **fmt**: Extra space before log lines when timestamps are disabled
([#1355])
- **env-filter**: Support for filters on spans whose names contain any
characters other than `{` and `]` ([#1368])
Thanks to @Folyd, and new contributors @akinnane and @aym-v for
contributing to  this release!
[#1321]: https://github.com/tokio-rs/tracing/pull/1321
[#1333]: https://github.com/tokio-rs/tracing/pull/1333
[#1334]: https://github.com/tokio-rs/tracing/pull/1334
[#1355]: https://github.com/tokio-rs/tracing/pull/1355
[#1368]: …
=> subscriber: prepare to release 0.2.18

tracing-core/src/field.rs
Impl `Value` for `&mut T` where `T: Value`. 
#1378 improve the `tracing::instrument` macro's recording behavior: 
all primitive types implementing the `Value` trait will be recorded as fields of that type instead of `fmt::Debug`. This PR is a prerequisite for those `&mut` function arguments to achieve that.
=> core: impl `Value` for `&mut T` where `T: Value`

tracing-attributes/src/lib.rs, tracing-core/src/event.rs, tracing-subscriber/src/subscribe.rs, tracing-tower/src/service_span.rs
This branch fixes some annoying new clippy lints no one cares about.
=> chore: fix clippy's awful new "inconsistent struct constructor" lint

tracing/src/lib.rs
The RAII pattern documentation has been moved.
Update the link to the document.
=> Fix link to RAII pattern document

examples/Cargo.toml, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/src/span_ext.rs, tracing-opentelemetry/src/subscriber.rs, tracing-opentelemetry/src/tracer.rs, tracing-opentelemetry/tests/trace_state_propagation.rs
Support the latest OpenTelemetry specification.
Update `opentelemetry` to the latest `0.14.x` release. Despite breaking changes upstream, no additional public API or behavioral changes are necessary in `tracing-opentelemetry`, but simplifications in the propagation of span information have removed the need for the current internal `CompatSpan` and custom parent context construction.
Performance has improved by ~30% on current benchmarks.
Resolves #1395, Resolves #1396
=> opentelemetry: update to otel 0.14.x

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
Changelog:
- Upgrade to `v0.14.0` of `opentelemetry` (#1394)
For list of breaking changes in OpenTelemetry, see the [v0.14.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0140).
=> opentelemetry: prepare for v0.13.0 release

tracing-attributes/src/lib.rs, tracing-core/src/event.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/layer.rs, tracing-tower/src/service_span.rs
=> chore: backport fix clippy's awful new "inconsistent struct constructor" lint

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
=> opentelemetry: backport prepare for v0.13.0 release

tracing-opentelemetry/src/subscriber.rs
There is some more context in #1397 but the main idea is that we should be able to trace a Span back to the location in the code where it was created. Currently many crates have spans with very generic names (`h2` has `send_data` and `reserve_capacity`) and this makes it very difficult to figure out where spans are coming from. This change will make it much easier to find the location in the code where spans are created.
We can capture the location information using the existing location data on the `tracing::Span`.
The opentelemetry specification calls for a number of attributes to correlate
traces to their location in the code. They are documented here [1]. This commit
adds support for the following fields based on the tracing span metadata (all
relative to span creation):
- …
=> Add opentelemetry source code attributes to spans

tracing-core/src/metadata.rs
Get the string representation of the `Level` is quite a common usecase.
Without this method, I normally need to implement it by myself, which is fairly noisy.
```rust
#[inline]
fn level_to_str(level: &tracing::Level) -> &'static str {
match *level {
tracing::Level::TRACE => "TRACE",
tracing::Level::DEBUG => "DEBUG",
tracing::Level::INFO => "INFO",
tracing::Level::WARN => "WARN",
tracing::Level::ERROR => "ERROR"
}
}
```
Add an `as_str()` method for `Level`. Similar to [log::Level::as_str()](https://docs.rs/log/0.4.14/log/enum.Level.html#method.as_str).
=> core: add `as_str()` for `Level`

examples/examples/toggle-subscribers.rs, tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/prelude.rs, tracing-subscriber/src/subscribe.rs
I dislike using `*` imports in my code, so I'm not using prelude modules provided by libraries. With the way the examples in the `tracing-subscriber` docs are currently set up, there is no hint on where some methods are coming from. Just removing the prelude import unfortunately doesn't lead to a solution. The compiler prefers the prelude re-export:
```
= help: items from traits can only be used if the trait is in scope
help: the following trait is implemented but not in scope; perhaps add a `use` for it:
|
3   | use crate::tracing_subscriber::prelude::__tracing_subscriber_SubscriberExt;
|
```
Use the traits directly in the documentation examples.
=> subscriber: Stop using prelude imports in doctests

tracing/src/instrument.rs
This provides a blanket implementation of `WithSubscriber`, as already implied by the docs, discussed at https://canary.discord.com/channels/500028886025895936/627649734592561152/850435247216001074, and already implemented by `tracing-futures`.
The current docs are confusing since they describe behaviour that is effectively unusable.
=> Blanket-implement tracing::instrument::WithSubscriber

tracing-core/src/dispatch.rs, tracing-error/src/subscriber.rs, tracing-futures/src/lib.rs, tracing-opentelemetry/benches/trace.rs, tracing-opentelemetry/src/subscriber.rs, tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/filter/level.rs, tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/registry/mod.rs, tracing-subscriber/src/registry/sharded.rs, tracing-subscriber/src/subscribe.rs, tracing/src/collect.rs, tracing/src/instrument.rs
The name `S` in `S: Collect` trait bound is outdated since we renamed `Subscribe` to `Collect`. We'd better unify the generic name of `S: Collect` to `C: Collect`.
=> chore: unify generic name of `Collect`

tracing-core/src/dispatch.rs, tracing-core/src/field.rs, tracing-core/src/metadata.rs, tracing-core/src/span.rs, tracing-subscriber/src/registry/mod.rs, tracing-subscriber/src/subscribe.rs, tracing/src/dispatch.rs, tracing/src/field.rs, tracing/src/lib.rs, tracing/src/span.rs
This branch resolves an issue where tooltips would render _over_ the block's content. I resolved this issue by removing the usage of rustdoc's tooltip icons, whose styling isn't meant to be stable.
Before:
After:
=> docs: Fix rendering issue with misaligned tooltips

tracing-core/src/dispatcher.rs, tracing-core/src/field.rs, tracing-core/src/metadata.rs, tracing-core/src/span.rs, tracing-subscriber/src/layer.rs, tracing-subscriber/src/registry/mod.rs, tracing/src/dispatcher.rs, tracing/src/field.rs, tracing/src/lib.rs, tracing/src/span.rs
=> chore: backport #1430 to v0.1.0

tracing-subscriber/src/layer.rs
Fixes #1428
Adds a new `Context::event_span` method as proposed in the issue.
No existing formatters were changed to use it yet, that seems like a secondary issue (especially if they already work correctly).
=> Add Context method for resolving an Event's SpanRef

tracing-subscriber/src/subscribe.rs
I'm sure we can avoid unnecessary `self.inner.register_callsite()` call in these two `Layered` implementations.
=> subscriber: explain why we always call `inner.register_callsite()` before if statement

tracing/src/dispatcher.rs
There is no struct named `Subscriber`, I think the `Subscriber` here is a trait.
=> docs: Fix typo

tracing-core/src/metadata.rs
This adds a section to the `Level` docs explaining the comparison rules
for `Level` and `LevelFilter`. It turns out this wasn't really
explicitly documented anywhere.
I may have gone a bit overboard on this, but I think the new docs should
be helpful...
See https://github.com/tokio-rs/tracing/pull/1274#discussion_r658339699
=> core: add a brief docs section on comparing levels

examples/Cargo.toml, tracing-core/src/metadata.rs, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/src/layer.rs, tracing-opentelemetry/src/tracer.rs, tracing-subscriber/src/fmt/fmt_layer.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/fmt/writer.rs, tracing-subscriber/src/layer.rs, tracing-subscriber/src/prelude.rs, tracing/src/lib.rs
This backports the following changes:
* 82d576fe core: add a brief docs section on comparing levels (#1446)
* 6def3c5d subscriber: add `MakeWriter` combinators (#1274)
* bf8d026d opentelemetry: improve performance by pre-determining attribute length (#1327)
* 1b84c7e5 subscriber: explain why we always call `inner.register_callsite()` before if statement (#1433)
* 6791e1e2 chore: fix new clippy warnings (#1444)
* 90c982aa opentelemetry: update opentelemetry to 0.15 (#1441)
* 656f9114 opentelemetry: add opentelemetry source code attributes to spans (#1411)
* 64f63e66 tracing: Fix link to RAII pattern document (#1398)
* 1bfe02b8 subscriber: add `MakeWriter::make_writer_for` (#1141)
=> backport recent changes from `master`

tracing-subscriber/CHANGELOG.md, tracing-subscriber/src/lib.rs
- **registry**: `SpanRef::parents`, `SpanRef::from_root`, and
`Context::scope` iterators, which are replaced by new `SpanRef::scope`
and `Scope::from_root` iterators (#1413)
- **registry**: `SpanRef::scope` method, which returns a leaf-to-root
`Iterator` including the leaf span (#1413)
- **registry**: `Scope::from_root` method, which reverses the `scope`
iterator to iterate root-to-leaf (#1413)
- **registry**: `Context::event_span` method, which looks up the parent
span of an event (#1434)
- **registry**: `Context::event_scope` method, returning a `Scope`
iterator over the span scope of an event (#1434)
- **fmt**: `MakeWriter::make_writer_for` method, which allows returning
a different writer based on a span or event's metadata (#1141)
- **fmt**: `MakeWriterExt` trait, with …
=> subscriber: prepare to release 0.2.19

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
- Upgrade to `v0.15.0` of `opentelemetry` ([#1441])
For list of breaking changes in OpenTelemetry, see the
[v0.14.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0140).
- Spans now include Opentelemetry `code.namespace`, `code.filepath`, and
`code.lineno` attributes ([#1411])
- Improve performance by pre-allocating attribute `Vec`s ([#1327])
Thanks to @Drevoed, @lilymara-onesignal, and @Folyd for contributing
Closes #1462
=> opentelemetry: prepare to release v0.14.0

tracing-subscriber/src/fmt/format/json.rs
It should be possible to remove `timestamp` and `level` fields when using json formatting.
As of now this has no effect:
```rs
let subscriber = tracing_subscriber::fmt()
.with_level(false)
.without_time()
.json()
.finish();
```
Use the existing `display_timestamp` and `display_level` fields to conditionally serialize `timestamp` and `level`.
=> Use display_timestamp and display_level in Json format_event

README.md, tracing/src/lib.rs
Adding a mention to `tracing-actix-web` in the ecosystem section.
=> Add tracing-actix-web

tracing-futures/README.md
Fixes #1196. I reported this a while ago but noticed it again recently and decided I might as well just fix it.
=> Fix broken crates.io link in tracing-futures README

tracing-subscriber/src/registry/sharded.rs
This may help give the user a hint to start debugging this.
See https://github.com/tokio-rs/tracing/issues/688 for further details
on this issue.
=> Expand the "tried to clone" panic with a hint about borrowing parents

tracing-error/src/backtrace.rs
I'm writing a tracing subscriber layer that captures tracing events to display in an in-program UI in a somewhat structured manner; as such I don't want to just use the fmt layer's format-to-a-single-string approach, and instead capture (currently) the event metadata, fields, timestamp, thread, and spantrace, to be displayed in a filterable/searchable/interactable manner later.
Currently, the only way to capture a `SpanTrace` is via `SpanTrace::capture`. This (rightfully) captures the `SpanTrace` of the current execution. However, I'm currently inside `Subscribe::on_event`; I have the span right here! Even if `Span::current` happens to be the same during `on_event` as when the event was fired, it seems more "proper" to create a `SpanTrace` from the span passed in to me, rather than …
=> feat: allow creating SpanTrace from Span directly

examples/Cargo.toml, examples/examples/fmt/yak_shave.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs
Forward-port of #1460 to the 0.2.x (master) branch.
=> 0.2 edition: subscriber::fmt: print all error sources

tracing-subscriber/src/fmt/format/pretty.rs
On v0.1.x,  `tracing_subscriber::fmt`'s `Pretty` formatter is missing
a space after the event's level, when printing levels is enabled.
This branch fixes that.
Fixes #1488
=> subscriber: add space after level with pretty formatter

examples/Cargo.toml, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/benches/trace.rs, tracing-opentelemetry/src/subscriber.rs, tracing-opentelemetry/src/tracer.rs, tracing-opentelemetry/tests/trace_state_propagation.rs
Updates to the latest otel spec version and addresses small internal method and module updates.
=> opentelemetry: update to otel v0.16.x

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
- Upgrade to `v0.16.0` of `opentelemetry` (#1497)
For list of breaking changes in OpenTelemetry, see the [v0.16.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0160).
=> opentelemetry: prepare for 0.15.0 release

.cargo/audit.toml, .github/workflows/CI.yml, examples/Cargo.toml, examples/examples/fmt-multiple-writers.rs, examples/examples/futures-proxy-server.rs, examples/examples/inferno-flame.rs, examples/examples/toggle-subscribers.rs, tracing-appender/Cargo.toml, tracing-appender/src/rolling.rs, tracing-flame/Cargo.toml, tracing-flame/tests/collapsed.rs, tracing-flame/tests/concurrent.rs
This branch contains several commits that should fix some CI failures and warnings. I'll rebase-merge this.
List of commits:
* 1e2b4d7d chore: ignore unmaintained warning for `net2` in `cargo audit`
`cargo audit` currently emits a warning that the `net2` crate is 
unmaintained. We only depend on `net2` as a transitive dependency of 
older versions of `mio`, which we depend on via `tokio` 0.1.
`tracing-futures` has feature flags for supporting `tokio` 0.1, which
we can't remove until the next breaking change. `tokio` 0.1 won't be 
updated, so as long as `tracing-futures` supports tokio 0.1, we can't 
really get rid of the `net2` dependency.
Therefore, this commit adds a `.cargo/audit.toml` to just ignore the 
warning. It only effects users who are using compatibility features
for
*other* …
=> chore: several CI fixes & cleanup

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/src/lib.rs
- **fmt**: Fixed `fmt` printing only the first `source` for errors with
a chain of sources ([#1460])
- **fmt**: Fixed missing space between level and event in the `Pretty`
formatter ([#1498])
- **json**: Fixed `Json` formatter not honoring `without_time` and
`with_level` configurations ([#1463])
- **registry**: Improved panic message when cloning a span whose ID
doesn't exist, to aid in debugging issues with multiple subscribers
([#1483])
- **registry**: Improved documentation on span ID generation ([#1453])
Thanks to new contributors @joshtriplett and @lerouxrgd, and returning
contributor @teozkr, for contributing to this release!
[#1460]: https://github.com/tokio-rs/tracing/pull/1460
[#1483]: https://github.com/tokio-rs/tracing/pull/1483
[#1463]: …
=> subscriber: prepare to release v0.2.20

tracing-subscriber/src/subscribe.rs
Resolves #1515. I'm pretty sure that I introduced this during the great `Layer` -> `Subscribe` renaming, so that's my bad.
=> subscriber: call `inner` instead of `subscriber`

tracing-opentelemetry/src/span_ext.rs
Repeat of #1480 to merge on master.
Discussed in #1121, the opentelemetry specifications allow adding a link to a propagated span and/or a closed span. However, the implemented `on_follows_from` of the `OpenTelemetryLayer` does not allow this.
The solution follows the same model as the `set_parent` `Span` extension function.
A `add_link` function that takes the linked span context was added to the `OpenTelemetrySpanExt`.
=> opentelemetry: Add extension to link spans

tracing-core/src/field.rs, tracing-opentelemetry/src/subscriber.rs, tracing-serde/src/lib.rs, tracing-subscriber/src/field/debug.rs, tracing-subscriber/src/field/display.rs, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/fmt/format/json.rs, tracing/tests/event.rs, tracing/tests/span.rs, tracing/tests/support/field.rs
Tracing is a really useful framework but a lack of floating point value support for the core visitors means these get coerced unnecessarily to strings.
This change adds support for floating point (f64) visitors.
=> Add support for visiting floating point values

tracing-subscriber/src/layer.rs
Currently, `Layered` only implements `fmt::Debug` if the outer layer,
the inner layer, *and* the subscriber type parameters all implement
`fmt::Debug`. However, in the case of a `Layered` with two `Layer`s, the
subscriber itself is not present --- it's only a `PhantomData`. So the
`fmt::Debug` implementation should be possible when only the actual
`layer` and `inner` values are `Debug`. For the `PhantomData`, we can
just print the type name.
This means that `Layered` consisting of two `Layer`s and no `Subscriber`
will now implement `Debug` if the `Layer`s are `Debug`, regardless of
the subscriber type. When the `Layered` is a `Layer` and a `Subscriber`,
the behavior will be the same, because the separate `PhantomData`
subscriber type param is always the same as the type of the inner …
=> subscriber: nicer `fmt::Debug` for `Layered`

.github/workflows/CI.yml
The default behavior for GitHub Actions `matrix` strategies is to cancel
all remaining jobs in a `matrix` job if *any* of them fail. However,
this sometimes obscures important information. For example, we have a
step that runs tests on stable, beta, and nightly Rust. In this case,
it's useful to know whether a failure occurred only on nightly, or if it
effects *every* Rust version.
Furthermore, our branch protection settings don't require the nightly
build to pass in order to merge a PR, because there are sometimes
spurious failures due to nightly-specific bugs. We *do* require the
stable build to pass. However, because the `matrix` strategy will cancel
all jobs in the matrix if any of them fails, this means that we
implicitly *do* require the tests to pass on nightly, as if the nightly …
=> chore(ci): turn off `fail-fast` for some build matrix jobs

tracing-subscriber/src/layer.rs, tracing-subscriber/src/registry/mod.rs, tracing-subscriber/tests/duplicate_spans.rs, tracing-subscriber/tests/field_filter.rs, tracing-subscriber/tests/filter.rs, tracing-subscriber/tests/filter_log.rs, tracing-subscriber/tests/fmt_max_level_hint.rs, tracing-subscriber/tests/registry_max_level_hint.rs, tracing-subscriber/tests/registry_with_subscriber.rs, tracing-subscriber/tests/reload.rs, tracing-subscriber/tests/same_len_filters.rs, tracing-subscriber/tests/utils.rs
Currently we can't run
```bash
cargo test -p tracing-subscriber --no-default-features
```
successfully, because there are a bunch of tests for feature flagged
APIs that are always enabled.
This commit adds feature flags to the modules and/or individual test
cases that test feature-flagged APIs.
There are still a few doctests that use feature-flagged APIs, and will
fail with `--no-default-features`. These are primarily the examples for
various `Layer::context` methods that rely on `LookupSpan`, and use the
`Registry` type, as it's the only subscriber that *implements*
`LookupSpan`. We could consider changing these examples, either by
removing the actual use of the layers in them, or by changing them to
use a mocked-out version of the registry. However, I think it's nicer to
show how the …
=> subscriber: add feature flags to tests

tracing-subscriber/src/layer.rs
Add `Layer<S>` impls for:
- `Box<L>`
- `Box<dyn Layer<S>>`
- `Arc<L>`
- `Arc<dyn Layer<S>>`
where `L: Layer<S>`
=> 0.1: add Layer implementations for various containers

.github/workflows/CI.yml
When reviewing https://github.com/tokio-rs/tracing/pull/1523, I suggested that the examples use `fmt::Layer` directly to allow readers to copy-and-paste examples into their own code. However, @hawkw pointed out that rustdoc doesn't receive feature flags from Cargo, which means that running tracing-subscriber's tests under `--no-default-features` would fail.
It turned out that that we're only running `cargo check --no-default-features` for tracing-subscriber. Running `cargo test --no-default-features` resulted in compilation failures, but it seems like nobody noticed. Building on https://github.com/tokio-rs/tracing/pull/1532, this branch argues that running tracing-subscriber's tests under `cargo test --lib --tests --no-default-features` is _probably_ fine if we're able to skip the …
=> chore: run tracing-subscriber's tests under `--no-default-features`

examples/examples/tower-load.rs, tracing/src/instrument.rs, tracing/src/span.rs
This adds a new `Span::or_current` method that returns the span it's
called on, if that span is enabled, or the current span if that span
is not enabled.
This should provide a more efficient alternative to writing code like
```rust
tokio::spawn(
future
.instrument(some_span)
.in_current_span()
);
```
since it doesn't wrap the future in two different spans which are
(potentially) both entered on polls. It's also a little more concise
to write, which (hopefully) will encourage people to use it instead
of the less efficient alternative.
`Span::or_current` may be useful in other cases as well.
=> tracing: add `Span::or_current` to help with efficient propagation

.github/workflows/CI.yml, examples/examples/fmt-multiple-writers.rs, examples/examples/fmt-pretty.rs, examples/examples/fmt.rs, examples/examples/tower-load.rs, tracing-attributes/src/lib.rs, tracing-core/src/field.rs, tracing-opentelemetry/src/layer.rs, tracing-opentelemetry/src/span_ext.rs, tracing-serde/src/lib.rs, tracing-subscriber/src/field/debug.rs, tracing-subscriber/src/field/display.rs, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/fmt/mod.rs, tracing/src/instrument.rs, tracing/src/span.rs, tracing/tests/event.rs, tracing/tests/span.rs, tracing/tests/support/field.rs
This backports the following commits from master:
* 151c0628 tracing: add `Span::or_current` to help with efficient propagation (#1538)
* c5ba3d36 chore: run tracing-subscriber's tests under `--no-default-features` (#1537)
* 7657fe08 chore(ci): turn off `fail-fast` for some build matrix jobs (#1530)
* 9cd3c567 attributes: record `f32` and `f64` as `Value` (#1522)
* c90e5c8c core: add support for visiting floating point values (#1507)
* d394efa8 opentelemetry: Add extension to link spans (#1516)
Additionally, I also fixed a few instances where we were accidentally using v0.2 names ("collector" rather than "subscriber") on v0.1.x.
=> backport commits from main & fix terminology

.github/workflows/CI.yml
This is a little bit nicer IMO.
=> chore(ci): use `working-directory` instead of cd

netlify.toml
Previously, the Netlify configuration copied the docs into a
`_netlify_out` dir as a workaround for netlify/build-image#505. This
upstream issue was fixed back in January, so this workaround hasn't been
necessary for a while. Therefore, we can remove this extra complexity
from our configuration.
I also changed the build script to a multi-line string which I think is
a bit nicer.
=> chore: simplify Netlify config

tracing-subscriber/src/fmt/writer.rs
This fixes a few broken rustdoc links in the `MakeWriter` and
`MakeWriterExt` rustdocs.
=> subscriber: fix broken docs links in `MakeWriter`

tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/filter/env/mod.rs
Currently, some types in the `filter` module that require the
"env-filter" feature flag don't properly show in the docs that they
require this feature. This is because the `doc(cfg(feature = "env-filter"))`
attribute is only placed on the _re-export_ from the
`env` module (and on the `EnvFilter` type), not on the individual
types that are re-exported. However, placing a `doc(cfg(...))` attribute
on a re-export doesn't actually do anything.
This commit fixes that.
=> subscriber: fix missing `doc(cfg(...))` attributes for `EnvFilter`

tracing-subscriber/src/layer/mod.rs
And for Arc
This is a fixup for https://github.com/tokio-rs/tracing/pull/1536.
=> Layer impls for Box<dyn Layer<..>> should be Send+Sync

tracing-core/src/dispatcher.rs, tracing-core/src/subscriber.rs
This is useful when you need a placeholder subscriber for something.
=> Make NoSubscriber public and move it to tracing_core::subscriber

tracing-log/src/log_tracer.rs, tracing-log/tests/log_tracer.rs
The `LogTracer::init()` will convert all logs to tracing events, and regardless of the tracing 'Collector' filter, just dispatch all events, cause inconsistent behavior between log and trace.
=> fix: log level filter with trace

.github/workflows/CI.yml, netlify.toml, tracing-log/src/log_tracer.rs, tracing-log/tests/log_tracer.rs, tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/filter/env/mod.rs
* ffbf8787 log: fix `LogTracer` not honoring max level filters (#1543)
* cd2af48c subscriber: fix missing `doc(cfg(...))` attributes for `EnvFilter` (#1544)
* d27d0b3f chore: simplify Netlify config (#1541)
* 23f1508f chore(ci): use `working-directory` instead of cd (#1540)
=> backport some stuff

tracing-attributes/src/lib.rs, tracing-attributes/tests/instrument.rs
Using `#[instrument(skip_all)]` is equivalent to `#[instrument(skip(foo, bar..))]` for all the parameters.
=> tracing-attributes: implement `skip_all`

tracing-subscriber/src/filter/mod.rs, tracing-subscriber/src/layer/mod.rs, tracing-subscriber/src/lib.rs
This branch adds some new documentation in a few places that references
other sections in the docs. This should help make some of the crate's
APIs easier to find. In particular, the crate's top level docs now
summarize the `Layer` and `Filter` traits, and link to their individual
docs sections. Additionally, the per-layer filtering section in the
`Layer` module docs now references some of the concrete `Filter`
implementations in the `filter` modules.
=> subscriber: add more cross-references to documentation

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md, tracing-core/src/lib.rs
This release adds support for `f64` as one of the `tracing-core`
primitive field values, allowing floating-point values to be recorded as
typed values rather than with `fmt::Debug`. Additionally, it adds
`NoSubscriber`, a `Subscriber` implementation that does nothing.
- **subscriber**: `NoSubscriber`, a no-op `Subscriber` implementation
([#1549])
- **field**: Added `Visit::record_f64` and support for recording
floating-point values ([#1507])
Thanks to new contributors @jsgf and @maxburke for contributing to this
release!
[#1549]: https://github.com/tokio-rs/tracing/pull/1549
[#1507]: https://github.com/tokio-rs/tracing/pull/1507
=> core: prepare to release 0.1.20

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/src/filter/mod.rs, tracing-subscriber/src/layer/mod.rs, tracing-subscriber/src/lib.rs
This release introduces the [`Filter`] trait, a new API for [per-layer
filtering][plf]. This allows controlling which spans and events are
recorded by various layers individually, rather than globally.
In addition, it adds a new [`Targets`] filter, which provides a
lighter-weight version of the filtering provided by [`EnvFilter`], as
well as other smaller API improvements and fixes.
- **registry**: `SpanRef::parent_id`, which cannot properly support
per-layer filtering. Use `.parent().map(SpanRef::id)` instead.
([#1523])
- **layer** `Context` methods that are provided when the `Subscriber`
implements `LookupSpan` no longer require the "registry" feature flag
([#1525])
- **layer** `fmt::Debug` implementation for `Layered` no longer requires
the `S` type parameter to implement `Debug` …
=> subscriber: prepare to release v0.2.21

tracing-subscriber/src/filter/directive.rs, tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/filter/mod.rs, tracing-subscriber/src/filter/targets.rs
I accidentally renamed this type in PR #1550 after getting confused by a
renaming import that I thought was publicly re-exported, but it wasn't
actually..sorry about that!
This commit renames (or...un-renames?) the type. Whoopsie!
Fixes #1557
=> subscriber: fix filter::ParseError accidentally being renamed 

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/src/lib.rs
This fixes a regression where the `filter::ParseError` type was
accidentally renamed.
- **filter**: Fix `filter::ParseError` accidentally being renamed to
`filter::DirectiveParseError` ([#1558])
[#1558]: https://github.com/tokio-rs/tracing/pull/1558
=> subscriber: prepare to release 0.2.22

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs
This release adds a new `#[instrument(skip_all)]` option to skip
recording *all* arguments to an instrumented function as fields.
Additionally, it adds support for recording arguments that are `tracing`
primitive types as typed values, rather than as `fmt::Debug`.
- add `skip_all` option to `#[instrument]` ([#1548])
- record primitive types as primitive values rather than as `fmt::Debug`
([#1378])
- added support for `f64`s as typed values ([#1522])
Thanks to @Folyd and @jsgf for contributing to this release!
[#1548]: https://github.com/tokio-rs/tracing/pull/1548
[#1378]: https://github.com/tokio-rs/tracing/pull/1378
[#1522]: https://github.com/tokio-rs/tracing/pull/1524
=> attributes: prepare to release v0.1.16

tracing-core/CHANGELOG.md, tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This release adds a new [`Span::or_current`] method to aid in
efficiently propagating span contexts to spawned threads or tasks.
Additionally, it updates the [`tracing-core`] version to [0.1.20] and
the [`tracing-attributes`] version to [0.1.16], ensuring that a number
of new features in those crates are present.
- **instrument**: Added missing `WithSubscriber` implementations for
futures and other types (#1424)
- `Span::or_current` method, to help with efficient span context
propagation (#1538)
- **attributes**: add `skip_all` option to `#[instrument]` (#1548)
- **attributes**: record primitive types as primitive values rather than
as `fmt::Debug` (#1378)
- **core**: `NoSubscriber`, a no-op `Subscriber` implementation
(#1549)
- **core**: Added `Visit::record_f64` and support for …
=> tracing: prepare to release v0.1.27 

tracing-subscriber/src/subscribe.rs
This PR cherrypicks #1536 and #1547 to the master branch and renames `Layer` to `Subscribe` accordingly.
=> chore: port Layer (`Subscribe`) change to master

tracing-subscriber/src/filter/directive.rs, tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/filter/targets.rs
The `DirectiveSet` type used in `EnvFilter` and `Targets` uses
`SmallVec` to store the filtering directives when the `SmallVec` feature
is enabled. This is intended to improve the performance of iterating
over small sets of directives, by avoiding a heap pointer dereference.
PR #1550 changed the directives themselves to also use `SmallVec` for
storing _field_ filters. This was intended to make the same optimization
for field filters. However, it had unintended consequences: an empty
`SmallVec` is an array of `T` items (plus metadata), while an empty
`Vec` is just a couple of words. Since _most_ filters don't have field
filters, this meant that we were suddenly using a lot more space to
store...nothing. This made `EnvFilter`s _much_ larger, causing problems
for some users (see #1567).
This …
=> subscriber: don't use SmallVecs for filter fields 

tracing-subscriber/src/layer/layered.rs, tracing-subscriber/tests/layer_filters/main.rs, tracing-subscriber/tests/layer_filters/targets.rs
Currently, when evaluating `register_callsite` for a stack containing
per-layer filters, the intermediate `Interest` from combining the per
layer filters' `Interest`s is stored in the thread-local `FilterState`.
When all per-layer filters have been evaluated, we reach the `Registry`,
which clears the `FilterState` and bubbles the `Interest` back up.
However, when a _global_ filter in the stack returns `Interest::never`,
we short-circuit, and don't reach the `Registry`. This means the
`Interest` state is not cleared.
This branch adds code in `Layered` to ensure the per-layer filter state
is cleared when a global filter short circuits `Interest` evaluation.
This fixes #1563.
=> subscriber: clear per-layer interest when short circuiting

tracing-core/src/dispatcher.rs, tracing-core/src/metadata.rs, tracing-core/src/span.rs, tracing-subscriber/src/layer/context.rs, tracing-subscriber/src/layer/mod.rs, tracing-subscriber/src/registry/mod.rs, tracing/src/dispatcher.rs, tracing/src/field.rs, tracing/src/lib.rs, tracing/src/span.rs
This branch removes the HTML `<div>` tags from the warning and note
blocks in the documentation, because they're screwing up RustDoc
rendering on docs.rs. We had done this previously on the `master`
branch, but apparently it never made it to `v0.1.x`.
This should fix #1571 once a new `tracing` version is published.
=> docs: remove divs from all notes/warnings

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release fixes a few bugs in the per-layer filtering API added in
v0.2.21.
- **env-filter**: Fixed excessive `EnvFilter` memory use ([#1568])
- **filter**: Fixed a panic that may occur in debug mode when using
per-layer filters together with global filters ([#1569])
- Fixed incorrect documentation formatting ([#1572])
[#1568]: https://github.com/tokio-rs/tracing/pull/1568
[#1569]: https://github.com/tokio-rs/tracing/pull/1569
[#1572]: https://github.com/tokio-rs/tracing/pull/1572
=> subscriber: prepare to release v0.2.23

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This release fixes an issue where the RustDoc documentation was rendered
incorrectly. It doesn't include any actual code changes, and is very
boring and can be ignored.
- **docs**: Incorrect documentation rendering due to unclosed `<div>`
tag ([#1572])
[#1572]: https://github.com/tokio-rs/tracing/pull/1572
=> tracing: prepare to release 0.1.28

tracing-subscriber/src/filter/directive.rs, tracing-subscriber/src/filter/mod.rs, tracing-subscriber/src/filter/targets.rs
There's currently no way to get the registered directives from a `Targets` instance, which is a barrier to some use-cases such as combining user-supplied directives with application-supplied defaults.
This commit adds a `Targets::targets` method, which returns an iterator of `(&str, LevelFilter)` pairs, one for each directive (excluding the default level, whose `target` is `None`).
Items are yielded as per the underlying `DirectiveSet::directives`, which would yield itms in specifity order (as constructed by
`DirectiveSet::add`). However, the order has been left explicitly undefined in the documentation for `Targets::targets` on the basis that this is an implementation detail that may change.
As hinted in the commit message, my use-case is to have an application-supplied 'base' `Targets` …
=> subscriber: add `Targets::targets` method to iterate directives

.github/workflows/CI.yml, tracing-subscriber/src/filter/env/field.rs
So...it turns out that passing `--bins` actually makes `cargo check` do
*nothing* on library-only projects without binaries. This
was...surprising.
It turns out that because of this, our MSRV check CI run is basically a
nop, and we accidentally merged code that doesn't compile on 1.42.0. I'm
very dumb lol.
I also fixed the use of `f64::EPSILON` and `f64::NAN` as imports from
the primitive type rather than from the primitive's module. Using `f64::NAN`
rather than `std::f64::NAN` doesn't compile on 1.42.0.
=> chore: remove `--bins` from CI cargo check runs 

.github/workflows/CI.yml, tracing-subscriber/src/filter/directive.rs, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/filter/layer_filters.rs, tracing-subscriber/src/layer/context.rs, tracing-subscriber/src/layer/layered.rs, tracing-subscriber/src/registry/mod.rs
Due to the CI issue fixed by PR #1580, we accidentally merged
`tracing-subscriber` changes that don't compile on our MSRV, Rust
1.42.0. This includes:
- use of associated consts on primitive types (`u64::MAX` rather than
`std::u64::MAX`)
- use of `#[cfg(...)]` on `if` expressions
- use of the `str::strip_suffix` method, which wasn't stable on 1.42.0
This branch backports #1508 to `v0.1.x`, and also fixes additional issues
in code that only exists on `v0.1.x`.
These changes are mostly very simple and mechanical. The only
significant change is changing the `StaticDirective` parsing code to not
use `strip_suffix`, which changes the implementation around a bit...but
it's still pretty straightforward.
This should fix 1.42.0 compatibility.
=> fix msrv (v0.1.x edition)

tracing-subscriber/src/filter/layer_filters.rs, tracing-subscriber/src/layer/layered.rs
This is essentially the same change as #1569, but for `enabled` states
rather than `register_callsite`. When a global filter returns `false`
from `enabled`, ensure that the per-layer filter `FilterMap` and debug
counters are cleared, so that they are empty on the next `enabled` call.
See #1563
=> subscriber: clear `enabled` filter map when short circuiting

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release contains a number of bug fixes, including a fix for
`tracing-subscriber` failing to compile on the minimum supported Rust
version of 1.42.0. It also adds `IntoIterator` implementations for the
`Targets` type.
- Fixed compilation on Rust 1.42.0 ([#1580], [#1581])
- **registry**: Ensure per-layer filter `enabled` state is cleared when
a global filter short-circuits filter evaluation ([#1575])
- **layer**: Fixed `Layer::on_layer` not being called for `Box`ed
`Layer`s, which broke  per-layer filtering ([#1576])
- **filter**: Added `Targets::iter`, returning an iterator over the set
of target-level pairs enabled by a `Targets` filter ([#1574])
- **filter**:  Added `IntoIterator` implementations for `Targets` and
`&Targets` ([#1574])
Thanks to new contributor @connec for …
=> subscriber: prepare to release 0.2.24

tracing-tower/Cargo.toml
Currently, our MSRV CI build is broken because of the `tracing-tower`
crate, which depends on `http`. The latest `http` release broke support
for Rust 1.42.0.
Since the `tracing-tower` crate is unreleased and is probably never
going to be published in its current form (see #238), this isn't
actually an issue, but the CI breakage is quite sad. I'm working on an
upstream PR to `tower` to add tracing support there, so we can
eventually deprecate the `tracing-tower` crate and direct users to
upstream. However, that's not quite ready.
Also, we should probably just drop the `http` support from
`tracing-tower` entirely, since tracing HTTP requests with `Tower`
services is probably better served by the `tower-http` crate's [`trace`
middleware][1]. This middleware is significantly more featureful. …
=> tower: drop `http` from default features

examples/examples/panic_hook.rs, examples/examples/tokio_panic_hook.rs
It turns out panic hooks also work nicely even when panics are captured.
I figured we may as well have an example demoing this!
=> examples: add `tokio_panic_hook` example

tracing-core/src/field.rs, tracing/tests/event.rs
I'm very interested in #1393 getting merged. Yep, I'm aware that the `Valuable` work may supersede this, but in the mean time this would be a huge improvement for how we use tracing.
Based on this comment https://github.com/tokio-rs/tracing/pull/1393#pullrequestreview-673362275 by @hawkw it looks like the only thing holding up #1393 is some tests? If so, here is one test. Let me know what other tests you'd like to see and I'll get them added.
I wasn't quite sure how to assert that the mock did _not_ record fields `none_str`, `none_bool`, etc.
=> core: impl field::Value for Option<T>

tracing-subscriber/src/filter/targets.rs, tracing-subscriber/src/layer/mod.rs
This PR contains two changes:
1. An example as how to use `Option<Layer>` to toggle layers at runtime, and...
2. A fix to an example writing to disk when doc tests are run.
=> subscriber: add example of Option<Layer>

tracing-core/src/subscriber.rs, tracing-subscriber/src/layer/mod.rs
I noticed a few typos when reading the documentation, so I might as well fix them.
=> chore: fix several typos in tracing-core and tracing-subscriber

tracing-attributes/src/lib.rs
Adding `#[instrument(level = "debug")]` attributes to functions in rustc
caused a performance regression (in release, where `debug!` is fully
optimized out) across all crates:
https://github.com/rust-lang/rust/pull/89048#issuecomment-929566530
While trying to debug this, I noticed that spans don't have the same
advantage that events have wrt to how LLVM sees them. Spans (or more
precisely, the enter-guard), will get dropped at the end of the scope,
which throws a spanner into the LLVM optimization pipeline. I am not
entirely sure where the problem is, but I am moderately certain that the
issue is that even entering a dummy span is too much code for LLVM to
reliably (or at all) optimize out.
My hope is that in trusting the Rust compiler to generate cool code when using
drop flags, we can …
=> Help LLVM understand that some spans are never going to do anything

tracing-core/src/spin/once.rs
Allow the deprecated API for now, until the next MSRV bump.
=> core: fix `spin_loop_hint` deprecation warnings

tracing-attributes/src/lib.rs
This is a backport of https://github.com/tokio-rs/tracing/pull/1600 to tracing 0.1
it applied cleanly with no manual adjustments
=> Backport LLVM optimization hint

tracing-core/src/spin/once.rs
This should *actually* fix the build on no-std.
=> core: additional deprecation fixes

tracing-appender/src/inner.rs
When a RollingFileAppender is refreshed, the previous `BufWriter` may encounter and suppress errors in `drop`.
From https://doc.rust-lang.org/std/io/struct.BufWriter.html:
> It is critical to call flush before BufWriter<W> is dropped. Though dropping will attempt to flush the contents of the buffer, any errors that happen in the process of dropping will be ignored.
Explicitly flush the previous buffer before dropping, printing any error to stderr.
=> explicitly flush previous BufWriter before dropping

tracing/src/instrument.rs, tracing/src/span.rs
The version of `WithCollector` in `tracing::instrument` (rather than in
`tracing-futures`) is currently...useless, since there is no `Future`
impl for the `WithDispatch` type. This means that calling
`with_collector` on a `Future` returns a value that _isn't_ a `Future`.
Additionally, the `WithCollector` trait isn't actually implemented for
anything (although this was fixed on v0.1.x).
This branch adds the missing implementations. I also improved the docs a
bit.
=> tracing: add missing `Future` impl for `WithDispatch`

tracing-attributes/src/lib.rs
In #1600, the `instrument` code generation was changed to avoid ever
constructing a `Span` struct if the level is explicitly disabled.
However, for `async` functions, `#[instrument]` will currently still
create the span, but simply skips constructing an `Instrument` future if
the level is disabled.
This branch changes the `#[instrument]` code generation for async blocks
to totally skip constructing the span if the level is disabled. I also
simplfied the code generation a bit by combining the shared code between
the `err` and non-`err` cases, reducing code duplication a bit.
=> attributes: skip `async` spans if level disabled

.github/workflows/CI.yml, examples/examples/panic_hook.rs, examples/examples/tokio_panic_hook.rs, tracing-appender/src/inner.rs, tracing-attributes/src/lib.rs, tracing-core/src/field.rs, tracing-core/src/spin/once.rs, tracing/src/instrument.rs, tracing/src/lib.rs
this backports the following changes from `master` to `v0.1.x`:
* 21ddd96a attributes: skip `async` spans if level disabled (#1607)
* d3fa53f5 tracing: add missing `Future` impl for `WithDispatch` (#1602)
* 37c4b5cd appender: explicitly flush previous BufWriter before dropping (#1604)
* a674278a core: additional deprecation fixes (#1606)
* cd8b24a6 core: fix `spin_loop_hint` deprecation (#1603)
* 47eac483 docs: add a parenthesis (#1597)
* b6544e74 core: fix missing `dyn` in `Visit` docs example (#1595)
* 72b07a14 examples: add `tokio_panic_hook` example (#1593)
Of these commits, only #1602 required meaningful modification for v0.1.x
(beyond tracking renamings). It was necessary to change the feature
flagging of `WithDispatch`/`WithSubscriber` from the version on
`master`, so that  the …
=> backport changes from `master`

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md, tracing-core/src/lib.rs
This release adds support for recording `Option<T> where T: Value` as
typed `tracing` field values.
- **field**: `Value` impl for `Option<T> where T: Value` ([#1585])
- Fixed deprecation warnings when building with `default-features`
disabled ([#1603], [#1606])
- Documentation fixes and improvements ([#1595], [#1601])
Thanks to @brianburgers, @DCjanus, and @matklad for contributing to this
release!
[#1585]: https://github.com/tokio-rs/tracing/pull/1585
[#1595]: https://github.com/tokio-rs/tracing/pull/1595
[#1601]: https://github.com/tokio-rs/tracing/pull/1601
[#1603]: https://github.com/tokio-rs/tracing/pull/1603
[#1606]: https://github.com/tokio-rs/tracing/pull/1606
=> core: prepare to release 0.1.21

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs
This release significantly improves performance when
`#[instrument]`-generated spans are below the maximum enabled level.
- improve performance when skipping `#[instrument]`-generated spans
below the max level ([#1600], [#1605])
Thanks to @oli-obk for contributing to this release!
[#1600]: https://github.com/tokio-rs/tracing/pull/1600
[#1605]: https://github.com/tokio-rs/tracing/pull/1605
=> attributes: prepare to release v0.1.17

tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs, tracing-attributes/tests/err.rs
Currently, `tracing-attributes` generates a `let _ = ();` in between the
`if tracing::level_enabled!(...) {}` and the function body. This is
intended to suppress the `clippy::suspicious_else_formatting` lint,
which is generated when an `if` is followed immediately by a block with
no whitespace in between. Since we can't add whitespace in the generated
code (as `quote` produces a stream of _rust tokens_, not text), we
can't suppress the lint without adding a no-op statement.
However, unfortunately, the no-op let triggers a _different_ lint
(`clippy::let_unit_value`), when `clippy::pedantic` is enabled. This is
kind of annoying for some users.
This branch changes the code to suppress the
`suspicious_else_formatting` lint using `#[allow(...)]` attributes,
instead. The warning is turned back …
=> attributes: suppress `clippy::suspicious_else` without nop let

tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs
The changes in #1607 introduced a potential compilation error when using
the `#[instrument]` attribute on `async fn`s that return a type that
includes a closure or is otherwise unnameable. This is because the
future's body code was quoted in two separate places in order to have a
separate branch when the span is statically disabled. This means that
when a closure is returned, it will technically have two distinct types
based on whether or not the span is enabled, since it originates from
two separate source code locations (although `quote_spanned!` obscures
this, so the compiler diagnostic will appear to have two closures
originating from the same location).
This branch fixes this issue by changing the code generated for
`#[instrument]`ed async functions. Unfortunately, for async …
=> attributes: fix compile error with instrumented async functions 

tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs
Apparently, using `quote_spanned!` can trigger a Clippy bug where the
text `else`, even inside a comment, _may_ cause the
`suspicious_else_formatting` lint to be triggered incorrectly (see
rust-lang/rust-clippy#7760 and rust-lang/rust-clippy#6249). This causes
the lint to fire in some cases when the `#[instrument]` attribute is
used on `async fn`s. See issue #1613 for details.
It turns out that some of the uses of `quote_spanned!` in the
`tracing-attributes` code generation are not needed. We really only need
`quote_spanned!` when actually interpolating the user provided code into
a block, not in the `tracing-attributes` code that inserts the generated
code for producing the span etc. Replacing some of these
`quote_spanned!` uses with the normal `quote!` macro still generates
correct …
=> attributes: remove unnecessary quote_spanned! 

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs
This release fixes issues introduced in v0.1.17.
- fixed mismatched types compiler error that may occur when using
`#[instrument]` on an `async fn` that returns an `impl Trait` value
that includes a closure ([#1616])
- fixed false positives for `clippy::suspicious_else_formatting`
warnings due to rust-lang/rust-clippy#7760 and
rust-lang/rust-clippy#6249 ([#1617])
- fixed `clippy::let_unit_value` lints when using `#[instrument]`
([#1614])
[#1617]: https://github.com/tokio-rs/tracing/pull/1617
[#1616]: https://github.com/tokio-rs/tracing/pull/1616
[#1614]: https://github.com/tokio-rs/tracing/pull/1614
=> attributes: prepare to release 0.1.18

tracing-subscriber/src/filter/layer_filters.rs, tracing-subscriber/tests/layer_filters/downcast_raw.rs, tracing-subscriber/tests/layer_filters/main.rs
I'm trying to implement a `Layer` that has something very similar to tracing-error's [`WithContext`](https://github.com/tokio-rs/tracing/blob/66cd79f72af5ebcb6f21a1017b6ce33bea05558d/tracing-error/src/layer.rs#L32) to support erasing types and getting access to the current span's state.
To do that, I implement `Layer::downcast_raw` in [the same way that tracing-error does](https://github.com/tokio-rs/tracing/blob/66cd79f72af5ebcb6f21a1017b6ce33bea05558d/tracing-error/src/layer.rs#L55-L63).
This works great when the layer is not filtered. However, once I filter the layer
```rust
let filter = tracing_subscriber::filter::Targets::new().with_default(tracing::Level::INFO);
let layer = MyLayer::new();
tracing_subscriber::registry().with(layer.with_filter(filter)).init();
```
I'm not able to get …
=> Forward `Filtered::downcast_raw` to wrapped Layer

tracing/CHANGELOG.md
tracing-attributes v0.1.18 was released yesterday not v0.1.19
=> docs: fix a typo in tracing's changelog

tracing-core/src/metadata.rs
A forward port of #1692.
Resolves #1669. Namely, I:
- fixed the incorrect docs on `LevelFilter`.
- Removed a stray backtick on `LevelFilter::current`.
- Added a matching backtick in Level's documentation.
I did _not_ add example of comparing a level against a `LevelFilter`; I
instead pointed readers to Level's documentation.
=> chore: forwardport #1692 

tracing-subscriber/src/fmt/writer.rs
In `tracing-subscriber` 0.3.x, `MakeWriter` filtering seems to have
stopped working when using the `BoxMakeWriter` wrapper to erase the type
of a `MakeWriter` implementation. It looks like what happened is that
commit 6cc6c47354ceeb47da7c95faa41c6d29b71b5f37, which backported the
change to add a lifetime parameter to `MakeWriter` (#781), I
accidentally clobbered the `make_writer_for` method on the inner `Boxed`
type, so that it only has `make_writer`:
https://github.com/tokio-rs/tracing/commit/6cc6c47354ceeb47da7c95faa41c6d29b71b5f37#diff-c5dc275b15a60c1a2d4694da3797f4247c4f2e1e0978fd210dd14452d6746283L737-L739
This meant that any filtering performed by the `MakeWriter` inside the
box is now ignored. My bad!
This commit puts back the missing `make_writer_for` method. Whoops!
Fixes #1694
=> subscriber: fix missing `make_writer_for` in `BoxMakeWriter`

tracing-subscriber/src/fmt/time/mod.rs, tracing-subscriber/src/fmt/time/time_crate.rs, tracing-subscriber/src/lib.rs
The `time` crate must be compiled with `--cfg unsound_local_offset` in
order for local timestamps to be enabled. For users whose first exposure
to the `time` crate's API is via `tracing-subscriber`'s `time` timestamp
formatters, this is potentially _very_ surprising! Therefore, although
this cfg is not part of `tracing`'s API surface, we should probably
document this aspect of `time`'s API in the
`tracing-subscriber::fmt::time` documentation.
This branch adds warnings in the `time::LocalTime` type's API docs, in
the struct-level documentation and on the `new` constructor, describing
that `--cfg unsound_local_offset` is necessary to record local
timestamps and referring users to the `time` documentation. I also added
`unsound_local_offset` to the `doc(cfg(...))` attributes for the …
=> subscriber: document `time`'s `--cfg unsound_local_offset`

tracing-subscriber/CHANGELOG.md
Resolves https://github.com/tokio-rs/tracing/issues/1697 by documenting this change in the CHANGELOG.md.
=> changelog: clarify implications of `env-filter` not being enabled

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs
Currently, whether `tracing-subscriber`'s `fmt` subscriber will ANSI
formatting escape codes use is configured on the `Format` type. This
means that the configuration is honored by the event formatters
implemented in `tracing-subscriber`, but is not easily exposed to those
in other crates. Additionally, it's not currently easy to expose the
configuration to the field formatter, so it's difficult to implement
field formatters that use ANSI escape codes conditionally.
Issue #1651 suggested a new API for this, where the writer that's passed
in to the event and field formatters provides a method for checking if
ANSI escape codes are supported.
This branch adds a new method to the `Writer` type added in #1661. The
`FormatEvent` and `FormatFields` implementations can call …
=> subscriber: propagate ANSI config via `Writer`

tracing-subscriber/src/fmt/fmt_layer.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs
This is a draft version of #1696 backported to v0.1.x for testing.
=> [WIP] backport #1696 to v0.1.x

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs
Depends on #1696 
PR #1696 adds a new API for propagating whether or not ANSI formatting
escape codes are enabled to the event formatter and field formatter via
the `Writer` type. This means that it's now quite easy to make field
formatting also include ANSI formatting escape codes when ANSI
formatting is enabled. Currently, `tracing-subscriber`'s default field
formatter does not use ANSI formatting --- ANSI escape codes are
currently only used for parts of the event log line controlled by the
event formatter, not within fields. Adding ANSI colors and formatting in
the fields could make the formatted output nicer looking and easier to
read.
This branch adds support for ANSI formatting escapes in the default
field formatter, when ANSI formatting is enabled. Now, field names will
be …
=> subscriber: use ANSI formatting in field formatters

tracing-journald/Cargo.toml, tracing-journald/tests/journal.rs
Per discussion with @hawkw in #1698 I'm adding a few simple integration tests for the journald subscriber, to have some safety net when implementing the actual issue in #1698.
These tests send messages of various complexity to the journal, and then use `journalctl`'s JSON output to get them back out, to check whether the message arrives in the systemd journal as it was intended to.
Increase test coverage for the journald subscriber and codify a known good state before approaching a fix for #1698.
=> journald: Add integration tests

tracing-subscriber/src/fmt/time/datetime.rs
Add comments to clarify the provenance of fmt/time/datetime.rs, addressing https://github.com/tokio-rs/tracing/issues/1644.
=> subscriber: clarify the provenance of fmt/time/datetime.rs

tracing-appender/src/non_blocking.rs, tracing-appender/src/worker.rs
Can be though of as a continuation to #1120 and #1125.
Example with problematic racy behavior:
```
use std::io::Write;
struct TestDrop<T: Write>(T);
impl<T: Write> Drop for TestDrop<T> {
fn drop(&mut self) {
println!("Dropped");
}
}
impl<T: Write> Write for TestDrop<T> {
fn write(&mut self, buf: &[u8]) -> std::io::Result<usize> {
self.0.write(buf)
}
fn flush(&mut self) -> std::io::Result<()> {
self.0.flush()
}
}
fn main() {
let writer = TestDrop(std::io::stdout());
let (non_blocking, _guard) = tracing_appender::non_blocking(writer);
tracing_subscriber::fmt().with_writer(non_blocking).init();
}
```
Running this test case in a loop with `while ./test | grep Dropped; do done`, it can be seen that sometimes writer (`TestDrop`) is not dropped and the message is not printed.
I suppose that …
=> appender: fix WorkerGuard not waiting for writer destruction

tracing-core/src/dispatch.rs, tracing/src/lib.rs, tracing/src/span.rs
Some documentations' rendering seems to be broken.
e.g. <https://docs.rs/tracing/0.1.29/tracing/span/index.html>
Fix the HTML by removing `</div>` tags which do not have corresponding open tags.
=> docs: remove unpaired closing tags

tracing-core/src/dispatcher.rs, tracing/src/lib.rs, tracing/src/span.rs
Backports #1722 to v0.1.x; will require a release of `tracing` and (optionally) tracing-core.
=> chore: backport #1722

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/format/mod.rs
Currently, `tracing_subscriber::fmt`'s `FmtContext` type is missing the
`span_scope`, `event_span`, and `event_scope` methods that `Context`
provides. This is a shame; these will make it much easier for users
implementing formatters to iterate over the scope of the event being
formatted correctly. We should expose those methods.
This branch adds new methods to `FmtContext`, most of which forward to
the similarly-named `Context` methods. However, because a `FmtContext`
is only constructed when formatting an event, we can also make the event
scope methods a little more ergonomic by storing a ref to the span being
formatted and automatically passing it to `Context::event_scope` and
`Context::event_span`. This means the `FmtContext` can just always return
the current event's scope without the …
=> subscriber: expose access to event scope in `FmtContext`

examples/Cargo.toml, tracing-appender/Cargo.toml, tracing-attributes/Cargo.toml, tracing-core/Cargo.toml, tracing-error/Cargo.toml, tracing-flame/Cargo.toml, tracing-futures/Cargo.toml, tracing-journald/Cargo.toml, tracing-log/Cargo.toml, tracing-macros/Cargo.toml, tracing-opentelemetry/Cargo.toml, tracing-serde/Cargo.toml, tracing-subscriber/Cargo.toml, tracing-tower/Cargo.toml, tracing/Cargo.toml
This branch adds the `[package.rust]` metadata to `Cargo.toml` for all
crates. See https://rust-lang.github.io/rfcs/2495-min-rust-version.html
for details.
=> chore: add MSRV cargo metadata

tracing-journald/src/lib.rs, tracing-journald/tests/journal.rs
See #1710: Do not write strings in Debug representation.
As discussed in #1710 writing strings literally makes tracing-journald behave like other journal clients, and allows 3rd party journal readers to extract the original value from the journal without having to "un"-parse the Debug representation of Rust strings.
=> tracing-journald: Write literal string values to journal

README.md, tracing/README.md, tracing/src/lib.rs
The test-env-log crate has been renamed to test-log to better reflect
its intent of not only catering to env_logger specific initialization
but also tracing (and potentially others in the future).
This change updates the documentation to reference test-log instead of
the now deprecated test-env-log.
=> docs: Mention test-log instead of test-env-log

examples/Cargo.toml, tracing-appender/Cargo.toml, tracing-attributes/Cargo.toml, tracing-core/Cargo.toml, tracing-error/Cargo.toml, tracing-flame/Cargo.toml, tracing-futures/Cargo.toml, tracing-journald/Cargo.toml, tracing-log/Cargo.toml, tracing-macros/Cargo.toml, tracing-opentelemetry/Cargo.toml, tracing-serde/Cargo.toml, tracing-subscriber/Cargo.toml, tracing-tower/Cargo.toml, tracing/Cargo.toml
https://github.com/tokio-rs/tracing/pull/1730 adds the Cargo MSRV field, however, the correct field name should be `rust-version`. See [The rust-version field](https://doc.rust-lang.org/nightly/cargo/reference/manifest.html#the-rust-version-field).
=> chore: fix cargo MSRV field typo

tracing-subscriber/src/fmt/format/mod.rs
The line of code that prints the event's fields (including its message)
was accidentally deleted in 0a16972ba4a5da5b9fd6534b9674d3df88652029,
while backporting PR #1696 from `master` (where the `Compact` formatter
implementation is significantly different).
This branch puts it back. Also, I've added tests for the `Compact` formatter's
output, to guard against accidentally breaking it in the future. Previously, we
only had tests for the `Full` and `Json` formatters.
Fixes #1741
=> subscriber: fix missing event fields in `Compact` formatter

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml
This release fixes a pair of regressions in `tracing-subscriber`'s `fmt`
module.
- **fmt**: Fixed missing event fields with `Compact` formatter ([#1755])
- **fmt**: Fixed `PrettyFields` formatter (and thus `format::Pretty`
event formatter) ignoring the `fmt::Layer`'s ANSI color code
configuration ([#1747])
[#1755]: https://github.com/tokio-rs/tracing/pull/1755
[#1747]: https://github.com/tokio-rs/tracing/pull/1747
=> subscriber: prepare to release 0.3.3

tracing-journald/Cargo.toml, tracing-journald/src/lib.rs, tracing-journald/src/memfd.rs, tracing-journald/src/socket.rs, tracing-journald/tests/journal.rs
See #1698: Properly write large payloads to journal.
I'd appreciate a very careful review; this cmsg stuff is nasty, and while it's well documented in `cmsg(3)` I had to fiddle a bit because the corresponding functions in libc aren't const and thus don't permit a direct allocation of the buffer as most `cmsg` C code around does.
Closes #1698
Linux limits the maximum amount of data permitted for a single Unix datagram; sending large payloads directly will fail.
Follow systemd.io/JOURNAL_NATIVE_PROTOCOL/ and check for EMSGSIZE from `send()`; in this case write the payload to a memfd, seal it, and pass it on to journald via a corresponding SCM_RIGHTS control message.
Per discussion in #1698 this adds no dependency on nix, and instead implements fd forwarding directly with some bits of unsafe …
=> tracing-journald: Send large journal payloads through memfd

tracing/README.md, tracing/src/lib.rs
As stated in the title.
Also synchronized the list between the README and lib.rs, as two crates were missing in the README.
=> Add tracing-fluent-assertions to related crates.

tracing-subscriber/src/field/mod.rs
=> subscriber: fix clippy needless borrow warning

assets/noindex.html, assets/warning.css, assets/warning.html, netlify.toml
This branch adds a warning header to documentation built from the
`master` branch, noting that this is _not_ documentation for the release
version, and suggesting that users refer to docs.rs for the release
documentation instead. Netlify is configured to include this header when
building documentation. This should make it clearer that documentation
built from `master` does _not_ document the currently documented release
versions on crates.io.
I'm very far from a web developer, so it's almost certainly possible
that the warning header could look nicer. I'll happily take suggestions
for improving the styling, but at least this gets the point across.
Additionally, I've added a [`noindex` meta tag][1] to the documentation's
HTML `<head>`. This should prevent it from showing up in search …
=> chore: add a warning header to docs built from `master`

tracing-journald/src/lib.rs, tracing-journald/src/socket.rs
Lets journald subscribers survive a journald restart.
Closes #1745
Currently the journald subscriber immediately connects to the journald socket.  As such I understand it'd not survive a full restart of journald.
Do not connect the client socket immediately; instead pass the socket pathname every time we send a message.  This is also what upstream does.
=> Use unconnected socket

tracing-opentelemetry/src/span_ext.rs
I was a little confused not to find a trait called `Extract` in the opentelemetry crate. Following the `TextMapPropagator` trait's `extract` function though I found that a reference to a `propagation::Extractor` is required instead.
I replaced `otel's 'Extract'` with `otel's Extractor`
=> docs: replace comments regarding otel's 'Extract' with 'Extractor'

tracing-core/src/subscriber.rs, tracing-subscriber/src/field/mod.rs
=> core: derive `Default` for `NoSubscriber`

tracing-flame/Cargo.toml, tracing-opentelemetry/src/span_ext.rs
The current version of tracing-flame on crates.io relies on tracing-subscriber 0.2. This release fixes that.
=> chore: prepare to release tracing-flame 0.2

tracing-appender/README.md
=> chore: backport #1780

.github/workflows/release.yml
Hopefully this should automatically publish a GitHub release with
each individual crate's changelog when an appropriate tag is pushed,
provided I haven't made a YAML mistake.
=> chore(CI): attempt to automate github releases

tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs
Before this PR there was one two many spaces between "on" and "ThreadId" when thread id formatting is enabled but thread name formatting is disabled.
There was no issue when both thread name and thread id were enabled.
Previous output:
```
2021-12-15T00:44:05.596510Z ERROR shotover_proxy::transforms::redis::cache: failed to fetch from cache: system.local not a caching table
at shotover-proxy/src/transforms/redis/cache.rs:366 on  ThreadId(5)
in shotover_proxy::server::request with id=5 source="CassandraSource"
```
new output:
```
2021-12-15T00:44:05.596510Z ERROR shotover_proxy::transforms::redis::cache: failed to fetch from cache: system.local not a caching table
at shotover-proxy/src/transforms/redis/cache.rs:366 on ThreadId(5)
in shotover_proxy::server::request with id=5 …
```
=> Fix pretty formatter thread id double space

tracing-core/src/dispatch.rs
This branch makes a small optimization to
`tracing-core::dispatch::get_default` in the case where only the global
default is in use. By factoring out the slow path, where we actually
perform a thread-local access to get the global default, into a second
function, it's now okay to always inline the fast path, since it's very
small. If the fast path fails because there _are_ scoped defaults in
use, we fall back to the slow path, a separate function call. This
should improve fast path performance significantly.
=> core: inline `get_default` global fast path

README.md
As a new user, I stumbled over a broken link and thought I'd fix it. Also noticed an unrelated open issue while searching for one about the broken link, and thought I'd fix that too.
Fix the typos.
=> fix README.md typo in example #1468

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release contains bugfixes for the `fmt` module, as well as documentation
improvements.
- **fmt**: Fixed `fmt` not emitting log lines when timestamp formatting fails
([#1689])
- **fmt**: Fixed double space before thread IDs with `Pretty` formatter
([#1778])
- Several documentation improvements ([#1608], [#1699], [#1701])
[#1689]: https://github.com/tokio-rs/tracing/pull/1689
[#1778]: https://github.com/tokio-rs/tracing/pull/1778
[#1608]: https://github.com/tokio-rs/tracing/pull/1608
[#1699]: https://github.com/tokio-rs/tracing/pull/1699
[#1701]: https://github.com/tokio-rs/tracing/pull/1701
Thanks to new contributors @Swatinem and @rukai for contributing to this
release!
=> subscriber: prepare to release v0.3.4

tracing/src/macros.rs
The current implementation triggers [`clippy::wildcard_imports`](https://rust-lang.github.io/rust-clippy/master/#wildcard_imports) warning.
Import items explicitly instead of using `*`.
=> Avoid wildcard imports

netlify.toml
The docs.rs documentation is built with `--all-features` enabled.
However, the Netlify docs build does not enable default-off feature
flags. This means the docs may not match what's built on docs.rs, and in
some cases also results in docs build _failures_ when documentation
links to code that's behind an off-by-default feature flag.
This commit changes the Netlify settings to enable all features.
=> docs: build Netlify docs with `--all-features`

tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/fmt/mod.rs
The removal of env-filter from the default features in 0.3.0 has caused a lot of developer frustration.
This PR addresses all of the issue I'm aware of, except #1329, in individual commits.
See the commit message for notes on the implementation and the related issues.
=> subscriber/fmt: address UX issues in defaults

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release re-enables `RUST_LOG` filtering in
`tracing_subscriber::fmt`'s default initialization methods, and adds an
`OffsetLocalTime` formatter for using local timestamps with the `time`
crate.
- **fmt**: Added `OffsetLocalTime` formatter to `fmt::time` for
formatting local timestamps with a fixed offset ([#1772])
- **fmt**: Added a `Targets` filter to `fmt::init()` and
`fmt::try_init()` when the "env-filter" feature is disabled, so that
`RUST_LOG` is still honored ([#1781])
Thanks to @marienz and @ishitatsuyuki for contributing to this release!
[#1772]: https://github.com/tokio-rs/tracing/pull/1772
[#1781]: https://github.com/tokio-rs/tracing/pull/1781
=> subscriber: prepare to release 0.3.5

tracing-journald/CHANGELOG.md, tracing-journald/Cargo.toml
This release improves how `tracing-journald` communicates with `journald`,
including the handling of large payloads.
- Use an unconnected socket, so that logging can resume after a `journald`
restart ([#1758])
- Fixed string values being written using `fmt::Debug` ([#1714])
- Fixed `EMSGSIZE` when log entries exceed a certain size ([#1744])
A huge thank-you to new contributor @lunaryorn, for contributing all of the
changes in this release!
[#1714]: https://github.com/tokio-rs/tracing/pull/1714
[#1744]: https://github.com/tokio-rs/tracing/pull/1744
[#1758]: https://github.com/tokio-rs/tracing/pull/1758
=> journald: prepare to release 0.2.1

tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/subscribe.rs
Apparently the links to the `Default::default()` methods didn't actually
work! Or, maybe they did work, but they don't on the latest nightly?
Regardless, this fixes them (as well as the RustDoc errors).
Should fix CI.
=> subscriber: fix broken docs links

tracing-journald/src/lib.rs
Set the `SYSLOG_IDENTIFIER` field on all events.  I noticed that the subscriber didn't do this so far.
The identifier is used with `journalctl -t`, and while it's normally better to filter by unit with `journalctl -u` the identifier is still nice for processes that are not started through systemd units.
Upstream does this as well, see [https://github.com/systemd/systemd/blob/81218ac1e14b4b50b4337938bcf55cacc76f0728/src/libsystemd/sd-journal/journal-send.c#L270]:
`program_invocation_short_name` is a glibc variable which holds the file name of the current executable; I tried to replicate this behaviour in Rust.
Add a syslog identifier field to the subscriber, defaulting to the filename of the current executable, and write this value as SYSLOG_IDENTIFIER with every event.  It's not written …
=> journald: Set syslog identifier

README.md, tracing/README.md
Currently, the documentation states in a few places that the
`tracing-futures` crate is required for asynchronous code to use
`tracing`. This is no longer the case, as `tracing` provides the
`Instrument` combinator for futures; `tracing-futures` is only needed
for things defined in the `futures` crate, such as `Stream` and `Sink`.
This branch updates the documentation so that it doesn't incorrectly
state that `tracing-futures` is required.
=> docs: don't state that `tracing-futures` is required

tracing-subscriber/src/fmt/format/pretty.rs
PR #1661 introduced a regression with the `Pretty` formatter: the
`PrettyVisitor` type was [accidentally changed][1] from being
constructed with `is_empty: true` to being constructed with 
`is_empty: false` This means that when visiting a set of span fields,
we emit a leading `, ` _before_ the first field, which looks quite bad.
This branch changes it back, and now the output looks nice again. :)
```
2022-01-13T17:09:04.772411Z TRACE fmt_pretty::yak_shave: hello! I'm gonna shave a yak, excitement: "yay!"
at examples/examples/fmt/yak_shave.rs:16 on main
in fmt_pretty::yak_shave::shave with , yak: 2
in fmt_pretty::yak_shave::shaving_yaks with , yaks: 3
```
```
2022-01-13T17:10:28.472525Z TRACE fmt_pretty::yak_shave: hello! I'm gonna shave a yak, excitement: "yay!"
at …
```
=> subscriber: fix leading comma with `Pretty` formatter

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release adds configuration options to `tracing_subscriber::fmt` to
log source code locations for events.
- **fmt**: Added `with_file` and `with_line_number` configuration
methods to `fmt::Format`, `fmt::SubscriberBuilder`, and `fmt::Layer`
([#1773])
- **fmt**: Removed incorrect leading comma from span fields with the
`Pretty` formatter ([#1833])
- **fmt**: Deprecated `Pretty::with_source_location`, as it can now be
replaced by the more general `Format`, `SubscriberBuilder`, and
`Layer` methods ([#1773])
Thanks to new contributor @renecouto for contributing to this release!
[#1773]: https://github.com/tokio-rs/tracing/pull/1773
[#1833]: https://github.com/tokio-rs/tracing/pull/1833
=> subscriber: prepare to release 0.3.6

tracing-journald/CHANGELOG.md, tracing-journald/Cargo.toml, tracing-journald/src/lib.rs
- Include a syslog identifier in log messages ([#1822])
- Added `Layer::with_syslog_identifier` method to override the syslog
identifier ([#1822])
Thanks to @lunaryorn for contributing to this release!
[#1822]: https://github.com/tokio-rs/tracing/pull/1822
=> journald: prepare to release 0.2.2

.github/workflows/check_msrv.yml, tracing-appender/Cargo.toml, tracing-appender/README.md
The `time` crate bumped its MSRV to 1.53.0 in v0.3.6:
https://github.com/time-rs/time/commit/2d37c01aff74bdccb8c537afa6bc7ce4f028048d
Since `tracing-appender` has a non-optional dependency on `time`, it's
necessary to increase its MSRV to track this.
=> appender: bump MSRV to 1.53.0

tracing-subscriber/Cargo.toml
Fixes https://rustsec.org/advisories/RUSTSEC-2022-0006.
`cargo audit` prevents us using `tracing-subscriber` at the moment. Upgrading `thread_local` to 1.1.4 would fix that.
Upgrade `thread_local`.
=> subscriber: update thread_local to 1.1.4

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release adds combinators for combining filters.
Additionally, this release also updates the `thread-local` crate to
v1.1.4, fixing warnings for the security advisory [RUSTSEC-2022-0006].
Note that previous versions of `tracing-subscriber` did not use any of
the `thread-local` crate's APIs effected by the vulnerability. However,
updating the version fixes warnings emitted by `cargo audit` and similar
tools.
- **filter**: Added combinators for combining filters ([#1578])
- **registry**: Updated `thread-local` to v1.1.4 ([#1858])
Thanks to new contributor @matze for contributing to this release!
[RUSTSEC-2022-0006]: https://rustsec.org/advisories/RUSTSEC-2022-0006
[#1578]: https://github.com/tokio-rs/tracing/pull/1578
[#1858]: https://github.com/tokio-rs/tracing/pull/1858
=> subscriber: prepare to release v0.3.7

README.md, tracing/README.md, tracing/src/lib.rs
We recently released a new version of the Rust SDK which has integration for `tracing`! 🎉
=> Add sentry-tracing to README/docs

.github/workflows/check_msrv.yml, examples/Cargo.toml, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/benches/trace.rs, tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/span_ext.rs, tracing-opentelemetry/src/subscriber.rs, tracing-opentelemetry/src/tracer.rs, tracing-opentelemetry/tests/trace_state_propagation.rs
Support the latest OpenTelemetry specification. Resolves #1857.
Update `opentelemetry` to the latest `0.17.x` release. Breaking changes upstream in the tracking of parent contexts in otel's `SpanBuilder` have necessitated a new `OtelData` struct to continue pairing tracing spans with their associated otel `Context`.
=> opentelemetry: Update otel to 0.17.0

tracing-subscriber/src/fmt/fmt_layer.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/layer/mod.rs
`SubscriberBuilder`s and `Layer`s configured with custom event/field formatters do not provide any means of accessing or mutating those formatters. Any configuration that needs to be done must be done before setting them on the builder/layer. This is frustrating as it makes it difficult to provide a pre-configured API akin to `tracing_subscriber::fmt()` along with accessors like `.compact()` that modify the formatter.
Add accessors `.map_event_format()` and `.map_fmt_fields()` to `SubscriberBuilder` and `Layer` that map the existing formatter through a closure. This allows the closure to modify it or to derive a new formatter from it with a different type.
Also add a `.map_writer()` method that does the same thing for the `MakeWriter`, to round out the accessors for the various type …
=> subscriber: Add `SubscriberBuilder`/`Layer` accessors

tracing/src/lib.rs, tracing/src/macros.rs
Change `concat!` -> `::core::concat!`
In my library I define a `macro_rules! concat` macro, i.e. [`callbag::concat`](https://docs.rs/callbag/latest/callbag/macro.concat.html).
When I try to call `tracing::info!(...)`, I get error output such as this:
<details>
<summary>error output</summary>
```
> RUSTFLAGS='-Z macro-backtrace' cargo +nightly clippy --features trace
Checking callbag v0.14.0 (/home/teohhanhui/projects/teohhanhui/callbag-rs)
error[E0308]: mismatched types
--> src/concat.rs:89:9
|
89 |         info!("from sink: {message:?}");
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ expected `&str`, found `u32`
error[E0277]: the trait bound `std::sync::Arc<core::Callbag<never::Never, _>>: std::convert::From<&str>` is not satisfied
--> src/concat.rs:58:9
|
56   | / macro_rules! concat {
57 …
```
=> Fix macro hygiene for `concat!` calls

.github/workflows/check_features.yml, tracing/test_static_max_level_features/Cargo.toml, tracing/test_static_max_level_features/tests/test.rs
The current tests for the compile-time maximum level were not being run in `--release` mode, and did not previously assert anything about `Span`s.
This also adds some test cases for various `#[instrument]`-ed functions.
=> Add static level tests for spans and instrumented fns

tracing/src/lib.rs
Since the formatting string is `"the answer to {} is {}.", question, answer`,
the value of `question` should be `"the ultimate question"`, not `"the answer to..."`.
=> Fix typo in "ultimate question" example snippet

tracing-opentelemetry/Cargo.toml
=> opentelemetry: revert "disable default `tracing-log` feature"

tracing-core/src/metadata.rs, tracing/src/macros.rs, tracing/tests/enabled.rs, tracing/tests/macros.rs
backporting https://github.com/tokio-rs/tracing/pull/1821
cherry-pick + really small adjustment to get it to compile and pass tests!
=> tracing: backport "implement enabled!"

examples/examples/valuable.rs, tracing-core/src/field.rs
This changes the `valuable` integration so that `record_value` takes
instances of `valuable::Value<'_>`, rather than `&dyn
valuable::Valuable` trait objects. The primary advantage of this is that
a `Value` can be produced by calling `Valuable::as_value`, so it allows
users to write code like this:
```rust
#[derive(Valuable, Debug)]
struct Foo {
// ...
}
tracing::trace!(foo = foo.as_value());
```
rather than this:
```rust
#[derive(Valuable, Debug)]
struct Foo {
// ...
}
tracing::trace!(foo = tracing::field::valuable(&foo));
```
which feels a bit more ergonomic. It also simplifies the code in
`tracing-core`, since we no longer need our own `ValuableValue` wrapper
type to turn things into trait objects.
It might also reduce boilerplate a bit on the visitor side, as
`as_value()` doesn't have …
=> core: record `Valuable` values as `valuable::Value`

tracing-core/src/field.rs
In #1881, I accidentally had the `Visit` trait take a `&Value<'_>`. This
was probably wrong, since `Value` is `Copy` and should only be a couple
words, one of which might be a pointer...so it's probably better to just
pass the `pointer + enum descriminant` (or `integer + enum descriminant`)
instead of passing `pointer to (pointer + enum descriminant)`.
This probably also makes the API a little nicer.
=> core: take `valuable` `Value`s by value

tracing-subscriber/Cargo.toml
tracing-subscriber depends on smallvec version `1`. When using minimal versions this resolves to version `1.0.0`. However, tracing-subscriber does not compile with smallvec 1.0.0. Instead, the actual minimum working version is `1.2.0`.
You can verify this by creating an app with `cargo new` that depends on tracing-subscriber, then set the versions to the minimum versions with command `cargo +nightly update -Z minimal-versions`. The app fails to compile.
tracing-subscriber declares a dependency on smallvec version `1`, which is incorrect. The minimum version is `1.2.0` (or `1.2`).
Because of this, some apps depending on tracing-subscriber cannot be built or tested when using minimal dependency versions.
Set smallvec dependency version to `1.2.0`.
=> subscriber: set smallvec minimum version to 1.2.0

examples/examples/valuable.rs, netlify.toml, tracing-core/Cargo.toml, tracing-core/src/field.rs, tracing-core/src/lib.rs, tracing/Cargo.toml, tracing/src/field.rs, tracing/src/instrument.rs, tracing/src/lib.rs
Depends on #1881
Right now, the `valuable` stuff isn't very discoverable --- enabling the
feature just adds some trait impls and stuff that aren't particularly
visible in the documentation. This PR adds some top-level docs on using
`valuable`. In particular:
- Added a section to the `tracing` and `tracing-core` lib.rs docs
explaining the unstable features versioning policy and how to turn on
unstable features
- Added a section in the `field` module that explains how to use
`valuable` to record fields.
- It turns out the `tracing::field` module didn't really have docs,
since it doesn't re-export the `tracing_core::field` module but
re-exports its _types_ in a new module (because it adds a trait). It
had a single line of docs that just said something about "structured
key-value data". I …
=> docs: document `valuable` support

tracing-core/src/metadata.rs
This changes the `Kind` type to a bitflag, in order to represent
callsites that are hints but also count as spans or events. The goal
here is to allow variants of the `enabled!` macro that specifically
check if a span would be enabled, or if an event would be enabled.
See [this comment][1] for details.
This does not actually implement the `enabled!` variants, just the
`Kind` representation change. This way, we can add to the `enabled!`
macro in a subsequent `tracing` release without having to change
`tracing-core` again.
I went with the bitflag representation rather than adding a bool to the
`KindInner::Span` and `KindInner::Event` enum variants because it felt a
bit simpler and maybe more performant, although I don't think it's
particularly important to micro-optimize here. I'd consider …
=> core: change `metadata::Kind` to a bitflag

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
Breaking changes in this release:
- Upgrade to `v0.17.0` of `opentelemetry` (#1853)
For list of breaking changes in OpenTelemetry, see the [v0.17.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0170).
- Disable the default `tracing-log` feature (#1869)
=> opentelemetry: prepare for 0.16.0 release

tracing-subscriber/src/fmt/format/mod.rs
This fixes outdated statements in the docs for the `Full` and `Compact`
logging formats.
Closes #1880.
=> subscriber: fix incorrect formatter docs

.github/workflows/CI.yml, examples/examples/valuable_instrument.rs, tracing-core/src/field.rs
Currently, the `valuable` support requires the `tracing_unstable` cfg to
be set. Because none of our current CI jobs set this, we aren't
currently testing that code, and have no way of even ensuring that it
compiles. This is Bad.
This PR adds a CI job to run tests with the unstable cfg enabled.
=> ci: add `tracing_unstable` to CI

tracing-core/CHANGELOG.md, tracing-core/README.md, tracing-core/src/lib.rs
This release adds *experimental* support for recording structured field
values using the [`valuable`] crate. See [this blog post][post] for
details on `valuable`.
Note that `valuable` support currently requires `--cfg
tracing_unstable`. See the documentation for details.
- **field**: Experimental support for recording field values using the
[`valuable`] crate ([#1608], [#1888], [#1887])
- **field**: Added `ValueSet::record` method ([#1823])
- **subscriber**: `Default` impl for `NoSubscriber` ([#1785])
- **metadata**: New `Kind::HINT` to support the `enabled!` macro in
`tracing` ([#1883], [#1891])
- Fixed a number of documentation issues ([#1665], [#1692], [#1737])
Thanks to @xd009642, @Skepfyr, @guswynn, @Folyd, and @mbergkvist for
[`valuable`]: …
=> core: prepare to release v0.1.22

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs, tracing/Cargo.toml
This release introduces a new `#[instrument(ret)]` argument to emit an
event with the return value of an instrumented function.
- `#[instrument(ret)]` to record the return value of a function
([#1716])
- added `err(Debug)` argument to cause `#[instrument(err)]` to record
errors with `Debug` rather than `Display ([#1631])
- incorrect code generation for functions returning async blocks
([#1866])
- incorrect diagnostics when using `rust-analyzer` ([#1634])
Thanks to @Swatinem, @hkmatsumoto, @cynecx, and @ciuncan for
[#1716]: https://github.com/tokio-rs/tracing/pull/1716
[#1631]: https://github.com/tokio-rs/tracing/pull/1631
[#1634]: https://github.com/tokio-rs/tracing/pull/1634
[#1866]: https://github.com/tokio-rs/tracing/pull/1866
=> attributes: prepare to release 0.1.19

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This release adds *experimental* support for recording structured field
values using the [`valuable`] crate. See [this blog post][post] for
details on `valuable`.
Note that `valuable` support currently requires `--cfg
tracing_unstable`. See the documentation for details.
This release also adds a new `enabled!` macro for testing if a span or
event would be enabled.
- **field**: Experimental support for recording field values using the
[`valuable`] crate ([#1608], [#1888], [#1887])
- `enabled!` macro for testing if a span or event is enabled ([#1882])
- `tracing-core`: updated to [0.1.22][core-0.1.22]
- `tracing-attributes`: updated to [0.1.19][attributes-0.1.19]
- **log**: Fixed "use of moved value" compiler error when the "log"
feature is enabled ([#1823])
- Fixed macro hygiene issues …
=> tracing: prepare to release 0.1.30

tracing-serde/src/lib.rs, tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/lib.rs
This PR adds documentation on `valuable` support in `tracing-serde` and
`tracing-subscriber`.
=> docs: document `tracing-subscriber` `valuable` support

tracing-subscriber/src/filter/directive.rs, tracing-subscriber/src/filter/targets.rs
As discussed on discord, this API + `Targets` being `: Clone` makes it easier to solve the original problem I had tried to solve in https://github.com/tokio-rs/tracing/pull/1889.
My plan on how to use this is in https://github.com/MaterializeInc/materialize/issues/10441 if you are interested!
I considered doing some macro magic to create a `Metadata` with a callsite and empty fields and everything, to be able to called `DirectiveSet::enabled`, but it felt cleaner and easier to reason about the special-case-ness (`Targets` never having field filters) using a new set of methods that do a similar thing.
For testing I opted for just a doc-test, let me know if thats fine!
=> implement `Targets::enabled_for`

tracing-serde/CHANGELOG.md, tracing-serde/Cargo.toml, tracing-serde/README.md, tracing-serde/src/lib.rs, tracing-subscriber/Cargo.toml
This release adds *experimental* support for recording structured field
values using the [`valuable`] crate. See [this blog post][post] for
details on `valuable`.
Note that `valuable` support currently requires `--cfg
tracing_unstable`. See the documentation for details.
- **valuable**: Experimental support for serializing user-defined types
using [`valuable`] and [`valuable-serde`] ([#1862])
- Support for serializing `f64` values ([#1507])
- Fixed incorrect size hint in `SerializeFieldSet` ([#1333])
- A number of documentation fixes
Thanks to @akinnane and @maxburke for contributing to this release!
[`valuable`]: https://crates.io/crates/valuable
[`valuable-serde`]: https://crates.io/crates/valuable-serde
[post]: https://tokio.rs/blog/2021-05-valuable
[#1862]: …
=> serde: prepare to release 0.1.3

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release adds *experimental* support for recording structured field
values using the [`valuable`] crate to the `format::Json` formatter. In
particular, user-defined types which are recorded using their
[`valuable::Valuable`] implementations will be serialized as JSON
objects, rather than using their `fmt::Debug` representation. See [this
blog post][post] for details on `valuable`.
Note that `valuable` support currently requires `--cfg
tracing_unstable`. See the documentation for details.
Additionally, this release includes a number of other smaller API
improvements.
- **json**: Experimental support for recording [`valuable`] values as
structured JSON ([#1862], [#1901])
- **filter**: `Targets::would_enable` method for testing if a `Targets`
filter would enable a given target ([#1903]) …
=> subscriber: prepare to release v0.3.8

tracing-journald/src/memfd.rs
Fixes #1879
`journald-tracing>=0.2.1` doesn't build with old glibc.
Make the `memfd_create` syscall ourselves.
cc @lunaryorn @Ralith
=> Make `memfd_create` syscall directly

tracing-journald/CHANGELOG.md, tracing-journald/Cargo.toml
- Fixed missing `memfd_create` with `glibc` versions < 2.25 ([#1912])
- Updated minimum supported Rust version to 1.49.0 ([#1913])
Thanks to @9999years for contributing to this release!
[#1912]: https://github.com/tokio-rs/tracing/pull/1912
=> journald: prepare to release v0.2.3

tracing-opentelemetry/src/subscriber.rs
=> opentelemetry: forward event metadata

tracing-opentelemetry/src/subscriber.rs
Currently, the `tracing-opentelemetry` subscriber will allocate several
strings for opentelemetry key-value fields in its `on_event`
implementation. Some of these allocations are not necessary, since
`opentelemetry::Value::String` can take a `Cow`, allowing `&'static str`s
to be used without allocating a new `String`.
Since this happens for _every_ event that's recorded to opentelemetry,
this probably has a meaningful performance impact.
This branch makes two primary changes:
+ Change the `on_event` method to subscriber to use `&'static str`s for
event targets when possible, similarly to how we did this for source
locations in #1911. This way, when events were not recorded via the
`tracing-log` adapter, we will use the `&'static` tracing metadata
string for their targets, rather than …
=> opentelemetry: allocate fewer strings for recording events

examples/README.md, examples/examples/fmt-compact.rs, tracing-subscriber/src/fmt/format/mod.rs
Currently, the RustDoc for the `format::Compact` formatter in
`tracing-subscriber` describes the output from the `master` (v0.2.x)
version of the formatter, not the version on the v0.1.x branch.
This PR updates the documentation to describe the actual output format.
Also, I added an example of the formatter in the `examples` directory.
Closes #1909
=> docs: update `Compact` formatter docs

tracing/src/macros.rs
tracing:  Fix wrong log level in warn macro
Fixes: #1929
=> tracing: Fix wrong log level in warn macro  #1929

tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs, tracing-subscriber/src/fmt/mod.rs
Currently, the documentation for the `fmt` module shows examples of the
output for each formatter in the top-level module. This is a lot of text
that makes finding other things in the documentation more difficult.
Meanwhile, the type-level docs for the various formatters are quite
terse and don't offer much useful information.
This branch moves the example output to the type-level docs for the
various formatters, and links to it from the list of formatters. I've
also updated and expanded some of the documentation for the formatters,
and added a similar list of formatters to the `fmt::format` module.
Hopefully, this makes things easier to navigate?
Finally, I've re-generated all example output with the latest versions
of each formatter.
Alternatively, we could not move the example output. …
=> docs: clean up `tracing_subscriber::fmt` formatter docs

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This release increases the minimum supported Rust version (MSRV) to
1.49.0. In addition, it fixes some relatively rare macro bugs.
- Added `tracing-forest` to the list of related crates ([#1935])
- Updated minimum supported Rust version (MSRV) to 1.49.0 ([#1913])
- Fixed the `warn!` macro incorrectly generating an event with the
`TRACE` level ([#1930])
- Fixed macro hygiene issues when used in a crate that defines its own
`concat!` macro, for real this time ([#1918])
Thanks to @QnnOkabayashi, @nicolaasg, and @teohhanhui for contributing
[#1935]: https://github.com/tokio-rs/tracing/pull/1935
[#1930]: https://github.com/tokio-rs/tracing/pull/1930
[#1918]: https://github.com/tokio-rs/tracing/pull/1918
=> tracing: prepare to release v0.1.31

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release updates the minimum supported Rust version (MSRV) to
1.49.0, and updates the (optional) dependency on `parking_lot` to v0.12.
- Updated minimum supported Rust version (MSRV) to 1.49.0 ([#1913])
- `parking_lot`: updated to v0.12 ([008339d])
- **fmt**: Documentation improvements ([#1926], [#1927])
[#1926]: https://github.com/tokio-rs/tracing/pull/1926
[#1927]: https://github.com/tokio-rs/tracing/pull/1927
[008339d]: https://github.com/tokio-rs/tracing/commit/008339d1e8750ffe7b4634fc7789bda0c522424f
=> subscriber: prepare to release v0.3.9

.github/workflows/check_features.yml, tracing-opentelemetry/src/subscriber.rs
Currently, `tracing-opentelemetry` v0.17.1 fails to compile with
`default-features = false`. This is because there's a `let` binding for
`normalized_metadata` with a `None` where the `Some` type can't be
inferred. This managed to slip past CI and get released because we were
never actually building the crate with its default features disabled, an
oversight in our CI configuration.
This branch fixes the issue by adding an explicit type annotation to the
`let` binding, so the `Option`'s type is known and the type error no
longer occurs. I also removed a feature-flagged import that was not
actually used.
I also added `tracing-opentelemetry` to the `cargo hack` CI job. This
way, we will now ensure that all its feature combinations are built on
CI (including no features), which should prevent …
=> opentelemetry: fix broken build with `default-features = false`

.github/workflows/check_features.yml, tracing-opentelemetry/src/layer.rs
Currently, `tracing-opentelemetry` v0.17.1 fails to compile with
`default-features = false`. This is because there's a `let` binding for
`normalized_metadata` with a `None` where the `Some` type can't be
inferred. This managed to slip past CI and get released because we were
never actually building the crate with its default features disabled, an
oversight in our CI configuration.
This branch fixes the issue by adding an explicit type annotation to the
`let` binding, so the `Option`'s type is known and the type error no
longer occurs. I also removed a feature-flagged import that was not
actually used.
I also added `tracing-opentelemetry` to the `cargo hack` CI job. This
way, we will now ensure that all its feature combinations are built on
CI (including no features), which should prevent …
=> opentelemetry: fix broken build with `default-features = false` (#1949)

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
This release fixes [an issue][#1944] introduced in v0.17.1 where
`tracing-opentelemetry` could not be compiled with
`default-features = false`.
- Compilation failure with `tracing-log` feature disabled ([#1949])
[#1949]: https://github.com/tokio-rs/tracing/pull/1917
[#1944]: https://github.com/tokio-rs/tracing/issues/1944
=> opentelemetry: prepare to release v0.17.2

bin/publish
This adds a check to the `bin/publish` script that the crate being
published builds successfully with all possible feature combinations,
using `cargo hack --feature-powerset`.
This would have prevented https://github.com/tokio-rs/tracing/issues/1944.
We test this on CI for most crates in the repo, but it's disabled for some
crates because the powerset is very large, making the check too slow
to run on CI. However, adding it to the publish script will ensure that it's
at least always run before publishing a crate.
=> chore: add `cargo hack` check to `bin/publish`

tracing-subscriber/src/fmt/format/mod.rs
Clippy now warns about code that calls `.map(...).flatten()` on an
iterator and suggests `.flat_map(...)` instead:
https://rust-lang.github.io/rust-clippy/master/index.html#map_flatten
This branch fixes one place where we do that. CI should be happy again.
=> subscriber: fix `clippy::map_flatten` lint

tracing-attributes/Cargo.toml
This sets the minimal version of `syn` to `1.0.43` - the actual minimal version that is required to build `tracing-attributes`.
See this build failure in Tokio: https://github.com/tokio-rs/tokio/runs/5344598894?check_suite_focus=true
CC: tokio-rs/tokio#4513
=> Set minimal version of syn

tracing-appender/CHANGELOG.md, tracing-appender/Cargo.toml, tracing-appender/README.md, tracing-appender/src/lib.rs
This release adds an implementation of the `MakeWriter` trait for
`RollingFileAppender`, allowing it to be used without wrapping in a
`NonBlocking` writer.
This release increases the minimum supported Rust version to 1.53.0.
- **rolling**: Added `MakeWriter` implementation for
`RollingFileAppender` ([#1760])
- Updated minimum supported Rust version (MSRV) to 1.53.0 ([#1851])
- `parking_lot`: updated to v0.12 ([#1878])
- Fixed several documentation typos and issues ([#1780], [d868054],
[#1943])
[#1760]: https://github.com/tokio-rs/tracing/pull/1760
[#1851]: https://github.com/tokio-rs/tracing/pull/1851
[#1878]: https://github.com/tokio-rs/tracing/pull/1878
[#1943]: https://github.com/tokio-rs/tracing/pull/1943
[d868054]: https://github.com/tokio-rs/tracing/commit/d8680547b509978c7113c8f7e19 …
=> appender: prepare to release v0.2.1

tracing-subscriber/src/filter/layer_filters/mod.rs, tracing-subscriber/src/reload.rs
Partially fixes #1629 (I think making `reload::Handle::reload` work with `Filtered` would be cleaner, but this approach seemed easier to me)
I assumed opening the PR against v0.1.x is correct as I couldn't find the `Filtered` type in master.
I think it'd be sensible to note the fact that `reload::Handle::reload` doesn't work with `Filtered` in the docs somewhere, should I add that?
Changing the filter of a `Filtered` at runtime is currently only possible by replacing it with a new `Filtered` via the `reload::Handle::reload` method.
This currently doesn't work as the new `Filtered` won't receive a `FilterId` (see https://github.com/tokio-rs/tracing/issues/1629).
While it would be desirable to just make that work, it would only be possible via a breaking change (according to Eliza) so this …
=> subscriber: add Filtered::filter_mut

tracing-subscriber/src/filter/targets.rs
The link `[global]` is defined at the bottom (and already used in line 32), so I used it here as well
=> Fix broken link in Targets rustdoc

tracing-core/src/dispatch.rs, tracing/benches/no_subscriber.rs, tracing/src/span.rs
Disabled spans introduce a non-trivial amount of overhead, even when no
`tracing` subscriber is in use. This is primarily due to the need to
create and then drop the empty `Span` struct even when the span is
disabled.
While thinking about #1970 a bit, I noticed that one source of overhead
is that dropping a disabled span always causes a function call, even
when the span is empty. This could be avoided.
In this branch, I've changed the `Drop` impls for `Span`, `Entered`, and
`EnteredSpan` to be `#[inline(always)]`. In the always-inlined
functions, we perform a check for whether or not the span is empty, and
if it is not empty, we call into the dispatcher method to drop the span
or guard. The dispatcher methods are no longer inlined. Now, the
function call only occurs when the span _is_ …
=> tracing: reduce disabled span `Drop` overhead

tracing-subscriber/src/filter/layer_filters/combinator.rs, tracing-subscriber/src/filter/layer_filters/mod.rs, tracing-subscriber/src/layer/mod.rs
Related to https://github.com/tokio-rs/tracing/issues/1955
Call those methods in the Layer methods for Filtered and delegate them in the filter combinators
Currently, if a Filter is going to implement dynamic filtering, it must do this by querying the wrapped Subscriber for the current span context. Since Filter only has callsite_enabled and enabled methods, a Filter implementation cannot track the span context internally, the way a Layer can.
Unfortunately, this means that the current implementation of EnvFilter can only implement Layer (and provide global filtering). It cannot currently implement Filter, because it stores span context data internally. See https://github.com/tokio-rs/tracing/issues/1868 for details.
We should add on_new_span, on_enter, on_exit, and on_close methods to …
=> Add new filter methods

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs
- Compilation failure with `--minimal-versions` due to a too-permissive
`syn` dependency ([#1960])
- Bumped minimum supported Rust version (MSRV) to 1.49.0 ([#1913])
Thanks to new contributor @udoprog for contributing to this release!
[#1960]: https://github.com/tokio-rs/tracing/pull/1960
=> attributes: prepare to release v0.1.20

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
- Removed `#[inline]` attributes from some `Dispatch` methods whose
callers are now inlined ([#1974])
- Bumped minimum supported Rust version (MSRV) to Rust 1.49.0 ([#1913])
[#1974]: https://github.com/tokio-rs/tracing/pull/1974
=> core: prepare to release 0.1.23

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This release reduces the overhead of creating and dropping disabled
spans significantly, which should improve performance when no `tracing`
subscriber is in use or when spans are disabled by a filter.
- **attributes**: Compilation failure with `--minimal-versions` due to a
too-permissive `syn` dependency ([#1960])
- Reduced `Drop` overhead for disabled spans ([#1974])
- `tracing-attributes`: updated to [0.1.20][attributes-0.1.20]
[#1974]: https://github.com/tokio-rs/tracing/pull/1974
[#1960]: https://github.com/tokio-rs/tracing/pull/1960
[attributes-0.1.20]: https://github.com/tokio-rs/tracing/releases/tag/tracing-attributes-0.1.20
=> tracing: prepare to release 0.1.32

.github/workflows/check_features.yml, bin/publish
The `tracing`' crate's feature powerset is kind of unmanageably huge due
to the large number of `max_level_XXX` and `release_max_level_XXX`
feature flags. This is why we currently _don't_ run a `cargo-hack`
feature powerset check for it on CI. However, I forgot about that when I
added feature powerset checks to the `bin/publish` script, so publishing
a `tracing` release results in a combinatorial explosion that takes a
*very* long time to complete.
It turns out that `cargo-hack` actually has flags for controlling what
features are included in the powerset (`--include-features` and
`--exclude-features`). This branch modifies `bin/publish` to use those
flags when checking the `tracing` and `tracing-subscriber` crate.
Additionally, I've modified the CI `cargo-hack` job to use the same
flags, …
=> chore: avoid giant feature powersets using `cargo-hack`

tracing-appender/src/rolling.rs
This branch fixes a bug in `RollingFileAppender` where
`compare_exchange` is called with the _current timestamp_ as the
"current value" of the next rollover timestamp, rather than the actual
current value. This means that if the current time is *greater* than the
rollover time, the CAS will fail and the appender will never roll over
--- currently, rolling only functions correctly if we try to write to
the file at *precisely* the rollover time. This means that, in practice,
the appender almost never rolls over.
I've fixed this by ensuring that the compare-and-swap is always
performed with the current value of the atomic, rather than the current
timestamp. `should_rollover` now returns an `Option` with the current
value in it to indicate it's time to roll over, so that we perform the
CAS …
=> appender: fix incorrect compare_exchange when rolling 

tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/filter/env/field.rs
Using a crate like Clap, it's possible to support directive validation:
```rust
#[derive(clap::Args, Debug)]
pub(crate) struct Intrumentation {
// ...
/// Tracing directives (see https://docs.rs/tracing-subscriber/latest/tracing_subscriber/filter/struct.EnvFilter.html#directives)
#[clap(long, global = true, group = "verbosity", multiple_occurrences = true)]
pub(crate) log_level: Vec<Directive>,
}
```
Resulting in nice runtime validation errors:
```
$ cargo run -- --log-level h2=tra
Finished dev [unoptimized + debuginfo] target(s) in 0.06s
Running `target/debug/refuge --log-level h2=tra`
error: Invalid value "h2=tra" for '--log-level <LOG_LEVEL>': invalid filter directive
For more information try --help
```
Then later, we can build up an `EnvFilter` with these directives:
```rust
let mut …
```
=> Implement Clone for Directive, Match

tracing-journald/src/memfd.rs
I would like to use tracing-journald on a 32 bit target (armv7).
On 32 bit targets (e.g. armv7) the syscall in memfd_create_syscall()
returns an i32, so this compilation error is printed:
```
| error[E0308]: mismatched types
|   --> .../tracing-journald-0.2.3/src/memfd.rs:27:9
|    |
| 25 |   fn memfd_create_syscall(flags: c_uint) -> i64 {
|    |                                             --- expected `i64`
|    |                                           because of return type
| 26 |       unsafe {
| 27 | /         syscall(
| 28 | |             SYS_memfd_create,
| 29 | |             "tracing-journald\0".as_ptr() as *const c_char,
| 30 | |             flags,
| 31 | |         )
|    | |_________^ expected `i64`, found `i32`
|    |
| help: you can convert an `i32` to an `i64`
|    |
| 31 | …
```
=> journald: fix memfd_create_syscall for 32 bit targets

tracing-core/src/field.rs
Use the fact that the `Debug` implementation of `DisplayValue`
corresponds to the `Display` implementation of the wrapped type. This
means that the string allocation of the `Display`ed type can be avoided
entirely.
=> Use less allocations in recording `Display` and `Error` values

tracing-journald/CHANGELOG.md, tracing-journald/Cargo.toml, tracing-journald/README.md
- Fixed compilation error in `memfd_create_syscall` on 32-bit targets
([#1982])
Thanks to new contributor @chrta for contributing to this release!
[#1982]: https://github.com/tokio-rs/tracing/pull/1982
=> journald: prepare to release 0.2.4

tracing-appender/CHANGELOG.md, tracing-appender/Cargo.toml, tracing-appender/README.md, tracing-appender/src/lib.rs
This release fixes an incorrect `compare_exchange` in RollingFileAppender 
when rolling files over, causing a panic.
- **rolling**: Fixed a panic that prohibited rolling files over. ([#1989])
[#1989]: https://github.com/tokio-rs/tracing/pull/1989
=> appender: prepare to release 0.2.2

tracing-subscriber/src/reload.rs
Missing example was noticed in https://github.com/tokio-rs/tracing/pull/1959#discussion_r816248186
Should the descriptions of the examples distinguish global filtering and per-layer filtering a bit more explicitly?
=> Add example for reloading a global filtering layer

tracing-core/src/collect.rs, tracing-core/src/dispatch.rs
This branch forward-ports PRs #1549 and #1785 from `v0.1.x`.
=> core: forward-port `NoCollector`

tracing-core/src/dispatch.rs, tracing/tests/no_collector.rs
Currently, it is not actually possible to use `set_default(NoCollector)`
or similar to temporarily disable the global default collector (see
#1999).
This is because `NoCollector` is currently used as a placeholder value
when the thread-local cell that stores the current scoped default
collector is initialized. Therefore, we currently check if the current
scoped collector is `NoCollector`, and if it is, we fall back to
returning the global default instead.
This was fine, _when `NoCollector` was a private internal type only_.
However, PR #1549 makes `NoCollector` into a public API type. When users
can publicly construct `NoCollector` instances, it makes sense to want
to be able to use `NoCollector` to disable the current collector. This
is not possible when there is a global default set, …
=> core: don't use NoCollector as local placeholder 

.github/workflows/check_features.yml, bin/publish, tracing-core/src/dispatcher.rs, tracing-core/src/field.rs, tracing/tests/no_subscriber.rs
This branch backports the following changes:
* 35ab8c03 core: don't use NoSubscriber as local placeholder  (#2001)
* b817ca0c core: avoid unnecessary `format_args!` and `write!` macros (#1988)
* 74eaf1ee chore: avoid giant feature powersets using `cargo-hack` (#1984)
=> backport recent changes to v0.1.x

tracing-subscriber/src/filter/layer_filters/mod.rs
Currently, the `Filtered` type's `Layer` impl accidentally calls the
inner `Filter`'s `on_enter` hook in the `on_exit` hook. This
is...obviously wrong, lol, and means that filters like `EnvFilter` will
never consider spans to have exited, breaking filtering behavior.
@tfreiberg-fastly originally noticed this bug (see
https://github.com/tokio-rs/tracing/pull/1983#issuecomment-1076174188),
but I wanted to make the change separately from PR #1983 so that we can
fix it on the main branch without waiting for #1983 to merge first.
This branch, uh, you know... fixes that.
=> subscriber: fix `Filtered::on_exit` calling `on_enter` by mistake

tracing-subscriber/src/filter/layer_filters/combinator.rs, tracing-subscriber/src/filter/layer_filters/mod.rs, tracing-subscriber/src/layer/mod.rs
Currently, `Filter` only has the `on_new_span`, `on_enter`, `on_exit`,
and `on_close` callbacks. This means it won't handle cases where a
span records a new field value that changes its filter state.
This branch adds the missing `on_record` callback.
=> subscriber: add `Filter::on_record` callback

tracing-core/src/spin/mutex.rs, tracing-core/tests/dispatch.rs
Currently, compiling `tracing-core` with `default-features = false`
(i.e. for `no_std` targets) emits a few warnings. This is due to the
spinlock implementation's use of the deprecated `atomic::spin_loop_hint`
function (renamed to `hint::spin_loop`), and the use of deprecated
`compare_and_swap` instead of `compare_exchange` methods. Now that our
MSRV is 1.49 (the version in which `hint::spin_loop` was stabilized), we
can fix these warnings.
This branch replaces the deprecated APIs. 
Also, I noticed that one of the tests emits unused-imports warnings with
`--no-default-features`. This is because the actual tests are feature
flagged to require `std`, but the module itself doesn't, so the imports
are just hanging out and not getting used for anything. I went ahead and
fixed that as well.
=> core: fix warnings when compiling without `std`

tracing-subscriber/src/subscribe/mod.rs
Currently, there is an `impl<C: Collect> Subscribe for Box<dyn
Subscribe<C>>` intended to allow type-erasing a subscriber.
Unfortunately, however, this impl is...completely and utterly useless.
In order to be set as the default, a collector must be `Send + Sync +
'static`. Because the boxed trait object does not bound the subscriber
with these traits, adding a boxed subscriber to a collector will make
that collector impossible to use. This means that a `Box<dyn
Subscribe<C>>` has no practical purpose whatsoever.
This branch adds an `impl<C: Collect> for Box<dyn Subscribe<C> + Send +
Sync + 'static>`, and removes the useless impl.
In addition, I've improved the documentation on runtime configuration of
subscribers to include an example of using `Box` to type-erase a
subscriber. This is, …
=> subscriber: make boxed subscribers not useless

tracing-subscriber/src/subscribe/mod.rs
RustDoc didn't actually parse the link to the `Subscribe` impl for
`Box<dyn Subscribe<C> + Send + Sync + 'static>` because the link URL
contained unescaped spaces. Therefore, the link reference was treated as
normal text rather than as a link reference.
This commit replaces the link ref with the escaped version, which works
correctly. My bad!
=> subscriber: fix docs link to `Subscribe` impl for `Box`

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/subscribe/mod.rs
Depends on #2023 
Currently, `FmtSubscriber` holds a `PhantomData<C>` with the `Collect`
type it wraps. This is unfortunate because it means that the
subscriber's auto traits such as `Send`, `Sync`, and `'static` (as well
as `UnwindSafe`, `Unpin`, etc) depend on the collector type's auto
traits...but the subscriber will never actually _store_ a value of type
`C`. While all collectors will be `Send + Sync + 'static` in practice,
the `PhantomData` means that functions returning a boxed `FmtSubscriber`
must unnecessarily bound the collector type parameter.
This commit changes the `PhantomData` to `PhantomData<fn(C)>`, solving
the problem.
=> subscriber: make `FmtSubscriber`'s auto traits not depend on `C`

tracing-subscriber/src/subscribe/mod.rs
PR #2023 made the `impl Subscribe` for boxed `dyn Subscribe` trait
objects actually be useful. One minor annoyance when working with boxed
trait objects is that, in some cases, in order to use `Box::new` to
erase a subscriber's type, it's necessary to add a type annotation like
this:
```rust
let boxed_subscriber: Box<dyn Subscribe<_> + Send + Sync + 'static>
= Box::new(some_subscriber);
```
Because the trait object includes `Send + Sync + 'static`, this is a bit
wordy to type out.
This commit adds a `Subscribe::boxed` method that takes `Self` and boxes
it as a type-erased `dyn Subscribe` trait object. This can then be
chained after a a chain of subscriber builder methods. Because the
`boxed` method _explicitly_ returns a `dyn Subscribe + ...` trait
object, it's not necessary to use a …
=> subscriber: add `Subscribe::boxed` method

tracing-subscriber/src/subscribe/mod.rs
Turns out the `Subscribe` impl for `Box<dyn Subscribe<...> + ...>` never
called the subscriber trait object's `register_callsite` method. Whoops!
This commit adds the missing `register_callsite` hook.
=> subscriber: fix missing `register_callsite` for `Box<dyn Subscribe>`

tracing-subscriber/src/filter/env/mod.rs
EnvFilter with ansi_term will say something like the following when statically disabled filters are present:
```
warning: some trace filter directives would enable traces ...
= note: the static max level is `LEVEL`
= help: to enable LEVEL logging, ...
```
Without the ansi_term feature, it instead says something like the following:
```
warning: some trace filter directives would enable traces ...
note: the static max level is `LEVEL`
note: to enable LEVEL logging, ...
```
This is due to a simple error in cfg'd code that ignores the requested prefix and always uses `note:` when `not(feature = "ansi_term")`.
Use the unused `prefix` variable to do what it does when `feature = "ansi_term"`.
The output without ansi_term is now
```
warning: some trace filter directives would enable traces ... …
```
=> Let `EnvFilter`'s filter disabled help say "help" without ansi_term

tracing-subscriber/src/subscribe/mod.rs
Currently, the implementation of `Subscribe` for
`Box<dyn Subscribe<C> + ...>` does not implement the `max_level_hint`
method. This means that if the boxed subscriber has a max level hint, it
will be lost when boxing a subscriber.
Found this while working on tests for #2027.
This commit adds the missing method implementation.
=> subscriber: fix boxed subscriber not forwarding `max_level_hint`

tracing-subscriber/src/filter/subscriber_filters/mod.rs, tracing-subscriber/src/fmt/fmt_subscriber.rs
This adds more modification methods for use with reloading. Replaces #2032.
Needs fixes in doc tests.
I have a Filtered layer that I'd like to modify with a reload handle. If I use `reload` then the filter doesn't work. If I use `modify` with `filter_mut` I can't update the writer. 
Adds some additional accessor methods to allow the writer to be modified in `modify`.
=> More layer modification

tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/filter/env/mod.rs
Currently, `EnvFilter` will always interpret all field value filter
directives that are not numeric,or boolean literals as regular
expressions that are matched against a field's `fmt::Debug` output. In
many cases, it may not be desirable to use regular expressions in this
case, so users may prefer to perform literal matching of `fmt::Debug`
output against a string value instead. Currently, this is not possible.
This branch introduces the ability to control whether an `EnvFilter`
interprets field value `fmt::Debug` match filters as regular expressions
or as literal strings. When matching literal `fmt::Debug` patterns, the
string is matched without requiring a temporary allocation for the
formatted representation by implementing `fmt::Write` for a matcher type
and "writing" the field's …
=> subscriber: add `EnvFilter::builder`, option to disable regex

tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/filter/layer_filters/mod.rs, tracing-subscriber/src/fmt/fmt_layer.rs, tracing-subscriber/src/layer/mod.rs, tracing-subscriber/tests/layer_filters/main.rs, tracing-subscriber/tests/layer_filters/vec.rs, tracing-subscriber/tests/vec_subscriber_filter_interests_cached.rs, tracing/src/macros.rs, tracing/tests/enabled.rs, tracing/tests/macros.rs
this backports some stuff from `master`
=> backport tracing subscriber changes

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release adds several new features, including a `Filter`
implementation and new builder API for `EnvFilter`, support for using a
`Vec<L> where L: Layer` as a `Layer`, and a number of smaller API
improvements to make working with dynamic and reloadable layers easier.
- **registry**: Implement `Filter` for `EnvFilter`, allowing it to be
used with per-layer filtering ([#1983])
- **registry**: `Filter::on_new_span`, `Filter::on_enter`,
`Filter::on_exit`, `Filter::on_close` and `Filter::on_record`
callbacks to allow `Filter`s to track span states internally ([#1973],
[#2017], [#2031])
- **registry**: `Filtered::filter` and `Filtered::filter_mut` accessors
([#1959])
- **registry**: `Filtered::inner` and `Filtered::inner_mut` accessors to
borrow the wrapped `Layer` ([#2034])
- **layer**: …
=> subscriber: prepare to release v0.3.10

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
This release fixes a bug where setting `NoSubscriber` as the local
default would not locally disable the current global default subscriber.
- Setting `NoSubscriber` as the local default now correctly disables the
global default subscriber ([#2001])
- Fixed compilation warnings with the "std" feature disabled ([#2022])
- Removed unnecessary use of `write!` and `format_args!` macros
([#1988])
[#1988]: https://github.com/tokio-rs/tracing/pull/1988
[#2001]: https://github.com/tokio-rs/tracing/pull/2001
[#2022]: https://github.com/tokio-rs/tracing/pull/2022
=> core: prepare to release 0.1.24

tracing-error/src/lib.rs, tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/prelude.rs, tracing-subscriber/src/registry/sharded.rs, tracing-subscriber/src/subscribe/layered.rs
The Rust 1.60 release introduced a few new lints that trigger on the
`tracing` codebase. In particular, `clippy` added some new lints for
method naming, and the `unreachable_pub` lint now seems to be triggered
incorrectly by `pub use foo as _` re-exports.
This branch fixes the lints.
=> chore: fix Rust 1.60 warnings

tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/filter/env/mod.rs
See issue #2046.
When using calling [`Builder::parse`] or [`Builder::parse_lossy`] with  an empty
string an error is produced. This happens for example when `EnvFilter::from_default_env()`
is called, but the `RUST_LOG` variable is unset.
This regression was introduced by #2035.
Filter any empty directives. This allows the whole string to be empty, as well as leading
and trailing commas.
A unit test was added for [`Builder::parse`], but not [`Builder::parse_lossy`] because it (per definition)
doesn't produce any side effects visible from tests when erroring.
[`Builder::parse`]: https://github.com/tokio-rs/tracing/blob/cade7e311848227348c9b3062e4a33db827a0390/tracing-subscriber/src/filter/env/builder.rs#L151=
[`Builder::parse_lossy`]: …
=> subscriber: fix issue with `EnvFilter::builder().parse`

tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/tests/env_filter/main.rs
Currently, there is a potential namespace resolution issue when calling
`EnvFilter` methods that have the same name in the `Filter` and
`Subscribe` traits (such as `enabled` and `max_level_hint`). When both
`Filter` and `Subscribe` are in scope, the method resolution is
ambiguous.
See https://github.com/tokio-rs/tracing/pull/1983#issuecomment-1088984580
This commit solves the problem by making the inherent method versions of
these methods public. When the traits are in scope, name resolution will
always select the inherent method prefer`entially, preventing the name
clash.
=> subscriber: add inherent impls for `EnvFilter` methods

tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/tests/env_filter/main.rs
Depends on https://github.com/tokio-rs/tracing/pull/2057
Currently, `EnvFilter`'s `Subscribe` implementation provides a
`Subscribe::on_record` method, but its `Filter` implementation is
missing the corresponding `Filter::on_record` implementation. This means
that when using `EnvFilter` as a per-subscriber filter, recording span
fields after the spans were created will not update the filter state.
This commit factors out the `on_record` implementation for `Subscribe`
into an inherent method, and adds a new `Filter::on_record` method that
calls it as well.
=> subscriber: add missing `Filter::on_record` for to `EnvFilter`

tracing-journald/src/lib.rs, tracing-journald/tests/journal.rs
Currently, `tracing-journald` prefixes event fields with the number
of parent spans, if present, in order to namespace field values. This
turned out to be unnecessary as journald preserves values for duplicated
field names.
This branch removes event field prefixes and emits parent span names
and their field/value pairs as additional key/value pairs.
=> journald: remove span field prefixes; add separate fields for span data

tracing/src/lib.rs, tracing/tests/macros_redefined_core.rs
This changes the "unregistered" interest state from `0xDEADFACED`
to`0xDEAD`, which should fit in a `usize` even on 16-bit platforms. The
actual value of this thing doesn't matter at all, it just has to be "not
0, 1, or 2", and it's good for it to be something weird to make it more
obvious in the event of stuff going wrong.
This should fix a warning being emitted when building for wasm (and
other <=32-bit platforms) because the previous literal would be
truncated.
Also, the `wasm_bindgen_test` macro apparently messes with the 
`macros_redefined_core` tests, so skip them on wasm.
=> tracing: fix issues compiling for WASM/other <=32-bit platforms

.github/workflows/CI.yml, tracing-core/Cargo.toml, tracing-error/src/lib.rs, tracing-journald/src/lib.rs, tracing-journald/tests/journal.rs, tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/layer/layered.rs, tracing-subscriber/src/registry/sharded.rs, tracing-subscriber/tests/env_filter/main.rs, tracing/src/lib.rs, tracing/tests/macros_redefined_core.rs
This branch backports:
* 14cc4de5 chore(ci): add a minimal-versions check (#2015)
* 4eed50aa journald: remove span field prefixes; add separate fields for span data (#1968)
* bd6c611e subscriber: add missing `Filter::on_record` for to `EnvFilter` (#2058)
* cd8d613b subscriber: add inherent impls for `EnvFilter` methods (#2057)
* 6f8f56d4 subscriber: fix empty string handling in `EnvFilter::builder().parse` (#2052)
* 5262b9ea chore: fix Rust 1.60 warnings (#2056)
=> backport changes to v0.1.x

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This release adds new `span_enabled!` and `event_enabled!` variants of
the `enabled!` macro, for testing whether a subscriber would
specifically enable a span or an event.
- `span_enabled!` and `event_enabled!` macros ([#1900])
- Several documentation improvements ([#2010], [#2012])
- Compilation warning when compiling for <=32-bit targets (including
`wasm32`) ([#2060])
Thanks to @guswynn, @arifd, @hrxi, @CAD97, and @name1e5s for
[#1900]: https://github.com/tokio-rs/tracing/pull/1900
[#2010]: https://github.com/tokio-rs/tracing/pull/2010
[#2012]: https://github.com/tokio-rs/tracing/pull/2012
[#2060]: https://github.com/tokio-rs/tracing/pull/2060
=> tracing: prepare to release v0.1.33

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This is a bugfix release for the `Filter` implementation for `EnvFilter` added
in [v0.3.10].
- **env-filter**: Added missing `Filter::on_record` callback to `EnvFilter`'s
`Filter` impl ([#2058])
- **env-filter**: Fixed method resolution issues when calling `EnvFilter`
methods with both the `Filter` and `Layer` traits in scope ([#2057])
- **env-filter**: Fixed `EnvFilter::builder().parse()` and other parsing methods
returning an error when parsing an empty string ([#2052])
Thanks to new contributor @Ma124 for contributing to this release!
[v0.3.10]: https://github.com/tokio-rs/tracing/releases/tag/tracing-subscriber-0.3.10
[#2058]: https://github.com/tokio-rs/tracing/pull/2058
[#2057]: https://github.com/tokio-rs/tracing/pull/2057
[#2052]: https://github.com/tokio-rs/tracing/pull/2052
=> subscriber: prepare to release v0.3.11

tracing-subscriber/src/layer/mod.rs
There's a broken link and broken formatting in the [mod-level docs] for
`tracing_subscriber::layer` referring to the `Layer` impl for `Vec`s of
`Layer`s. Looks like it got mangled by search+replace in #2038 so it's
not an issue in master.
[mod-level docs]: https://docs.rs/tracing-subscriber/0.3.11/tracing_subscriber/layer/index.html#runtime-configuration-with-layers
I have stolen the correct markdown and link from master.
=> subscriber: fix doc link for impl Layer for Vec

examples/examples/fmt/yak_shave.rs, tracing-core/src/field.rs
`Value` was already implemented for `dyn Error + 'static`, but rust doesn't silently coerce trait objects. This means that passing an error of type `dyn Error + Send + Sync + 'static` would not work. This is related to #1308.
Add impls for `dyn Error + …` variants for `Send`, `Sync`, and `Send + Sync`. These extra impls just delegate to the existing `dyn Error + 'static` impl.
Also update one of the examples to use `dyn Error + Send + Sync` to demonstrate that this works.
=> core: impl `Value` for `dyn Error + Send/Sync`

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
This release adds additional `Value` implementations for
`std::error::Error` trait objects with auto trait bounds (`Send` and
`Sync`), as Rust will not auto-coerce trait objects. Additionally, it
fixes a bug when setting scoped dispatchers that was introduced in the
previous release ([v0.1.24]).
- `Value` implementations for `dyn Error + Send + 'static`, `dyn Error +
Send + Sync + 'static`, `dyn Error + Sync + 'static` ([#2066])
- Failure to use the global default dispatcher if a thread has set a
scoped default prior to setting the global default, and unset the
scoped default after setting the global default ([#2065])
Thanks to @lilyball for contributing to this release!
[v0.1.24]: https://github.com/tokio-rs/tracing/releases/tag/tracing-core-0.1.24
[#2066]: …
=> core: prepare to release v0.1.25

tracing/src/lib.rs, tracing/src/macros.rs, tracing/src/span.rs, tracing/test-log-support/src/lib.rs, tracing/test-log-support/tests/log_no_trace.rs, tracing/test-log-support/tests/log_with_trace.rs, tracing/test-log-support/tests/span_activity_filtered_separately.rs, tracing/test-log-support/tests/span_lifecycle_can_be_enabled.rs, tracing/tests/future_send.rs
Currently, enabling the `log` feature can cause a compilation error when
using `tracing` macros in async functions or blocks. This is because,
when the `log` feature is enabled, the `tracing` macros will construct a
`log::Record`, which is not `Send`, causing the async fn/block future to
become `!Send`. This can break compilation when the future is `Send`
without the `log` feature enabled. This is really not great, as it makes
the feature no longer purely additive.
This branch fixes the issue by moving the `log::Record` construction
behind a function call. Because the `log::Record` is now only
constructed inside of a function, the `log::Record` is now never a local
variable within the async block, so it no longer affects the future's
auto traits. 
It's kind of a shame that the compiler …
=> tracing: fix the "log" feature making async block futures `!Send`

tracing-core/src/field.rs
This commit adds a `Value` implementation for `Box<T> where T: Value`.
This is *primarily* intended to make `Box<dyn Error + ...>` implement
`Value`, building on the `Value` impls for `dyn Error + ...` added in
#2066, but it may be useful for other boxed values as well.
Refs: #1308
=> core: add `Value` impl for `Box<T> where T: Value`

tracing-core/src/field.rs, tracing/src/lib.rs, tracing/src/macros.rs, tracing/src/span.rs, tracing/test-log-support/src/lib.rs, tracing/test-log-support/tests/log_no_trace.rs, tracing/test-log-support/tests/log_with_trace.rs, tracing/test-log-support/tests/span_activity_filtered_separately.rs, tracing/test-log-support/tests/span_lifecycle_can_be_enabled.rs, tracing/tests/future_send.rs
This backports the following changes from `master`:
* 6d68aab0 core: add `Value` impl for `Box<T> where T: Value` (#2071)
* f333048a tracing: fix the "log" feature making async block futures `!Send` (#2073)
=> backport #2071 and #2073

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
This release adds a `Value` implementation for `Box<T: Value>` to allow
recording boxed values more conveniently. In particular, this should
improve the ergonomics of the implementations for `dyn std::error::Error`
trait objects, including those added in [v0.1.25]. 
- `Value` implementation for `Box<T> where T: Value` ([#2071])
- Broken documentation links ([#2068])
Thanks to new contributor @ben0x539 for contributing to this release!
[v0.1.25]: https://github.com/tokio-rs/tracing/releases/tag/tracing-core-0.1.25
[#2071]: https://github.com/tokio-rs/tracing/pull/2071
[#2068]: https://github.com/tokio-rs/tracing/pull/2068
=> core: prepare to release v0.1.26

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md
This release includes bug fixes for the "log" support feature and for
the use of both scoped and global default dispatchers in the same
program.
- Failure to use the global default dispatcher when a thread sets a
local default dispatcher before the global default is set ([#2065])
- **log**: Compilation errors due to `async` block/fn futures becoming
`!Send` when the "log" feature flag is enabled ([#2073])
- Broken links in documentation ([#2068])
Thanks to @ben0x539 for contributing to this release!
[#2065]: https://github.com/tokio-rs/tracing/pull/2065
[#2073]: https://github.com/tokio-rs/tracing/pull/2073
[#2068]: https://github.com/tokio-rs/tracing/pull/2068
=> tracing: prepare to release v0.1.34

tracing-journald/CHANGELOG.md, tracing-journald/Cargo.toml
This is a breaking release which changes the format in which span fields
are output to `journald`. Previously, span field names were prefixed
with the depth of the span in the current trace tree. However, these
prefixes are unnecessary, as `journald` has built in support for
duplicated field names.
See PR [#1986] for details on this change.
- Removed span field prefixes ([#1986])
- Renamed `S{num}_NAME` fields to `SPAN_NAME` ([#1986])
- Fixed broken links in documentation ([#2077])
Thanks to @wiktorsikora and @ben0x539 for contributing to this release!
[#1986]: https://github.com/tokio-rs/tracing/pull/1986
[#2077]: https://github.com/tokio-rs/tracing/pull/2077
=> tracing-journald: prepare to release v0.3.0

tracing-core/Cargo.toml, tracing-core/src/callsite.rs, tracing-core/src/dispatcher.rs, tracing-mock/src/subscriber.rs, tracing/Cargo.toml, tracing/src/lib.rs, tracing/src/macros.rs, tracing/tests/register_callsite_deadlock.rs
Currently on `v0.1.x`, the global callsite registry is implemented as a
`Mutex<Vec<&'static dyn Callsite>>`. This has a few downsides:
* Every time a callsite is registered, the `Mutex` must be locked. This
can cause a deadlock when a `register_callsite` implementation calls
into code that _also_ registers a callsite. See #2020 for details.
* Registering callsites is relatively slow and forces the program to
synchronize on the callsite registry (and not on *individual*
callsites). This means that if two threads are both registering
totally different callsites, both threads must wait for the lock.
Although this overhead is amortized over the entire rest of the
program, it does have an impact in short-running applications where
any given callsite may only be hit once or twice.
* Memory …
=> core: add a limited form of the linked-list callsite registry for v0.1.x

tracing-attributes/src/attr.rs, tracing-attributes/src/expand.rs, tracing-attributes/src/lib.rs, tracing-attributes/tests/parents.rs
This PR extends the `#[instrument]` attribute to accept an optionally `parent = …` argument that provides an explicit parent to the generated `Span`.
This PR resolves #2021 and partially resolves #879. (It only partly resolves #879 in that it only provides a mechanism for specifying an explicit parent, but *not* for invoking `follows_from`.)
This PR follows the implementation strategy articulated by @hawkw: https://github.com/tokio-rs/tracing/issues/879#issuecomment-668168468. The user-provided value to the `parent` argument may be any expression, and this expression is provided directly to the invocation of [`span!`](https://tracing.rs/tracing/macro.span.html).
=> attributes: permit setting parent span via `#[instrument(parent = …)]`

tracing-attributes/src/attr.rs, tracing-attributes/src/expand.rs, tracing-attributes/src/lib.rs, tracing-attributes/tests/follows_from.rs, tracing-mock/src/collector.rs
This PR extends the `#[instrument]` attribute to accept an optional `follows_from = …` argument that supplies any number of `Span::follows_from` relationships to the generated `Span`.
This PR resolves #879.
This PR largely follows the implementation strategy articulated by @hawkw: https://github.com/tokio-rs/tracing/issues/879#issuecomment-668168468
In that comment, @hawkw suggests taking one of two approaches:
1. each `follows_from` relationship is supplied with a distinct `follows_from` argument
2. the `follows_from` argument is provided once, and its value is a **list** of indirect causes
I take the second approach, since it is slightly more flexible: it allows for the number of indirect causes to vary at runtime.
This addition is complemented by changes to `tracing-mock` to permit …
=> attributes, mock: permit `#[instrument(follows_from = …)]`

tracing-attributes/src/attr.rs, tracing-attributes/src/expand.rs, tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs, tracing-attributes/tests/follows_from.rs, tracing-attributes/tests/parents.rs, tracing-core/src/callsite.rs, tracing-core/src/subscriber.rs, tracing-mock/src/subscriber.rs
This branch backports the following commits from `master`:
* attributes: permit `#[instrument(follows_from = …)]` (#2093)
* 21b6ddc6 attributes: permit setting parent span via `#[instrument(parent = …)]` (#2091)
* 3d7a18b1 attributes: remove extra braces around `async` blocks (#2090)
* f9685177 core: document the `callsite` module (#2088)
After this, we'll prep a new `tracing-attributes` release, and 
add additional docs to the changes in #2083 based on those
added in #2093
=> backport recent commits from `master`

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs
This release adds support for setting explicit parent and follows-from
spans in the `#[instrument]` attribute.
- `#[instrument(follows_from = ...)]` argument for setting one or more
follows-from span ([#2093])
- `#[instrument(parent = ...)]` argument for overriding the generated
span's parent ([#2091])
- Extra braces around `async` blocks in expanded code (causes a Clippy
warning) ([#2090])
- Broken documentation links ([#2068], [#2077])
Thanks to @jarrodldavis, @ben0x539, and new contributor @jswrenn for
[#2093]: https://github.com/tokio-rs/tracing/pull/2093
[#2091]: https://github.com/tokio-rs/tracing/pull/2091
[#2090]: https://github.com/tokio-rs/tracing/pull/2090
[#2077]: https://github.com/tokio-rs/tracing/pull/2077
[#2068]: …
=> attributes: prepare to release v0.1.21

tracing-opentelemetry/src/subscriber.rs
Fixes: #2094
Properly attach event's source locations.
Append the locations to events' attributes instead of span's attributes.
=> opentelemetry: fix event source location

tracing-subscriber/Cargo.toml
This attempts to address https://github.com/tokio-rs/tracing/issues/2106.
Closes #2106
=> Don't enable tracing-core features by default

tracing-opentelemetry/README.md
The example code for `tracing-opentelemetry` in the README.md file was based on
older versions of `tracing`, `tracing-opentelemetry` and `opentelemetry`. It
did not compile with the latest versions of these crates.
Developers should be able to copy/paste example code and it should work.
Following some type renames allows this code to work.
This is @lilymara-onesignal's branch #1414 but rebased to point at the
`v0.1.x` branch as the base. I think we will also want to update the use
of the otel APIs on `master`, but `master` currently uses the correct
`tracing` type names _for v0.2.x_.
Co-authored-by: Lily Mara <lilymara@onesignal.com>
Closes #1414
=> opentelemetry: Fix example in README.md

examples/examples/opentelemetry.rs
https://github.com/tokio-rs/tracing/issues/1743
Fix the opentelemetry example's bug of missing root span.
The result of example should not miss root span.
The `root` span should be dropped before `opentelemetry provider` shutdown.
p.s. I'm sorry that I'm not good at English, so please be relaxed to edit.
=> Opentelemetry: Fix example bug of missing root span

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/mod.rs
I noticed that the documentation for `tracing-subscriber`'s methods relating to logging thread information doesn't have periods, inconsistent from the rest of the documentation.
=> docs: added missing periods to `with_thread_{names, ids}`

tracing-opentelemetry/src/subscriber.rs
The `with_event_location(false)` method will now properly omit `code.*` tags from spans.
Recently, I attempted to remove the `code.*` tags from opentelemetry tracing spans utilizing the [`with_event_location`](https://github.com/tokio-rs/tracing/blob/master/tracing-opentelemetry/src/subscriber.rs#L343) of OpenTelemetrySubscriber. This did not work as expected because the [`on_new_span`](https://github.com/tokio-rs/tracing/blob/master/tracing-opentelemetry/src/subscriber.rs#L448-L460) doesn't account for the `event_location` boolean similar to how [`on_event`](https://github.com/tokio-rs/tracing/blob/master/tracing-opentelemetry/src/subscriber.rs#L582) does.
The change presented will expand the use of the `event_location` to check before adding the `code.*` KeyValue attributes in …
=> opentelemetry: enforce event_location for span tags

tracing-opentelemetry/src/layer.rs
BREAKING CHANGE: previously error values were recorded using their `Debug` representation. They are now reported with their `Display` implementation. This is more in line with current best practices for error handling, but we may want this to be an opt-in behavior.
This is a change in how error values are recorded in the opentelemetry adapter.
For a given field `x` that contains an error type, record an additional dynamic
field `x.chain` that contains an array of all errors in the source chain. This
allows users to determine where a high-level error originated.
Rust's `Error` type includes a `source` method which allows library authors to compose errors on top of one another in a way that indicates how errors originated down to the OS level. Surfacing this information to the users will …
=> opentelemetry: record error source chain

tracing-appender/Cargo.toml, tracing-appender/benches/bench.rs, tracing/src/macros.rs
This patch adds blocking and nonblocking benchmarks. This code is from
an old PR (#703) that was never merged, and now ported to TOT so that it
compiles.
Co-authored-by: Zeki Sherif <9832640+zekisherif@users.noreply.github.com>
=> appender: add initial set of benches

tracing/src/lib.rs
there's a correct one towards the top, so this only needs to be removed
=> docs: remove old msrv note

tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/src/subscriber.rs
OpenTelemetry has [semantic conventions][1] for reporting thread names
and IDs on spans. This branch adds support for recording thread names
and IDs according to these conventions.
[1]: https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/span-general/#source-code-attributes
=> opentelemetry: add support for thread names/ids 

tracing-core/Cargo.toml, tracing-core/src/callsite.rs, tracing-core/src/dispatch.rs, tracing-flame/Cargo.toml, tracing-flame/src/lib.rs, tracing-log/Cargo.toml, tracing-log/src/lib.rs, tracing-subscriber/Cargo.toml, tracing-subscriber/src/filter/env/directive.rs
Replace `lazy_static` with `once_cell`. Fixes #2146.
`lazy_static!`, while a declarative macro, is a macro nonetheless. It can add quite a bit of additional compilation time cost. `once_cell::sync::Lazy` does the same thing with generics, and can be used more flexibly (i.e. non-static lazily initialized values), and has been proposed to be added to `std` (see linked issue).
I'm trying to reduce the compile time and dependency tree complexity of a dependent project: [bevy](https://bevyengine.org), which is using tracing. `lazy_static` and `once_cell` are both in our dependency tree and both end up doing the same thing.
Migrate to `once_cell`.
=> Migrate from lazy_static to once_cell

examples/examples/opentelemetry.rs
This patch adds a bit more context around why we are creating a smaller
scope for the spans, and also what happens when we call
`global::shutdown_tracer_provider()` (that comment was copied from
the`rust-opentelemetry` repo).
=> opentelemetry: add more comments to example

examples/Cargo.toml, examples/examples/hyper-echo.rs, examples/examples/opentelemetry.rs, tracing-appender/Cargo.toml, tracing-appender/benches/bench.rs, tracing-attributes/Cargo.toml, tracing-core/Cargo.toml, tracing-core/src/callsite.rs, tracing-core/src/lib.rs, tracing-error/src/lib.rs, tracing-flame/Cargo.toml, tracing-flame/src/lib.rs, tracing-futures/Cargo.toml, tracing-journald/Cargo.toml, tracing-log/Cargo.toml, tracing-log/src/interest_cache.rs, tracing-log/src/lib.rs, tracing-mock/Cargo.toml, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/src/layer.rs, tracing-subscriber/Cargo.toml, tracing-subscriber/src/filter/env/directive.rs, tracing-subscriber/src/filter/env/mod.rs, tracing/src/lib.rs, tracing/src/macros.rs
This branch backports the following commits:
* core, subscriber: migrate from `lazy_static` to `once_cell` (#2147)
* 094783de chore(deps): update parking_lot requirement from >= 0.9.0, <= 0.12 to >= 0.9.0, <= 0.13 (#2143)
* 44892b40 opentelemetry: add support for thread names/ids  (#2134)
* aa55bd1a docs: remove incorrect MSRV note (#2137)
* fc370cdb appender: add initial set of benches (#2128)
* 92c5425c opentelemetry: enforce event_location for span tags (#2124)
* 1afc9d5c error: add missing backtick to `prelude` docs (#2120)
* cc19449e fix opentelemetry example (#2110)
* f22f2861 Add additional information to references of my_crate in env_filter docs. (#1088)
* 6878d8db journald: disable default features of tracing-subscriber (#1476)
* fea09a8b chore(deps): update tokio-test …
=> backport 13 commits from master

tracing-core/src/field.rs, tracing-core/src/span.rs
This PR adds two new accessor functions that are useful for creating a structured serde implementation for tracing.
This is a sort of "distilled" version of https://github.com/tokio-rs/tracing/pull/2113, based on the `v0.1.x` branch.
As it is unlikely that "structured serde" will be 1:1 compatible with the existing JSON-based `tracing-serde` (or at least - I'm not sure how to do it in a reasonable amount of effort), these functions will allow me to make a separate crate to hold me over until breaking formatting changes are possible in `tracing-serde`.
CC @hawkw, as we've discussed this pretty extensively
=> Add accessor functions necessary for structured serde

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md, tracing/Cargo.toml
This release of `tracing-core` introduces a new `DefaultCallsite` type,
which can be used by instrumentation crates rather than implementing
their own callsite types. Using `DefaultCallsite` may offer reduced
overhead from callsite registration.
- `DefaultCallsite`, a pre-written `Callsite` implementation for use in
instrumentation crates ([#2083])
- `ValueSet::len` and `Record::len` methods returning the number of
fields in a `ValueSet` or `Record` ([#2152])
- Replaced `lazy_static` dependency with `once_cell` ([#2147])
- Added documentation to the `callsite` module ([#2088], [#2149])
Thanks to new contributors @jamesmunns and @james7132 for contributing
[#2083]: https://github.com/tokio-rs/tracing/pull/2083
[#2152]: https://github.com/tokio-rs/tracing/pull/2152
[#2147]: …
=> core: prepare to release v0.1.27

bin/publish
This fixes an issue in the `bin/release` shell script where `cargo list`
was used instead of `cargo --list` to check if `cargo-hack` is
installed. It also fixes some unrelated shell script issues.
=> chore: `bin/publish` shell script fixes

tracing-core/src/collect.rs, tracing-subscriber/src/subscribe/layered.rs
Adds inherent `downcast_ref` and `is` inherent methods to:
- `dyn Subscriber + Send`
- `dyn Subscriber + Sync`
- `dyn Subscriber + Send + Sync`
- `Layered`
These additional implementations reduce the circumstances in which one
must cast to `dyn Subscriber` (which, previously, was the only type for
which `downcast_ref` and `is` were available).
=> tracing-core,tracing-subscriber: more `downcast_ref` & `is` methods

tracing-subscriber/src/reload.rs, tracing-subscriber/tests/reload.rs
The `reload` layer doesn't (and can't) implement downcasting correctly, which breaks certain subscribers like the opentelemetry one.
. Most usages of this type (including mine) are just to change the filter, so this pr implements `Filter` on the reload type to allow users to not need to wrap the whole layer trait. Another advantage of this is that the common-case critical sections are shortened
=> implement filter for the reload layer/subscriber

README.md, tracing/README.md, tracing/src/lib.rs
Adds tracing-logfmt crate to the related crates section
=> docs: Add tracing-logfmt to related crates

tracing-attributes/tests/fields.rs, tracing-core/src/field.rs, tracing/tests/event.rs
Currently, it is rather difficult to record `String`s as field values,
even though `&str` is a primitive `Value` type. For example, this code
does not currently compile:
```rust
let my_string = String::from("hello world!");
tracing::debug!(my_string);
```
Instead, it is necessary to explicitly call `String::as_str` or a
similar conversion method:
```rust
let my_string = String::from("hello world!");
tracing::debug!(my_string = my_string.as_str());
```
This is unfortunate, as it makes a fairly straightforward, commomplace
task (recording a `String` as a field) unnecessarily verbose.
This branch adds an `impl Value for String` in `tracing-core` when the
"alloc" feature flag is enabled. The impl simply calls `String::as_str`
and then calls `record_str`. Because `Value` takes an `&self`, and …
=> core: `impl field::Value for String`

tracing-core/src/collect.rs
These broader impls supersede the previous impls where the inner type was a
`dyn Collect`. With these generic impls, you no longer must (but still can,
if you wish) cast the inner type of a boxed or arc'd collector to
`dyn Collect` to use it as a `Collect`.
=> tracing-core: impl<C: Collect + ?Sized> Collect for Box<C>, Arc<C>

tracing-core/src/field.rs
I've received a request at work to record 128-bit integers and realized that we should probably support recording them.
Added two methods to the `Visit` trait, `record_i128` and `record_u128`. However, I didn't add the size conversions present for 64-bit integers, as 128-bit integers are, at this time, more specialized.
=> core: add support for recording 128-bit integers

tracing-core/src/collect.rs, tracing-core/src/dispatch.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/reload.rs, tracing-subscriber/src/subscribe/layered.rs, tracing-subscriber/src/subscribe/mod.rs, tracing-subscriber/tests/event_enabling.rs
Allow filter layers to filter on the contents of events (closes #2007).
Add `Subscribe::event_enabled(&self, event: &Event<'_>, ctx: Context<'_, C>) -> bool;`. This is called before `Subscribe::on_event`, and if `event_enabled` returns `false`, `on_event` is not called (nor is `Collect::event`).
`Subscribe::on_event` returns `ControlFlow`, and the `Layered` subscriber only continues to call `on_event` on `ControlFlow::Continue`.
This PR exists mainly as a place for discussion of this potential solution. Looking at this diff, and given that *most* subscriber layers will want to continue and not break the layering, it might make sense to make this a new method which delegates to on_event by default. Since Layered is the primary way of layering two subscribers together, perhaps the footgun …
=> Add Subscribe::event_enabled to conditionally dis/enable events based on fields

.github/workflows/check_msrv.yml, tracing-futures/Cargo.toml, tracing-futures/src/lib.rs, tracing-subscriber/Cargo.toml
In many cases, new releases of a dependency can break compatibility with
`tracing`'s minimum supported Rust version (MSRV). It shouldn't be
necessary for a `tracing` crate to bump its MSRV when a dependency does,
as users on older Rust versions should be able to depend on older
versions of that crate explicitly and avoid bumping. Instead, we should
probably just run our MSRV checks with minimal dependency versions. This
way, we don't need to bump our MSRV when the latest version of a
dependency does, unless we actually *need* to pick up that new version.
This branch changes the `check_msrv` CI jobs to do that. I also did some
minor dependency editing to actually make tracing build with
`-Zminimal-versions`.
Note that `tracing-futures` is currently excluded from the MSRV build
because it …
=> chore(ci): run MSRV checks with minimal versions

.github/workflows/check_msrv.yml, README.md, bin/publish, examples/examples/opentelemetry.rs, tracing-attributes/tests/fields.rs, tracing-core/src/dispatcher.rs, tracing-core/src/field.rs, tracing-core/src/subscriber.rs, tracing-futures/Cargo.toml, tracing-futures/src/lib.rs, tracing-subscriber/Cargo.toml, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/layer/layered.rs, tracing-subscriber/src/layer/mod.rs, tracing-subscriber/src/reload.rs, tracing-subscriber/tests/event_enabling.rs, tracing/README.md, tracing/src/lib.rs, tracing/tests/event.rs
This backports the following changes from `master` to `v0.1.x`:
* 10bf03a6 chore(ci): run MSRV checks with minimal versions (#2171)
* 8dd8151a core, subscriber: add `event_enabled` to filter events on fields (#2008)
* 3cad70d6 core: add support for recording 128-bit integers (#2166)
* e43af367 core: `impl<S: Subscriber + ?Sized> Subscriber` for `Box<S>`, `Arc<S>` (#2161)
* c059f81f core: `impl field::Value for String` (#2164)
* bf695ba9 docs: add tracing-logfmt to related crates (#2163)
* 240cd500 core, subscriber: more `downcast_ref` & `is` methods (#2160)
* 7302a884 chore: `bin/publish` shell script fixes (#2162)
* 09df7ba8 opentelemetry: add more comments to example (#2140)
In particular, PR #2171 fixes the CI build.
=> backport 9 commits from `master`

tracing-opentelemetry/src/layer.rs
When an error value is recorded, it should add the `exception.message` and
`exception.stacktrace` fields from the opentelemetry semantic conventions to the
span/event. Ideally the `exception.type` field would be provided also, but there
is currently not a mechanism to determine the type name of a trait object.
Motivated by comment on another PR - https://github.com/tokio-rs/tracing/pull/2122#issuecomment-1133181925
=> opentelemetry: add semconv exception fields

tracing-subscriber/src/filter/layer_filters/mod.rs, tracing-subscriber/src/reload.rs, tracing-subscriber/tests/reload.rs
The old `Layer` has an extra `S` parameter, but I found that the way I setup the impls, this passes all tests
@hawkw and @davidbarsky , I did my best in the cherry-pick, but some of the docs may have been messed up, so please review carefully!
=> backport: subscriber: implement `FIlter` for `reload::Subscriber`

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
This release of `tracing-core` adds new `Value` implementations,
including one for `String`, to allow recording `&String` as a value
without having to call `as_str()` or similar, and for 128-bit integers
(`i128` and `u128`). In addition, it adds new methods and trait
implementations for `Subscriber`s.
- `Value` implementation for `String` ([#2164])
- `Value` implementation for `u128` and `i28` ([#2166])
- `downcast_ref` and `is` methods for `dyn Subscriber + Sync`,
`dyn Subscriber + Send`, and `dyn Subscriber + Send + Sync` ([#2160])
- `Subscriber::event_enabled` method to enable filtering based on
`Event` field values ([#2008])
- `Subscriber` implementation for `Box<S: Subscriber + ?Sized>` and
`Arc<S: Subscriber + ?Sized>` ([#2161])
Thanks to @jswrenn and @CAD97 for contributing to this …
=> chore: prepare to release `tracing-core` v0.1.28

tracing/src/macros.rs
Although it shares the name, `event_enabled!` *does not* call `Collect::event_enabled`. `Collect::event_enabled` is only called once the event fields are available.
=> Document that `event_enabled!` does not call `Collect::event_enabled`

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release of `tracing-subscriber` adds a new `Layer::event_enabled`
method, which allows `Layer`s to filter events *after* their field
values are recorded; a `Filter` implementation for `reload::Layer`, to
make using `reload` with per-layer filtering more ergonomic, and
additional inherent method downcasting APIs for the `Layered` type. In
addition, it includes dependency updates, and minor fixes for
documentation and feature flagging.
- **layer**: `Layer::event_enabled` method, which can be implemented to
filter events based on their field values (#2008)
- **reload**: `Filter` implementation for `reload::Layer` (#2159)
- **layer**: `Layered::downcast_ref` and `Layered::is` inherent methods
(#2160)
- **parking_lot**: Updated dependency on `parking_lot` to 0.13.0
(#2143)
- Replaced …
=> subscriber: prepare to release v0.3.12

tracing-subscriber/Cargo.toml
PR #2008 added a new method to the `tracing_core::Subscriber` trait, and
modified `tracing-subscriber` to and implement that method. However,
that PR did *not* increase the minimum `tracing-core` dependency for the
`tracing-subscriber` crate.
This means that if a dependent of `tracing-subscriber` updates *only*
`tracing-subscriber` dependency version (e.g. by running
`cargo update -p tracing-subscriber`), it will not also update its
`tracing-core` version to one that contains the new method, and
`tracing-subscriber` will fail to compile. This is a common occurrence
with projects using Dependabot, for example.
This commit updates `tracing-subscriber`'s minimum `tracing-core` dep to
0.1.28. Once this merges, I'll release 0.3.13 of `tracing-subscriber`
and yank 0.3.12.
=> subscriber: update minimum `tracing-core` dep to 0.1.28

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release of `tracing-subscriber` fixes a compilation failure due to
an incorrect `tracing-core` dependency that was introduced in v0.3.12.
- **tracing_core**: Updated minimum dependency version to 0.1.28 (#2190)
=> subscriber: prepare to release v0.3.13

CONTRIBUTING.md
The gitter room is not used anymore.
This commit updates CONTRIBUTING.md to guide the reader to the discord channel.
=> docs: update dev chat link

tracing-subscriber/src/subscribe/mod.rs
Sorry @guswynn @hawkw
This is wrong.
Make it unwrong.
=> <None as Subscribe>::event_enabled should be true

tracing-attributes/Cargo.toml, tracing-attributes/src/expand.rs, tracing-attributes/src/lib.rs, tracing-attributes/tests/err.rs, tracing-attributes/tests/ret.rs
https://github.com/tokio-rs/tracing/discussions/2182
=> Ensure 'res' and 'err' inherit 'target'

tracing-opentelemetry/src/layer.rs
Currently, the `tracing-opentelemetry` docs indicate that the support
for OpenTelemetry's exception semantic conventions added in #2135 is
enabled by default. However, this is not the case --- this feature was
changed to opt-in rather than opt-out prior to merging PR #2135.
This branch updates the docs to state that these features are disabled
by default, rather than enabled by default.
=> opentelemetry: fix exception fields defaults in docs

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
This release adds optional support for recording `std::error::Error`s
using OpenTelemetry's [semantic conventions for exceptions][exn-semconv].
- `Layer::with_exception_fields` to enable emitting `exception.message`
and `exception.backtrace` semantic-convention fields when an `Error`
is recorded as a span or event field ([#2135])
- `Layer::with_exception_field_propagation` to enable setting
`exception.message` and `exception.backtrace` semantic-convention
fields on the current span when an event with an `Error` field is
recorded ([#2135])
Thanks to @lilymara-onesignal for contributing to this release!
[thread-semconv]: https://opentelemetry.io/docs/reference/specification/trace/semantic_conventions/exceptions/
[#2135]: https://github.com/tokio-rs/tracing/pull/2135
=> opentelemetry: prepare to release v0.17.4

tracing-subscriber/src/reload.rs, tracing-subscriber/tests/reload.rs
When using a `reload` layer, the fast-path current level check doesn't work, as the `max_level_hint` is just `None`, which `rebuild_interest` interprets as `TRACE`
Pass through to the underlying layer/filter. On poisons, when already panicking, just return `None`
=> pass through max_level_hint in reload::Layer

.github/workflows/CI.yml, .github/workflows/audit.yml, .github/workflows/release.yml
Older versions use node 12 which is no longer supported (end-of-life on April 30, 2022). Also, `@main`/`@master` is not very good as they may run into unreleased breaking changes.
=> chore(ci): update actions/checkout action to v3

tracing-appender/src/worker.rs
I find it useful when debugging applications with lots of threads to
easily identity them by their names.
Just name the thread as other crates such as `sentry-rust` are doing.
=> appender: name spawned thread

tracing/src/span.rs
Previously, using `record("x", "y")` would give an error:
```
error[E0277]: the size for values of type `str` cannot be known at compilation time
--> src/main.rs:3:22
|
243  |                 span.record("x", "y");
|                      ^^^^^^ doesn't have a size known at compile-time
|
= help: the trait `Sized` is not implemented for `str`
note: required by a bound in `Span::record`
--> /home/jnelson/.local/lib/cargo/registry/src/github.com-1ecc6299db9ec823/tracing-0.1.32/src/span.rs:1184:30
|
1184 |     pub fn record<Q: ?Sized, V>(&self, field: &Q, value: &V) -> &Self
|                              ^ required by this bound in `Span::record`
```
Take `Q: Value` directly instead of `Q: &Value`. This doesn't break any existing code, because there's a generic `impl<T: Value> Value for &T`: …
=> Allow owned values and fat pointers in `Span::record`

tracing-core/src/callsite.rs, tracing-core/src/field.rs, tracing-core/src/metadata.rs
This change manually re-implements `PartialEq` and `Eq` for
`Metadata` and `FieldSet` to define their equality strictly in
terms of callsite equality. In debug builds, the equality of
these types' other fields is also checked.
Documentation is added to both `Metadata` and `FieldSet`
explaining this behavior. The expectation that, in a well-behaving
application, `Metadata`and `FieldSet`s with equal callsites will be
otherwise equal is documented on `Callsite::metadata`. This is not
a breaking change, as previous releases did not define equality for
`Metadata` or `FieldSet`. The `Callsite` trait remains safe, as this
expectation is not (yet) a safety-critical property.
This change improves the ergonomics of comparing `Metadata`, which
is very useful for testing and user-facing examples.
=> tracing-core: implement `PartialEq`, `Eq` for `Metadata`, `FieldSet`

.github/workflows/CI.yml, .github/workflows/audit.yml, .github/workflows/release.yml, tracing-appender/Cargo.toml, tracing-appender/src/rolling.rs, tracing-appender/src/rolling/builder.rs, tracing-appender/src/worker.rs, tracing-core/src/callsite.rs, tracing-core/src/field.rs, tracing-core/src/metadata.rs, tracing-subscriber/src/reload.rs, tracing-subscriber/tests/reload.rs, tracing/README.md, tracing/src/span.rs, tracing/src/subscriber.rs
This backports the following commits from `master` to `v0.1.x`:
* cf3ab0e2 core: implement `PartialEq`, `Eq` for `Metadata`, `FieldSet` (#2229)
* 7f70dc6d appender: add a builder for constructing `RollingFileAppender`s (#2227)
* 9b9e6a55 core: remove misleading dispatcher docs (#2220)
* b2501d5b tracing: allow owned values and fat pointers in `Span::record` (#2212)
* 2c39b609 appender: name spawned thread (#2219)
* c09a660d docs: remove hard coded version link from readme (#2208)
* 7f90b545 chore(ci): update actions/checkout action to v3 (#2213)
* e73747fe subscriber: pass through `max_level_hint` in `reload` (#2204)
=> backport commits from `master` to v0.1.x

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/lib.rs
This release fixes a bug where the `reload` layer would fail to pass
through  `max_level_hint` to the underlying layer, potentially breaking
filtering.
- **reload**: pass through `max_level_hint` to the inner `Layer`
([#2204])
Thanks to @guswynn for contributing to this release!
[#2204]: https://github.com/tokio-rs/tracing/pull/2204
=> subscriber: prepare to release v0.3.15

tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/fmt/mod.rs
Builders not marked `#[must_use]` can not be initialized sometimes, causing silent failures.
Eg.
```rust
fn main() {
tracing_subscriber::fmt();
tracing::info!("hello");
}
```
won't print anything.
Added `#[must_use]` to builder types in the tracing-subscriber crate.
=> feat: mark builders as must_use

tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/metrics.rs, tracing-opentelemetry/tests/metrics_publishing.rs
In the upstream `opentelemetry` crate, the `trace` and `metrics`
features are gated by separate feature flags. This allows users who are
only using OpenTelemetry for tracing, or who are only using it for
metrics, to pick and choose what they depend on.
Currently, the release version of `tracing-opentelemetry` only provides
tracing functionality, and therefore, it only depends on `opentelemetry`
with the `trace` feature enabled. However, the metrics support added in
#2185 adds a dependency on the `opentelemetry/metrics` feature. This is
currently always enabled. We should probably follow the same approach as
upstream `opentelemetry`, and allow enabling/disabling metrics and
tracing separately.
This branch adds a `metrics` feature to `tracing-opentelemetry`, and
makes the …
=> opentelemetry: feature-flag `MetricsSubscriber`

tracing-subscriber/src/filter/targets.rs
This makes it possible to fully "override" some base `Targets` filter with another (e.g. user-supplied) filter. Without some way to obtain the default, only explicit targets can be overridden (via `IntoIter` and friends).
We can add a method to `Targets` that filters the underlying `DirectiveSet` for the default directive. This works because `DirectiveSet::add` will replace directives with the same `target`/`field_names`, which is always `None`/`vec![]` for the directive added by `with_default` (and in fact we are only concerned with `target`, since no other `Targets` API allows adding directives with a `None` target).
Ideally the method would be named `default`, corresponding to `with_default`, however this conflicts with `Default::default` and so would be a breaking change (and harm …
=> Add a method to `Targets` to get the default level

tracing-subscriber/src/registry/mod.rs, tracing-subscriber/src/subscribe/mod.rs
These implementations mirror those provided by tracing-core for `Collect` on `Box<C>` and `Arc<C>`.
=> tracing-subscriber: impl `LookupSpan` for `Box<LS>` and `Arc<LS>`

examples/Cargo.toml, tracing-appender/Cargo.toml, tracing-attributes/Cargo.toml, tracing-core/Cargo.toml, tracing-error/Cargo.toml, tracing-flame/Cargo.toml, tracing-futures/Cargo.toml, tracing-journald/Cargo.toml, tracing-journald/src/lib.rs, tracing-log/Cargo.toml, tracing-macros/Cargo.toml, tracing-mock/Cargo.toml, tracing-opentelemetry/Cargo.toml, tracing-serde/Cargo.toml, tracing-subscriber/Cargo.toml, tracing-tower/Cargo.toml, tracing/Cargo.toml, tracing/test-log-support/Cargo.toml
Essentially a cherry-pick of #2231, but redone by hand.
- `cargo minimal-versions msrv verify -- cargo check --all-features`
- `cargo minimal-versions msrv verify -- cargo check --no-default-features`
- `cargo update && cargo upgrade --to-lockfile`
- Identify [a bug](https://github.com/killercup/cargo-edit/issues/750) and manually resolve it
- loop; upgrade transitive deps
- `cargo minimal-versions check --all-features`
- Identify failing dep
- `cargo minimal-versions tree -i dep --all-features`
- Find the closest dependency leading to pulling in `dep`
- `cargo add fixdep --optional` to force a more recent more-minimal-versions-correct version
- loop; downgrade to msrv
- `cargo minimal-versions msrv verify -- cargo check --all-features`
- Identify failing dep
- `cargo minimal-versions …
=> fix minimal-versions correctness (v0.1.x)

tracing-serde/src/lib.rs
I've wanted to serialize fieldset of current span.
Expose already existing `SerializeFieldSet` for users by implementing `AsSerde` for `FieldSet`.
=> Make FieldSet implement AsSerde

tracing-subscriber/src/filter/subscriber_filters/combinator.rs, tracing-subscriber/src/filter/subscriber_filters/mod.rs, tracing-subscriber/src/registry/sharded.rs, tracing-subscriber/src/subscribe/mod.rs, tracing-subscriber/tests/subscriber_filters/main.rs, tracing-subscriber/tests/subscriber_filters/per_event.rs
Like for `Collect` and `Subscribe`, allow per-layer `Filter`s to filter based on event fields.
Add `Filter::event_enabled`, plumb it through the combinator implementations, and call it from `Filtered`.
The bit I'm the least confident about is the check in `Registry`'s implementation, but I *think* it matches what `event` is doing and everything seems to function correctly.
=> Add `Filter::event_enabled`

tracing-subscriber/src/filter/subscriber_filters/combinator.rs
=> `Not` is `not`, not `or`

tracing-core/src/dispatch.rs
When a global default dispatcher has already been set, the
`dispatch::set_global_default` function fails with a
`SetGlobalDefaultError`. The `fmt::Display` impl for this type includes
a message explaining that the error indicates that a global default has
already been set, but the `fmt::Debug` impl is derived, and just looks
like this:
```
SetGlobalDefaultError { _no_construct: () }
```
which isn't particularly helpful.
Unfortunately, when `unwrap()`ping or `expect()`ing a `Result`, the
`fmt::Debug` implementation for the error type is used, rather than
`fmt::Display`. This means that the error message will not explain to
the user why setting the global default dispatcher failed, which is a
bummer.
This branch replaces the derived `Debug` impl with a manually
implemented one that prints …
=> core: give `SetGlobalDefaultError` a useful `Debug` impl

.github/workflows/CI.yml
Test msrv and minimal-versions compliance in the currently best-known fashion.
- Use cargo-hack and cargo-minimal-versions
- Also I replaced uses of actions-rs (abandoned) while I was passing by
=> Refactor CI msrv & minver checks

tracing-subscriber/src/fmt/mod.rs
Previously the documentation for `fmt::init()` was misleading. It stated that it was shorthand for `fmt().init()`. This lead to confusion as users would expect the same behavior from both. However `fmt::init()` would, whether you used the env-filter feature or not, rely on RUST_LOG to set the tracing level. `fmt().init()` does not do this and it must be set with a specific configuration via `with_env_filter`.
The documentation has been updated to no longer state that it is 1:1 shorthand for the other. The documentation now specifically points out that you must be using the `env-filter` feature and gives a correct example to mimic the `fmt::init()` behavior using `fmt().init()`.
fixes: #2217 #1329
=> tracing-subscriber: correct fmt::init() documentation

tracing-subscriber/src/filter/subscriber_filters/combinator.rs, tracing-subscriber/src/filter/subscriber_filters/mod.rs
<!--
Thank you for your Pull Request. Please provide a description above and review
the requirements below.
I'm not completely happy with the explanation as-is.
Try clarifying both the what and the why.
=> Clarify `filter.not()` w.r.t. event_enabled

tracing-appender/src/rolling.rs, tracing-appender/src/rolling/builder.rs, tracing-core/src/dispatcher.rs, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/metrics.rs, tracing-opentelemetry/tests/metrics_publishing.rs, tracing-serde/src/lib.rs, tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/filter/layer_filters/combinator.rs, tracing-subscriber/src/filter/layer_filters/mod.rs, tracing-subscriber/src/filter/targets.rs, tracing-subscriber/src/fmt/mod.rs, tracing-subscriber/src/layer/mod.rs, tracing-subscriber/src/registry/mod.rs, tracing-subscriber/src/registry/sharded.rs, tracing-subscriber/tests/layer_filters/main.rs, tracing-subscriber/tests/layer_filters/per_event.rs
* 9f8c020f subscriber: clarify `filter.not()` docs w.r.t. event_enabled (#2251)
* 5dd00487 core: give `SetGlobalDefaultError` a useful `Debug` impl (#2250)
* 403d506c subscriber: `Not` is `not`, not `or` (#2249)
* f0663e81 subscriber: add `Filter::event_enabled` (#2245)
* 1dbd6689 serde: implement `AsSerde` for `FieldSet` (#2241)
* 64f20f97 subscriber: impl `LookupSpan` for `Box<LS>` and `Arc<LS>` (#2247)
* dc6c1813 subscriber: add `Targets::default_level` method (#2242)
* 63914b6e opentelemetry: feature-flag `MetricsLayer` (#2234)
* 9099a696 opentelemetry: support publishing metrics (#2185)
* af5a800a subscriber: mark builders as must_use (#2239)
* 1f9dad1b appender: add `Builder::filename_suffix` parameter (#2225)****
=> backport a bunch of stuff

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
This release of `tracing-core` adds `PartialEq` and `Eq` implementations
for metadata types, and improves error messages when setting the global
default subscriber fails.
- `PartialEq` and `Eq` implementations for `Metadata` ([#2229])
- `PartialEq` and `Eq` implementations for `FieldSet` ([#2229])
- Fixed unhelpful `fmt::Debug` output for
`dispatcher::SetGlobalDefaultError` ([#2250])
- Fixed compilation with `-Z minimal-versions` ([#2246])
Thanks to @jswrenn and @CAD97 for contributing to this release!
[#2229]: https://github.com/tokio-rs/tracing/pull/2229
[#2246]: https://github.com/tokio-rs/tracing/pull/2246
[#2250]: https://github.com/tokio-rs/tracing/pull/2250
=> core: prepare to release v0.1.29

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This release adds support for owned values and fat pointers as arguments
to the `Span::record` method, as well as updating the minimum
`tracing-core` version and several documentation improvements.
- Incorrect docs in `dispatcher::set_default` ([#2220])
- Compilation with `-Z minimal-versions` ([#2246])
- Support for owned values and fat pointers in `Span::record` ([#2212])
- Documentation improvements ([#2208], [#2163])
- `tracing-core`: updated to [0.1.29][core-0.1.29]
Thanks to @fredr, @cgbur, @jyn514, @matklad, and @CAD97 for contributing
[core-0.1.29]: https://github.com/tokio-rs/tracing/releases/tag/tracing-core-0.1.29
[#2220]: https://github.com/tokio-rs/tracing/pull/2220
[#2246]: https://github.com/tokio-rs/tracing/pull/2246
[#2212]: …
=> tracing: prepare to release v0.1.36

tracing-subscriber/src/fmt/mod.rs
Follow up to #2239
Discovered that 
```rust
tracing_subscriber::fmt().with_ansi(false).finish();
tracing::info!("hello");
```
doesn't actually do anything, because `finish` returns a `Collector` and `init` is the thing that actually installs the collector.
Added `#[must_use]` which suggests using `try_init` instead.
=> add must_use for CollectorBuilder::finish

examples/examples/futures-proxy-server.rs, tracing-attributes/src/expand.rs, tracing-core/src/dispatch.rs, tracing-error/src/error.rs
This fixes some new Clippy lints introduced in the latest Rust version.
=> chore: fix `clippy::borrow_deref_ref` lints

README.md
This PR is my response to
> if you're the maintainer of a tracing ecosystem crate not in this list, please let us know!
I have such a crate, `tracing-chrome`, which writes traces in the format used by `chrome://tracing`, which makes for a handy trace viewer that I usually already have installed.
=> Add tracing-chrome to list of related crates

README.md
`tracing-subscriber` has been on `0.3` for almost a year now.
I naively copied the versions from the README, and when trying to use the library with the current versions of e.g. `tracing-opentelemetry`, I ran into the same error message as seen in this issue: https://github.com/tokio-rs/tracing/issues/852
=> Update tracing-subscriber version in README

tracing-attributes/Cargo.toml, tracing-attributes/src/expand.rs, tracing-attributes/tests/ui.rs, tracing-attributes/tests/ui/async_instrument.rs, tracing-attributes/tests/ui/async_instrument.stderr
Return type errors on instrumented async functions are a bit vague, since the type error originates within the macro itself due to the indirection of additional `async {}` blocks generated in the proc-macro (and due to the way that inference propagates around in Rust). 
This leads to a pretty difficult to understand error. For example:
```rust
#[instrument]
async fn foo() -> String {
""
}
```
results in...
```
error[E0308]: mismatched types
--> src/main.rs:1:1
|
1 | #[tracing::instrument]
| ^^^^^^^^^^^^^^^^^^^^^^- help: try using a conversion method: `.to_string()`
| |
| expected struct `String`, found `&str`
```
Installs a fake `return` statement as the first thing that happens in the auto-generated block of an instrumented async function. 
This causes the coercion machinery within rustc …
=> Add fake return to improve span on type error in `tracing::instrument`

tracing-subscriber/src/filter/env/builder.rs
I just saw this warning when trying to debug something in Miri:
```
warning: some trace filter directives would enable traces that are disabled statically
| `miri::tls=trace` would enable the TRACE level for the `miri::tls` target
= note: the static max level is `info`
= help: to enable DEBUG logging, remove the `max_level_info` feature
```
I spent 10min figuring out why the `log` crate is doing this (Miri is using env-logger for logging), until I realized that this error actually originates from inside rustc, which I guess uses `tracing`. It would have helped if the error message would say which crate is even talking to me here. :)
=> disabled level warning: say which create the message refers to

tracing-core/src/callsite.rs, tracing-core/src/collect.rs, tracing-core/src/dispatch.rs, tracing-subscriber/src/filter/subscriber_filters/mod.rs, tracing-subscriber/src/reload.rs, tracing-subscriber/src/subscribe/layered.rs, tracing-subscriber/src/subscribe/mod.rs
The `on_register_dispatch` method is invoked when a `Collect` is registered as a `Dispatch`. This method can be overridden to perform actions upon the installation of a collector/subscriber; for instance, to send a copy of the collector's `Dispatch` to a worker thread.
Unresolved questions:
- Should it take `&self`, or `&mut self`?
- Should it take `&self`, or _only_ the `&Dispatch` parameter (which can then, if desired, be downcasted to `&self`)?
=> tracing-core, tracing-subscriber: Add `{Collect,Subscriber}::on_register_dispatch`

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/mod.rs
I noticed that #1871 and #2102 targeted the `v0.1.x` branch and they were never ported to master. This branch fixes that.
(On an aside, I discovered the `-Xfind-renames` flag on `git cherry-pick`, which makes handling the layer -> subscriber rename much easier.)
=> chore: port PRs pointed at v0.1.x to master

README.md, tracing/src/lib.rs
Fixes #2280 
I've implemented an alternative to [`tracing-wasm`](https://github.com/storyai/tracing-wasm) to fix some issues that I had when using it (most are open as longer time bug reports, no need to recount them here). It should be more up to date with the current tracing framework and, being layer based, is easier to compose with other subscribers, e.g. supports formatting and timing on event logs out of the box.
Add the [`tracing-web`](https://crates.io/crates/tracing-web/) crate to the list of related crates.
=> Add tracing-web to the list of related crates

.github/workflows/CI.yml, examples/Cargo.toml, examples/examples/sloggish/sloggish_collector.rs, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md, tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs, tracing-subscriber/src/lib.rs
This increases the MSRV of `tracing-subscriber` to 1.50+.
See also: #2040
[ansi_term](https://github.com/ogham/rust-ansi-term) last time update is over 2 years ago, use 
nushell team forked [nu-ansi-term](https://github.com/nushell/nu-ansi-term) instead
Use [nu-ansi-term](https://github.com/nushell/nu-ansi-term)
=> deps: Use `nu-ansi-term` to replace unmaintained `ansi_term`

tracing-opentelemetry/src/subscriber.rs
One can want to have an event added from outside context of a span,
especially in an async code (e.g. between polls of the future, or
between polling multiple futures instrumented with that span). Then it
is expected that the event will be attached indeed to the span specified
as the parent and not the contextual one.
Fixes: #2295 
see #2295 
see #2295
=> opentelemetry: on_event respects event's explicit parent

.github/workflows/CI.yml, examples/Cargo.toml, examples/examples/opentelemetry.rs, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/metrics.rs, tracing-opentelemetry/src/subscriber.rs, tracing-opentelemetry/src/tracer.rs, tracing-opentelemetry/tests/metrics_publishing.rs, tracing-opentelemetry/tests/trace_state_propagation.rs
Support the latest OpenTelemetry specification.
Update `opentelemetry` to the latest `0.18.x` release. Breaking changes in the metrics spec have removed value recorders and added histograms so the metrics layer's `value.` prefix has been changed to `histogram.` and behaves accordingly. Additionally the `PushController` configuration for the metrics layer has been simplified to accept a [`BasicController`](https://docs.rs/opentelemetry/0.18.0/opentelemetry/sdk/metrics/controllers/struct.BasicController.html) that can act in either push or pull modes. Finally trace sampling in the sdk's `PreSampledTracer` impl has been updated to match the sampling logic in https://github.com/open-telemetry/opentelemetry-rust/pull/839.
=> opentelemetry: Update otel to 0.18.0

.github/workflows/CI.yml, examples/Cargo.toml, examples/examples/opentelemetry.rs, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/layer.rs, tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/metrics.rs, tracing-opentelemetry/src/tracer.rs, tracing-opentelemetry/tests/metrics_publishing.rs, tracing-opentelemetry/tests/trace_state_propagation.rs
=> opentelemetry: backport update otel to 0.18.0

tracing/src/macros.rs
`bare_trait_objects` lint will become a hard error in Rust 2021.
While tracing is still using Rust 2018, `bare_trait_objects` is a warning in the MSRV and `dyn` keyword is recommended.
Replace all `&Value` with `&dyn Value` in macro expansions.
=> macros: Add dyn keyword for trait objects in valueset! expansion

.github/workflows/CI.yml, README.md, examples/Cargo.toml, examples/examples/opentelemetry.rs, tracing-attributes/Cargo.toml, tracing-attributes/src/expand.rs, tracing-attributes/tests/ui.rs, tracing-attributes/tests/ui/async_instrument.rs, tracing-attributes/tests/ui/async_instrument.stderr, tracing-core/src/callsite.rs, tracing-core/src/dispatcher.rs, tracing-core/src/subscriber.rs, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/layer.rs, tracing-opentelemetry/src/lib.rs, tracing-opentelemetry/src/metrics.rs, tracing-opentelemetry/src/tracer.rs, tracing-opentelemetry/tests/metrics_publishing.rs, tracing-opentelemetry/tests/trace_state_propagation.rs, tracing-subscriber/src/filter/env/builder.rs, tracing-subscriber/src/filter/layer_filters/mod.rs, tracing-subscriber/src/layer/layered.rs, tracing-subscriber/src/layer/mod.rs, tracing-subscriber/src/reload.rs, tracing/src/lib.rs, tracing/src/macros.rs
Some additional backports.
(Let's see if CI passes first—I suspect that it won't...)
=> chore: Backports to v0.1.x

tracing-opentelemetry/CHANGELOG.md, tracing-opentelemetry/Cargo.toml, tracing-opentelemetry/README.md, tracing-opentelemetry/src/lib.rs
Changelog:
- Upgrade to `v0.18.0` of `opentelemetry` ([#2303])
For list of breaking changes in OpenTelemetry, see the
[v0.18.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0180).
- `on_event` respects event's explicit parent ([#2296])
=> opentelemetry: prepare for v0.18.0 release

tracing-attributes/tests/async_fn.rs, tracing-attributes/tests/ui/async_instrument.stderr
* **attributes: suppress dead code warnings for compile tests**
The `async_fn` test file in `tracing-attributes` contains several
functions that exist just to test whether they _compile_, rather than
make assertions about their behavior. Because these functions are never
called, they (naturally) emit dead code warnings.
This commit adds `#[allow(dead_code)]` to the compilation tests, plus a
comment explaining why we do this.
* **attributes: update trybuild output for Rust 1.64.0**
The error messages for these tests appear to have changed a bit with
Rust 1.64. This branch runs the tests with `TRYBUILD=overwrite` to
update for the latest Rust.
=> attributes: update trybuild, fix warnings

tracing-core/src/collect.rs, tracing-core/src/dispatch.rs, tracing-subscriber/src/subscribe/mod.rs, tracing/src/dispatch.rs
Allows collectors and subscribers to stash their own `Dispatch` without causing a memory leak.
Resolves a shortcoming of https://github.com/tokio-rs/tracing/pull/2269: that it's impossible for collectors or subscribers to stash a copy of their own `Dispatch` without creating a reference cycle that would prevent them from being dropped. 
Introduces `WeakDispatch` (analogous to `std::sync::Weak`) that holds a weak pointer to a collector. `WeakDispatch` can be created via `Dispatch::downgrade`, and can be transformed into a `Dispatch` via `WeakDispatch::upgrade`.
=> tracing-core: Add `Dispatch::downgrade()` and `WeakDispatch`

tracing-appender/Cargo.toml, tracing-appender/src/rolling.rs, tracing-appender/src/rolling/builder.rs
`tracing-appender` does not have `Rotation` based on size yet.
Also, it doesn't have the feature of **keeping the most recent `N` log files**
I believe the second feature is more easy to implement, and also will partially solve the `Rotation` based on size problem. Because people may choose `hourly` or `daily` rotation based on their needs, and put an extra boundary of `keep the last 5 files` for example. Of course it won't handle all the edge cases for `Rotation` based on size. But it will cover most of the scenarios. And also, it is a good feature to have on its own :)
Introduce another field called `keep_last: Option<usize>` to the `Inner` of `RollingFileAppender` struct.
I managed to did not touch any of the existing functions, so it **WON'T BE A BREAKING CHANGE**. Yay :)
The solution …
=> max_log_files_feature

tracing-opentelemetry/src/metrics.rs, tracing-opentelemetry/tests/metrics_publishing.rs
This fixes a discrepancy in the `tracing-opentelemetry` docs for the new MetricsLayer. The docs refer to `value.` as a way to collect discrete data point, but this doesn't match any of the prefix constant mentioned in the same file.
```rust
const METRIC_PREFIX_MONOTONIC_COUNTER: &str = "monotonic_counter.";
const METRIC_PREFIX_COUNTER: &str = "counter.";
const METRIC_PREFIX_HISTOGRAM: &str = "histogram.";
```
This fixes the documentation and test by referring to `histogram.` instead of `value.`.
=> doc(opentelemetry): use histogram for metrics

README.md, tracing/src/lib.rs
Add [`reqwest-tracing`](https://crates.io/crates/reqwest-tracing) to the list of related crates.
=> docs: Add reqwest-tracing to related crates in README

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
This release of `tracing-core` adds a new `on_register_dispatch` method to the `Subscriber` trait to allow the `Subscriber` to perform initialization after being registered as a `Dispatch`, and a `WeakDispatch` type to allow a `Subscriber` to store its own `Dispatch` without creating reference count cycles.
- `Subscriber::on_register_dispatch` method ([#2269])
- `WeakDispatch` type and `Dispatch::downgrade()` function ([#2293])
Thanks to @jswrenn for contributing to this release!
[#2269]: https://github.com/tokio-rs/tracing/pull/2269
[#2293]: https://github.com/tokio-rs/tracing/pull/2293
=> core: prepare to release v0.1.30

tracing-attributes/src/expand.rs, tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs, tracing-attributes/tests/instrument.rs
When the `instrument` attribute is used on a function with inner attributes, the proc macro generates code above the attributes within the function block that causes compilation errors. These should be parsed out separately and handled.
Fixes: #2294
I updated `MaybeItemFn` and `MaybeItemFnRef` to so they hold both the outer and inner attributes for the instrumented function and updated the codegen to inlcude them in the appropriate locations.
I couldn't preserve the existing `impl From<&'_ ItemFn> for MaybeItemFnRef<'_, Box<Block>>` due to lifetime issues and error handling (converting the `ItemFn` requires me to parse the `item.block` for inner attributes which is a local that I can't return, and the parsing could fail), so instead we now have an `impl From<ItemFn> for MaybeItemFn`. I …
=> attributes: fix handling of inner attributes

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md, tracing-attributes/src/lib.rs
This release of `tracing-attributes` fixes a bug where compiler diagnostic spans for type error sin `#[instrument]`ed `async fn`s have the location of the `#[instrument]` attribute rather than the location of the actual error, and a bug where inner attributes in `#[instrument]`ed functions would cause a compiler error. ### Fixed
- Fix incorrect handling of inner attributes in `#[instrument]`ed functions ([#2307])
- Add fake return to improve spans generated for type errors in `async fn`s ([#2270])
- Updated `syn` dependency to fix compilation with `-Z minimal-versions` ([#2246])
Thanks to new contributors @compiler-errors and @e-nomem, as well as @CAD97, for contributing to this release!
[#2307]: https://github.com/tokio-rs/tracing/pull/2307
[#2270]: …
=> attributes: prepare to release v0.1.23

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This release of `tracing` incorporates changes from `tracing-core`
[v0.1.30][core-0.1.30] and `tracing-attributes` [v0.1.23][attrs-0.1.23],
including the new `Subscriber::on_register_dispatch` method for
performing late initialization after a `Subscriber` is registered as a
`Dispatch`, and bugfixes for the `#[instrument]` attribute.
Additionally, it fixes instances of the `bare_trait_objects` lint, which
is now a warning on `tracing`'s MSRV and will become an error in the
next edition.
- **attributes**: Incorrect handling of inner attributes in
`#[instrument]`ed functions (https://github.com/tokio-rs/tracing/pull/2307)
- **attributes**: Incorrect location of compiler diagnostic spans
generated for type errors in `#[instrument]`ed `async fn`s (https://github.com/tokio-rs/tracing/pull/2270) …
=> tracing: prepare to release v0.1.37

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml
This release of `tracing-subscriber` fixes a regression introduced in
[v0.3.15][subscriber-0.3.15] where `Option::None`'s `Layer`
implementation would set the max level hint to `OFF`. In addition, it
adds several new APIs, including the `Filter::event_enabled` method for
filtering events based on fields values, and the ability to log internal
errors that occur when writing a log line.
This release also replaces the dependency on the unmaintained
[`ansi-term`] crate with the [`nu-ansi-term`] crate, resolving an
*informational* security advisory ([RUSTSEC-2021-0139] for
[`ansi-term`]'s maintainance status. This increases the minimum
supported Rust version (MSRV) to Rust 1.50+, although the crate should
still compile for the previous MSRV of Rust 1.49+ when the `ansi`
feature is not enabled. …
=> subscriber: prepare to release v0.3.16

netlify.toml
Currently, the Netlify docs are failing because of a warning that one of the lints we explicitly enable is no longer a warning on nightly but becoming a hard error. This is because the docs are built on nightly with `-D warnings`, which denies all warnings...which seems not ideal.
For now, let's not remove that lint from the `deny` list, as it's still a valid lint on stable. Instead, this PR explicitly allows that lint on the docs build.
=> chore: allow renamed and removed lints on docs build

tracing-subscriber/src/filter/targets.rs
There's currently a `fmt::Display` impl for `EnvFilter` that emits an
equiovalent filter string that can be parsed back into an `EnvFilter`,
but the `Targets` filter does not have a `fmt::Display` impl. We ought
to have one, especially to make using `Targets` with `clap` v4.0 easier.
This branch adds a `fmt::Display` impl for `filter::Targets`. The
implementation is pretty straightforward.
I also added tests that a `Targets`' `fmt::Display` output can be parsed
back into a filter that's equivalent to the original.
=> subscriber: impl `fmt::Display` for `filter::Targets`

tracing-appender/src/lib.rs, tracing-attributes/Cargo.toml, tracing-attributes/src/lib.rs, tracing-attributes/tests/instrument.rs, tracing-attributes/tests/levels.rs, tracing-core/src/field.rs, tracing-core/src/lib.rs, tracing-error/src/lib.rs, tracing-flame/src/lib.rs, tracing-futures/src/executor/mod.rs, tracing-futures/src/lib.rs, tracing-log/src/lib.rs, tracing-serde/src/lib.rs, tracing-subscriber/src/lib.rs, tracing-tower/src/lib.rs, tracing/src/field.rs, tracing/src/lib.rs
The `#[instrument(level = X)]` parameter accepts `Level::DEBUG` (etc) constants, which seems like the most natural way to
specify it, and more consistent with the other `event!`/`span!` macros.
This PR:
- adds tests for specifying level with `Level` constants
- updates the documentation to use Level constants as the preferred/default usage
There are no functional changes to the macros themselves.
=> Better documentation & tests for using `Level` constants for `#[instrument(level = X)]`

clippy.toml, tracing-attributes/src/expand.rs, tracing-core/src/dispatch.rs, tracing-subscriber/benches/support/mod.rs, tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/registry/sharded.rs, tracing-subscriber/tests/field_filter.rs, tracing/src/span.rs, tracing/tests/span.rs
This commit fixes some new Clippy lints that landed in Rust 1.65.0, and removes a deprecated config key in `clippy.toml` in favor of its new name.
This should fix warnings on CI.
=> chore: track Rust 1.65 clippy lints

tracing-subscriber/src/fmt/time/mod.rs
This `doc_cfg` attribute's `cfg` part has multiple predicates without an `all`, which iis what's breaking the netlify build. I'm...kind of surprised this ever succeeded, since the cfg is malformed...
=> subscriber: fix wrong `doc_cfg` attribute

tracing-appender/src/non_blocking.rs, tracing-appender/src/worker.rs
The worker thread name in non blocking mode is always "tracing-appender".
It can be convenient to quickly identify the appender threads for
audit reasons or affinity pinning.
This patch adds a new setter to the builder and propagates the info to
the thread initialization.
=> appender: allow worker thread name to be configured (#2364)

tracing-attributes/src/expand.rs
Getting clippy warnings when using the macro https://github.com/tokio-rs/tracing/pull/2270#issuecomment-1282881008
Adding the clippy lint warning as discussed here https://github.com/tokio-rs/tracing/pull/2270#issuecomment-1282887973
=> tracing-attributes: allow warning clippy unreachable

tracing-mock/Cargo.toml, tracing-mock/src/collector.rs, tracing-mock/src/expectation.rs, tracing-mock/src/lib.rs, tracing-mock/src/subscriber.rs, tracing-subscriber/Cargo.toml, tracing-subscriber/tests/cached_subscriber_filters_dont_break_other_subscribers.rs, tracing-subscriber/tests/env_filter/main.rs, tracing-subscriber/tests/env_filter/per_subscriber.rs, tracing-subscriber/tests/hinted_subscriber_filters_dont_break_other_subscribers.rs, tracing-subscriber/tests/multiple_subscriber_filter_interests_cached.rs, tracing-subscriber/tests/subscriber_filter_interests_are_cached.rs, tracing-subscriber/tests/subscriber_filters/filter_scopes.rs, tracing-subscriber/tests/subscriber_filters/main.rs, tracing-subscriber/tests/subscriber_filters/per_event.rs, tracing-subscriber/tests/subscriber_filters/trees.rs, tracing-subscriber/tests/subscriber_filters/vec.rs, tracing-subscriber/tests/unhinted_subscriber_filters_dont_break_other_subscribers.rs, tracing-subscriber/tests/vec_subscriber_filter_interests_cached.rs
The `tracing-subscriber` module `tests::support` included functionality to mock a subscriber (via the `Subscribe` trait). This code depends on some items from `tracing_mock::collector` which should otherwise not be public.
This change moves the mocking functionality inside `tracing-mock` behind a feature flag. Allowing the `Expect` enum and `MockHandle::new` from `tracing_mock::collector` to be made `pub(crate)` instead of `pub`. Since it's now used from two different modules, the `Expect` enum has been moved to its own module.
This requires a lot of modifications to imports so that we're not doing wildcard imports from another crate (i.e. in `tracing-subscriber` importing wildcards from `tracing-mock`).
Closes: #2359
=> mock: move subscriber mock from tracing-subscriber tests

tracing-appender/src/rolling.rs
The `MakeWriter` trait comes from the `tracing-subscriber` crate, not `tracing-appender`.
=> Fix typo in RollingFileAppender docs

tracing-subscriber/src/lib.rs
There is a small wording mistake in the tracing-subscriber docs that can be fixed quickly and easily.
Two duplicate words were removed.
=> fix(docs): Remove accidentally duplicated words

tracing-subscriber/src/fmt/format/mod.rs
Fixes https://github.com/tokio-rs/tracing/issues/2408
Fixes https://github.com/tokio-rs/tracing/issues/2408
Just switch to use `dim`
Before:
After:
Full mode for comparison:
=> format: dim compact targets, matching the default formatter

tracing-attributes/tests/ui/async_instrument.stderr
There is a broken test in `tracing-attributes/tests/ui/async_instrument.rs`
caused by a change in an error message in `rustc`.
The error message suggesting that you remove a semicolon to return a
value (instead of unit) was updated slightly in rust-lang/rust#102650,
which was included in Rust 1.66.0.
This causes one of the tests in tracing-attributes to fail. We fix it by
using the updated error message.
=> attributes: update `async_instrument` error text for Rust 1.66

tracing-attributes/src/lib.rs, tracing-attributes/tests/ui.rs, tracing-attributes/tests/ui/const_instrument.rs, tracing-attributes/tests/ui/const_instrument.stderr
Fixes: #2414
I'm newer to using macro expansions to enforce `compile_error!` calls, and this is my interpretation on how to approach it.  Unfortunately, the `compile_error!` is triggering regardless of whether I'm instrumenting a function or not, which makes me think I'm not approaching the code generation portion correctly.
Should I be forming this as a `proc_macro` instead of a `macro_rules`?
=> Add compile error on const fn instrumentation

tracing-mock/src/collector.rs, tracing-mock/src/event.rs, tracing-mock/src/subscriber.rs
There has been interest around publishing `tracing-mock` to crates.io
for some time. In order to make this possible, documentation and some
code clean up is needed.
The `subscriber` module needs documentation and examples.
This change adds documentation to the `subscriber` module and all the public
APIs within it. This includes doctests on all the methods which serve as
examples.
The `MockSubscriberBuilder::record` method was removed as its
functionality is not implemented.
Previously, the `MockSubscriber` would verify the scope of an
`ExpectedEvent`, even if `in_scope` hadn't been called. In this case,
that would check that an event was not in a span if `in_scope` had not
been called. `tracing-subscriber` all adhere to this pattern. However it
is different to the behavior of all other …
=> mock: document public APIs in `subscriber` module

tracing-error/src/subscriber.rs, tracing-opentelemetry/src/subscriber.rs
New clippy lints in Rust 1.67.0 are causing pipelines to fail with
existing code, this should be fixed so that pipelines pass again.
There are new warnings as errors reported by clippy in Rust 1.67.0.
This are causing builds to fail, e.g.:
https://github.com/tokio-rs/tracing/actions/runs/4027112923/jobs/6922513360
In both cases they are reports of lifetimes that can be elided. This
change removes the unnecessary lifetime annotations to make clippy
happy.
=> fix new clippy lints from 1.67.0

assets/warning-css.html, netlify.toml
The documentation under https://tracing.rs/tracing/ is missing CSS styles.
Fixes #2444 
Used the `--html-in-header` rustdoc flag instead of `--extend-css`. Converted the css file into an html file.
=> fix(doc): warning styles in html-in-header

tracing-attributes/src/lib.rs
The current description for the default level of the `err` return value event _strongly implies_ it's the same as the span. However, the implementation actually defaults to `ERROR`.
This PR documents that, so future generations don't have to chase down the truth, like I did. 😉
=> attributes: document default level for `err`

tracing-journald/tests/journal.rs
This fixes a Clippy lint that a borrow is not needed. Totally trivial but will make clippy happier.
=> chore: fix `clippy::needless_borrow` lint in journald tests

tracing-core/src/field.rs, tracing-core/src/metadata.rs, tracing/src/macros.rs
Make `tracing::event!` codegen smaller
Add `inline` to several functions called by `tracing::event!`.
Simple example: https://github.com/ldm0/tracing_test
After inlining, executable size drops from 746kb to 697kb(`cargo build --release + strip`), saves 50 bytes per `event!`.
Test environment:
```
toolchain: nightly-aarch64-apple-darwin
rustc-version: rustc 1.70.0-nightly (88fb1b922 2023-04-10)
```
=> `inline` several methods to make `tracing::event!` smaller

tracing-appender/src/lib.rs, tracing-attributes/src/expand.rs, tracing-attributes/src/lib.rs, tracing-attributes/tests/ui/async_instrument.stderr, tracing-core/src/dispatcher.rs, tracing-core/src/lib.rs, tracing-error/src/lib.rs, tracing-flame/src/lib.rs, tracing-futures/src/lib.rs, tracing-log/src/lib.rs, tracing-serde/src/lib.rs, tracing-subscriber/src/filter/targets.rs, tracing-subscriber/src/lib.rs, tracing-subscriber/src/registry/sharded.rs, tracing-tower/src/lib.rs, tracing/src/lib.rs
Clippy check fails in recent CI runs in v0.1.x branch PRs, for example this run: https://github.com/tokio-rs/tracing/actions/runs/4641107803/jobs/8215263838 .
Relevant error logs:
```
error: lint `const_err` has been removed: converted into hard error, see issue #71800 <https://github.com/rust-lang/rust/issues/71800> for more information
--> tracing-core/src/lib.rs:132:5
|
132 |     const_err,
|     ^^^^^^^^^
|
= note: `-D renamed-and-removed-lints` implied by `-D warnings`
error: deref which would be done by auto-deref
--> tracing-core/src/dispatcher.rs:371:26
|
371 |                 return f(&*entered.current());
|                          ^^^^^^^^^^^^^^^^^^^ help: try this: `&entered.current()`
|
= help: for further information visit …
```
=> CI: fix clippy warnings for v0.1.x

tracing-subscriber/Cargo.toml, tracing-subscriber/src/fmt/time/time_crate.rs
As I asked earlier in [discussions](https://github.com/tokio-rs/tracing/discussions/2545), I'm trying to use `LocalTime` in `tracing-subscriber::fmt`, i.e. something like this: 
```
tracing_subscriber::fmt()
.with_timer(tracing_subscriber::fmt::time::LocalTime::rfc_3339())
```
However, with the `time` crate 0.3.2, I need to build with `--cfg unsound_local_offset`, which is not desirable. In fact, `time` crate has removed this requirement since v0.3.18. Hence I propose to update `time` crate version in this branch.
Update `time` crate to version `0.3.18`. I tried locally to use `LocalTime` after updating, there is no problem without `--cfg unsound_local_offset`.
=> subscriber: update time crate to 0.3.18

tracing-attributes/Cargo.toml
Remove unused `syn`s feature `visit`
=> tracing-attributes: remove unused syn's feature visit

tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/mod.rs
Currently it is not possible to disable ANSI in `fmt::Subscriber` without enabling the `ansi` crate feature. This makes it difficult for users to implement interoperable settings that are controllable with crate features without having to pull in the dependencies `ansi` does.
I hit this while writing an application with multiple logging options set during compile-time and I wanted to cut down on dependencies if possible.
This adds a simple `fmt::Subscriber::disable_ansi()` that is available even without the `ansi` crate feature.
=> subscriber: add ability to disable ANSI without crate feature

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml
This release of `tracing-subscriber` fixes a build error when using `env-filter` with recent versions of the `regex` crate. It also introduces several minor API improvements.
- **env-filter**: Add "unicode-case" and "unicode-perl" to the `regex` dependency, fixing a build error with recent versions of `regex` (#2566)
- A number of minor documentation typos and other fixes (#2384, #2378, #2368, #2548)
- **filter**: Add `fmt::Display` impl for `filter::Targets` (#2343)
- **fmt**: Made `with_ansi(false)` no longer require the "ansi" feature, so that ANSI formatting escapes can be disabled without requiring ANSI-specific dependencies (#2532)
- **fmt**: Dim targets in the `Compact` formatter, matching the default formatter (#2409)
Thanks to @keepsimple1, @andrewhalle, @LeoniePhiline, …
=> subscriber: prepare to release v0.3.17

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/src/lib.rs
This release of `tracing-attributes` adds support for passing an optional `level` to the `err` and `ret` arguments to `#[instrument]`, allowing the level of the generated return-value event to be overridden. For example,
```rust
#[instrument(err(level = "info"))]
fn my_great_function() -> Result<(), &'static str> {
// ...
}
```
will emit an `INFO`-level event if the function returns an `Err`.
In addition, this release updates the [`syn`] dependency to v2.x.x.
- `level` argument to `err` and `ret` to override the level of the generated return value event (#2335)
- Improved compiler error message when `#[instrument]` is added to a `const fn` (#2418)
- Updated `syn` dependency to 2.0 (#2516)
- Fix `clippy::unreachable` warnings in `#[instrument]`-generated code (#2356)
- Removed unused …
=> attributes: prepare to release v0.1.24

tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md, tracing/src/lib.rs
This `tracing` release changes the `Drop` implementation for
`Instrumented` `Future`s so that the attached `Span` is entered when
dropping the `Future`. This means that events emitted by the `Future`'s
`Drop` implementation will now be recorded within its `Span`. It also
adds `#[inline]` hints to methods called in the `event!` macro's
expansion, for an improvement in both binary size and performance.
Additionally, this release updates the `tracing-attributes` dependency
to [v0.1.24][attrs-0.1.24], which updates the [`syn`] dependency to
v2.x.x. `tracing-attributes` v0.1.24 also includes improvements to the
`#[instrument]` macro; see [the `tracing-attributes` 0.1.24 release
notes][attrs-0.1.24] for details.
- `Instrumented` futures will now enter the attached `Span` in their
`Drop` …
=> tracing: prepare to release v0.1.38

tracing/src/field.rs, tracing/src/span.rs
When reading the docs I noticed some typo's and while fixing them I noticed warnings from cargo doc
Fixed the typos and the doc warnings in tracing
=> Improve tracing docs

tracing-subscriber/src/lib.rs
This was inconsistent with other features, which mention their requirements, and a reader might assume they don't need to inspect the feature flags page or manifest.
Document the requirement.
=> docs: document `registry` feature requirement for `fmt` feature

tracing-core/src/dispatcher.rs, tracing-core/src/subscriber.rs, tracing-core/tests/local_dispatch_before_init.rs
Currently, when a call to `dispatcher::get_default` occurs, `tracing`
will check the thread-local default dispatcher first. If a thread-local
scoped default is set, it is returned. Otherwise, the thread will then
check the global default. If a global default is present, it is then
cached in the thread local, so that subsequent calls do not need to
check the global default.
Unfortunately, this behavior results in issues if the scoped default is
accessed (e.g. using `get_default` or creating a new span) *prior* to a
global default being set. When `get_default` runs for the first time and
there is no global default, a `none` dispatcher is cached as the
thread-local default. This means that the thread will now behave as
though its default dispatcher is `None` until the scoped default is …
=> core: remove thread local caching of the global default subscriber

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
This release of `tracing-core` fixes a bug that caused threads which
call `dispatcher::get_default` _before_ a global default subscriber is
set to never see the global default once it is set. In addition, it
includes improvements for instrumentation performance in some cases,
especially when using a global default dispatcher.
- Fixed incorrect thread-local caching of `Dispatch::none` if
`dispatcher::get_default` is called before
`dispatcher::set_global_default` (https://github.com/tokio-rs/tracing/pull/2593)
- Cloning a `Dispatch` that points at a global default subscriber no
longer requires an `Arc` reference count increment, improving
performance substantially (https://github.com/tokio-rs/tracing/pull/2593)
- `dispatcher::get_default` no longer attempts to access a thread local
if the …
=> core: prepare to release v0.1.31

tracing/src/lib.rs
While reading tracing docs on https://docs.rs/tracing/latest/tracing/index.html# I found a dead link which should have lead to RAII pattern documentation. 
I'm submitting a code change to update the reference foremented document to refer to correct location for the RAII pattern.
=> Fix doc link to RAI pattern crate documentation

tracing-attributes/src/expand.rs
A patch release with this would be very appreciated; I think the lint is new in 1.70.
=> Fix clippy::let_with_type_underscore in generated code

tracing/tests/span.rs
The purpose of this test is to assert two clones of the same span are equal to each other, so the clone is kind of the whole point of the test. This commit adds an allow attribute to make clippy shut up about it.
=> chore: silence `clippy::redundant_clone` warning

tracing-core/src/field.rs
Module `tracing::field` documentation is missing a word.
Fixing the typo by adding `event`.
=> core: field: fix typo in doc

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md
This release of `tracing-attributes` fixes warnings due to `allow` attributes in generated code that allow lints which may not exist on earlier versions of rustc.
- Allow `unknown_lints` in macro-generated code ([#2626])
Thanks to @mladedav for contributing to this release!
=> attributes: prepare to release v0.1.26

tracing/src/lib.rs, tracing/tests/rebuild_interest_doesnt_deadlock.rs, tracing/tests/register_callsite_doesnt_deadlock.rs
A deadlock exists when a collector's `register_callsite` method calls
into code that also contains tracing instrumentation and triggers a
second `register_callsite` call for the same callsite. This is because
the current implementation of the `MacroCallsite` type holds a
`core::sync::Once` which it uses to ensure that it is only added to the
callsite registry a single time. This deadlock was fixed in v0.1.x in PR
#2083, but the issue still exists on v0.2.x.
This branch forward-ports the solution from #2083. Rather than using a
`core::sync::Once`, we now track the callsite's registration state
directly in `MacroCallsite`. If a callsite has started registering, but
has not yet completed, subsequent `register` calls will just immediately
receive an `Interest::sometimes` until the …
=> tracing: fix recursive `register_callsite` deadlock

tracing-core/src/field.rs, tracing-core/src/lib.rs, tracing-log/src/lib.rs, tracing-subscriber/src/filter/subscriber_filters/mod.rs, tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/macros.rs, tracing-subscriber/src/subscribe/mod.rs, tracing/src/macros.rs, tracing/tests/macros.rs
Currently, in many places, macros do not use fully qualified names for items exported from the prelude. This means that naming collisions (`struct Some`) or the removal of the std library prelude will cause compilation errors.
- Identify and use fully qualified names in macros were we previously assumed the Rust std prelude. We use `::core` rather than `::std`.
- Add [`no_implicit_prelude`](https://doc.rust-lang.org/reference/names/preludes.html#the-no_implicit_prelude-attribute) to `tracing/tests/macros.rs`. I'm unsure if this is giving us good coverage - can we improve on this approach? I'm not confident I've caught everything.
=> use fully qualified names in macros for items exported from std prelude

tracing-journald/src/socket.rs, tracing-subscriber/src/fmt/time/mod.rs
This lint is blocking landing https://github.com/tokio-rs/tracing/pull/2407, so I'd like get rid of that blocker.
(cc: @jsgf)
=> tracing-journald: remove unnecessary `mut`

tracing-core/src/field.rs
The test relies on TEST_CALLSITE_1 and TEST_CALLSITE_2 to have different addresses. However, as they are zero-sized types, this is not guaranteed.
This fixes the test failure with LLVM 17 and certain optimization options reported at https://github.com/rust-lang/rust/issues/114699.
=> Ensure callsites in test have unique addresses

tracing/tests/macros.rs
Tests involving `wasm_bindgen_test` currently fail:
https://github.com/tokio-rs/tracing/actions/runs/5756318807/job/15605512576
=> chore: fix `wasm_bindgen_test` macros

tracing-attributes/src/expand.rs
The instrument macro currently doesn't work with the "log" crate feature: #2585
Change the generated code to create a span if either `tracing::if_log_enabled!` or `tracing::level_enabled!`. I'm not sure how to add a test for this or if this is the best solution.
=> Fix #2585: instrument with "log" feature

tracing-flame/src/lib.rs
The `.folded` format expects a `;`-separated list of the stack function, optionally followed up by a sample count.
The implementation before this commit added a blank space after each `;` which made parsers, such as `inferno-flamegraph` mis-interpret the data.
Furthermore, normally one wouldn't expect the filename and line-number in such stack trace.
Remove white-space between `;` for the generated file and remove filename and line-number by default.
=> flame: fix folded formatting

tracing-attributes/src/expand.rs
`#[tracing::instrument]` uses `unreachable!()` macro which needlessly expands to panicking and formatting code. It only needs any `!` type.
`loop {}` works just as well for a `!` type, and it crates less work for the compiler. The code is truly unreachable, so the message would never be useful. Rust used to be concerned about semantics of empty loops in LLVM, but this [has been solved](https://reviews.llvm.org/D85393).
=> Generate less dead code for async block return type hint

tracing-core/src/field.rs, tracing/src/lib.rs, tracing/src/span.rs, tracing/tests/macros.rs
fixes: #1566
This change removes the maximum of 32 fields limitation using const generics.
Having this arbitrary restriction in place to prevent stack overflows feels a little misplaced to me since stack size varies between environments.
=> Allow `value_set`s  of any length

tracing/src/lib.rs, tracing/src/macros.rs, tracing/tests/macros.rs
The motivation is #1426.  Currently, event names are set to a default value of `event file:line`, which (1) doesn't allow for customization, and (2) prevents events from working for some opentelemetry endpoints (they often use the event name `exception` to designate something like a panic).
Went through the event macros, and added new parameterization that allows for setting the `name`.  In addition, added some comments, and reordering, to make life a bit better for the next person that comes along to edit those macros.  Finally, added tests for the macro expansion alongside the existing tests with a reasonable amount of coverage (though, admittedly, more could be added for all of the macro invocation types).
=> Allow setting event names in macros.

tracing-attributes/Cargo.toml
As part of landing #2728, I noticed that the `-Zminimal-versions` check fails due to proc-macro2 1.0.40 referencing a since-removed, nightly-only (`proc_macro_span_shrink`) feature. Since this change doesn't change the MSRV of `proc-macro2` (or `tracing`, for that matter), this feels like a safe change to make.
=> attributes: bump minimum version of proc-macro2 to 1.0.60

tracing-attributes/tests/async_fn.rs, tracing-journald/src/lib.rs
The latest Clippy emits warnings for uses of `unwrap_or_else` with
functions that return a type's `Default::default` value, such as
`.unwrap_or_else(String::new)`. Clippy would prefer us to use
`unwrap_or_default` instead, which does the same thing.
This commit fixes the lint. Personally, I don't really care about this,
but it makes the warning go away...
=> journald: fix clippy `unwrap_or_default` warning

tracing-log/Cargo.toml
The package `atty`, a dependent of env_logger < 0.10, has a RUSTSEC advisory raised against it.
=> update to env_logger 0.10 to fix https://github.com/advisories/GHSA-g98v-hv3f-hcfr

tracing-attributes/src/lib.rs
Noticed while reading the docs
=> Spelling: "overriden" => "overridden"

tracing-log/Cargo.toml
Due to minimum version selection issues, a desire to remove the `env_logger` feature wholesale, and to keep the number of breaking changes to a minimum, I'm reverting #2740 in favor of marking the `tracing-log/env_logger` feature as deprecated and releasing `tracing-log` 0.2.0 _without_ `env_logger`.
=> log: revert #2740

tracing-log/src/lib.rs
Continuation of the plan outlined in #2750.
(Note that this is intentionally _not_ targeting the `master` branch, as we'll just remove `env_logger` feature there.)
=> log: deprecate `env_logger` in favor of `tracing_subscriber::fmt::Subscriber`

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml
Cherry-picked out of https://github.com/tokio-rs/tracing/pull/2749.
=> chore: prepare tracing-attributes 0.1.27

tracing/src/macros.rs, tracing/tests/macros.rs
When a custom macro "format_args" is defined, macros such as `tracing::warn`, `tracing::debug`, etc. will fail. 
Using the full path `::core::format_args!` fixes this.
Also added a short test case (+ cargo fmt on the macro tests).
Fixes: #2721
=> tracing: use full path when calling format_args!

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml
=> chore: prepare tracing-core 0.1.32

tracing/CHANGELOG.md, tracing/Cargo.toml
Cherry-picked out of https://github.com/tokio-rs/tracing/pull/2749.
=> chore: prepare tracing 0.1.39

tracing/src/instrument.rs
The current code is UB and LLVM could choose to reuse the stack slot causing a UAF.
UB is bad.
Don't do that.
=> Use ManuallyDrop instead of mem::forget

tracing-core/src/metadata.rs
These docs were updated (in response to #1669), but the "or equal to" phrase should have been moved to the other case.
Fixes: #1993
When these docs were updated in response to #1669, they were updated incompletely (a level that is equal to a filter is _enabled_, not _disabled_) and therefore remained incorrect.
The docs were updated, moving the "or equal to" phrase to the other case.
=> Fix incorrectly updated incorrect docs for `tracing_core::LevelFilter`

tracing/src/lib.rs, tracing/src/macros.rs
When a user has a crate named `core`, it can cause issues because our crates import from `::core::*`. Now we are importing from `$crate::__macro_support::*` and there won't be any name clashes anymore.
Fixes: #2761
=> tracing: removed core imports in macros

tracing-log/CHANGELOG.md, tracing-log/Cargo.toml
Bit overdue, but here's the prepared changes for tracing-log 0.1.4.
=> chore: Prepare tracing-log 0.1.4

tracing-log/CHANGELOG.md, tracing-log/Cargo.toml, tracing-subscriber/Cargo.toml
This branch prepares a release of `tracing-log 0.2.0`. The sole breaking change
is the removal of the `env_logger` feature. Please refer to #2771 and #2750 
for the context behind this decision.
(Note that this branch depends on #2770 and #2771. I will rebase this branch to
catch changes that exist on v0.1.x when those branches land.)
=> chore: prepare tracing-log 0.2.0

tracing-attributes/src/lib.rs
There was an error when backporting #1378 (here: #1418) and a trailing dot (.) was forgotten (which was breaking the link). Fixed also the link to `std::fmt::Debug`.
=> docs: attributes: fix small backporting error

tracing-subscriber/src/filter/env/builder.rs
The from_env and try_from_env method on the builder had the same documentation. This change updates their docs to correctly describe their difference in behavior.
Make the docs more clear, so that users need not look at the source to understand the difference between these two functions.
Updated the docs
=> subcriber: update docs for EnvFilter Builder

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml
=> chore: prepare tracing-subscriber 0.3.18 release

tracing-subscriber/tests/reload.rs
fixes https://github.com/tokio-rs/tracing/actions/runs/6785393202/job/18443641813
cargo test runs tests in the same file in parallel by default, causing race condition,
this can be proven by running 
`cargo test --test reload -- --test-threads=1` => successes 
`cargo test --test reload -- --test-threads=2` => flaky
multiple times 
This fix runs only the two tests in serial.
We could seperate the tests in different files, but they share the same testing dependencies, so I left them in the same file.
=> Fixes flaky test

examples/examples/sloggish/sloggish_collector.rs
@taiki-e Sorry, I can't reopen https://github.com/tokio-rs/tracing/pull/2842 cuz I pushed first.
Anyway, turns out this seems to only be a bug on 1.75. I couldn't repro because I'm on nightly, so we can just suppress it for now.
=> chore: suppress clippy lint

tracing-journald/src/lib.rs, tracing-journald/tests/journal.rs
This allows to manually map tracing levels to journald levels.
It seems that @little-dude, who started the original PR, doesn't have time to finish this, so I picked it up.  Reapplied the changes to the newest master branch and fixed the latest comments/issues.
This will also fix/close:
- #2649
- #2661
- #2347 (the original pr)
=> journald: make level mappings configurable

examples/examples/fmt/yak_shave.rs, tracing-core/src/metadata.rs, tracing-error/CHANGELOG.md, tracing-error/src/error.rs, tracing-mock/src/subscriber.rs, tracing-subscriber/CHANGELOG.md, tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/filter/filter_fn.rs, tracing-subscriber/src/filter/mod.rs, tracing-subscriber/src/filter/subscriber_filters/mod.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/time/datetime.rs, tracing-subscriber/src/subscribe/mod.rs, tracing/CHANGELOG.md, tracing/README.md, tracing/src/lib.rs, tracing/src/macros.rs, tracing/tests/enabled.rs
There are quite a few typos in the docs.
=> chore: Fix spelling

README.md
Missed this during https://github.com/tokio-rs/tracing/pull/2602/files
=> Update README.md with correct link to tracing-etw

examples/examples/sloggish/sloggish_collector.rs, tracing-core/src/dispatch.rs, tracing-subscriber/src/filter/subscriber_filters/mod.rs, tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/registry/sharded.rs
=> Use const thread_locals when possible

tracing-attributes/src/expand.rs, tracing-attributes/tests/async_fn.rs
When using `#[tracing::instrument]` and the `async unsafe` modifiers the generated function read `unsafe async fn`, which is wrong. Corrected the order and added a test.
Fixes: #2576
=> Change order of async and unsafe modifiers in `instrument` procmacro

tracing/src/macros.rs, tracing/tests/macros.rs
If something like `warn!(?foo)` and `warn!(name: "foo", ?foo)` works, then `warn!(name: "foo", target: "foo_events", ?foo)` should arguably also work. Before this change the more complicated variants of the macros however required a message argument, due to the usage of the `+` specifier in the macro definitions. 
This commit changes the `+` (1 or more) to `*` (0 or more), which matches how the `field` tokens are used in the simpler variants of the macro.
~Note that this PR includes https://github.com/tokio-rs/tracing/pull/2878 to avoid merge conflicts, since they both target the same lines.~
=> macros: Fix non-simple macro usage without message

tracing-attributes/src/expand.rs
On clippy version 1.76.0 this gives a warning, extracting the scrutinee to a variable fixes this.
Fixes: #2876
=> attributes: extract match scrutinee

tracing-attributes/src/expand.rs, tracing-attributes/tests/instrument.rs, tracing-core/src/dispatch.rs, tracing-core/src/field.rs, tracing-futures/tests/std_future.rs, tracing-subscriber/src/registry/sharded.rs, tracing/tests/instrument.rs
clippy is failing with recent Rust toolchain up to 1.77.2.
Give clippy what it wants.
=> chore: new clippy/rust lints

tracing-appender/Cargo.toml, tracing-core/src/field.rs, tracing-subscriber/Cargo.toml, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/fmt/time/datetime.rs, tracing-subscriber/src/lib.rs, tracing-subscriber/src/registry/sharded.rs, tracing/Cargo.toml, tracing/src/span.rs
New lints were added to 1.78 which breaks CI.
New lints are fixed. I also fixed lints present in the beta channel for 1.79.
=> chore: fix clippy lints

tracing-core/src/field.rs, tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/fmt/format/pretty.rs
Users may want to pass data to `Subscribe`s which is not valid UTF-8. Currently, it would have to be encoded into `&str` to be passed as a field value.
This branch adds a `record_byte_slice` method to `Visit`. It has an implementation falling back to `record_debug` so it is not be a breaking change.
`JsonVisitor` got an overridden implementation as it should not use `Debug` output and encode it as a string, but rather store the bytes as an array.
`PrettyVisitor` go an overridden implementation to make the output more pretty.
=> tracing: allow `&[u8]` to be recorded as event/span field

tracing-mock/src/collector.rs, tracing-mock/src/expect.rs, tracing-mock/src/span.rs
It currently isn't possible to differentiate spans with the same name,
target, and level when setting expectations on `enter`, `exit`, and
`drop_span`. This is not an issue for `tracing-mock`'s original (and
still primary) use case, which is to test `tracing` itself. However,
when testing the tracing instrumentation in library or application code,
this can be a limitation.
For example, when testing the instrumentation in tokio
(tokio-rs/tokio#6112), it isn't possible to set an expectation on which
task span is entered first, because the name, target, and level of those
spans are always identical - in fact, the spans have the same metadata
and only the field values are different.
To make differentiating different spans possible, `ExpectId` has been
introduced. It is an opaque struct which …
=> mock: add `ExpectedId` to link span expectations

tracing-attributes/tests/fields.rs, tracing/src/macros.rs, tracing/tests/event.rs, tracing/tests/span.rs
Currently, a keyword like `type` fails compilation as (a path segment of) a field name, for no clear reason. Trying to use `r#type` instead leads to the `r#` being part of the field name, which is unhelpful¹. 
Don't require the field path to match a `macro_rules!` `expr`, use repeated `tt` instead. I can't tell why this was ever required: The internal stringify macro was introduced in https://github.com/tokio-rs/tracing/commit/55091c92edb537bfc126e32f1f24acd614ad9fe0#diff-315c02cd05738da173861537577d159833f70f79cfda8cd7cf1a0d7a28ace31b with an `expr` matcher without any explanation, and no tests are failing from making it match upstream's `stringify!` input format.
Special thanks to whoever implemented the unstable `macro-backtrace` feature in rustc, otherwise this would have been nigh …
=> macros: Allow field path segments to be keywords

tracing-core/src/lib.rs, tracing/src/lib.rs, tracing/src/macros.rs
This commit fixes a bug where a macro call to macros defined in the
standard lib from the `tracing` and `tracing-core` crates could be
resolved to a local macro with the same name, causing a compilation
error. 
This commit prefixes these calls with `::core::` to ensure that
they are resolved to the standard library macros.
Fixes: <https://github.com/tokio-rs/tracing/issues/3023>
While this fixes the specific issue at hand, there's likely many macro calls that are impacted by this problem - specifically every call to module_path (there are many). I haven't updated all of those places as I was unsure if that was a good idea as there's about 220 calls of that macro. I also haven't checked for other macros that would also be problematic.
=> fix: prefix macro calls with ::core to avoid clashing with local macros

tracing-serde/src/lib.rs, tracing-subscriber/src/fmt/fmt_subscriber.rs, tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/fmt/format/mod.rs
Clippy in 1.80.0 alerted us to the fact that `SerializeField` was never
constructed (and due to its non-`pub` member, it can't be constructed
outside the `tracing-serde` crate where it's from).
This change fixes the definition to hold a reference to a `Field`, which
is what the other `Serialize*` types do. It also implements `AsSerde`
for this type and uses it inside the `SerializeFieldSet` type.
As a bonus, Clippy is now also happy that the type is constructed.
The example collector in the `tracing-serde` crate was also renamed from
`JsonSubscriber` to `JsonCollector`.
=> fix: correct SerializeField definition

tracing-attributes/tests/parents.rs, tracing-futures/tests/std_future.rs, tracing-mock/src/ancestry.rs, tracing-mock/src/collector.rs, tracing-mock/src/event.rs, tracing-mock/src/expect.rs, tracing-mock/src/lib.rs, tracing-mock/src/span.rs, tracing-mock/src/subscriber.rs, tracing-mock/tests/event_ancestry.rs, tracing-mock/tests/span_ancestry.rs, tracing/tests/event.rs, tracing/tests/instrument.rs, tracing/tests/span.rs
When recording the parent of an event or span, the `MockCollector`
treats an explicit parent of `None` (i.e. an event or span that is an
explicit root) in the same way as if there is no explicit root. This
leads to it picking up the contextual parent or treating the event or
span as a contextual root.
This change refactors the recording of the parent to use `is_contextual`
to distinguish whether or not an explicit parent has been specified. The
actual parent is also written into an `Ancestry` enum so that the
expected and actual values can be compared in a more explicit way.
Additionally, the `Ancestry` struct has been moved into its own module and
the check behavior has been fixed. The error message has also been
unified across all cases.
Another problem with the previous API is that the …
=> mock: correct contextual/explicit parent assertions

Cargo.toml, examples/Cargo.toml, tracing-attributes/Cargo.toml, tracing-attributes/tests/instrument.rs, tracing-core/Cargo.toml, tracing-core/src/field.rs, tracing-futures/Cargo.toml, tracing-futures/src/executor/futures_01.rs, tracing-futures/src/executor/mod.rs, tracing-futures/tests/std_future.rs, tracing-journald/Cargo.toml, tracing-log/Cargo.toml, tracing-macros/Cargo.toml, tracing-mock/Cargo.toml, tracing-serde/Cargo.toml, tracing-subscriber/Cargo.toml, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/time/chrono_crate.rs, tracing-subscriber/src/fmt/time/datetime.rs, tracing-subscriber/src/lib.rs, tracing-subscriber/src/registry/sharded.rs, tracing-tower/Cargo.toml, tracing/Cargo.toml, tracing/tests/instrument.rs
=> master: clean up warnings

tracing-attributes/src/expand.rs, tracing-attributes/tests/async_fn.rs
#2864 and #2880 both targeted `0.1.x` instead of `master`.
=> chore: forward-port attributes changes

tracing-mock/src/collector.rs, tracing-mock/src/span.rs, tracing-mock/src/subscriber.rs
Many of the methods on `MockCollector` take an `ExpectedSpan`. This
often requires significant boilerplate. For example, to expect that a
span with a specific name enters and then exits, the following code is
needed:
```rust
let span = expect::span().named("span name");
let (collector, handle) = collector::mock()
.enter(span.clone())
.exit(span)
.run_with_handle();
```
In order to make using `tracing-mock` more ergonomic and also more
compact, the `MockCollector` and `MockSubscriber` methods that previous
took an `ExpectedSpan`, are now generic over `Into<ExpectedSpan>`.
There are currently 3 implementations of `From` for `ExpectedSpan` which
allow the following shorthand uses:
`T: Into<String>` - an `ExpectedSpan` will be created that expects to
have a name specified by `T`.
```rust
let …
```
=> mock: improve ergonomics when an `ExpectedSpan` is needed

.github/workflows/CI.yml, examples/Cargo.toml
There is an incompatibility with the version of Node available on our
test runners and wasm32 in Rust 1.82 (#3123).
To unblock the CI, this change pins Rust to 1.81 for the tests using the
`wasm32-unknown-unknown` target. This is the same strategy used in Tokio
to mitigate tokio-rs/tokio#6910 until a more permanent fix can be put in
place.
This change also bumps the MSRV on the `tracing-examples` crate from
1.63.0 to 1.64.0 to avoid triggering a lint about the MSRV after a
change in Tokio 1.41.0 which bumps the required Rust version for the
`try_join!` macro. The Tokio MSRV is 1.70 now, so needing this bump for
the examples seems reasonable.
=> ci: pin Rust to 1.81 for `wasm32-unknown-unknown` tests

tracing/README.md, tracing/src/lib.rs
I've created a library for better customization of JSON log lines and would like to make it more discoverable.
This subscriber could help with a lot of issues such as #1531 
Add `json-subscriber` to the ecosystem.
=> Add `json-subscriber` to ecosystem

tracing-mock/src/ancestry.rs, tracing-mock/src/collector.rs, tracing-mock/src/event.rs, tracing-mock/src/expect.rs, tracing-mock/src/metadata.rs, tracing-mock/src/span.rs, tracing-mock/src/subscriber.rs, tracing-mock/tests/event_ancestry.rs, tracing-mock/tests/span_ancestry.rs
The `with_ancestry` methods on `NewSpan` and `ExpectedEvent` provide a
way to match whether the span or event is a contextual or explicit root
or if it has a contextual or explicit parent span.
However, in the case of matching on a contextual or explicit parent
span, only the span name could be used for matching. This is
sufficiently precise when testing tracing instrumentation in other
libraries or applications as opposed to testing tracing itself.
It is likely that a user would like to test that some span or event has
a specific span as a parent, and not just any span with a specific name,
in many cases, all the possible parent spans may have the same name.
This is the case when testing tracing instrumentation in Tokio.
To solve this problem, the `Ancestry` struct was renamed to …
=> mock: match parent span on `ExpectedSpan`

tracing-subscriber/src/fmt/mod.rs
The commit 1cb523b87d3d removed this cfg gate on master. However, when the change was backported in 049ad730c1ba the docs were updated but the `cfg` change was omitted. Some more detail and links are in issue #2996.
This made the docs misleading, since they say "This method itself is still available without the feature flag."
Fixes #2996.
=> subscriber: don't gate `with_ansi()` on the "ansi" feature

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
- Add index API for `Field` ([#2820])
- allow `&[u8]` to be recorded as event/span field ([#2954])
- Use const `thread_local`s when possible ([#2838])
- Fix missed `register_callsite` error ([#2938])
- Do not add `valuable/std` feature as dependency unless `valuable` is used ([#3002])
- prefix macro calls with ::core to avoid clashing with local macros ([#3024])
- Fix incorrect (incorrectly updated) docs for LevelFilter ([#2767])
Thanks to new contributor @maddiemort for contributing to this release!
[#2767]: https://github.com/tokio-rs/tracing/pull/2767
[#2820]: https://github.com/tokio-rs/tracing/pull/2820
[#2838]: https://github.com/tokio-rs/tracing/pull/2838
[#2938]: …
=> chore: prepare tracing-core 0.1.33

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md
- Added missing RecordTypes for instrument ([#2781])
- Change order of async and unsafe modifier ([#2864])
- Extract match scrutinee ([#2880])
- Allow field path segments to be keywords ([#2925])
- Support const values for `target` and `name` ([#2941])
- Fix backporting error in attributes ([#2780])
[#2780]: https://github.com/tokio-rs/tracing/pull/2780
[#2781]: https://github.com/tokio-rs/tracing/pull/2781
[#2864]: https://github.com/tokio-rs/tracing/pull/2864
[#2880]: https://github.com/tokio-rs/tracing/pull/2880
[#2925]: https://github.com/tokio-rs/tracing/pull/2925
[#2941]: https://github.com/tokio-rs/tracing/pull/2941
=> chore: prepare tracing-attributes 0.1.28

tracing/Cargo.toml
Updates the main `tracing` crate with the newly released versions of
`tracing-core` and `tracing-attributes`.
=> tracing: update core to v0.1.33 and attributes to v0.1.28

tracing-mock/Cargo.toml, tracing-subscriber/Cargo.toml, tracing/CHANGELOG.md, tracing/Cargo.toml, tracing/README.md
[ [crates.io][crate-0.1.41] ] | [ [docs.rs][docs-0.1.41] ]
This release updates the `tracing-core` dependency to [v0.1.33][core-0.1.33] and
the `tracing-attributes` dependency to [v0.1.28][attrs-0.1.28].
- **core**: Add index API for `Field` ([#2820])
- **core**: Allow `&[u8]` to be recorded as event/span field ([#2954])
- **core**: Use const `thread_local`s when possible ([#2838])
- Removed core imports in macros ([#2762])
- **attributes**: Added missing RecordTypes for instrument ([#2781])
- **attributes**: Change order of async and unsafe modifier ([#2864])
- Fix missing field prefixes ([#2878])
- **attributes**: Extract match scrutinee ([#2880])
- Fix non-simple macro usage without message ([#2879])
- Fix event macros with constant field names in the …
=> chore: prepare tracing 0.1.41

tracing-serde/CHANGELOG.md, tracing-serde/Cargo.toml, tracing-serde/README.md, tracing-serde/src/lib.rs, tracing-subscriber/Cargo.toml
[ [crates.io][crate-0.2.0] ] | [ [docs.rs][docs-0.2.0] ]
<a id = "0.2.0-breaking"></a>
- Correct SerializeField definition and doc formatting ([#3040])
`SerializeField` has gained a generic lifetime parameter.
- Implement `AsSerde` for `FieldSet` ([#2241])
- [**breaking**](#0.2.0-breaking) Correct SerializeField definition and doc formatting ([#3040])
[#2241]: https://github.com/tokio-rs/tracing/pull/2241
[#3040]: https://github.com/tokio-rs/tracing/pull/3040
[docs-0.2.0]: https://docs.rs/tracing-serde/0.2.0/tracing-serde/
[crate-0.2.0]: https://crates.io/crates/tracing-serde/0.2.0
=> chore: prepare tracing-serde 0.2.0

examples/examples/counters.rs, examples/examples/sloggish/sloggish_subscriber.rs, tracing-appender/benches/bench.rs, tracing-appender/src/rolling.rs, tracing-attributes/src/expand.rs, tracing-core/src/dispatcher.rs, tracing-core/src/field.rs, tracing-core/src/metadata.rs, tracing-error/src/backtrace.rs, tracing-log/src/lib.rs, tracing-mock/src/field.rs, tracing-serde/src/fields.rs, tracing-serde/src/lib.rs, tracing-subscriber/src/field/mod.rs, tracing-subscriber/src/filter/env/field.rs, tracing-subscriber/src/fmt/fmt_layer.rs, tracing-subscriber/src/fmt/format/json.rs, tracing-subscriber/src/fmt/format/mod.rs, tracing-subscriber/src/fmt/format/pretty.rs, tracing-subscriber/src/fmt/time/mod.rs, tracing-subscriber/src/fmt/writer.rs, tracing-subscriber/src/layer/context.rs, tracing-subscriber/src/registry/mod.rs, tracing-subscriber/src/registry/sharded.rs, tracing-subscriber/tests/layer_filters/option.rs, tracing-test/src/lib.rs, tracing/benches/shared.rs, tracing/src/field.rs, tracing/src/span.rs
Most of these changes are places where lifetimes were named, but can be
elided. Then a few cases where a lifetime was elided, but actually
resolves to a named lifetime. So lots of lifetimes.
This is the `v0.1.x` branch sister PR to #3164 (for the `master`
branch), since `clippy --fix` on another branch is a much better way to
apply these changes than backporting.
=> chore: fix new Clippy lints in Rust 1.83.0

tracing-subscriber/CHANGELOG.md, tracing-subscriber/Cargo.toml, tracing-subscriber/README.md
[ [crates.io][crate-0.3.19] ] | [ [docs.rs][docs-0.3.19] ]
This release updates the `tracing` dependency to [v0.1.41][tracing-0.1.41] and
the `tracing-serde` dependency to [v0.2.0][tracing-serde-0.2.0].
- Add `set_span_events` to `fmt::Subscriber` ([#2962])
- **tracing**: Allow `&[u8]` to be recorded as event/span field ([#2954])
- Set `log` max level when reloading ([#1270])
- Use const `thread_local`s when possible ([#2838])
- Don't gate `with_ansi()` on the "ansi" feature ([#3020])
- Updated tracing-serde to 0.2.0 ([#3160])
[#1270]: https://github.com/tokio-rs/tracing/pull/1270
[#2838]: https://github.com/tokio-rs/tracing/pull/2838
[#2954]: https://github.com/tokio-rs/tracing/pull/2954
[#2962]: …
=> chore: prepare tracing-subscriber 0.3.19

tracing-error/CHANGELOG.md, tracing-error/Cargo.toml, tracing-error/README.md
[ [crates.io][crate-0.2.1] ] | [ [docs.rs][docs-0.2.1] ]
- Use intra-doc links instead of relative file paths ([#2068])
- More intra-doc links ([#2077])
- Add missing backtick to `prelude` docs ([#2120])
[#2068]: https://github.com/tokio-rs/tracing/pull/2068
[#2077]: https://github.com/tokio-rs/tracing/pull/2077
[#2120]: https://github.com/tokio-rs/tracing/pull/2120
[docs-0.2.1]: https://docs.rs/tracing-error/0.2.1/tracing_error/
[crate-0.2.1]: https://crates.io/crates/tracing-error/0.2.1
=> chore: prepare tracing-error 0.2.1

tracing-journald/CHANGELOG.md, tracing-journald/Cargo.toml
[ [crates.io][crate-0.3.1] ] | [ [docs.rs][docs-0.3.1] ]
- disable default features of tracing-subscriber ([#1476])
- allow custom journal fields ([#2708])
- make level mappings configurable ([#2824])
[#1476]: https://github.com/tokio-rs/tracing/pull/1476
[#2708]: https://github.com/tokio-rs/tracing/pull/2708
[#2824]: https://github.com/tokio-rs/tracing/pull/2824
[docs-0.3.1]: https://docs.rs/tracing-journald/0.3.1
[crate-0.3.1]: https://crates.io/crates/tracing-journald/0.3.1
=> chore: prepare tracing-journald 0.3.1

tracing-mock/CHANGELOG.md, tracing-mock/Cargo.toml, tracing-mock/README.md
[ [crates.io][crate-0.1.0-beta.1] ] | [ [docs.rs][docs-0.1.0-beta.1] ]
`tracing-mock` provides tools for making assertions about what `tracing`
diagnostics are emitted by code under test.
- Initial beta release
[docs-0.1.0-beta.1]: https://docs.rs/tracing-mock/0.1.0-beta.1
[crate-0.1.0-beta.1]: https://crates.io/crates/tracing-mock/0.1.0-beta.1
I used this PR to also clean up a few things in the README that referenced
`tracing-mock` not being on crates.io (because the idea is that now it will
be). I added badges linking to where the crate should be when it's uploaded,
hopefully they're even the correct links.
The changelog is new of course.
And I added my own name to the list of authors in `Cargo.toml` 😅.
Refs: #539
=> chore: prepare tracing-mock 0.1.0-beta.1

CONTRIBUTING.md, tracing-attributes/Cargo.toml, tracing-core/Cargo.toml, tracing-error/Cargo.toml, tracing/Cargo.toml
Follow up of https://github.com/tokio-rs/tracing/commit/60c60bef62972e447414a748a95b31ff9027165b
I have removed outdated release instructions from our document.
=> chore: remove outdated release instructions

README.md
@jonhoo recorded a great resource about the crate's inner workings and included practical suggestions about patterns to follow when annotating one's code.
I added the link to the YouTube video under the "Talks" header as that seemed appropriate enough.
=> docs: Adding a link to a stream recording of @jonhoo

tracing-subscriber/src/fmt/format/mod.rs
Closes #2979. 
The current behaviour of `DefaultVisitor` is that it will write padding even if it is going to skip writing a value, which results in extraneous padding being added when values are skipped by the `tracing-log` integration.
With this change, `DefaultVisitor` will only insert padding if it is actually going to write a value.
=> subscriber: skip padding when skipping `log.*` fields in `DefaultVisitor`

tracing-attributes/tests/ui/async_instrument.stderr, tracing-subscriber/src/fmt/writer.rs
There was only a single case of the new `needless_as_bytes` lint which
was triggered and needed to be fixed.
There was also a "UI" test in `tracing-attributes` that needed to be
updated because the error text has changed (it gives more details of
course).
=> chore: fix Rust 1.84.0 lints and errors

tracing-attributes/tests/ui/async_instrument.stderr, tracing-subscriber/src/fmt/writer.rs
=> chore: fix Rust 1.84.0 lints and errors (#3202)

tracing-subscriber/Cargo.toml
The change #2954 was released in 0.3.19 (#3162).
Notably, it relied on features from tracing-core 0.1.33, however, the
version was never bumped. Users of the `tracing` feature of
`tracing-subscriber` would have no issue since it pulls in the higher
version transitively.
The specific feature used was implementing trait method `record_bytes`
from the `field::Visit` trait on `JsonVisitor` from the
tracing-subscriber json format module. (see linked #2945, or [ `impl
field::Visit for
JsonVisitor<'_>`](https://github.com/tokio-rs/tracing/blame/master/tracing-subscriber/src/fmt/format/json.rs#L491))
I believe this dependency mismatch requires users to manually select the
higher tracing-core version or suffer compilation failure.
This probably reflects some failure in how the tests utilize …
=> subscriber: update tracing-core to v0.1.33

tracing-journald/src/lib.rs, tracing-log/src/lib.rs, tracing-subscriber/src/lib.rs, tracing/src/collect.rs
We had some broken link formatting in the `tracing-journald` docs which
clippy picked up (the text looked like a link definition, but wasn't
meant to be). 
The incorrect links have now been corrected. They have to link to the
`tracing-core` crate because `tracing-journald` doesn't depend on
`tracing` directly.
Fixes for a broken link in the `tracing-subscriber` main page and
correcting the link to `Collect` from `tracing-log` (which also doesn't
depend on `tracing` directly) were also included.
=> chore: fix Rust 1.85.0 lints and errors

tracing/src/macros.rs, tracing/src/span.rs, tracing/tests/span.rs
Currently, Span.record_all() is part of the public API and accepts ValueSet as a parameter.
However, constructing a ValueSet is both verbose and undocumented, making it not so practical.
To make recording multiple values easier, we introduce a new macro: record_all!, which wraps the Span.record_all() function. As we don't intend anyone to call Span.record_all() directly, we hide it from the documentation. We reference the new macro from Span.record() doc comment instead.
The new record_all! macro supports optional formatting sigils % and ?, ensuring a consistent DevEx with the other value-recording macros.
=> tracing: add `record_all!` macro for recording multiple values in one call

tracing-core/Cargo.toml, tracing-core/src/collect.rs, tracing-core/src/dispatch.rs
- Fixes #3173
- Added `portable-atomic-util` as an optional dependency gated behind a new feature, `portable-atomic` to `tracing-core`
- When `portable-atomic` is enabled, switched uses of `Arc` and `Weak` away from `alloc::sync` to `portable_atomic_util`.
- Added workaround for a lack of support for [unsized coercion](https://github.com/rust-lang/rust/issues/18598) in custom types. I've included a comment linking to this issue explaining the missing functionality.
I'm currently working on `no_std` support for the [Bevy Game Engine](https://github.com/bevyengine/bevy/issues/15460), which includes targeting embedded devices without full native support for atomics, such as the RP2040 Raspberry Pi Pico. Using `portable-atomic`, users can provide a fallback implementation for atomics to …
=> core: add `portable-atomic` support

.github/workflows/CI.yml, tracing-core/Cargo.toml, tracing-core/src/callsite.rs, tracing-core/src/dispatch.rs, tracing-core/src/metadata.rs, tracing-core/src/spin/once.rs, tracing-futures/Cargo.toml, tracing-macros/Cargo.toml, tracing-macros/src/lib.rs, tracing-serde/Cargo.toml, tracing-subscriber/Cargo.toml, tracing-subscriber/src/registry/mod.rs, tracing/Cargo.toml, tracing/src/lib.rs
This PR expands [`portable-atomic`](https://docs.rs/portable-atomic/) utilisation within Tracing, improving platform support without breaking the existing public API.
Since #3199 was merged, it's now possible to bring more tracing crates to atomically challenged platforms through `portable-atomic`. Additionally, CI is not currently setup to ensure this feature behaves as expected (allowing compilation on platforms with incomplete atomic support).
- Added `portable-atomic` support to:
- `tracing`
- `tracing-futures`
- `tracing-serde`
- `tracing-subscriber`
- Added `no_std` support to:
- `tracing-macros`
- `tracing-futures`
- Added CI task to catch regressions in `portable-atomic` _and_ `no_std` support.
- A `critical-section` feature is also added to make CI testing and usage of …
=> tracing: Add `portable-atomic` support to other `tracing` crates

tracing-subscriber/Cargo.toml, tracing-subscriber/src/filter/env/directive.rs
Intended to fix #3174. Have not done any benchmarks yet -- suggestions on how best to approach that are welcome.
This is a little bit more code, but IMO maybe slightly more readable?
It's correct enough that it passes the tests, there might be edge cases that aren't covered but those should be easy to solve.
=> subscriber: use state machine to parse `EnvFilter` directives

tracing/src/lib.rs, tracing/src/macros.rs, tracing/tests/event.rs
Currently a call like `info!(..., r#type = "...")` ends up emitting a field named "r#type", which is never desirable. Previous work in https://github.com/tokio-rs/tracing/pull/2925 made the desired behavior expressible as `info!(..., type = "...")`, and even before that PR one could write it as `info!(..., "type" = "...")`.
However, when dealing with macro-generated use of tracing, we do still sometimes end up with raw identifiers. For example, if user-provided identifiers are used for both declaring (or instantiating, or accessing) a struct, and also for tracing. Something like this:
```rust
example!(name, r#type);
// expands to:
...
info!(..., name = GLOBAL.name, r#type = GLOBAL.r#type);
...
```
If we ask the user of `example!` to pass `type` (unraw), there is no way for the macro to …
=> macros: Remove 'r#' prefix from raw identifiers in field names

examples/Cargo.toml, examples/examples/env-filter-explorer.rs
On [discord](https://discord.com/channels/500028886025895936/627649734592561152/1349440700919316692), Conrad suggested a website to experiment with env-filter syntax. I think a TUI in tree makes a pretty decent replacement, especially as the output can exactly match the output that a real user might see if they're configuring tracing_subscriber with the default values.
This example demonstrates how to use the `tracing-subscriber` crate's
`EnvFilter` type to filter log messages based on their metadata. The
example provides a text area where users can input an environment filter
string, and displays the log messages that would be captured by that
filter.
There are preset filters that can be selected that show off the syntax.
=> Add env-filter-explorer example

tracing-subscriber/src/fmt/writer.rs
=> MakeWriterExt docs fix

examples/Cargo.toml, tracing-appender/Cargo.toml
The ecosystem has upgraded to thiserror v2, so this crate was causing duplicate dependency versions.
Bump thiserror to v2 - https://github.com/dtolnay/thiserror/releases/tag/2.0.0
=> chore: bump thiserror to v2

Cargo.toml, tracing-appender/src/lib.rs, tracing-appender/src/non_blocking.rs, tracing-subscriber/src/subscribe/mod.rs
There are a few warnings when building the docs causing failures on CI.
This change fixes those and adds `unsound_local_offset` as an unexpeced cfg.
=> chore: fix doc issues

tracing-attributes/src/expand.rs, tracing-attributes/src/lib.rs, tracing-attributes/tests/async_fn.rs, tracing-attributes/tests/dead_code.rs, tracing-attributes/tests/err.rs, tracing-attributes/tests/instrument.rs, tracing-attributes/tests/ui/async_instrument.rs, tracing-attributes/tests/ui/async_instrument.stderr
`#[instrument]`ed functions never trigger a `dead_code` lint.
Closes (partially?) #1366
Include all of the input tokens in the output. In particular, the brace tokens surrounding the function body, the parenthesis surrounding the function parameters, and the angle brackets surrounding the generics must be included.
Prior art: https://github.com/andrewhickman/fn-error-context/commit/cfa749aaef91157bae8d3a984e6650bc00f6af68
=> Let `dead_code` lint work on `#[instrument]`ed functions

tracing-core/src/metadata.rs
`self` and `other` are references, and the `ptr::eq()` call intends to determine if they designate the same object. Putting them behind another level of reference will always return `false`, as those short-lived references will be compared instead.
Remove the extra references.
As this is only an optimization which was missed, it is not possible to design a test which failed before this PR and succeeds after.
=> fix: do not compare references to pointers to compare pointers

tracing/src/macros.rs, tracing/tests/macros.rs
I'm on tracing v0.1.40 and cannot use macro
```
tracing::event!(name: "name", parent: &span, Level::ERROR, "foo")
``` 
and its variants (`debug!()`, etc) due to error
```
no method named `is_enabled` found for struct `DefaultCallsite` in the current scope
```
Looks like it was just missed out by accident
=> fix `Name / parent` variant of `event!()`  

tracing-subscriber/src/fmt/fmt_layer.rs
Backports #2944 to the `main` branch.
=> (backport) tracing-subscriber: count numbers of enters in `Timings` (#2944)

tracing-core/CHANGELOG.md, tracing-core/Cargo.toml, tracing-core/README.md
- Bump MSRV to 1.65 ([#3033])
- Do not compare references to pointers to compare pointers ([#3236])
[#3033]: https://github.com/tokio-rs/tracing/pull/3033
[#3236]: https://github.com/tokio-rs/tracing/pull/3236
=> chore: prepare tracing-core 0.1.34

tracing/Cargo.toml
Updates the main `tracing` crate with the newly released versions of
`tracing-core` and `tracing-attributes`.
=> tracing: update core to 0.1.34 and attributes to 0.1.29

README.md
Explain that `master` is no longer in use and direct users to `main` for
the released crates and `v0.2.x` for the pre-release versions.
=> chore: explain new branch set up on `master` branch

tracing-attributes/CHANGELOG.md, tracing-attributes/Cargo.toml, tracing-attributes/README.md
- Fix `tracing::instrument` regression around shadowing ([#3311])
[#3311]: https://github.com/tokio-rs/tracing/pull/3311
=> chore: prepare tracing-attributes 0.1.30

tracing-subscriber/src/filter/env/mod.rs, tracing-subscriber/src/sync.rs
In #2360, people have requested `impl Clone for EnvFilter` in order to use `EnvFilter` as a `clap` argument. In `conduwuit`, we want this in order to do something like this:
```rust
let filter_layer: EnvFilter = ...;
let subscriber = Registry::default()
.with(console_subscriber::spawn())
.with(logging_subscriber_a.with_filter(filter_layer.clone()))
.with(logging_subscriber_b.with_filter(filter_layer.clone()))
```
`tokio-console`'s `console_subscriber` layer needs to be unfiltered in order to pick up tokio trace events, but we have several "logging-type" layers that we want to apply the configured `EnvFilter` to.
We considered the workaround of constructing several fresh `EnvFilter`s with `EnvFilter::try_new(config.log.clone())`, but would prefer to just clone the `EnvFilter` itself and …
=> subscriber: impl Clone for EnvFilter

tracing-appender/src/rolling.rs, tracing-appender/src/rolling/builder.rs
The prune_old_logs function only gets called when we rollover the appender. The problem is that at startup we create an initial log file without rolling over, if e.g., the executable then exits before rolling over for the first time, we never call prune_old_logs.
E.g.: If we have a tracing-appender that rolls over every minute and we have a max_files parameter of 2. Running the program (which prints a single log line and exits) every minute, will result in a new log file everytime without deleting the old ones.
Fixes: #2937
=> appender: Prune old files at startup
