- tokio-trace-macros/src/lib.rs
Some of these macro cases were incorrect and it looks like naming was wrong for the `(target: $level:expr, ...` case.
Signed-off-by: Kevin Leimkuhler <kevin@kleimkuhler.com>
> Fix macro cases for `trace_dbg!` and `dbg!`

- tokio-trace-env-logger/examples/hyper-echo/sloggish.rs
- tokio-trace-futures/src/lib.rs
- tokio-trace-futures/src/test_support/event.rs
- tokio-trace-futures/src/test_support/field.rs
- tokio-trace-futures/src/test_support/metadata.rs
- tokio-trace-futures/src/test_support/mod.rs
- tokio-trace-futures/src/test_support/span.rs
- tokio-trace-futures/src/test_support/subscriber.rs
- tokio-trace-log/src/lib.rs
- tokio-trace-macros/src/lib.rs
- tokio-trace-subscriber/src/compose.rs
- tokio-trace-subscriber/src/registry.rs
tokio-rs/tokio@9dc0129fe2c108bf1d0d52fd38e60455213bace7 merged a fairly large change to the upstream `tokio-trace` in order to support more efficient batching of field values. This changed several of the `tokio-trace` and `tokio-trace-core` APIs that the crates in this repository depend on. This PR updates all the `tokio-trace-nursery` crates to compile against the latest upstream `tokio-trace`. Note that the `tokio-trace-subscriber` crate will still require a fairly significant rewrite to actually be functional, but that API has needed to be reworked for a while.
> Update to track upstream changes

- .travis.yml
- tokio-trace-futures/src/test_support/event.rs
- tokio-trace-futures/src/test_support/metadata.rs
- tokio-trace-futures/src/test_support/span.rs
- tokio-trace-log/src/lib.rs
- tokio-trace-macros/examples/factorial.rs
- tokio-trace-macros/src/lib.rs
- tokio-trace-subscriber/src/compose.rs
This branch updates the Travis config so that the `tokio-trace-macros`
crate is tested, and the "test proc-macros" step actually tests the
`tokio-trace-proc-macros` crate.
Closes #4 
> chore: update .travis.yml

- tokio-trace-proc-macros/examples/basic.rs
There was no event in `fn suggest_band`, so the span was entered but
nothing showed it doing so. A `debug!` line was added as well as
configuring the logger to log span entry and exits. This way, we see the
traced function has its own span.
Signed-off-by: Kevin Leimkuhler <kevinl@buoyant.io>
> proc-macros: Make basic example more useful

- tokio-trace-proc-macros/examples/args.rs
- tokio-trace-proc-macros/src/lib.rs
The parameters to the function are now passed as fields into `span!` so
that we can see what arguments a traced function is called with.
Before:
```
DEBUG 2019-02-08T22:51:06Z: args: fibonacci_seq: Pushing 0 fibonacci; traced_function="fibonacci_seq";
DEBUG 2019-02-08T22:51:06Z: args: nth_fibonacci: Base case; traced_function="nth_fibonacci";
DEBUG 2019-02-08T22:51:06Z: args: fibonacci_seq: Pushing 1 fibonacci; traced_function="fibonacci_seq";
DEBUG 2019-02-08T22:51:06Z: args: nth_fibonacci: Base case; traced_function="nth_fibonacci";
DEBUG 2019-02-08T22:51:06Z: args: fibonacci_seq: Pushing 2 fibonacci; traced_function="fibonacci_seq";
DEBUG 2019-02-08T22:51:06Z: args: nth_fibonacci: Recursing; traced_function="nth_fibonacci";
DEBUG 2019-02-08T22:51:06Z: args: nth_fibonacci: Base case; …
```
> proc-macros: Pass params to the function as fields

- tokio-trace-fmt/Cargo.toml
- tokio-trace-fmt/src/lib.rs
- tokio-trace-fmt/src/span.rs
This branch rewrites the span store in `tokio-trace-fmt` to
significantly reduce lock contention. Rather than requiring a single
global write lock be acquired for any modification to the span store,
write locks may now be acquired on individual spans without a global
write lock. The write lock around the slab itself must only be acquired
in order to grow the slab.
The significantly reduced lock contention ameliorates any additional
performance hit incurred by the fix in #17. H2 instrumented with
`tokio-trace` can manage over 35RPS in `h2load`, at maximum verbosity.
> fmt: Reduce span store lock contention

- tokio-trace-fmt/src/lib.rs
- tokio-trace-fmt/src/span.rs
- tokio-trace-futures/src/test_support/subscriber.rs
- tokio-trace-log/src/lib.rs
- tokio-trace-proc-macros/examples/args.rs
- tokio-trace-subscriber/src/compose.rs
- tokio-trace-subscriber/src/registry.rs
This branch updates the nursery crates to build with tokio-rs/tokio#923,
which changes the `Subscriber::new_span` function's signature.
> chore: Update to pick up tokio-rs/tokio#923

- tokio-trace-tower-http/Cargo.toml
This branch temporarily changes `tokio-trace-tower-http`'s
dev-dependency on `tower-h2` to require a fixed git SHA. 
This is because the upstream change
tower-rs/tower-h2@226523df4fc33eeafd653f45676ffc01ee7b75c6 introduced a
dependency on the crates.io version of `tower-service`, while other
dependencies of `tower-h2` require a Git version of `tower-service`. 
While `tower-h2` resolves this using a `[patch]`, we don't seem to be
able to, as it appears that `[patch]` does not effect dev-dependencies
(possibly a cargo bug?). Therefore, I've just set the `tower-h2` dev
dependency to depend on the git SHA from before the upstream change
landed, which should fix the CI build for now.
> chore: Temporarily fix upstream version incompatibility

- tokio-trace-fmt/src/filter.rs
This if statement was blocking spans from being registered if the span's level was below that of the one specified as the max_level. This means if a user expressed specific interest in that span and the max level was above it the sub will not enable that. This now enables that type of feature.
> fmt: Fix filtering of spans when they are included in the directive

- tokio-trace-fmt/Cargo.toml
- tokio-trace-fmt/src/filter.rs
- tokio-trace-fmt/src/lib.rs
> fmt: Replace horrible handwritten parser with a regex

- tokio-trace-env-logger/examples/hyper-echo.rs
- tokio-trace-fmt/src/span.rs
- tokio-trace-futures/src/lib.rs
- tokio-trace-futures/src/test_support/subscriber.rs
- tokio-trace-log/src/lib.rs
- tokio-trace-subscriber/src/registry.rs
This branch updates the nursery to ensure compatibility with
tokio-rs/tokio#971 and tokio-rs/tokio#973.
> chore: Update for upstream changes

- tokio-trace-tower-http/Cargo.toml
- tokio-trace-tower-http/src/lib.rs
tower-rs/tower#197 renamed the `tower-util` crate to just `tower`. This
commit updates our dependencies to track that (and thus fix the build).
> tower-http: Fix tower-util breaking the build

- tokio-trace-fmt/src/lib.rs
- tokio-trace-fmt/src/span.rs
Currently, the `FmtSubscriber` doesn't play nice in situations where it
might be wrapped by an outer type which also implements `Subscriber`, if
that outer subscriber requires span refcounting. This is because there
are several cases where `FmtSubscriber` will call `clone_span` or
`drop_span` on `self` directly rather than on the current dispatcher,
meaning that if another subscriber is layered around the
`FmtSubscriber`, it won't see those calls to `clone_span` or
`drop_span`.
I've fixed this by ensuring that `FmtSubscriber` never calls the
ref-counting functions on `self`, and always calls them on the current
subscriber instead.
In the future, the best way to deal with this issue is probably to not
compose subscribers with this kind of layering; but to have one central
registry that …
> fmt: Make `FmtSubscriber` more friendly to being in a stacked

- tokio-trace-fmt/src/filter.rs
This adds the ability to filter fields and values by matching exactly their output as seen in the log line produced from fmt.
> fmt: Filter fields and values

- tokio-trace-env-logger/examples/hyper-echo.rs
- tokio-trace-futures/src/executor.rs
- tokio-trace-futures/src/lib.rs
- tokio-trace-tower-http/src/lib.rs
- tokio-trace-tower/src/lib.rs
tokio-rs/tokio#988 removed the generic lifetime parameter from
`Span`. This branch updates the nursery crates to match.
> chore: Update for tokio-rs/tokio#988

- tokio-trace-futures/examples/proxy_server.rs
This is an example of demonstrating `tokio-trace` instrumentation. I have used the proxy server implementation in the Tokio crate examples.
> Tokio trace instrumentation example

- tokio-trace-fmt/src/default.rs
This allows users to use field names that are reserved keywords like so `info!(r#type = typetag)` and it will ignore the `r#` only if it is the first two characters.
> fmt: Ignore r# if it is included as the field name

- tokio-trace-fmt/src/lib.rs
- tokio-trace-fmt/src/span.rs
This branch makes a couple of minor fixes in `tokio-trace-fmt`:
* When entering a span, if that span has already been entered and we 
are currently in a child of that span, the duplicate entry is 
ignored. This means that spans may be free to re-enter themselves
without wiping out any "deeper" context.
* `tokio-trace-fmt` now actually honors the explicitly specified span
parents added in tokio-rs/tokio#923, rather than ignoring them and
always determining parents contextually.
> fmt: Improve behavior around span entry and parents

- tokio-trace-env-logger/Cargo.toml
- tokio-trace-fmt/Cargo.toml
- tokio-trace-fmt/src/filter/env.rs
- tokio-trace-futures/Cargo.toml
- tokio-trace-futures/src/test_support/field.rs
- tokio-trace-log/Cargo.toml
- tokio-trace-log/src/lib.rs
- tokio-trace-macros/Cargo.toml
- tokio-trace-macros/src/lib.rs
- tokio-trace-proc-macros/Cargo.toml
- tokio-trace-slog/Cargo.toml
- tokio-trace-subscriber/Cargo.toml
- tokio-trace-tower-http/Cargo.toml
- tokio-trace-tower/Cargo.toml
Recent changes to tokio-trace and tokio-trace-core broke the build on
master for tokio-trace-nursery. This change adds missing fields to calls
in tokio-trace-nursery so that it compiles again.
> fix: update nursery to build with trace 0.1 and core 0.2

- Cargo.toml
- tokio-trace-fmt/src/lib.rs
This commit overrides the `downcast_raw` method on `FmtSubscriber` so
that a `FmtSubscriber` can also be downcast to pointers to its generic
components (its on-event callback, filter, and `NewVisitor`).
This will allow implementations of the components of a `FmtSubscriber`
to support "out-of-band" APIs that don't require knowledge of the types
of the _other_ components to downcast the subscriber to a concrete type.
This is intended for use-cases such as dynamic filter reloading (#42).
> fmt: Allow downcasting a FmtSubscriber to its components

- tokio-trace-tower-http/Cargo.toml
- tokio-trace-tower-http/examples/tower-h2-server.rs
- tokio-trace-tower-http/src/lib.rs
This improves tower-http by allow you to not have to specify a span on creation of the instrumented service.
This is dependent on #54
> Improved tower http

- tokio-trace-futures/Cargo.toml
- tokio-trace-futures/src/executor.rs
- tokio-trace-futures/src/lib.rs
This branch simplifies the feature flags used in the
`tokio-trace-futures` crate, and adds compatibility with the
`tokio-executor` crate. The feature formerly called `with-tokio` was
replaced by enabling the optional `tokio` dependency as a feature flag,
and a new `tokio-executor` optional dependency has been added, which
provides additional impls for types implementing
`tokio_executor::Executor`. This allows these impls to be used in crates
that depend on `tokio-executor` rather than `tokio`
> futures: Improve feature flags, add `tokio-executor` compat

- tokio-trace-fmt/src/filter/reload.rs
- tokio-trace-fmt/src/lib.rs
This branch changes the `ReloadFilter` and `Handle` types in
`ReloadFilter` to be generic over the context's `NewRecorder` type,
rather than making the reloading _functions_ generic over that type.
This prevents situations where the `NewRecorder` type is uninferrable.
Fixes #63
> fmt: Make ReloadFilter generic over recorder

- tokio-trace-env-logger/Cargo.toml
- tokio-trace-futures/Cargo.toml
This branch updates the dev-dependency `tokio` versions to 0.1.21, which
depends on tokio-trace-core 0.2. This should resolve issues where
examples and tests did not properly propagate the subscriber contexts
due to a `tokio-trace-core` version mismatch.
> chore: Upgrade tokio version in examples/tests

- tokio-trace-fmt/src/lib.rs
Currently, the `span::Context` type in `tokio-trace-fmt` is required to
write custom formatting functions, as is part of the signature of
`on_event`, etc. However, it is in the private `span` module, and is not
re-exported. This effectively seals the method signature necessary for
`on_event` formatters, meaning custom formatters may not be written.
This branch re-exports `Context` publically so that users may implement
their own formatting functions.
> fmt: re-export Context

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- CONTRIBUTING.md
- README.md
This branch adds a `README.md`, a `CONTRIBUTING.md`, and issue and pull
request templates. These are all based on `tokio-rs/tokio`'s, with some
minor tweaks.
Fixes: #7
> add README.md, CONTRIBUTING.md, and issue/PR templates

- tokio-trace-log/src/lib.rs
Currently, the `LogTracer` adapter in `tokio-trace-log` does not check
if an event translated from a `log` record would be enabled by the
current dispatcher, and _always_ dispatches the event. This means that
the `tokio-trace` subscribers never have the opportunity to filter that
event.
This branch changes the `LogTracer` to call `enabled` on the current
dispatcher before creating an event. Unfortunately, we can't do this in
the `log::Log::enabled` impl for `LogTracer`, since the `log::Metadata`
lacks all the information required to create a `tokio_trace::Metadata`.
There are some potential improvements that we can make as follow-ups: in
particular, the `LogTracer` can keep its own cache of log records and
`Interests`, similar to the callsite cache, to avoid re-evaluating
filters. …
> log: `LogTracer` checks if events are enabled

- tokio-trace-fmt/src/filter/env.rs
The `env_logger` crate allows log directives ending in `off` to
_disable_ all logging from a matching target. However,
`tokio-trace-fmt`'s `EnvFilter` does not.
For example:
``` 
ignoring invalid log directive 'linkerd2_proxy::proxy::canonicalize=off'
ignoring invalid log directive 'linkerd2_proxy::proxy::http::router=off' 
ignoring invalid log directive 'linkerd2_proxy::proxy::tcp=off' 
```
`env_logger` accepts these directives.
This branch adds support for directives with `off`. It was necessary to
reimplement a `LevelFilter` type, here similar to the one in
`tokio-trace`, as `tokio-trace-fmt` only depends on `tokio-trace-core`.
Fixes: #68
> fmt: add support for `off` filter directives

- tokio-trace-fmt/src/filter/env.rs
PR #72 introduced a bug in `EnvFilter` where spans and events whose
level is _equal_ to the filter's max level are rejected, rather than
accepted.
This branch fixes the comparisons so that filters once again
work as expected.
> fmt: fix `EnvFilter` rejecting levels equal to the filter level

- tokio-trace-fmt/src/filter/env.rs
Currently, when parsing filter directives, the `EnvFilter` type in
`tokio-trace-fmt` will skip any invalid directives, and return a default
value if the environment variable is unset. In some cases, users may
prefer to reject filter strings containing invalid directives.
This branch adds new `try_from_env`/`try_from_default_env`/`try_new`
functions to `EnvFilter` which return `Result`s, and return `Err` if any
filtering directives are invalid. The functions not prefixed with `try_`
retain thair old behaviour.
> fmt: add fallible filter parsing

- tokio-trace-fmt/src/filter/reload.rs
In some cases, when filter reloading is in use, it can be valuable to
inspect the current value of a filter without reloading it. For example,
this could be used to format the current state, or call filter-specific
methods on it.
This branch adds a new `Handle::with_current` method. This method
invokes a closure with a borrowed reference to the filter's current
state and returns the result. This does not require acquiring a write
lock.
> fmt: add `reload::Handle::with_current`

- tracing/src/macros.rs
- tracing/tests/event.rs
- tracing/tests/macros.rs
- tracing/tests/support/event.rs
- tracing/tests/support/mod.rs
- tracing/tests/support/span.rs
- tracing/tests/support/subscriber.rs
The event macros added support for overriding the event's parent in
tokio-rs/tracing#1109, but the overridden parent was not actually set,
as the macro always called `Event::dispatch`.
This branch fixes this, and adds tests that assert that the correct
parent is set. I've also changed the macro tests to deny all warnings,
as an unused variable warning was an indicator that the parent field was
being ignored.
Fixes #100
> tracing: fix event macros not overriding parents

- tracing-env-logger/examples/hyper-echo.rs
- tracing-fmt/Cargo.toml
- tracing-fmt/examples/yak_shave.rs
- tracing-fmt/src/default.rs
- tracing-fmt/src/filter/reload.rs
- tracing-fmt/src/lib.rs
- tracing-fmt/src/time.rs
- tracing-futures/examples/proxy_server.rs
- tracing-futures/examples/spawny-thing.rs
- tracing-proc-macros/examples/args.rs
- tracing-proc-macros/examples/basic.rs
- tracing-tower-http/examples/tower-h2-server.rs
This provides an initial implementation of the feature outlined in https://github.com/tokio-rs/tracing/issues/94: timestamps in log messages from the `fmt` subscriber.
See https://github.com/tokio-rs/tracing/issues/94.
This PR introduces a trait for event formatters (`Formatter`) so that it is easier to write more complex formatters (previously they were just `Fn(...) -> fmt::Result` which would require boxing a closure to produce). It then implements this new trait for `default::Standard`, which is the new default formatter. It implements "normal"/full formatting exactly like before, except that it also has a builder (`default::Builder`), and is generic over a timer. The timer must implement `default::FormatTime`, which has a single method that writes the current time out to a …
> fmt: Timestamped log messages

- tracing-core/src/field.rs
- tracing-core/src/metadata.rs
- tracing-env-logger/Cargo.toml
- tracing-env-logger/examples/hyper-echo.rs
- tracing-fmt/Cargo.toml
- tracing-fmt/examples/yak_shave.rs
- tracing-fmt/src/filter/env.rs
- tracing-fmt/src/filter/reload.rs
- tracing-futures/Cargo.toml
- tracing-futures/src/executor.rs
- tracing-futures/src/lib.rs
- tracing-log/Cargo.toml
- tracing-macros/Cargo.toml
- tracing-macros/src/lib.rs
- tracing-proc-macros/Cargo.toml
- tracing-proc-macros/examples/basic.rs
- tracing-proc-macros/src/lib.rs
- tracing-slog/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-tower-http/Cargo.toml
- tracing-tower-http/examples/tower-h2-server.rs
- tracing-tower-http/src/lib.rs
- tracing-tower/Cargo.toml
- tracing-tower/src/lib.rs
This branch updates the "nursery" crates to depend on `tracing` and
`tracing-core` as path dependencies, rather than depending on the
crates.io releases of `tokio-trace` and `tokio-trace-core`. When
`tracing` and `tracing-core` are released, we will change these from
path dependencies to crates.io dependencies.
This branch also updates those crates to track API changes in `tracing`
and `tracing-core`.
> chore: update nursery crates to use path deps on `tracing`

- tracing-fmt/src/filter/env.rs
- tracing-log/Cargo.toml
- tracing-log/src/lib.rs
PR #106 broke some APIs that the nursery crates `tracing-fmt` and
`tracing-log` depended on. At the time, we didn't catch this, as those
crates still depended on `tokio-trace`/`tokio-trace-core` from
crates.io. However, after merging #101, which updated those crates to
use path dependencies on `tracing`/`tracing-core`, those crates broke. 
This branch updates `tracing-fmt` and `tracing-log` to compile with the
changed APIs. `tracing-log` was also changed to depend on `tracing-core`
rather than `tracing`, as only the `core API is required by that crate,
and the `identify_callsite!` macro is not publically re-exported by 
`tracing`.
> fmt, log: fix API breakage

- tracing-core/src/dispatcher.rs
- tracing-core/src/event.rs
- tracing-core/src/span.rs
- tracing-core/src/subscriber.rs
- tracing-fmt/src/lib.rs
- tracing-log/src/lib.rs
Currently, the `span::Attributes` type in `tokio-trace-core` contains a
reference to `Metadata` with a generic lifetime `'a`. This means that if
a `Subscriber` wishes to store span metadata, it cannot simply store a
`&'static Metadata<'static>`. Instead, it must extract the individual
components from the metadata and store them in its own structure. In
addition, while the `name` and `FieldSet` in a `Metadata` are always
`'static`, the target and file path are not.  If the `Subscriber` needs
to store those values, they must be cloned into a `String` on the heap.
This is somewhat unergonomic for subscriber implementors, in comparison
to being able to use a `&'static Metadata<'static>` reference. In
addition, it implies additional overhead when using certain parts of a
span's metadata.
This …
> core: change `Span` and `Event` metadata to be `'static`

- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
0.1.0 (June 27, 2019)
- Initial release
> core: prepare v0.1.0 release

- tracing-fmt/Cargo.toml
- tracing-log/Cargo.toml
- tracing/Cargo.toml
This branch updates `tracing`, `tracing-fmt`, and `tracing-log`
to depend on `tracing-core` 0.1 from crates.io.
> update crates to depend on core from crates.io

- tracing-fmt/Cargo.toml
- tracing-log/Cargo.toml
- tracing/Cargo.toml
This undoes https://github.com/tokio-rs/tracing/pull/113, which erroneously removed `path` from `tracing-core` dependencies. That breaks packages that depend on `tracing-core` _and_ another `tracing-*` crate through `git` dependencies (e.g., in `dev-dependencies`). Instead, all dependencies should list _both_ `version` _and_ `path`, which makes both crates.io and git builds work.
> Undo #113 and re-enable git dependencies

- tracing-tower/src/lib.rs
- tracing/src/macros.rs
- tracing/src/span.rs
- tracing/tests/event.rs
- tracing/tests/macros.rs
- tracing/tests/span.rs
Currently, there is inconsistent syntax in the `event!` and `span!`
macros when setting explicit parents. The `span!` macro takes both
`target` and `parent` after the level, while `event!` expects `target`
before the level and `parent` after. The `event!` syntax is confusing,
and both macros _should_ use a consistent syntax.
This branch updates both macros to follow a consistent syntax where
`target` and `parent` are expected before the level.
Closes #102
> tracing: fix inconsistent macros

- tracing-fmt/src/default.rs
- tracing-fmt/src/lib.rs
With the previous implementation of `Default` for `fmt::default::Format`, users would have to explicitly type out what timer they want when calling `Format::default`, even if they then immediately go on to use `with_timer`. This PR changes the implementation of `Default` to use `SystemTime` like the default generic types on `Format` itself.
> Remove need to typehint Timer

- tracing-fmt/src/default.rs
- tracing-fmt/src/lib.rs
- tracing-fmt/src/time.rs
This fixes some warnings when building with nightly.
> trace-fmt: Use dyn.

- tracing-core/Cargo.toml
- tracing-fmt/Cargo.toml
- tracing-futures/Cargo.toml
- tracing-log/Cargo.toml
- tracing-macros/Cargo.toml
- tracing-serde/Cargo.toml
- tracing-slog/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-tower-http/Cargo.toml
- tracing-tower/Cargo.toml
- tracing/Cargo.toml
- tracing/test-log-support/Cargo.toml
- tracing/test_static_max_level_features/Cargo.toml
#122 updated all crates to use Rust 2018 syntax, but I neglected to add
`edition = "2018"` to the `Cargo.toml`s. 
This fixes that.
> chore: add `edition = "2018` to Cargo.tomls

- .travis.yml
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- tracing/src/readme_doctest.rs
Add a new feature `doctest-readme` which includes the README.md for the `tracing` crate as documentation for an empty module so that it can be treated as a doctest, verifying the examples. This change depends on some nightly only features.
Also adjusts the travis config so that on nightly we also run tests with the optional feature enabled so we verify that the examples in the readme don't become broken.
> feature: include readme in doctests

- .travis.yml
I found the `cargo test --verbose` output on CI very hard to
scroll through to find the errors describing why a build actually
failed. We rarely, if ever, need this level of output, IMO.
This branch removes the `--verbose` flags from CI.
> chore: remove verbose from CI

- .travis.yml
- Cargo.toml
- tracing-env-logger/examples/hyper-echo.rs
- tracing-futures/examples/proxy_server.rs
- tracing/src/lib.rs
- tracing/src/macros.rs
- tracing/src/span.rs
- tracing/test-log-support/Cargo.toml
- tracing/test_static_max_level_features/Cargo.toml
`tracing`'s `log` feature flag was not being properly tested on CI,
since it is tested by a separate test crate that sets the feature flag.
When this crate lived in the `tokio-rs/tokio` repository, the test crate
was built on CI, but I neglected to add it here during the repo move.
Then, we inadvertently committed code that broke that feature.
I've added the test crates to the workspace so that they are built
correctly by `cargo test --all`, which we run on CI.
Fixes #137
> tracing: fix log support

- CONTRIBUTING.md
- bin/publish
This branch updates CONTRIBUTING.md to document how to release
a new version of a Tracing crate, and adds the `publish` shell script
from the `tokio-rs/tokio` repo to aid in the release process.
I've also updated references in CONTRIBUTING.md to refer to Tracing
rather than Tokio Trace.
> meta: add releasing docs and automation

- tracing/Cargo.toml
This bumps the dependency on `humantime` to the latest 
minor version.
> tracing: bump deps

- tracing/README.md
- tracing/src/lib.rs
This branch cleans up the `tracing` readme, including fixing
links that incorrectly pointed to `tracing-core`, and adds a 
link to `tracing-timing` in related crates.
> tracing: readme cleanup

- .github/ISSUE_TEMPLATE/bug_report.md
- .github/ISSUE_TEMPLATE/feature_request.md
- .github/PULL_REQUEST_TEMPLATE.md
- tracing-core/src/lib.rs
This branch removes all remaining references to the
non-existent `tracing-nursery` repository that weren't
removed in #142 and #141.
Closes #125
> chore: remove remaining references to tracing-nursery

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/src/lib.rs
This branch prepares tracing to release version 0.1.1, to get the fixes for log support out.
> prepare to release tracing 0.1.1

- tracing-log/Cargo.toml
- tracing-log/src/lib.rs
It would be nice if `Event`s created by `tracing-log` (which are derived from `log::Record`) include the additional metadata that `log` includes: target, module, file, and line information. This can be used by subscribers to print this metadata to make the events look more like tracing events. 
In fact, the static `Callsite` in `tracing-log` includes those as fields, so I hoped this was the intended behaviour.
This follows the same patterns as existed for adding values to the `ValueSet` included with a dispatched event.
> tracing-log: Add `log` metadata values to the dispatched `Event`.

- tracing/src/span.rs
In some cases, users may or may not want to include a `Span` with
something like a request. For example, if users want to trace only a
certain subset of the requests. To do that, it is currently necessary to
keep an `Option<Span>` along with some code like:
```rust
let _guard = self.span.map(Span::enter);
```
This works okay, but it'd be nicer if there existed a sort of "void"
`Span` that was free to produce, and that did nothing when entered.
Ideally, the constructor would not require `Metadata` for it, since it
shouldn't ever be used.
This branch adds a `Span::none()` constructor, which returns a totally
disabled span, without requiring a `Metadata` reference. Unlike
`new_disabled`, this span will *not* log, even if the log-support
feature flag is enabled. It is not constructed by the …
> tracing: add `Span::none()` constructor

- tracing/src/macros.rs
- tracing/tests/macro_imports.rs
1a02731ab09a0c568dd0aa67d6f7186911ea2fcc broke imports of `tracing`'s
span macros prefixed with the crate name, as in 
```rust
tracing::span!(...);
```
This is due to some cases where those macros invoked macros in `tracing`
without the `$crate::` prefix.
This branch adds the missing `$crate::`. I've added a test to ensure
that prefixed imports compile, in order to guard against any future
regressions.
Closes #151
> tracing: fix prefixed macro imports not working

- tracing-core/src/span.rs
This fixes a typo in the `tracing-core` rustdoc. Thanks @jonhoo.
> core: add missing "and"

- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/lib.rs
This branch prepares `tracing-core` to release v0.1.1, and makes a few
minor README and crates.io metadata improvements.
Changelog:
- `Subscriber::current_span` API to return the current span (#148).
- `span::Current` type, representing the `Subscriber`'s view of the current
span (#148).
- Typos and broken links in documentation (#123, #124, #128, #154)
> core: prepare for 0.1.1

- tracing-serde/Cargo.toml
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- `Span::none()` constructor, which does not require metadata and
returns a completely empty span (#147).
- `Span::current()` function, returning the current span if it is
known to the subscriber (#148).
- Broken macro imports when used prefixed with `tracing::` (#152).
> tracing: prepare to release 0.1.2

- tracing-fmt/src/lib.rs
- tracing-fmt/src/span.rs
The `Subscriber::current_span` method was added in `tracing-core` 0.1.1.
Subscribers which track the current span should provide implementations
of this macro, to allow the use of `Span::current` by instrumentation.
This branch adds an implementation of `Subscriber::current_span` to the
`FmtSubscriber` type in `tracing::fmt`.
> fmt: add support for `Subscriber::current_span`

- tracing/src/macros.rs
- tracing/tests/macros.rs
The tracing event macros currently don't compile when invoked with a
single local variable, if there is no trailing comma. The macros fall
back to the format_args cases instead when a single local var name
appears.
This branch fixes this issue by adding new macro arms, and additional
compile tests for this case.
Fixes #165
> tracing: fix event macros with single local variables

- tracing-core/src/dispatcher.rs
- tracing-core/src/subscriber.rs
As discussed in #136, a proposed `Layer` trait for composing
subscribers required should probably _not_ be responsible for
managing ref-counts and determining span closures. Instead, the root
subscriber should be responsible for this, and `Layer`s should be able
to opt into a callback that's notified _when_ a span is closed. 
Adding a callback that's called on closure to `Layer` requires modifying
the `Subscriber` trait to allow indicating when a span closes.
This branch attempts to do this without a breaking change, by adding a new
`try_close` trait method to `Subscriber`. `try_close` is identical to
`drop_span` except that it returns a boolean value, set to `true` if the
span has closed. 
The `try_close` default implementation simply returns `false`, so that
if subscribers don't care …
> core: add `Subscriber::try_close`

- tracing-env-logger/Cargo.toml
- tracing-fmt/Cargo.toml
- tracing-futures/Cargo.toml
- tracing-log/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/layer.rs
- tracing-tower-http/Cargo.toml
- tracing-tower/Cargo.toml
- tracing/Cargo.toml
As I mentioned in https://github.com/tokio-rs/tracing/pull/136#discussion_r300158248, the
`Layer` trait proposed in #136 should probably _not_ be responsible for
managing ref-counts and determining span closures. Instead, the root
subscriber should be responsible for this, and `Layer`s should be able
to opt into a callback that's notified _when_ a span is closed. 
Adding a callback that's called on closure to `Layer` requires modifying
the `Subscriber` trait to allow indicating when a span closes. This
branch attempts to do this without a breaking change, by adding a new
`try_close` trait method to `Subscriber`. `try_close` is identical to
`drop_span` except that it returns a boolean value, set to `true` if the
span has closed. 
The `try_close` default implementation simply returns …
> [RFC] subscriber: remove ref-counting from Layer

- tracing-core/src/span.rs
This commit adds implementations of `Into<Option<Id>>`,
`Into<Option<&'a Id>>`, and `Into<Option<&'static Metadata<'static>>>`.
These should make using `span::Current` with functions like
`Span::record_follows_from` in `tracing` more fluid.
> core: add `Into` impls for `span::Current`

- tracing-core/src/dispatcher.rs
- tracing-core/src/subscriber.rs
As discussed in [PR 149], we determined that the `Subscriber::drop_span`
method should be deprecated in favour of `try_close`. This commit
deprecates it.
[PR 149]: https://github.com/tokio-rs/tracing/pull/149#discussion_r300802298
> core: deprecate `drop_span`

- tracing-core/src/dispatcher.rs
The `tracing-core::dispatcher` module is currently somewhat
under-documented, which has caused confusion for many users. There
should be a detailed description of how traces are dispatched, and the
different methods of setting a default subscriber. In addition, the
`tokio` feature flag that enables automatic dispatcher propagation is
undocumented, which has also caused issues (see  #169).
This branch adds new module-level docs to the `dispatcher` module,
including examples of how default subscribers are set. It also corrects
a factual error in the documentation for `with_default`.
> core: update dispatcher documentation

- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/lib.rs
- `Subscriber::drop_span` in favor of new `Subscriber::try_close` (#168)
- `Into<Option<&Id>>`, `Into<Option<Id>>`, and
`Into<Option<&'static Metadata<'static>>>` impls for `span::Current` (#170)
- `Subscriber::try_close` method (#153)
- Improved documentation for `dispatcher` (#171)
> core: prepare to release 0.1.2

- .travis.yml
Recent CI builds have failed on nightly due to a compiler bug:
https://github.com/tokio-rs/tracing/pull/174#issuecomment-51058427
In general, nightly Rust is unstable, and it may often fail for reasons
that are not our fault. We shouldn't block merging branches on nightly
failures, when they are often spurious or unrelated to `tracing`. It is,
however, still good to look at these builds when possible.
This branch allows failures on `nightly` CI builds. 
This means that the readme-doctest build is also allowed to fail, which
is a shame. It would be good to find a solution for testing readme
examples that doesn't require `nightly` Rust. I have some ideas for this
that I'll try to address in a subsequent branch.
> chore: allow nightly build to fail

- tracing-fmt/Cargo.toml
- tracing-fmt/src/lib.rs
- tracing-fmt/src/span.rs
- tracing-futures/Cargo.toml
- tracing-log/Cargo.toml
- tracing-log/src/lib.rs
- tracing-serde/Cargo.toml
- tracing/Cargo.toml
- tracing/examples/sloggish/sloggish_subscriber.rs
- tracing/src/span.rs
- tracing/tests/support/subscriber.rs
`tracing-core` 0.1.2 deprecated the `Subscriber::drop_span` function in
favour of `try_close`.
This branch updates all other crates to depend on core 0.1.2, and
replaces uses of `drop_span` with `try_close`.
> chore: update everything to use `try_close`

- tracing-fmt/src/default.rs
- tracing-fmt/src/lib.rs
This adds a `with_ansi` builder argument that can be used to enable and disable ansi dynamically without having to recompile with a different feature flag. There is a bit of duplicated code but I think for the moment it is fine since I suspect this file will get a rewrite at some point. @hawkw if you'd like me to reduce that I can.
Signed-off-by: Lucio Franco <luciofranco14@gmail.com>
> fmt: Add `with_ansi` builder flag

- tracing/src/span.rs
- tracing/test-log-support/src/lib.rs
- tracing/test-log-support/tests/log_with_trace.rs
The `log` compatibility feature in the `tracing` logs when spans are
entered or exited, but does not track the full span lifecycle. This is
largely because there was not previously any way for the `tracing` crate
to be made aware of span closes.
#153 added the `try_close` method to `Subscriber`, allowing subscribers
to communicate when spans are closed. This commit changes the `log`
compatibility feature in `tracing` to log when spans are closed, if a
subscriber is active and informs it of span closures.
I've also added tests for this.
> tracing: when log support is enabled, log closes

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/src/lib.rs
- Log messages when a subscriber indicates that a span has closed, when the
`log` feature flag is enabled (#180).
- `tracing-core` minimum dependency version to 0.1.2 (#174).
- Fixed an issue where event macro invocations with a single field, using local
variable shorthand, would recur infinitely (#166).
- Fixed uses of deprecated `tracing-core` APIs (#174).
> tracing: prepare to release 0.1.3

- tracing-serde/Cargo.toml
- tracing-slog/Cargo.toml
Now that `tracing` 0.1.3 is released, this branch removes path 
dependencies on `tracing` from other crates in the repo.
> chore: un-path-dep tracing

- tracing-futures/examples/proxy_server.rs
- tracing-futures/examples/spawny-thing.rs
The tracing-futures examples either need the tokio `experimental-tracing` flag set, or to use a global default subscriber.
Use `set_global_default` in the examples, which is the simplest and probably the clearest for people getting started.
> futures: Change examples to use `set_global_default`.

- tracing-env-logger/examples/hyper-echo.rs
- tracing-tower-http/examples/tower-h2-server.rs
Same as in #183, extended to the other examples. When using tokio, need to either use global subscriber, or `experimental-tracing` tokio feature.
Use `set_global_default` in examples.
Might be a common mistake people make. Perhaps document this behaviour and reference in the examples somewhere.
> Update other examples to use `set_global_default`.

- tracing-log/src/lib.rs
The metadata produced for logs by `as_trace` (used for filtering), when using `tracing-log`, have inverted file and module path fields:
```
Metadata { name: "log record", target: "tokio_reactor", level: Level(Trace),
module_path: "/.../.cargo/registry/src/github.com-.../tokio-reactor-0.1.9/src/lib.rs",
location: tokio_reactor:390, [...] }
```
It is fixed by passing them in the right order in the `Metadata` constructor.
> log: Fix inverted module_path and file in AsTrace implementation

- .travis.yml
- tracing-futures/Cargo.toml
- tracing-futures/src/executor.rs
- tracing-futures/src/lib.rs
- tracing-futures/test_std_future/Cargo.toml
- tracing-futures/test_std_future/tests/test.rs
This PR adds a `std::future::Future` implementation to `Instrumented<T>`~~, but with some caveats:~~
~~- To support `async` functions, the inner future must be boxed.~~
~~- If someone can figure out how to support `!Unpin` futures without boxing, please do so.~~ Thanks hawkw!
> futures: add support for std::futures::Future

- tracing-core/src/metadata.rs
Provide a way to get a clean display of a `Level`. It uses the same strings as displayed in fmt.
> core: add a Display implementation for Level

- tracing-log/src/lib.rs
As we started discussing in #197, setting up level filter for log is a bit complicated, and currently has to be done twice (not counting optional filtering in subscriber):
* Once in `log` with `log::set_max_level`
* Once in `tracing_log` with `LogTracer::with_filter`
Both use `log::LevelFilter` and have exactly the same behavior (but a different default level).
This PR removes the filter in `LogTracer`, and adds a function to allow easily setting up a logger and a filter directly from `tracing_log`.
The equivalent in the `env_logger` crate are:
```rust
pub fn try_init() -> Result<(), SetLoggerError> {
try_init_from_env(Env::default())
}
pub fn init() {
try_init().expect("env_logger::init should not be called after logger initialized");
}
```
We may want to stay close as it is a well known …
> log: Remove filter in LogTracer

- tracing-fmt/src/filter/env.rs
- tracing-fmt/src/format.rs
- tracing-fmt/src/lib.rs
This PR renames the `default` module to `format` because `default` seems not descriptive enough (and actually contains formatting tools!). Although `default::Format` might make sense, `
default::Full` or  `default::Compact` could probably be more suited in `format::`.
> fmt: Rename default module to format

- .travis.yml
- azure-pipelines.yml
- tracing/Cargo.toml
- tracing/src/lib.rs
- tracing/src/readme_doctest.rs
You'll have to follow the instructions over at https://github.com/crate-ci/azure-pipelines to get it fully set up.  Might also run into some weirdness with having to change the "default" branch once merged. But :tada:
Oh, yeah, and need to also update Cargo.toml, README badge, etc.
> First draft of Azure Pipelines CI config

- azure-pipelines.yml
Brings back `cargo check` as discussed here: https://github.com/tokio-rs/tracing/pull/191#issuecomment-513897819 now that https://github.com/crate-ci/azure-pipelines/pull/42 has landed.
> Re-enable cargo checks

- tracing-fmt/src/format.rs
- tracing-fmt/src/lib.rs
Is suggested in https://github.com/tokio-rs/tracing/pull/205#issuecomment-513894970, `FormatEvent` fits better in the `format` module.
> fmt: Move FormatEvent into format module

- tracing-tower/src/service_span.rs
The `MakeService` type in `tracing_tower::service_span` was 
missing a `Clone` implementation.
This PR adds the missing `Clone` impl.
> tower: impl Clone for service_span::MakeService

- README.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-env-logger/Cargo.toml
- tracing-fmt/Cargo.toml
- tracing-fmt/README.md
- tracing-futures/Cargo.toml
- tracing-log/Cargo.toml
- tracing-macros/Cargo.toml
- tracing-proc-macros/Cargo.toml
- tracing-serde/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-tower-http/Cargo.toml
- tracing-tower/Cargo.toml
- tracing/Cargo.toml
- tracing/README.md
This branch makes a few small README and Cargo.toml changes:
* Add Azure Pipelines build status badges to Cargo.tomls
* Change README build status badges to Azure Pipelines
* Add "maintenance: experimental" badges to unreleased crates
* Link to `tracing` docs and crates.io page in the root README, 
rather than `tracing-core`.
> meta: README and badges tweaks

- tracing-log/Cargo.toml
Fix for #216 
Adds the `log/std` feature.
Side note: how did the CI pass previously? This doesn't even compile on my machine?
> log: Add `std` feature.

- tracing/src/lib.rs
- Remove hanging phrase
- Fix typo of `intended`
> docs: Minor documentation fixes

- tracing-fmt/src/format.rs
- tracing-fmt/src/lib.rs
Being able to skip target in log messages sometimes make sense, this PR makes the default formats able to skip it.
Adding an boolean option on the formats and the subscriber builder.
A few questions left:
* What could be the rationale to chose between an option on default formats or a dedicated format for log content? Displaying the target or not is about log content and precision, so it feels closer to _Full vs. Compact_ than for example to the ansi option. We obviously don't want a dedicated format for each option combination, so for now adding options seems better, but it feels a bit inconsistent.
* Current code may display an isolated " :  " between level and log if span context is empty and target is empty or disabled. It doesn't look good but we also probably want log format to be …
> fmt: Support disabling the target in formatted output

- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
There's been demand for a crates.io release of the `tracing-subscriber`
crate, particularly so that the `Layer` type (which is relatively
stable) may be used in other crates.
This branch prepares `tracing-subscriber` to release an alpha. I've
updated the documentation and Cargo.toml, and added a README.
> subscriber: prepare to release v0.0.1-alpha.1

- tracing-futures/Cargo.toml
- tracing-futures/README.md
- tracing-futures/src/lib.rs
This branch adds rudimentary documentation to the `tracing-futures`
crate.
The docs could probably stand to be made more detailed, but I think this
should at least be sufficient to release an alpha version.
> futures: add docs

- tracing-futures/Cargo.toml
- tracing-futures/README.md
This commit prepares `tracing-futures` for an alpha crates.io release.
> futures: prepare to release alpha.1

- tracing-fmt/Cargo.toml
- tracing-fmt/src/format.rs
- tracing-fmt/src/lib.rs
- tracing-log/Cargo.toml
- tracing-log/src/lib.rs
- tracing-log/tests/log_tracer.rs
Start implementing changes discussed in #185.
> fmt: support `tracing-log` `log.XXX` fields nicely

- tracing-fmt/Cargo.toml
- tracing-fmt/src/format.rs
- tracing-fmt/src/lib.rs
- tracing-log/Cargo.toml
- tracing-log/src/lib.rs
- tracing-log/tests/log_tracer.rs
These changes were merged in PR #193, but I accidentally undid the commit that merged that PR to master by doing a force push (i'm a fool). This re-merges them.
That PR was already approved.
>  fmt: support `tracing-log` `log.XXX` fields nicely (#193) 

- tracing-log/src/lib.rs
since trait objects without an explicit 'dyn' are deprecated hence I added it before `fmt::Debug`
> Use 'dyn' since trait objects without an explicit 'dyn' are deprecated

- tracing-fmt/src/format.rs
Implements the quick fix explained in #247
> fmt: ignore `log.*` fields when formatting events

- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/callsite.rs
- tracing-core/src/dispatcher.rs
- tracing-core/src/event.rs
- tracing-core/src/field.rs
- tracing-core/src/lib.rs
- tracing-core/src/metadata.rs
- tracing-core/src/subscriber.rs
- tracing-core/tests/macros.rs
A new release of `tracing` is planned to add the `#[instrument]` attribute. Since there have been a couple additions to `tracing-core` since the last release, I've prepared a new version of `tracing-core` as well.
I've also run `cargo fix --edition` on `tracing-core` pre-release.
- `std::fmt::Display` implementation for `Level` (#194)
- `std::str::FromStr` implementation for `Level` (#195)
>  core: prepare to release 0.1.3 

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/benches/subscriber.rs
- tracing/examples/counters.rs
- tracing/examples/sloggish/sloggish_subscriber.rs
- tracing/src/field.rs
- tracing/src/lib.rs
- tracing/src/span.rs
- tracing/tests/subscriber.rs
- tracing/tests/support/event.rs
- tracing/tests/support/field.rs
- tracing/tests/support/metadata.rs
- tracing/tests/support/mod.rs
- tracing/tests/support/span.rs
- tracing/tests/support/subscriber.rs
This branch prepares to release 0.1.4 of `tracing`, and includes an edition idioms fix & docs updates. 
- `#[instrument]` attribute for automatically adding spans to functions (#253)
> tracing: prepare to release 0.1.4

- azure-pipelines.yml
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/callsite.rs
- tracing-core/src/dispatcher.rs
- tracing-core/src/field.rs
- tracing-core/src/lib.rs
- tracing-core/src/metadata.rs
- tracing-core/src/span.rs
- tracing-core/src/std.rs
- tracing-core/src/stdlib.rs
- tracing-core/src/subscriber.rs
- tracing-core/tests/macros.rs
Users have expressed interest in using `tracing` on no_std platforms
with `liballoc`.
This branch adds `no_std` support to `tracing-core` by adding a `std`
feature flag (on by default) which can be disabled to use `libcore` +
`liballoc` instead of `libstd`.
When the `std` feature is disabled, `tracing-core` will use
`spin::Mutex` rather than `std::sync::Mutex`, and the thread-local
scoped dispatcher will be disabled (since it necessitates a defined OS
threading model, which may not exist on `no_std` platforms).
Refs: #213
> core: support `no-std` + `alloc`

- tracing-core/src/dispatcher.rs
- tracing-core/src/lib.rs
- tracing-core/src/subscriber.rs
This branch makes some minor tweaks to the `tracing-core` RustDoc,
including fixing some broken links, and using `#[doc(inline)]` on some
of the more important re-exports so they're highlighted front and centre
in the docs.
> core: minor doc fixes

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/instrument.rs
Want to be able to use the amazing `#[instrument]` attribute on functions which have generics/bounds.
Add these to the proc macro.
> Add generics to instrumented methods.

- tracing-attributes/test_async_await/Cargo.toml
- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/lib.rs
Changes:
- Support for `no-std` + `liballoc` (#256)
- Broken links in RustDoc (#259)
> core: prepare to release 0.1.4

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/src/lib.rs
- Using the `#[instrument]` attribute on `async fn`s no longer requires a
feature flag (#258)
- The `#[instrument]` macro now works on generic functions (#262)
> attributes: prepare to release 0.1.1

- azure-pipelines.yml
- tracing-attributes/Cargo.toml
- tracing/Cargo.toml
- tracing/examples/counters.rs
- tracing/examples/sloggish/main.rs
- tracing/src/level_filters.rs
- tracing/src/lib.rs
- tracing/src/macros.rs
- tracing/src/span.rs
- tracing/src/stdlib.rs
- tracing/src/subscriber.rs
- tracing/tests/event.rs
- tracing/tests/filter_caching_is_lexically_scoped.rs
- tracing/tests/filters_are_not_reevaluated_for_the_same_span.rs
- tracing/tests/filters_are_reevaluated_for_different_call_sites.rs
- tracing/tests/span.rs
- tracing/tests/subscriber.rs
Users have expressed interest in using `tracing` on no_std platforms
with `liballoc`. Now that `tracing-core` supports no_std (see #256), 
we can now add no_std support to `tracing` as well.
This branch adds `no_std` support to `tracing` by adding a `std`
feature flag (on by default) which can be disabled to use `libcore` +
`liballoc` instead of `libstd`.
When the `std` feature is disabled, `tracing-core` will use
`spin::Once` rather than `std::sync::Once`, and the thread-local
scoped dispatcher will be disabled (since it necessitates a defined OS
threading model, which may not exist on `no_std` platforms).
Some tests, which rely on the thread-local dispatcher, are disabled when
the standard lib is disabled. The alternative is to use
`set_global_default` in those tests, which would …
> tracing: support `no-std` + `alloc`

- tracing/Cargo.toml
- tracing/src/lib.rs
This branch bumps `tracing`'s `tracing-attributes` dependency so that
the `async-await` feature flag is no longer required.
> tracing: don't require feature flag for async fn

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- Support for `no-std` + `liballoc` (#263)
- Using the `#[instrument]` attribute on `async fn`s no longer requires a
feature flag (#258)
- The `#[instrument]` macro now works on generic functions (#262)
> tracing: prepare to release 0.1.5

- tracing-log/Cargo.toml
- tracing-log/README.md
- tracing-log/src/lib.rs
- tracing-log/src/trace_logger.rs
- tracing-log/tests/log_tracer.rs
This PR prepares the `tracing-log` crate to publish an alpha release to
crates.io. 
I realised this was necessary as I wanted to publish a new alpha of
`tracing-fmt`, and that crate now depends on `tracing-log`.
I've also done some cleanup & added some documentation. 
> log: prepare to release tracing-log 0.0.1-alpha.1

- .github/labeler.yml
- .github/workflows/label.yml
The `tokio` org is now part of the github actions beta.
This branch dips our feet in the metaphorical water by
setting up a simple action that adds crate labels to PRs.
>  chore: add PR labeler action 

- tracing-fmt/Cargo.toml
- tracing-fmt/README.md
- tracing-fmt/examples/yak_shave.rs
- tracing-fmt/src/filter/env.rs
- tracing-fmt/src/filter/mod.rs
- tracing-fmt/src/filter/reload.rs
- tracing-fmt/src/format.rs
- tracing-fmt/src/lib.rs
- tracing-fmt/src/span.rs
- tracing-fmt/src/time.rs
This PR prepares a new alpha of `tracing-fmt` with the improved
support for log events added in PR #249.
I've also tried to add some more rudimentary docs & done some
minor cleanup like fixing Rust 2018 edition idioms.
> fmt: prepare to release tracing-fmt 0.0.1-alpha.3

- nightly-examples/examples/async_fn.rs
- tracing-attributes/examples/args.rs
- tracing-attributes/examples/basic.rs
- tracing-env-logger/Cargo.toml
- tracing-env-logger/examples/hyper-echo.rs
- tracing-env-logger/src/lib.rs
- tracing-fmt/examples/yak_shave.rs
- tracing-futures/examples/proxy_server.rs
- tracing-futures/examples/spawny-thing.rs
- tracing-macros/examples/factorial.rs
- tracing-serde/examples/serde_shaved_yak.rs
- tracing-subscriber/examples/filter_yakshave.rs
- tracing-tower-http/examples/tower-h2-server.rs
- tracing-tower/examples/h2-client.rs
- tracing-tower/examples/h2-server.rs
- tracing-tower/examples/load.rs
- tracing/examples/counters.rs
- tracing/examples/sloggish/main.rs
- tracing/examples/sloggish/sloggish_subscriber.rs
`tracing` is built with Rust's 2018 edition, but some examples use
outdated idioms. Ideally, examples would show code using the currently
preferred idioms. This improves clarity, especially for newer Rust
programmers who may not be familiar with the idioms of earlier editions.
This branch updates all the examples to use Rust 2018 edition idioms,
and adds `deny` attributes to prevent the use of outdated idioms.
> examples: update to use Rust 2018 idioms

- nightly-examples/Cargo.toml
- tracing-attributes/Cargo.toml
- tracing-env-logger/Cargo.toml
- tracing-env-logger/examples/hyper-echo.rs
- tracing-env-logger/src/lib.rs
- tracing-fmt/examples/yak_shave.rs
- tracing-fmt/src/filter/env.rs
- tracing-fmt/src/filter/reload.rs
- tracing-futures/Cargo.toml
- tracing-futures/examples/proxy_server.rs
- tracing-futures/examples/spawny-thing.rs
- tracing-serde/examples/serde_shaved_yak.rs
- tracing-subscriber/Cargo.toml
- tracing-subscriber/examples/filter_yakshave.rs
- tracing-tower-http/Cargo.toml
- tracing-tower-http/examples/tower-h2-server.rs
- tracing-tower/Cargo.toml
- tracing-tower/src/request_span.rs
- tracing/examples/sloggish/main.rs
Some Tracing examples, especially in unstable crates, were written
against earlier versions of `tracing`. They don't always demonstrate
the most idiomatic use of Tracing APIs.
This updates the examples to use newer Tracing APIs and syntax. Now, the
examples will demonstrate the preferred idioms.
> examples: make use of tracing APIs more idiomatic

- .github/workflows/publish_pages.yml
Currently, we link to RustDoc on docs.rs. This is built when a crate is
published to crates.io. In some cases, it is also valuable to publish
the documentation for the latest `master` branch, so that users using
git dependencies can see up to date docs.
This branch adds a GitHub action that will build docs & publish them to
the `gh-pages` branch when source files change.
Closes: #210
> meta: add pages publish action on master commits

- tracing/src/lib.rs
- tracing/src/macros.rs
This commit makes some minor changes to RustDoc examples
in `tracing`. In particular, I've removed the use of `extern crate`
and replaced it with Rust 2018 style macro imports.
> tracing: update some RustDoc examples to newer idioms

- tracing-core/src/field.rs
Currently, errors are typically recorded using their `fmt::Display` or
`fmt::Debug` implementations. This doesn't give the subscriber much
control over how the error is recorded --- in particular, it cannot
decide whether to format the error using `Display` or `Debug`, and it
cannot access the error's `source` or downcast it to another error type.
The `std::error::Error` type is implemented by a majority of errors in
both the standard library and in most crates, so its use is fairly
widespread.
This commit adds `dyn std::error::Error + 'static` as a new primitive
type. The `'static` bound is included so that the error can be downcast.
Closes: #222
> core: add `std::error::Error` as a new primitive type

- tracing-log/src/lib.rs
The upgrade from Rust 1.36.0 to Rust 1.37.0 introduced a regression in
`tracing-log` on macOS, where callsite identifiers for generated `log`
callsites that were previously considered equal are no longer equal.
Previously, the generated callsite was represented as a zero-sized
struct with no fields:
```rust
struct Callsite;
```
The metadata for the generated callsite was constructed by invoking the
`identifiy_callsite!` macro with `&Callsite`, like this:
```rust
field::FieldSet::new(FIELD_NAMES, identify_callsite!(&Callsite)),
```
and the block generated by the macro ended with `&Callsite`, which would
be assigned to a static.
Previously, this resulted with the callsite identifier and the static
being pointers to the _same_ address, and everything worked correctly.
However, the compiler …
> log: fix log callsites sometimes now having stable addresses

- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/lib.rs
Added:
- `std::error::Error` as a new primitive `Value` type (#277)
- `Event::new` and `Event::new_child_of` to manually construct `Event`s (#281)
> core: prepare to release 0.1.5

- tracing/README.md
- tracing/examples/counters.rs
- tracing/examples/sloggish/main.rs
- tracing/src/lib.rs
- tracing/src/macros.rs
- tracing/tests/event.rs
- tracing/tests/macros.rs
Currently, the `tracing` macros require curly braces as delimiters when
a `format_args` macro is used in addition to structured fields, like:
```rust
info!({ field1 = value1, field2 = value2 }, "unstructured message");
```
This is confusing, since the delimiters are not used in other cases; it
makes the syntax more complex; and, most importantly, I think it looks
kind of ugly. 
I've been planning to get rid of this when we transition to procedural
macros, but the transition is currently blocked on a compiler bug,
rust-lang/rust#62325.
(see https://github.com/tokio-rs/tracing/issues/133#issuecomment-517486474)
I've been getting tired of waiting for this.
This branch updates the `tracing` crate's macros to support a
format_args message after the structured key-value fields without curly …
> tracing: don't require delimiters for format_args

- tracing-attributes/Cargo.toml
- tracing-attributes/src/lib.rs
- update `quote`, `syn`, and `proc-macro2` all to version 1
- react to breaking changes in `syn`
`tokio` 0.2 introduced a `tokio-macros` crate that uses macro-related dependencies similar to `tracing-attributes`. Recently, [those dependencies were updated], incorporating breaking changes from those dependencies. This means that users of `tokio` 0.2 and `tracing-attributes` will have duplicate dependencies.
Update `proc-macro2`, `syn`, and `quote` to version 1, and react to the breaking changes (mostly in `syn`).
Note that this is currently a naive, compiler-error-driven refactoring of `tracing-attributes`. Everything appears to be working, but I'm not sure if there's a better (e.g. more performant) way to use the new dependencies. Additionally, I noticed that `tokio-macros` dropped having …
> attributes: update dependencies

- tracing-fmt/Cargo.toml
- tracing-fmt/examples/yak_shave.rs
- tracing-fmt/src/format.rs
- tracing/Cargo.toml
This branch updates `tracing-core` and `tracing-fmt` to use the suppport for `std::error::Error` added in #277.
I'd like to update the examples in other crates as well, but I'm holding off on that until after the next `tracing` release, to avoid adding path deps in unpublished crates.
> tracing, fmt: update to use core std::error::Error support

- tracing-attributes/Cargo.toml
- tracing-attributes/src/lib.rs
As discussed in #292:
> A follow-up to remove an explicit dependency on `proc-macro2` would be great, though, as it would make it easier to avoid pulling duplicate versions of that crate.
Remove `proc-macro2` as a direct dependency and replace usages of types from it accordingly.
> attributes: remove direct dependency on proc-macro2

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
Changed:
- Updated `syn` and `quote` dependencies to 1.0 (#292)
- Removed direct dependency on `proc-macro2` to avoid potential version
conflicts (#296)
Fixed:
- Outdated idioms in examples (#271, #273)
> attributes: prepare to release 0.1.2

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
Added:
- `std::error::Error` as a new primitive type (#277)
- Support for mixing key-value fields and `format_args` messages without
curly braces as delimiters (#288)
Changed:
- `tracing-core` dependency to 0.1.5 (#294)
- `tracing-attributes` dependency to 0.1.2 (#297)
> tracing: prepare to release 0.1.6

- nightly-examples/Cargo.toml
- nightly-examples/examples/async_fn.rs
- nightly-examples/examples/echo.rs
- nightly-examples/examples/proxy_server.rs
- nightly-examples/examples/spawny_thing.rs
Knocking off a couple of items from #269 by porting over the examples under `tracing-future`.
Ported over the example from Tokio's [`proxy_server`][proxy] example and updated it with trace information similar to what is currently present. In order to show case the example, I also added the [`echo` server][echo] example, as the server being proxied needs to be concurrent as well.
Finally I ported over the `spawny_thing` example to use async await.
[proxy]: https://github.com/tokio-rs/tokio/blob/master/tokio/examples/proxy.rs
[echo]: https://github.com/tokio-rs/tokio/blob/master/tokio/examples/proxy.rs
> Port examples from `tracing-futures` to use async await

- nightly-examples/examples/echo.rs
- nightly-examples/examples/proxy_server.rs
Apparently `TcpListener::bind` is async now.
This fixes CI.
> nightly-examples: track upstream

- README.md
There is now a handful of blog posts and conference talks about Tracing.
These external resources may be very helpful, especially for new users
or contributors learning how to use Tracing. However, they aren't
currently linked anywhere in this repository, so they can be hard to
discover.
This PR adds an "External Resources" section to README.md.
I also considered adding a new document (maybe RESOURCES.md or
something?), instead of putting them in the README, but I thought that
it was easier to find the references in the README. Since the section is
currently quite short, I'm not concerned about making the README too
long. If, in the future, there are a lot of talks & posts listed here,
we could consider moving the list to a separate document and linking to
it in the README.
Signed-off-by: …
> docs: add links to external resources

- azure-pipelines.yml
- tracing/src/macros.rs
#288 introduced a regression that causes infinite macro recursion when
the `log` feature is enabled. This PR fixes it (by making the macros 
significantly worse).
I've also added a new test step that runs with `--all-features`, since
apparently CI doesn't already do this.
Fixes #303
> tracing: fix macro log support

- tracing/src/macros.rs
The old syntax for macros with messages would put the message field
first, followed by all the other fields. The new (no curly braces)
syntax (added in #288) puts messages last, inconsistently with 
everything else. Since message field ordering currently matters for 
how some subscribers (e.g. `tracing-fmt`) display events, we should 
make this somewhat more consistent.
This branch changes the new macro syntax to put the `message` 
field first, rather than last.
> tracing: new syntax puts messages first

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
Changed:
- New (curly-brace free) event message syntax to place the message in
the first field rather than the last (#309)
Fixed:
- Fixed a regression causing macro stack exhaustion when the `log`
feature flag is enabled (#304)
> tracing: prepare to release 0.1.7

- tracing-subscriber/src/filter/directive.rs
- tracing-subscriber/src/filter/field.rs
- tracing-subscriber/src/filter/level.rs
- tracing-subscriber/src/filter/mod.rs
- tracing-subscriber/src/fmt/format.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/fmt/span.rs
- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/lib.rs
- tracing-subscriber/src/prelude.rs
- tracing-subscriber/src/reload.rs
- tracing-subscriber/src/thread.rs
- tracing-tower/examples/load.rs
In the near future, the `tracing-subscriber` crate should be ready for a
stable 0.1 release. Before we can do that, we should do some pre-release
polish, such as denying warnings, updating idioms, and adding missing
documentation.
This branch performs most of the necessary polish for
`tracing-subscriber`. Please note the following:
* The next release will not be version 0.1, as PR #241 would be a 
breaking change, and I'd like to land that first. We'll probably do
an alpha.4 first.
* I didn't add `deny(warnings)`, as that will also deny deprecation 
warnings, and I've had bad experiences with deprecations breaking
CI in the past. Instead, I've denied most other warnings explicitly.
The downside to this is a *very* long list of deny attributes.
* The docs added in this branch are pretty …
> subscriber: pre-0.1 polish pass

- tracing-env-logger/Cargo.toml
- tracing-log/Cargo.toml
- tracing-log/src/trace_logger.rs
- tracing-subscriber/Cargo.toml
Currently, the `tracing-log` crate uses the `CurrentSpan` utility in
`tracing-subscriber`. However, now that `tracing-fmt` has been moved
into `tracing-subscriber`, its `log` feature (which depends on
`tracing-log`) creates a cyclic dependency between these two crates.
This branch solves the cyclic dependency by removing the
`tracing-subscriber` dependency from `tracing-log`. Instead, the
current span is tracked manually.
> log: fix cyclic dependency

- tracing/src/lib.rs
- tracing/src/macros.rs
This branch updates and reorganizes the crate-level docs in `tracing`. In
particular, I've:
- moved the documentation on `span!` and `event!` macro syntax to a
single place that the macros link to, and made the differences 
between the span and event macros clearer.
- added more section headers to make linking into the docs easier
- fixed some typos, broken links, and markdown errors
- simplified the "Core Concepts" section a little
- made it clearer that the `tracing` crate does not provide 
subscriber impls
- added more documentation describing how to use the 
instrumentation APIs
- replaced the link to `tracing-fmt` with `tracing-subscriber`
> tracing: reorganize & clarify documentation

- examples/Cargo.toml
- tracing-env-logger/Cargo.toml
- tracing-log/CHANGELOG.md
- tracing-log/Cargo.toml
- tracing-log/README.md
- tracing-log/src/lib.rs
- tracing-log/src/log_tracer.rs
- tracing-log/src/trace_logger.rs
- tracing-subscriber/Cargo.toml
This branch prepares `tracing-log` for an 0.1 release.
Taking this crate out of alpha will allow us to publish
`tracing-subscriber` 0.1, as that crate depends on `tracing-log` & I
don't want to publish an 0.1 that depends on an alpha crate.
> log: prepare to release 0.1

- tracing-tower-http/Cargo.toml
- tracing-tower/Cargo.toml
These examples were moved in #316, but apparently I forgot to delete
the dev dependencies in some Cargo.tomls.
> chore: rm unused dev deps

- examples/Cargo.toml
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
Changed
- Reorganized and improved API documentation (#317)
Removed
- Dev-dependencies on `ansi_term` and `humantime` crates, which were
used only for examples (#316)
> tracing: prepare to release 0.1.8

- CONTRIBUTING.md
- README.md
- netlify.toml
- tracing-attributes/README.md
- tracing-core/README.md
- tracing-fmt/README.md
- tracing-futures/README.md
- tracing-log/README.md
- tracing-serde/README.md
- tracing-subscriber/README.md
- tracing/README.md
chore: build and publish documentation for each branch.
This commit introduces support for:
- building and deploying documentation for the master branch
- building and deploying (preview) documentation for each pull request and for each PR
- adds a link in `README.md` pointing to the generated documentation for the master branch
- notes the per-PR documentation previews in `CONTRIBUTING.md`
Closes #210
> chore: publish docs `tracing` for master + PR branches

- tracing-subscriber/src/filter/mod.rs
- tracing-subscriber/src/lib.rs
- tracing-subscriber/src/thread.rs
The `ThreadLocal` struct used by `CurrentSpan` currently can cause a
double panic, since it is unclear why the current thread's slot is
unset. The `try_get` function may return `None` because that thread has
not yet been created, _or_ it may return `None` because we are
panicking. However, the code that calls this function doesn't correctly
handle this --- it assumes `None` is returned because the thread has not
yet had its local slot created, and `expect`s that it will exist after
inserting the local slot.
I've updated this code to present a more `LocalKey`-like API, and avoid
potential double panics here. Now, when the thread is panicking, the
closure passed into `with` is not invoked.
> subscriber: avoid double panics in `CurrentSpan`

- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/lib.rs
Fixed:
- Potential double panic in `CurrentSpan` (#325)
> subscriber: prepare to release 0.1.1

- tracing-core/src/dispatcher.rs
- tracing-macros/Cargo.toml
- tracing/Cargo.toml
- tracing/benches/no_subscriber.rs
- tracing/benches/subscriber.rs
- tracing/src/lib.rs
- tracing/src/macros.rs
- tracing/src/span.rs
When `tracing` is not in use, no default subscriber will be set, and
tracing instrumentation points can be skipped. Currently, the
instrumentation macros detect this by testing if the callsite's
`Interest` is `never`. However, this is significantly slower than how
the `log` crate detects that there is no logger: we must call a function
through a trait object, do a relaxed load, construct an `Interest` from
an integer, and then test on the value of the `Interest`. Furthermore,
we must construct the callsite _at all_ in order to do this. Meanwhile, 
when no logger is set, `log` can skip log records with only a single 
relaxed atomic load.
This branch adds a new private-API method in `tracing_core::dispatcher`
that allows us to check if a dispatcher has ever been set. If this is
false, then …
> core, tracing: make disabled events way faster

- .github/workflows/CI.yml
The `tokio` org is in the Github actions beta. Running our CI jobs on Actions
rather than Azure Pipelines has a few potential advantages: 
- GitHub Actions allows us to conditionally run workflows based on what
files were modified. This lets us configure the Rust CI tests/checks
to only run when actual Rust source code was modified. This will let 
us merge PRs that change READMEs, CI configs, etc. but don't actually
modify any source code more quickly, since they won't have to wait
for all the tests to run.
- GitHub Actions has slightly nicer integration with the GitHub UI 
(IMO), and it takes fewer clicks to see the logs from a failed build
than on Azure.
- Finally, I've (anecdotally) observed GitHub Actions workflows to
start much sooner than the corresponding Azure Pipelines workflows. …
> chore: port CI to GitHub Actions

- tracing-subscriber/src/filter/directive.rs
- tracing-subscriber/src/filter/field.rs
- tracing-subscriber/src/filter/level.rs
- tracing-subscriber/src/filter/mod.rs
The `tracing-fmt::filter::EnvFilter` type implemented `fmt::Display`,
but `tracing-subscriber::filter::Filter` does not. A `fmt::Display` impl
for filters can be useful, in order to show users the currently active
filter (e.g. linkerd/linkerd2-proxy#342).
This branch adds a `fmt::Display` implementation to `Filter`.
Since the `matchers::Pattern` type used internally for pattern matching
does not implement `fmt::Display` nor expose the string from which the
pattern was constructed, it was necessary to add a new internal type
which holds both a `matchers::Pattern` and the string representation of
that pattern. This has the side benefit of fixing a _technically_
incorrect `cmp::PartialEq` implementation for `ValueMatch`, although
this was never a problem in practice.
I've also added a test …
> subscriber: add `fmt::Display` impl for `Filter`

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/names.rs
PR for the issue #298 
Add a new function to either parse the name from the macro's attribute or return the default name (instrumented method's name). Do you want to have the previous function's name as a field? In that case, that would require a bit of change (maybe return an option of something from `name`).
I added some tests, please tell me if you need more (in the nightly async/await test for example)
> attributes: support overriding name of the span

- .github/workflows/CI.yml
Apparently, the GitHub Actions `paths:` filtering for events uses [an
API][1] from the standard library of a known bad programming language,
which [doesn't behave the way normal unix globs do][2] and [cannot match
arbitrarily nested files][3].
This means that the filter was running the CI action only on PRs that
changed a `Cargo.toml` or `*.rs` _in the root of the repository_, rather
than _any_ `Cargo.toml` or `*.rs`, as a reasonable person might assume
it would. 
This branch removes path filtering from the CI workflow, since 
apparently it is *impossible* to get the relatively simple behavior we
would want using this thing.
Since almost all `tracing` pull requests touch a `*.rs` or `Cargo.toml`
anyway, this path filtering wasn't really getting us a whole lot.
Removing it shouldn't make a …
> chore: make CI filters less restrictive

- tracing-subscriber/src/filter/directive.rs
- tracing-subscriber/src/filter/mod.rs
Currently, the `tracing-subscriber::Filter` type can be constructed from
an environment variable or string containing filter directives. However,
once it has been constructed, new directives may not be added.
This commit adds an API for adding directives to a filter after it has
been constructed. Directives can be constructed either from
`LevelFilter`s or by parsing a string. Eventually, this API will also
allow us to add a programmatic builder API for directives.
This is a prerequisite for future work such as https://github.com/tokio-rs/tracing/issues/332#issuecomment-529138912
> subscriber: allow adding directives to filters

- tracing-subscriber/Cargo.toml
- tracing-subscriber/benches/filter.rs
- tracing-subscriber/src/filter/env/mod.rs
- tracing-subscriber/src/fmt/span.rs
- tracing-subscriber/src/lib.rs
- tracing-subscriber/src/reload.rs
- tracing-subscriber/src/sync.rs
- tracing-subscriber/src/thread.rs
The `tracing-subscriber` currently depends on both the `crossbeam-util`
crate (for its `ShardedLock` type) and the `parking_lot` crate for it's
`RwLock` implementation. The Rust standard library also provides a
`RwLock` implementation, so these external dependencies are not strictly
necessary. In the past, using these crates was anecdotally observed to
result in a performance improvement, but the tradeoff is adding
additonal crates (and their transitive dependencies) to the user's
dependency tree.
This branch removes the `crossbeam-util` dependency, and makes the
`parking_lot` dependency opt-in. The explicit use of
`parking_lot::RwLock` with a wrapper type that abstracts over the
`parking_lot::RwLock` and `std::sync::RwLock` types to provide a
matching API. This allows the `parking_lot` …
> subscriber: rm crossbeam-utils, make parking_lot opt-in

- tracing/Cargo.toml
- tracing/src/lib.rs
- tracing/src/macros.rs
- tracing/src/span.rs
- tracing/test-log-support/Cargo.toml
- tracing/test-log-support/tests/log_no_trace.rs
Currently, when `tracing`'s `log` feature is enabled, all spans and
events will emit `log` records as well as `tracing` events. When
`tracing-log` is being used to convert `log` records into `tracing`
events, this results in duplicate events being observed: those emitted
by the event macros directly, and those generated from the log records
they emit by `tracing-log`.
In `tracing-core` 0.1.6, we added an internal API for checking if a
`tracing` subscriber has ever been set. In addition to the performance
optimizations which this was initially intended to enable, this also
gives us a way for `tracing` macros in libraries to check if a
downstream application that depends on those libraries is actually using
`tracing`. If `tracing` is in use and a subscriber has been set, the
macros can be …
> tracing: don't emit log events if a subscriber has been set

- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- `EnvFilter` ignoring directives with targets that are the same number
of characters (#333)
- `EnvFilter` failing to properly apply filter directives to events
generated from `log` records by`tracing-log` (#344)
- Renamed `Filter` to `EnvFilter`, deprecated `Filter` (#339)
- Renamed "filter" feature flag to "env-filter", deprecated "filter" (#339)
- `FmtSubscriber` now defaults to enabling only the `INFO` level and
above when a max level filter or `EnvFilter` is not set (#336)
- `EnvFilter::add_directive` to add new directives to filters after they
are constructed (#334)
- `fmt::Builder::with_max_level` to set a global level filter for a
`FmtSubscriber` without requiring the use of `EnvFilter` (#336)
- `Layer` implementation for `LevelFilter` (#336)
- `EnvFilter` now implements …
> subscriber: prepare to release 0.1.2

- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- `Layered` subscribers not properly forwarding calls to `current_span` (#350)
> subscriber: prepare to release 0.1.3

- README.md
I viewed the amazing talk from Eliza Weisman on the RustConf 2019 on Youtube. Saw that it is missing in the list of Talks.
Add it ;)
> Add RustConf 2019 Talk to the README

- tracing/src/lib.rs
Fix typo on the docs index page in sector [shorthand macros](https://tracing-rs.netlify.com/tracing/#shorthand-macros) which prevents link rendering.
> Fix small format bug in tracing documentation

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/instrument.rs
This adds a `skip` directive to the `#[instrument]` macro that allows
specifying one or more arguments to the function which will not appear
in the generated span.  In particular, this means that it's possible to
use `#[instrument]` on functions with a non-`Debug` parameter.
The interior of a `skip(arg1, arg2)` argument is scanned for identifiers and these are filtered out of the identifier list used to generate the span.
This hopefully closes #11.
> Allow skipping arguments in `#[instrument]`.

- tracing-subscriber/src/fmt/span.rs
- tracing-subscriber/tests/duplicate_spans.rs
Entering twice in the same span causes the span to be lost after the second span got droped, see #358 
Duplicate spans are tracked in the `CONTEXT` thread local stack  and ignored when finding the current span id. Spans are always pushed on the `CONTEXT` stack. This way, when a span is dropped, its ref count reflects the content of the thread local
Fixes #358
> fmt: Track duplicate spans in fmt context

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
Added:
- Optional `skip` argument to `#[instrument]` for excluding function
parameters from generated spans (#359)
> attributes: prepare to release 0.1.4

- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
Fixed:
- Spans entered twice on the same thread sometimes being completely
exited when the more deeply-nested entry is exited (#361)
> subscriber: prepare to release 0.1.4

- README.md
- tracing-attributes/README.md
- tracing-core/README.md
- tracing-futures/README.md
- tracing-log/README.md
- tracing-subscriber/README.md
- tracing/README.md
Tokio is experimenting with Discord, and the Tokio discord server has
a Tracing channel. This PR adds Discord links to READMEs.
> chore: add discord links to READMEs

- tracing-subscriber/src/fmt/span.rs
The `tracing_subscriber` `FmtSubscriber` currently clones span IDs in
calls to `Subscriber::current_span`. However, this is incorrect --- IDs
should only be cloned when constructing an _entering span handle_; the
`tracing-core` `span::Current` type does not call `drop_span` on drop.
In `tracing`, `Span::current` already clones the ID returned by
`Subscriber::current_span`.
This means that any use of `Subscriber::current_span` or `Span::current`
with `FmtSubscriber` will result in the current span being "leaked" and
never dropped.
This commit removes the unnecessary `clone_span`.
Thanks to @twissel for reporting the bug!
> subscriber: fix duplicate clone_span in `FmtSubscriber`

- tracing-futures/Cargo.toml
- tracing-futures/src/lib.rs
This allows us to remove an unnecessary clone of the dispatcher or span
from poll impls. Also, it is commonly used in other crates (e.g.
`tokio`), so might make users' dependency graphs smaller.
> futures: replace `pin_utils` with `pin_project`

- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- Spans not being closed properly after calling
`FmtSubscriber::current_span` (#371)
> subscriber: prepare to release 0.1.5

- tracing-futures/src/lib.rs
`tracing-futures`
Previously, both traits expose a single method (Instrument::instrument and WithSubscriber::with_subscriber, respectively) which accepts the span or dispatcher to attach to the future.
This PR adds convenience methods to `Instrument` and `WithSubscriber` that instrument the future in the current span/dispatcher context. I'm expecting the method names to change and
would very much appreciate your input.
Fixes: #231
> futures: use current span and dispatcher context

- tracing-fmt/examples/custom_visitor.rs
- tracing-subscriber/src/field/debug.rs
- tracing-subscriber/src/field/delimited.rs
- tracing-subscriber/src/field/display.rs
- tracing-subscriber/src/field/mod.rs
- tracing-subscriber/src/fmt/format.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/fmt/span.rs
- tracing-subscriber/src/lib.rs
- tracing-subscriber/src/prelude.rs
The `tracing-fmt` crate crate currently uses a `NewVisitor` trait to
abstract over constructing field visitors of different types or with
different configurations:
https://github.com/tokio-rs/tracing/blob/d51d4d69d81ce2e4c6c7166fe70c58a1f881d668/tracing-fmt/src/lib.rs#L192-L196
There have been other use-cases where having this abstraction seems
valuable. For example, issue #73 is a proposal for adding utilities for
wrapping a visitor to skip a set of excluded field names. A `MakeVisitor`
abstraction would allow us to provide much more ergonomic APIs for
composing this kind of visitor behaviour.
Additionally, the current trait in `tracing-fmt` is tied pretty closely
to `tracing-fmt- specific behaviour. A generalized version of this trait
should be generic over the input type used to build …
> subscriber: add an abstraction for building visitors

- tracing-futures/src/lib.rs
Currently it is not possible to implement 3rd party traits for `Instrumented` because there is no way to access the `inner` type without consuming the `Instrumented` wrapper.
This adds `inner` and `inner_mut` methods to `Instrumented`
> futures: add Instrumented::{inner,inner_mut}

- tracing-subscriber/src/filter/env/mod.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/lib.rs
Configuring the `FmtSubscriber` with the `EnvFilter` and installing it globally is very verbose.
This adds `init` and `try_init` functions (modeled after `env_logger` [`init`](https://docs.rs/env_logger/0.7.0/env_logger/fn.init.html) and [`try_init`](https://docs.rs/env_logger/0.7.0/env_logger/fn.try_init.html)) to simplify setup for users that do not want to configure their own `Subscriber`.
Note, these functions are currently behind the `env-logger-compat` feature flag but enabled by default. We can remove the feature flag if you think this should always be included (note it does add the dependency on `tracing`).
> Add init and try_init functions

- azure-pipelines.yml
This updates our CI configs to use crate-ci/azure-pipelines#65, which fixes
the build failures on recent nightly Rust compilers.
Since there's some uncertainty over when and how that upstream PR will
be merged to master (see https://github.com/crate-ci/azure-pipelines/pull/65#issuecomment-543929460), I think
it's best to depend on the branch for now, until `crate-ci`'s master branch
no longer breaks our build.
This should fix all the nightly CI builds.
> chore: fix nightly CI

- tracing-core/src/field.rs
u8 had been forgotten from the list of automatically generated implementations for the Value Trait.
See bug report #389 
Added u8 to the list of automatically generated implementations for the Value Trait.
Fixes: #389
> core: Add u8 to the list of generated Value implementations

- tracing-core/CHANGELOG.md
- tracing-core/README.md
- tracing-core/src/lib.rs
- Added `dispatcher::set_default` API which returns a drop guard (#388)
- Added missing `Value` impl for `u8` (#392)
- Broken links in docs.
> core: prepare to release 0.1.7

- tracing-core/src/subscriber.rs
This fixes the `Subscriber::exit` doc comment where some copy-pasta from `Subscriber::enter` was evident.
> docs: minor fix to Subscriber::exit doc comment

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
Added:
- Support for destructuring in arguments to `#[instrument]`ed
functions (#397)
- Generated field for `self` parameters when `#[instrument]`ing
methods (#397)
> tracing-attributes: prepare to release 0.1.5

- tracing-log/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/fmt/mod.rs
https://github.com/tokio-rs/tracing/pull/385 incorrectly used the feature flag `tracing_log` when it should have been `tracing-log`. As a result, you need to specify both in order to make `try_init` initialize the global logger.
Use the correct feature flag
> subscriber: fix tracing-log feature flag for init + try_init

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
Added
- Support for destructuring in arguments to `#[instrument]`ed functions
(#397)
- Generated field for `self` parameters when `#[instrument]`ing methods
(#397)
- Optional `skip` argument to `#[instrument]` for excluding function
parametersfrom generated spans (#359)
- Added `dispatcher::set_default` and `subscriber::set_default` APIs,
which return a drop guard (#388)
Fixed
- Some minor documentation errors (#356, #370)
> tracing: prepare to release 0.1.10

- tracing-subscriber/src/filter/env/directive.rs
Setting `RUST_LOG=target` currently enables only the `ERROR` level, while it should enable everything.
Change the default to `TRACE` if no level is specified
> subscriber: fix default level for env filter

- tracing-attributes/Cargo.toml
- tracing-core/Cargo.toml
- tracing-futures/Cargo.toml
- tracing-log/Cargo.toml
- tracing-macros/Cargo.toml
- tracing-serde/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-tower/Cargo.toml
- tracing/Cargo.toml
These were set to the value that crates.io implicitly applies, except for those which had already fallen out of date, illustrating the maintenance hazard.
> Remove redundant documentation metadata

- examples/examples/serde-yak-shave.rs
- tracing-attributes/src/lib.rs
- tracing-core/src/lib.rs
- tracing-futures/src/lib.rs
- tracing-log/src/lib.rs
- tracing-serde/src/fields.rs
- tracing-serde/src/lib.rs
- tracing-subscriber/src/lib.rs
- tracing-tower/src/lib.rs
- tracing/src/lib.rs
Currently, most crates in `tracing` are configured to deny all compiler
warnings when compiling tests. This means that if the compiler reports
any warnings, the build will fail. This can be an issue when changes are
made locally that introduce warnings (i.e. unused code is added, imports
are no longer needed, etc) and a contributor wishes to test an
incomplete state to ensure their changes are on the right path. With
warnings denied, tests will not run if the project contains any
warnings, so contributors must either fix all warnings or disable the
deny attribute. Disabling the deny attribute when making changes locally
has become a fairly common practice, but it's error-prone: sometimes,
the deny attribute is commented out and then accidentally committed. 
This branch removes all …
> chore: rethink warnings

- README.md
I don't believe Gitter is used anymore; most of the `tracing` discussions happen on Discord.
> Update README.md to remove Gitter Links

- examples/examples/log.rs
- tracing-log/Cargo.toml
- tracing-log/src/log_tracer.rs
- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/fmt/mod.rs
:man_facepalming: 
I thought the boxing errors solution implemented in https://github.com/tokio-rs/tracing/pull/400 was equivalent to the enum solution in https://github.com/emschwartz/tracing/commit/f22bae5a2daa18e60c063db4afad67288e0d3bd7, but the current master doesn't actually work to install the global `LogTracer`.
I can't figure out why the current cargo features don't end up turning on [this line](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/fmt/mod.rs#L452-L453), but I confirmed with the log example in https://github.com/tokio-rs/tracing/commit/4511325b29ab074a604c0fc462bed2edc18efaee that it's not currently working.
Using an enum for the two types of errors instead of boxing them solves the problem.
> Fix global LogTracer installation by using InitError enum instead of Boxed errors 

- tracing-log/CHANGELOG.md
- tracing-log/README.md
- tracing-log/src/lib.rs
- tracing-log/src/trace_logger.rs
- `TraceLogger` (use `tracing`'s "log" and "log-always" feature flags instead)
- Issues with `log/std` feature flag (#406)
- Minor documentation issues (#405, #408)
> log: prepare to release 0.1.1

- tracing-futures/CHANGELOG.md
- tracing-futures/Cargo.toml
- tracing-futures/README.md
- tracing-futures/src/lib.rs
- `Instrumented::inner` and `inner_mut` methods that expose access to the
instrumented future (#386)
> futures: prepare to publish 0.1.1

- tracing-core/src/dispatcher.rs
This PR addresses the issue outlined in #172 
As outlined in #172 , we can improve the use of default dispatch by implementing `Default` to create `Dispatch::default`, thus ease the use of dispatch.
implementation of `Default` trait from standard library that calls `get_default` and produces a clone of default.
> Implemented Default trait for Dispatch in tracing-core

- tracing-subscriber/src/fmt/format/json.rs
JSON log lines are not correct JSON, the ending `}` is missing.
Ending the `SerializeMap` correctly.
> Add the closing } to the JSON logs

- tracing-subscriber/Cargo.toml
- tracing-subscriber/benches/fmt.rs
- tracing-subscriber/benches/support/mod.rs
These benchmarks were originally written for assessing before/after
performance on a branch that was not merged. However, they are probably
generally useful for other fmt subscriber changes (e.g. #420).
> subscriber: add benchmarks for fmt subscriber

- tracing/src/field.rs
There was a dead link to `Field` in the documentation of [AsField](https://docs.rs/tracing/0.1.10/tracing/field/trait.AsField.html). Probably some artifact refactoring.
> tracing: Fix link in `AsField` documentation

- tracing-subscriber/src/fmt/mod.rs
With #420, we introduced `FmtContext`, and made it a required parameter on `FormatEvent`'s primary methods. However, I forgot to export it, making it impossible to write custom `FormatEvent` implementations. This PR fixes that oversight. Thanks to @samscott89 for noticing this!
Signed-off-by: David Barsky <me@davidbarsky.com>
> subscriber: export `FmtContext`

- tracing-subscriber/src/fmt/fmt_layer.rs
`fmt::Layer::on_record` was looking up extensions using `FormattedFields<Self>>` when it _should_ have been using `FormattedFields<N>>`. While `on_record` _probably_ hasn't ever been called, this code code was still wrong.
> subscriber: Fix incorrect extensions lookup in `fmt::Layer::on_record`

- tracing-core/Cargo.toml
- tracing-core/src/lazy_static/LICENSE
- tracing-core/src/lazy_static/core_lazy.rs
- tracing-core/src/lazy_static/mod.rs
- tracing-core/src/lib.rs
- tracing-core/src/spin/LICENSE
- tracing-core/src/spin/mod.rs
- tracing-core/src/spin/mutex.rs
- tracing-core/src/spin/once.rs
- tracing-core/src/stdlib.rs
- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/registry/sharded.rs
- tracing/Cargo.toml
- tracing/src/lib.rs
This PR implements the second option ("The One With The `downcast_ref`") in @hawkw's [comment](https://github.com/tokio-rs/tracing/issues/429#issuecomment-554077428). The benchmarks of this change, relative to the master branch, are available [here](https://gist.github.com/davidbarsky/3620247e6cf74e77e1d5d4c24014c6d1). 
Edit: The same benchmarks running on a significantly less noisy c3.8xlarge: https://gist.github.com/davidbarsky/111814dcc55e89580e5ee283b9900bbf.
Resolves #429
> subscriber: For registry-backed layers, delay deletion of span until all layers have processed the event

- nightly-examples/Cargo.toml
This PR fixes nightly builds by opting to use `tokio = "0.2.0-alpha.6"` instead of taking a git dependency on Tokio.
> nightly-examples: fix nightly builds

- tracing-subscriber/Cargo.toml
- tracing-subscriber/benches/fmt.rs
- tracing-subscriber/src/filter/env/mod.rs
- tracing-subscriber/src/filter/mod.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/lib.rs
- tracing/benches/subscriber.rs
This PR removes the deprecated items, notices and aliases in preparation of releasing tracing-subscriber 0.2.0-alpha.1.
> subscriber: remove deprecated items and notices

- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/registry/sharded.rs
This branch fixes several bugs in the `Registry` span close logic, and
adds new tests for these issues.
* Spans not being removed at the end of `on_close`
There is currently a bug in the `Registry` that prevents spans from
being removed, even when all `on_close` callbacks are complete. The test
for this behavior ( `span_is_removed_from_registry`) fails to catch the
bug, since there is a bug in the test as well.
The test asserts that a span extension was dropped after the span
closes. Current, the test uses `subscriber::with_default`, and then
made the assertion _outside_ of the `with_default` block. However, this
was incorrect, as even if the `Registry` fails to drop the span, the
span extension will be dropped when the whole `Registry` itself is
dropped, at the end of the `with_default` …
> subscriber: fix spans never being removed from the registry

- examples/Cargo.toml
- nightly-examples/Cargo.toml
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
Note that this `tracing-subscriber` release will also need a release of `tracing-serde`.
> subscriber: prepare release 0.2.0-alpha.1 release

- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/layer.rs
This patch moves the current `FmtContext::visit_spans`
implementation into a new method `layer::Context::scope`, leaving
`visit_spans` itself in place in order to maintain compatibility.
Fixes #427
This is based on my interpretation of the requirements from the issue's descriptions - Happy to make any changes or suggestions!
> subscriber: Move visit_spans impl to layer::Context

- tracing-subscriber/src/layer.rs
What I wanted to achieve: lookup data from a span _outside_ of a `Layer`/`Subscriber` implementation. (i.e. without having a `Context<S>`)
What I was trying: get the configured subscriber with `dispatcher::get_default(...)`, and then downcasting to a `Layered<...., Registry>`. But I (a) cant get access to the inner `Registry` and (b) don't have an implementation of `LookupSpan` for `Layered`.
Since there was already a `LookupMetadata` impl, this just seemed like an oversight. So I changed the implementation over.
Note that `LookupMetadata` gets implemented via the blanket impl on `L: LookupSpan`.
> Implement `LookupSpan` for `Layered`.

- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/registry/mod.rs
Currently there are some links that 404 because they contain
a reference to a struct 'struct.Layer.html' which presumably
should be the trait 'layer/trait.Layer.html'.
> docs: Fix broken links to Layer trait

- tracing/src/lib.rs
This fixes the link to the examples in the tracing crate doc.
> Fix link to tracing examples in crate doc

- tracing-subscriber/src/layer.rs
Currently, `Layer::downcast_raw` constructs a pointer with:
```rust
&self as *const _ as *const ()
```
This is wrong. The method's receiver is already `&self`, so this code
constructs a reference _to_ the `&self` reference, and converts _that_
into a pointer. Since this is not the actual memory address of the
layer, this is invalid.
We didn't catch this because the tests for downcasting layers are
also wrong: they never actually dereference the ref created by 
`downcast_ref`. Therefore, if an invalid pointer is returned, the 
test can still pass, as long as _any_ pointer is returned.
This branch changes the pointer to:
```rust
self as *const _ as *const ()
```
Now, the returned pointer is valid.
In addition, it changes the tests  to try and access data through the
returned references. The …
> subscriber: fix `Layer::downcast_ref` returning invalid references

- azure-pipelines.yml
- examples/Cargo.toml
- nightly-examples/Cargo.toml
- tracing-futures/CHANGELOG.md
- tracing-futures/Cargo.toml
- tracing-futures/README.md
- tracing-futures/src/executor/futures_01.rs
- tracing-futures/src/lib.rs
- tracing-futures/test_std_future/Cargo.toml
- tracing-tower/Cargo.toml
Also upgrades futures-03 to the non-preview crate and renames the `futures` feature to `futures-01`.
Fixes #418
> future: futures-03 & std-future is the default

- tracing/README.md
Follow-up of #439, as suggested here: https://github.com/tokio-rs/tracing/pull/439#pullrequestreview-321847810.
This adds a link to the examples directory, located in the root of the repository, in the README of the `tracing` crate.
> Add link to examples directory from tracing crate README

- tracing-subscriber/src/fmt/format/mod.rs
Latest master cannot infer types in the `fmt` function.
Tell the compiler the result type. Funnily I couldn't reproduce this directly from `tracing` repo, but when I have `tracing` as a dependency following it from github, the later versions would not pass `cargo check`
We used to be on this version `16fee661ac1f5dd175491e611ff4c08b33c070fa`, and `cargo update` would break the project.
> Fix type annotations in ansi fmt

- tracing-subscriber/Cargo.toml
Currently tracing-subscriber doesn't compile on 32-bit platforms as discussed here: https://github.com/hawkw/sharded-slab/issues/9
The underlying issue has been fixed by @hawkw. This pull simply updates the dependency inside this project. Thanks for your work on this!
> subscriber: upgrade sharded-slab to 0.0.7 to fix 32-bit build

- tracing-core/src/event.rs
Current link in [here](https://docs.rs/tracing/0.1.10/tracing/event/struct.Event.html#method.metadata), which should point to the correct [`metadata`](https://docs.rs/tracing/0.1.10/tracing/struct.Metadata.html) struct definition, instead points to [here](https://docs.rs/tracing/0.1.10/tracing/metadata/struct.Metadata.html).
Link is broken.
Fix link. :)
> Event struct definition link typo

- tracing/src/level_filters.rs
Makes it possible to get a `Level` without having to check which `LevelFilter` is being used.
Simply moves the inner `Option<Level>` out of the `LevelFilter`.
> Add `LevelFilter::to_level`

- tracing/src/level_filters.rs
Can't create a filter for a specific level without having to `match` on a `Level`.
Add `LevelFilter::from_level` `const` function and  `From<Level> for LevelFilter` impl
> Add conversions from `Level` to `LevelFilter`

- tracing-attributes/Cargo.toml
- tracing-attributes/src/lib.rs
This PR updates `tracing-attributes`'s documentation to: 
- Document the previously undocumented `skip` argument.
- Build the `async fn` example now that `tracing`'s MSRV is 1.39.
> tracing-attributes: update documentation; note skipability of arguments

- tracing/src/span.rs
There is currently no way to detect when a span is "empty" (i.e., it was
created with `Span::none`). This would be handy in cases where you want
to perform some (perhaps costly) additional metric-gathering when a
particular request _is_ being traced (i.e., it has a `Span`).
This branch adds `Span::is_none`.
Closes #469 
> tracing: add `Span::is_none`

- tracing-subscriber/src/fmt/fmt_layer.rs
> fmt: add public constructor to `FormattedFields`

- tracing-log/README.md
I stumbled upon this issue when trying to get tracing-log working with env_logger. The comments in-code are right, but the README uses a hyphen instead of an underscore.
Switched the hyphen for an underscore :)
> Fix env_logger feature name in README

- tracing/src/macros.rs
- tracing/test-log-support/tests/log_no_trace.rs
- tracing/test-log-support/tests/log_with_trace.rs
When using the `tracing/log` feature flag to emit log records from
tracing events which contain a message and fields, there is missing
whitespace between the message and the rest of the fields.
For example, events like
```rust
tracing::trace!(
sz,
old = self.window_size.0,
new = val,
"inc_window"
);
```
and
```rust
tracing::trace!(
sz,
window = self.window_size.0,
available = self.available.0,
"send_data",
);
```
result in `log` records like this:
```
TRACE 2019-12-05T18:26:56Z: h2::proto::streams::flow_control: inc_windowsz=65535 old=0 new=65535
TRACE 2019-12-05T18:26:56Z: h2::proto::streams::flow_control: inc_windowsz=65535 old=0 new=65535
TRACE 2019-12-05T18:26:56Z: h2::proto::streams::flow_control: inc_windowsz=65535 old=0 new=65535
TRACE 2019-12-05T18:26:56Z: …
```
> tracing: fix missing whitespace in log records

- tracing-subscriber/src/fmt/format/mod.rs
> subscriber: fix buggy format with module disabled

- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/time.rs
> subscriber: fix missing space issue

- README.md
- tracing-attributes/README.md
- tracing-core/README.md
- tracing-futures/README.md
- tracing-log/README.md
- tracing-subscriber/README.md
- tracing/README.md
This branch updates all the README links and badges. In particular, it:
* Changes build status badges to GitHub Actions, since we've turned off
the Azure Pipelines CI build,
* Removes Gitter links, since nobody is on Gitter these days and we
probably don't want to point new users to an empty chat room,
* Make Discord links "actually work"
> chore: update README links/badges

- tracing-core/CHANGELOG.md
- tracing-core/README.md
- tracing-core/src/lib.rs
Added
- `Default` impl for `Dispatch` (#411)
Fixed
- Removed duplicate `lazy_static` dependencies (#424)
- Fixed no-std dependencies being enabled even when `std` feature flag
is set (#424)
- Broken link to `Metadata` in `Event` docs (#461)
> core: prepare to release v0.1.8

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- `Span::is_none` method (#475)
- `LevelFilter::into_level` method (#470)
- `LevelFilter::from_level` function and `From<Level>` impl (#471)
- Documented minimum supported Rust version (#482)
- Incorrect parameter type to `Span::follows_from` that made it impossible to
call (#467)
- Missing whitespace in `log` records generated when enabling the `log` feature
flag (#484)
- Typos and missing links in documentation (#405, #423, #439)
> tracing: prepare to release 0.1.11

- tracing-subscriber/src/fmt/mod.rs
Resolves #489.
To get this to compile, I had to change the error types from `impl Error + Send + Sync + 'static` to `Box<dyn Error + Send + Sync + 'static>`.
I verified the corrected behavior by running `cargo run --example log` which, prior to this change, wrote:
```
Dec 21 14:02:15.827  INFO log: this is a tracing line
```
After this change, the `log` example wrote:
```
Dec 21 14:15:20.490 DEBUG log: this is a log line
Dec 21 14:15:20.490 DEBUG log: this is a tracing line
```
> tracing-subscriber: fix #489

- tracing-subscriber/src/layer.rs
This fixes the following compilation error:
```
error[E0433]: failed to resolve: use of undeclared type or module `registry`
--> tracing-subscriber/src/layer.rs:844:25
|
844 |         S: for<'lookup> registry::LookupSpan<'lookup>,
|                         ^^^^^^^^ use of undeclared type or module `registry`
error[E0412]: cannot find type `Scope` in this scope
--> tracing-subscriber/src/layer.rs:842:28
|
842 |     pub fn scope(&self) -> Scope<'_, S>
|                            ^^^^^ not found in this scope
error[E0425]: cannot find function, tuple struct or tuple variant `Scope` in this scope
--> tracing-subscriber/src/layer.rs:850:9
|
850 |         Scope(scope)
|         ^^^^^ help: a local variable with a similar name exists (notice the capitalization): `scope`
```
> subscriber: Fixup compilation error with features disabled

- tracing/src/span.rs
Intended to allow library authors to access a span's dispatcher for out-of-band interaction with subscribers/layers. 
see #473 for details
Closes #473
> add with_subscriber to span

- .github/workflows/CI.yml
Fixes #501
I've found multiple compilation error involving non-default features.
cargo-hack was a suggested solution (by @davidbarsky and @hawkw) to run compilation checks on all features.
> ci: try cargo-hack

- tracing-futures/Cargo.toml
- tracing-futures/src/executor/futures_03.rs
- tracing-futures/src/executor/futures_preview.rs
- tracing-futures/src/lib.rs
- tracing-futures/src/stdlib.rs
Being able to trace futures in platforms that do not support stdlib would be nice.
> futures: no_std support

- README.md
- tracing-error/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
This branch adds a list of related crates not in this repository to the
`tracing` RustDoc, the `tracing` README, and the root repository README.
(cc @jonhoo, @jtescher, @pkinsky, @GregBowyer, @zanria, @hlb8122)
Closes #373
> docs: add third-party crates to docs

- tracing-subscriber/src/registry/sharded.rs
- tracing-subscriber/src/registry/stack.rs
In cases where spans are not popped in FILO (first-in-last-out) order,
`pop` would return `None`. This would cause issues in `Registry` where
spans that are exited out of order would not be closed properly.
Fixes #495
> subscriber: traverse SpanStack on pop

- .github/workflows/CI.yml
- tracing-attributes/src/lib.rs
- tracing-attributes/test_async_await/tests/async_fn.rs
- tracing-core/src/dispatcher.rs
- tracing-core/src/field.rs
- tracing-subscriber/src/field/mod.rs
- tracing-subscriber/src/filter/env/mod.rs
- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/registry/mod.rs
- tracing/src/span.rs
- tracing/tests/span.rs
This is a follow up draft PR for #477 that runs clippy on CI. It is not using [actions-rs/clippy-check](https://github.com/actions-rs/clippy-check) yet but I will switch over to that shortly.
I've created this as a draft because it looks like there are some additional clippy warnings that will need to be fixed first.
I've also just replaced the `check` step with `clippy` since running both would be a little redundant (`cargo clippy` runs `cargo check` already). However, I can change this if you'd like to keep them separate.
> Run clippy-check action on CI

- tracing-subscriber/src/registry/sharded.rs
This branch fixes a couple of issues which might result in child spans
not correctly triggering their parents to close:
* subscriber: fix spans closed by their children not being removed
The issue here is that the `CloseGuard` removes the span from the
registry (dropping the `DataInner`) *before* it decrements CLOSE_COUNT.
Dropping the `DataInner` will decrement the parent span's ref count,
potentially allowing it to close. When the new close for the parent span
starts, CLOSE_COUNT will be 1, not 0, and it will not be decremented
until after the try_close call completes. This means that although the
close is processed and all the layers see `on_close` calls for that
span, the span's data is never removed from the registry, effectively
leaking it.
This commit fixes the problem by …
> subscriber: fix issues when a span triggers its parents to close

- tracing-core/src/subscriber.rs
The docs for `drop_span` incorrectly state that the method is
"soft-deprecated", when it's actually...normal deprecated. The RustDoc
says that "using this method won't cause a compilation warning", but
this is incorrect.
This branch updates the doc comment.
> core: s/soft deprecated/deprecated

- netlify.toml
- tracing-core/Cargo.toml
- tracing-core/src/dispatcher.rs
- tracing-core/src/field.rs
- tracing-core/src/lib.rs
- tracing-core/src/metadata.rs
- tracing-futures/Cargo.toml
- tracing-futures/src/lib.rs
- tracing/Cargo.toml
- tracing/src/dispatcher.rs
- tracing/src/lib.rs
- tracing/src/subscriber.rs
Starts on #440.
This branch adds `doc_cfg` attributes to `tracing` and `tracing-core`,
when a `docsrs` cfg flag is passed to rustdoc. It also adds 
docs.rs crate metadata to configure docs.rs to set that flag, and adds
it to the Netlify config as well.
Co-authored-by: Jane Lusby <jlusby@yaah.dev>
> docs: add doc-cfg attributes to tracing and tracing-core

- .github/workflows/CI.yml
- tracing/src/dispatcher.rs
It appears that this setting doesn't actually do what I thought it did.
Having this seems to result in all the CI actions being run one
additional time *when the PR is opened* (which should be identical to
the first push?), and if it fails, it marks the PR as failing
permanently. Subsequent pushes don't appear to change the PR's state.
This is clearly not what we want — I think `on: pull_request` was
intended for stuff like labeling the PR or posting a welcome message for
new contributors, not for running CI jobs.
Therefore, I've removed it.
> ci: remove `on: pull_request`

- README.md
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- tracing/README.md
- **fmt**: Public `FormattedFields::new` constructor (#478)
- **fmt**: Added examples to `fmt::Layer` documentation (#510)
- Documentation now shows what feature flags are required by each API item (#525)
- **fmt**: Missing space between timestamp and level (#480)
- **fmt**: Incorrect formatting with `with_target(false)` (#481)
- **fmt**: `fmt::SubscriberBuilder::init` not setting up `log` compatibility
(#489)
- **registry**: Spans exited out of order not being closed properly on exit
(#509)
- **registry**: Memory leak when spans are closed by a child span closing (#514)
- **registry**: Spans closed by a child span closing not also closing _their_
parents (#514)
- Compilation errors with `no-default-features` (#499, #500)
> subscriber: prepare to release 0.2.0-alpha.3

- tracing-subscriber/src/registry/sharded.rs
These were added while debugging issue #511. They were never intended to
be committed, but apparently I missed a few while removing them, and
they slipped into PR #514 by mistake.
Once this merges, I'll publish `tracing-subscriber` 0.2.0-alpha.4. We may
want to consider yanking alpha.3.
> subscriber: remove `dbg!` macros from registry

- README.md
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- tracing/README.md
- **registry**: Removed inadvertently committed `dbg!` macros (#533)
> subscriber: prepare to release 0.2.0-alpha.4

- .github/workflows/CI.yml
I've made some improvements to the CI workflow script.
I've consistently used the `actions-rs` actions where possible and have enabled caching for several of the jobs, bringing their completion time from minutes down to seconds. I've also added a job that runs `cargo audit`.
I added the `.gitattributes` since I was developing on windows. The rust-lang repo [also uses this](https://github.com/rust-lang/rust/blob/caa231d998a5e853c7ba1455d7a05b500df9d63c/.gitattributes#L3).
The `Cargo.lock` needs to be committed (or regenerated on CI if you prefer; although this will need to be done for each job which is why I've opted not to do that) in order to generate the hashes for caching keys. Note that when `Cargo.lock` is updated, the first subsequent CI run will be slower since the caches need to …
> CI workflow improvements

- tracing-core/src/field.rs
- tracing/Cargo.toml
- tracing/test-log-support/tests/log_with_trace.rs
- tracing/tests/event.rs
For tracing there's no difference between a `NonZero*` or `Wrapping` type and their underlying type. This allows such types to directly be referenced by the tracing macros without requiring additional method calls or boilerplate.
Implemented `Value` for `Wrapping<T: Value>` and for all the `NonZero*` types from `std::num`.
This required a slight refactoring of the macros generating the regular integer impls as to reduce the amount of generated code.
> Support tracing `Wrapping` and `NonZero` types

- tracing-log/Cargo.toml
- tracing-log/src/lib.rs
- tracing-log/src/log_tracer.rs
- tracing-tower/Cargo.toml
- tracing-tower/src/lib.rs
- tracing-tower/src/request_span.rs
- tracing-tower/src/service_span.rs
Closes #440 
this should be the last of them
> finish doc_cfg for tracing-tower and tracing-log

- tracing-subscriber/Cargo.toml
The smallvec 0.6 dependency is causing some duplicate dependencies in quinn. smallvec 1.0 has been released in November, it would be nice not to have to build it twice.
Upgrade to the 1.1.0 version from December.
> subscriber: upgrade to smallvec 1.1.0

- tracing-futures/src/lib.rs
tracing-futures currently supports instrumenting futures 0.1 Futures, Streams, and Sinks, and std::future::Future from futures 0.3. However, the futures 0.3 Stream and Sink traits in the futures-preview crate are not supported.
Implement traits `Sink` and `Stream` from the `futures 0.3` crate for struct `Instrumented`. These new features are guarded by a combination of feature flags `futures-03` and `std-future`.
Add basic unit tests for both new features, closely modelled after existing unit tests for corresponding features for the `futures 0.1` crate.
Move some test structs only used by futures 0.1-related tests "down" into their test module to avoid warnings about unused code when running tests with `futures-03` enabled.
**Note** that compiling `tracing-futures` with `futures-03` …
> #226: support futures 0.3 Streams/Sinks

- tracing-subscriber/src/layer.rs
Currently, a `Layered` struct's implementations of `Subscriber` and
`Layer` will successfully downcast to either the the `Layer` type or the
inner type, but *not* to `Layered<Layer, Inner>`. This means that when a
`Layer` tries to downcast the wrapped subscriber to a known type, and it
is a `Layered` (so, any time more than one layer wraps a subscriber and
a layer other than the first one tries to downcast to the inner type it
wraps), the downcast will fail incorrectly.
This commit fixes the issue by checking if the downcast target `TypeId`
equals the `Layered` type's `TypeId`, _before_ trying to downcast to the
layer itself or to the inner type.
> subscriber: fix `Layered` layers not downcasting to themselves

- tracing-subscriber/src/filter/env/mod.rs
This PR is extracted from #368 and introduces additional documention for filter directives in `tracing-subscriber`.
Signed-off-by: David Barsky <me@davidbarsky.com>
Co-authored-by: Lucio Franco <luciofranco14@gmail.com>
> docs: document filter directives

- README.md
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- tracing/README.md
- **env_filter**: Documentation for filtering directives (#554)
- **registry**, **env_filter**: Updated `smallvec` dependency to 0.1
(#543)
- **registry**: Fixed a memory leak in the slab used to store per-span
data (3c35048)
- **Layer**: Fixed `Layered` subscribers failing to downcast to their
own type (#549)
- **fmt**: Fixed a panic when multiple layers insert `FormattedFields`
extensions from the same formatter type (1c3bb70)
- **fmt**: Fixed `fmt::Layer::on_record` inserting a new
`FormattedFields` when  formatted fields for a span already exist
(1c3bb70)
> subscriber: prepare to release 0.2.0-alpha.5

- tracing-attributes/src/lib.rs
- tracing-subscriber/src/filter/env/mod.rs
- tracing-subscriber/src/reload.rs
This PR fixes two types of warnings:
1. Usage of deprecated methods on `std::error::Error`.
2. An unused warning on `extern crate proc_macro` in tracing-attributes. This does not occur on the stable release of `1.41`, but it does occur on `1.42.0-beta.1` and `1.42.0-nightly (cd1ef390e 2020-01-31)`. 
Prior to merging this PR, I'd like to determine whether the second warning is a deliberate change or a regression.
> chore: fix warnings on nightly

- examples/Cargo.toml
- tracing-error/Cargo.toml
This updates `tracing-error` to depend on `tracing-subscriber` from
crates.io, rather than via a path dependency. This means that git deps
on `tracing-error` should "actually work" now.
Additionally, I've updated the `tracing-subscriber` dep to only enable
the feature flags `tracing-error` requires. This means that depending on
`tracing-error` won't enable `tracing-subscriber`'s default features
unless they are actually needed.
> error: switch tracing-subscriber to crates.io dependency

- tracing-subscriber/src/fmt/format/mod.rs
* subscriber: fix misaligned levels with ANSI disabled
Currently, when ANSI color formatting is enabled, `tracing-subscriber`'s
`fmt` module left-pads the INFO and WARN levels so that log lines are
aligned. However, when ANSI colors are off, these levels are not padded.
I've fixed this by replacing the string literals in the ANSI and
not-ANSI implementations with constants, to ensure the same string is
used regardless.
* subscriber: make ANSI and not-ANSI formatting consistent
Currently, the `tracing-subscriber` crate's `fmt` module has two
separate `fmt::Display` impls for its' `FmtCtx` and `FullCtx` types,
depending on whether the feature flag that enables ANSI colors is set.
Since a lot of the `fmt::Display` implementations doesn't have …
> subscriber: several small `fmt` formatting fixes

- README.md
- tracing-error/src/layer.rs
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- tracing/README.md
Fixed
- **fmt**: Fixed empty `{}` printed after spans with no fields (f079f2d)
- **fmt**: Fixed inconsistent formatting when ANSI colors are disabled (506a482)
- **fmt**: Fixed mis-aligned levels when ANSI colors are disabled (eba1adb)
- Fixed warnings on nightly Rust compilers (#558)
> subscriber: prepare to release 0.2.0-alpha.6

- tracing-subscriber/Cargo.toml
This should fix the `doc-cfg` attributes not being present in the
docs.rs docs.
> subscriber: fix missing rustdoc-args on docs.rs

- tracing-subscriber/src/lib.rs
- tracing-subscriber/src/registry/mod.rs
- tracing-subscriber/src/registry/sharded.rs
Currently, both the `Registry` type _and_ the `LookupSpan` and
`SpanData` traits require the "registry" feature flag. This means that
if a user wishes to implement their own custom registry type that
implements `LookupSpan`, they must enable the "registry" feature flag,
which also enables the `Registry` type and its dependencies.
This commit changes the feature flag so that only the `Registry` and
`Data` types are conditional on the "registry" feature. The `LookupSpan`
and `SpanData` traits are now always enabled, as they are not much code
& don't require any additional internal dependencies (although if anyone
thinks it's important for them to have their own separate feature flag,
I am willing to change that).
> subscriber: feature flag registry implementation only

- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/format/json.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/registry/mod.rs
- tracing-subscriber/src/registry/sharded.rs
The `LookupMetadata` trait was essentially a prototype for `LookupSpan`,
and was intended to allow subscribers to implement more granular sets of
"registry" behavior. However, in practice, nothing ended up using it and
it was generally eclipsed by `LookupSpan`. The model of allowing
`Layer` implementations to opt in to more granular capabilities doesn't
make a whole lot of sense when there are only two such traits available
and one is a more powerful superset of the other. Before we release
`tracing-subscriber` 0.2.0, we should try to remove any APIs that aren't
necessary, since removing them later is a breaking change.
Therefore, this commit removes `LookupMetadata`, and rewrites the
`Context::metadata` method to use `LookupSpan` to look up the metadata,
instead. …
> subscriber: remove `LookupMetadata` trait

- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/registry/mod.rs
Depends on #564 
This commit adds a new section to the `Layer` docs on how `Layer`s and
`Subscriber`s are composed. Additionally, it updates the docs to prefer
the use of `SubscriberExt::with` over `Layer::with_subscriber`.
Additionally, I've fixed how `SubscriberExt::with` is implemented, so
that `Layer`s may use `with_subscriber` as a callback for composition.
Closes  #452
Closes #505 (IMO)
> subscriber: improve docs on `Layer` composition

- README.md
- tracing-error/src/layer.rs
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- tracing/README.md
- **fmt**: Renamed `Context` to `FmtContext` (#420, #425)
- **fmt**: Renamed `Builder` to `SubscriberBuilder` (#420)
- **filter**: Removed `Filter`. Use `EnvFilter` instead (#434)
- **registry**: `Registry`, a `Subscriber` implementation that `Layer`s can use
as a high-performance, in-memory span store. (#420, #425, #432, #433, #435)
- **registry**: Added `LookupSpan` trait, implemented by `Subscriber`s to expose
stored span data to `Layer`s (#420)
- **fmt**: Added `fmt::Layer`, to allow composing log formatting with other `Layer`s
- **fmt**: Added support for JSON field and event formatting (#377, #415)
- **filter**: Documentation for filtering directives (#554)
- **fmt**: Renamed `Context` to `FmtContext` (#420, #425) (BREAKING)
- **fmt**: Renamed `Builder` to `SubscriberBuilder` (#420) …
> subscriber: prepare to release 0.2.0 stable

- tracing/src/span.rs
Hidden lifetime parameters in types are deprecated in Rust 2018. These
specific instances were missed as they are in code that is only compiled
with the `log` feature enabled, and the CI warnings step does not enable
that feature.
This PR adds explicit empty lifetimes.
> tracing: fix hidden lifetime params in types

- examples/Cargo.toml
- tracing-error/CHANGELOG.md
- tracing-error/Cargo.toml
- tracing-error/README.md
- tracing-error/src/layer.rs
- tracing-error/src/lib.rs
This branch prepares `tracing-error` to publish to crates.io.
> error: prepare to release 0.1.0

- tracing-core/Cargo.toml
- tracing-core/src/field.rs
- tracing/Cargo.toml
- tracing/src/lib.rs
- tracing/src/span.rs
Right now, there is no way to indicate that a span field _currently_
has no value but that a value will be recorded later. Tracing used to
support this concept, but when we added local-variable shorthand, it was
removed from the macros, as we needed to use the previous syntax for
indicating empty fields for local variable shorthand. See #77 for
details.
This commit side-steps the problem of determining an appropriate
_syntax_ for empty fields by adding a special value _type_, called
`Empty`. Now, empty values can be indicated like
```rust
span!("my_span", foo = 5, bar = tracing::field::Empty);
```
The `Empty` type implements `Value`, but its' `record` method is a no-op
that doesn't' call any functions on the visitor. Therefore, when a field
is empty, the visitor will not see it. An empty …
> tracing, core: re-implement empty fields

- bin/publish
- examples/Cargo.toml
- nightly-examples/Cargo.toml
- tracing-attributes/Cargo.toml
- tracing-attributes/test_async_await/Cargo.toml
- tracing-error/Cargo.toml
- tracing-futures/Cargo.toml
- tracing-futures/test_std_future/Cargo.toml
- tracing-log/Cargo.toml
- tracing-serde/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-tower/Cargo.toml
- tracing/Cargo.toml
Intra-workspace dependencies can go out of sync if only referencing crates.io, where changing one crate locally and testing the whole library will result in errors stemming from two different versions of the same trait etc. This is hard to keep track of and makes development more difficult than it needs to be. 
Afaik it's common practice to specify both a version and a path as per https://github.com/rust-lang/cargo/blob/master/src/doc/src/reference/specifying-dependencies.md#multiple-locations. This is what tokio does with its subcrates too.
> Specify path dependencies for workspace crates

- tracing-futures/Cargo.toml
- tracing-futures/src/executor/futures_03.rs
- tracing-futures/src/executor/mod.rs
I tried to use `futures_03` module, but it is unusable in current state. The code has seemingly never been compiled before. On first sight, with this PR, it's actually working as intended.
Current code does not compile.
- use correct feature name
- use correct paths to imported types
- use correct trait names
- pass correct types to Spawn and SpawnLocal traits
- remove unused imports
@hawkw
> futures: make the executor/futures_03 module compile

- tracing-subscriber/src/filter/env/mod.rs
Currently, `tracing-subscriber`'s `EnvFilter` type uses a user-space
thread local for storing any entered spans which are relevant to
filters. This was intended to support allowing multiple `EnvFilter`s to
coexist in the same subscriber, which was never implemented. It turns
out this has a noticeable performance impact versus a proper
thread-local.
I replaced the user-space thread local type with a proper thread-local.
(vs master, note that there was some noise in the benchmark environment,
as evidenced by the "regression" in the baseline tests)
```
Running target/release/deps/filter-56ce39a1aef6b2a0
static/baseline_single_threaded
time:   [98.622 ns 101.54 ns 104.78 ns]
change: [+2.5820% +6.1667% +9.7976%] (p = 0.00 < 0.05)
Performance has regressed.
Found 7 outliers among 100 …
```
> subscriber: remove user-space thread local from filters

- tracing-subscriber/Cargo.toml
- tracing-subscriber/benches/filter.rs
- tracing-subscriber/benches/filter_log.rs
Currently, there are a few cases that aren't adequately covered by the
`tracing-subscriber` filtering benchmarks. In particular, we don't have
benchmarks which involve filters with multiple directives, missing a
large amount of potential overhead from iterating over the directive
set, and we don't have benchmarks for events generated by the `log`
integration. Since `log` events can't participate in the callsite
caching mechanism, their performance picture is radically different.
This branch adds new benchmarks for filters with multiple static
directives, filters with multiple dynamic directives, and filters with
mixed static and dynamic directives. Additionally, I've added a new set
of benchmarks which are identical to the current ones, except that
`log`'s macros are used to emit events …
> subscriber: add more benchmarks for filters

- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/registry/mod.rs
Quick glance at `perf` shows a lot of time being spent in `btree_set::Iter::next()`. Since we only ever iterate over it after it's built, we don't really need to pay this cost, so this switches to just building a Vec.
> subscriber: use Vec instead of BTreeSet in DirectiveSet

- README.md
Found a simple spelling error in the README.
Fixed it. :)
Fixes #577
> docs: fix minor spelling error in README.md

- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/mod.rs
The benchmarks added in #581 indicate that `tracing-subscriber`'s 
`EnvFilter` has significant overhead when filtering events generated
from `log` records that is not present when filtering native `tracing` 
events.
Additionally, the behavior of `EnvFilter` differs from the `env_logger`
crate it emulates: when a less specific filter is more verbose than a
more specific filter, the more verbose filter is used. For example:
```
RUST_LOG=debug,tokio_postgres=info,hyper::server::response=info
```
* With `env_logger` - treat all targets as DEBUG *except* for 
`tokio_postgres` and `hyper::server::response`
* With `EnvFilter::from_default_env()` - treat all targets as DEBUG.
This then overrides the explicit setting of INFO for the other two,
so they are DEBUG as well.
(see #512)
This branch …
> subscriber: fix incorrect filter selection + improve filter performance

- tracing-futures/CHANGELOG.md
- tracing-futures/Cargo.toml
- tracing-futures/src/lib.rs
- Support for `futures` 0.3 `Stream`s and `Sink`s (#544)
- Compilation errors when using the `futures-03` feature (#576)
Thanks to @obergner and @najamelan for their contributions to this
release!
> futures: prepare to release 0.2.2

- tracing-futures/src/lib.rs
For the same reasoning as https://github.com/tokio-rs/tracing/pull/386
> Allow borrowed access to WithDispatch.inner.

- tracing-futures/src/lib.rs
Adds the possibility for the client code to access a pinned projection of the wrapped types in `Instrumented` and `WithDispatch`. As suggested in #386.
I added this after seeing the suggestion, it compiles fine, but be warned I have not actually tried to use this for anything. Let me know if you want to see any tests added.
The main thing I see this enabling is calling `poll` directly on a wrapped future, which would disable the functionality from the wrappers. I'm not sure of the use case, but that's not a reason to make it impossible I suppose.
I got stuck a bit wondering how sound it is to give access to both a `&mut` and a `Pin<&mut>` for the same field, but haven't been able to find any way to break anything without unsafe code.
> futures: Add Instrumented and WithDispatch ::{inner_pin_ref, inner_pin_mut}

- tracing-core/src/dispatcher.rs
- tracing-core/src/lib.rs
- tracing-core/src/subscriber.rs
- tracing-error/src/backtrace.rs
- tracing-error/src/lib.rs
- tracing-log/src/lib.rs
- tracing-log/src/trace_logger.rs
- tracing-subscriber/src/lib.rs
- tracing-subscriber/src/registry/mod.rs
- tracing/src/span.rs
This commit fixes several RustDoc links which were either broken
(without references) or had unresolvable references.
It looks like nightly RustDoc has recently gotten much smarter about
finding links that were unresolvable. These had always been broken, but
they used to silently 404. Now, the nightly build of RustDoc will emit a
warning, which we deny, causing the build to fail. This should fix CI
(as well as actually fixing the wrong links).
> docs: fix broken and unresolvable links

- tracing-core/CHANGELOG.md
- tracing-core/README.md
- tracing-core/src/lib.rs
- `field::Empty` type for declaring empty fields whose values will be
recorded later (#548)
- `field::Value` implementations for `Wrapping` and `NonZero*` numbers
(#538)
- Broken and unresolvable links in RustDoc (#595)
Thanks to @oli-cosmian for contributing to this release!
> core: prepare to release 0.1.10

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/fields.rs
This PR adds support for adding arbitrary key/value pairs to be used as fields to `tracing::instrument`.
Current syntax:
```rust
#[instrument(fields(key = "value", v = 1, b = true, empty))]
```
- Empty keys are supported
- If a key is not a single identifier, it's value is not a string/int/bool (or missing), is repeated or shares a name with a parameter, an error is reported
Remarks:
- I noticed that the `Value` trait is implemented only for integers, booleans, strings and Debug/Empty values. I wonder why floating point numbers are not supported?
- The testing infrastructure (`MockSpan` etc.) is awesome!
- Field keys in spans can be nested (for example `parent.child = 1`). We might achieve something similar here by transforming a path (`parent::child`) into a nested key (`parent.child`). …
> attributes: support adding arbitrary fields to the instrument macro

- examples/examples/instrumented_error.rs
- tracing-error/Cargo.toml
- tracing-error/src/backtrace.rs
- tracing-error/src/heap_error.rs
- tracing-error/src/lib.rs
- tracing-error/src/stack_error.rs
The tracing_error crate should provide some basic functionality for instrumenting Errors with `SpanTraces` generically. The goal is to make it easy for users to instrument their errors without needing to add a `SpanTrace` to every error they construct.
Critically this trait provides 3 traits for instrumenting errors, `InstrumentResult`, `InstrumentError`, and `ExtractSpanTrace`. The first two traits expose a `in_current_span()` method that can work on a `Result<T, E: InstrumentError>` and an `Error`, respectively, that wraps the error type in a `TracedError` that stores the inner error and a SpanTrace. The third trait, `ExtractSpanTrace`, is used to retrieve the span_trace member of a `TracedError` from a `&dyn Error` trait object.
This is done by downcasting the error to a `TracedError` …
> Add error instrumentation type and traits

- tracing-attributes/src/lib.rs
This PR adds a check to the `#[instrument]` macro to emit a compiler error if the user tries to skip non-existing parameters.
Fixes: https://github.com/tokio-rs/tracing/issues/562
> attributes: check if a skipped parameter exists

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/src/lib.rs
This allows consumers to use the convenience of `tracing` without having to pull in the `syn` crate.
> tracing: Make tracing-attributes (and syn) optional

- tracing-futures/CHANGELOG.md
- tracing-futures/Cargo.toml
- tracing-futures/README.md
- tracing-futures/src/lib.rs
- `WithDispatch::inner` and `WithDispatch::inner_mut` methods to allow
borrowing the wrapped type (#589)
- `WithDispatch::with_dispatch` method, to propagate the subscriber to
another type (#589)
- `inner_pin_ref` and `inner_pin_mut` methods to `Instrumented` and
`WithDispatch` to project to the inner future when pinned (#590)
> futures: prepare to release 0.2.3

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- **field**: `field::Empty` type for declaring empty fields whose values
will be recorded later (#548)
- **field**: `field::Value` implementations for `Wrapping` and `NonZero*`
numbers (#538)
- **attributes**: Support for adding arbitrary literal fields to spans
generated by `#[instrument]` (#569)
- **attributes**: `#[instrument]` now emits a helpful compiler error when
attempting to skip a function parameter (#600)
- **attributes**: The `#[instrument]` attribute was placed under an
on-by-default  feature flag "attributes" (#603)
- Broken and unresolvable links in RustDoc (#595)
Thanks to @oli-cosmian and @Kobzol for contributing to this release!
> tracing: prepare to release 0.1.13

- tracing-log/src/lib.rs
- tracing-log/tests/reexport_log_crate.rs
Resolves #552.
Re-export the whole log crate.
> Re-export the log crate from tracing-log

- tracing-attributes/tests/bad_skip.rs
- tracing/src/lib.rs
- tracing/src/span.rs
- tracing/test-log-support/src/lib.rs
- tracing/test-log-support/tests/log_no_trace.rs
- tracing/test-log-support/tests/log_with_trace.rs
- tracing/test-log-support/tests/span_lifecycle_can_be_filtered.rs
- tracing/test-log-support/tests/span_lifecycle_defaults_off.rs
Currently, the `tracing` crate's "log" feature always logs span
lifecycle (creation/enter/exit/close) events, even when the span has no
fields. This can be quite noisy. Since the enter, exit, and close logs
don't include the span's fields, it doesn't add that much additional
context to the surrounding log records.
Additionally, when using `tracing` with the `log-always` feature and a
subscriber is active, the IDs of enabled spans are available, but not
included in the span lifecycle `log` records. These could be used to
enable tracking individual span's lifecycles via these log records, but
this is not currently possible.
In order to continue recording this data while improving the
signal-to-noise ratio of `tracing`-generated logs, this branch changes
the log integration to log span …
> tracing: less noisy, more useful `log` records for spans

- tracing-error/src/backtrace.rs
- tracing-error/src/lib.rs
Because `SpanTrace` does not have a header, implementations that wish to print a `SpanTrace` must print their own header before printing the `SpanTrace` itself. When the `SpanTrace` is empty this ends up inserting a header with no content after it, and the only way to avoid this via the current API is to `to_string` the `SpanTrace` prior to printing the header to check if `SpanTrace` would print any content.
This change adds a `SpanTrace::status()` fn and accompanying `SpanTraceStatus` enum type to indicate to the user what will be printed if anything when the user attempts to display/debug print the `SpanTrace`.
> Add a status fn to SpanTrace

- tracing-error/src/heap_error.rs
- tracing-error/src/stack_error.rs
The current impl for `ExtractSpanTrace` is implemented for references and takes &self as its receiver type, which causes it to reborrow the error and the lifetime of the returned SpanTrace is tied to this new borrow. This prevents the SpanTrace from outliving the borrow created from the `span_trace` call which functionally means you cannot return references to the borrowed `SpanTrace`s
This changes the receiver type from `&dyn Error` to `dyn Error` so that the `&` in the `&self` pattern ends up matching against the original borrow, which could be a borrow that was passed in from another function, which lets us use the longer lifetime as the lifetime for the reference to the SpanTrace.
> Fix receiver type to avoid a reborrow

- tracing-attributes/src/lib.rs
Previously, some compile errors generated by `tracing-attributes` on bad
inputs, such as for an invalid `skip` arg, would be generated as the
_entire_ output of the attribute. Since the attribute is invoked in item
position (to generate a function), this would result in invalid code,
and the compiler would emit a much more cryptic parse error rather than
the intended helpful error.
For example, this code
```rust
#[instrument(skip(baz))]
fn bad_skip(foo: usize) {}
```
would result in the compiler outputting this error:
```
error: macros that expand to items must be delimited with braces or followed by a semicolon
--> tracing-attributes/tests/bad_skip.rs:3:19
|
3 | #[instrument(skip(baz))]
|                   ^^^
|
help: change the delimiters to curly braces
|
3 | #[instrument(skip( {a}))] …
```
> attributes: fix compile error generation

- tracing-error/CHANGELOG.md
- tracing-error/Cargo.toml
- tracing-error/README.md
- tracing-error/src/lib.rs
- **TracedError**: `TracedError`, an error type wrapper that annotates
an error with the current span.
- **SpanTrace**:`SpanTrace::status` method and `SpanTraceStatus` type
for determing whether a `SpanTrace` was successfully captured (#614)
- **SpanTrace**: Made backtrace formatting more consistent with upstream
changes to `std::backtrace` (#584)
> error: prepare to release 0.1.2

- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/tests/filter.rs
Recent changes to `tracing-subscriber` (#580 and #583) introduced some
regressions in filter directive selection. In particular, directive
selection appears to depend on the _order_ in which directives were
specified in a env filter string, or on the order in which they were
added using `add_directive`, rather than on specificity. 
This regression is due to the change that switched the storage of filter
directives in `DirectiveSet`s from a `BTreeSet` to a `Vec`. Previously,
the `DirectiveSet::add` and `DirectiveSet::extend` methods both relied
on the inherent ordering of `BTreeSet`s. After changing to a `Vec`, the
`DirectiveSet::add` method was changed to use a binary search to find
the correct position for each directive, and use `Vec::insert` to add
the directive at that position. This …
> subscriber: fix filter selection regressions

- README.md
- examples/Cargo.toml
- tracing-error/Cargo.toml
- tracing-error/src/layer.rs
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **env-filter**: Regression where filter directives were selected in the order
they were listed, rather than most specific first (#624)
> subscriber: prepare to release 0.2.3

- tracing-error/Cargo.toml
tracing-error's ErrorLayer depends upon subscriber changes that were introduced in tracing "0.1.12" and depending on tracing = "0.1" allows it to select versions that will not compile.
> error: Bump minimum version for tracing dep

- examples/examples/tower-load.rs
I forgot to await the inner future in the `tower-load` which led to the example _not doing anything_. Whoops!
> examples: await inner future

- tracing-subscriber/src/lib.rs
Looks like Clippy is once again complaining about the
`match_wild_err_arm` lint, presumably as a result of the Rust 1.42
release. This lint triggers on the `try_lock!` macro that
`tracing-subscriber` uses to avoid double panics when a mutex is
poisoned. In this case, the lint is something of a false positive here,
since we _do_ actually have two different `Err(...)` arms; the
differentiation between the two arms is not in the match pattern but in
a guard. See https://github.com/rust-lang/rust-clippy/issues/3688 for
details on the lint.
I've refactored the code in question to use `if`/`else`, avoiding the
lint.
> subscriber: fix clippy lints

- tracing-error/src/error.rs
The originally given example for how to use TracedError along side the Error Kind pattern was subtly incorrect. You cannot use a derive macro on the error itself because it needs to forward all implementation other than `backtrace()` to its inner error type, which is not supported by the existing `transparent` attribute of thiserror.
> Fix example of using TracedError with error kind pattern

- tracing-subscriber/src/fmt/fmt_layer.rs
Right now theres a bug where if you have an error layer and a fmt layer, and the error layer is first, the fmt layer will still fmt the args and will end up duplicating the output in the formatted fields.
This change correctly skips formatting fields if the fields already exist in the registry.
> Fix but in new_span for fmt layer

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/err.rs
From #545:
> When using `?` for error handling, trace events on returning an Err need to be handled in the caller explicitly. In a lot of cases I'd rather be lazy and instrument any returned Errs implicitly, in the same span that encompasses the function the Err was returned from.
This adds `#[instrument(err)]`, which instruments returned Errs implicitly. Fixes #545.
> attributes: instrument Err

- .github/workflows/CI.yml
Our CI builds currently have an issue where `cargo hack` doesn't work
after loading a cached build of the tool. This causes builds to fail.
See #648.
This is an admittedly hacky workaround: I've added a step to check if
`cargo hack` exists by running `cargo hack --help`. If this doesn't
succeed, we assume it doesn't exist and forcibly install it from
crates.io.
> ci: add possible workaround for missing cargo-hack

- tracing-subscriber/src/lib.rs
The filter feature has already been removed.
> subscriber: fix outdated documentation

- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/mod.rs
There isn't an actual reason that `fmt::Layer` needs a separate builder
type, since the builder and layer structs are identical and only differ
in what methods they provide. If the methods for configuring a `Layer`
were exposed by the `Layer` type instead, it would be simple to
construct `Layer`s — no need to call `.finish()` on the builder.
This commit moves all the `LayerBuilder` methods to `Layer`, makes
`LayerBuilder` a type alias for `Layer`, and deprecates
`Layer::builder`, the `LayerBuilder` type, and `LayerBuilder::finish()`.
Since nothing has been removed, this shouldn't be a breaking change, but
we can remove the deprecated APIs in 0.3.x.
> subscriber: move `fmt::LayerBuilder` methods to `fmt::Layer`

- tracing-subscriber/src/fmt/fmt_layer.rs
Fix the issue #627 
If the remaining values is not empty I just append a whitespace to format
BTW than you all for your work and tag `Good first issue` ❤️ you build a real opensource project with a real community.
> subscriber: add space when recording new values on an existing span

- tracing-subscriber/src/fmt/format/mod.rs
Currently, a bug exists in the `Compact` tracing-subscriber event
formatter where levels are always displayed, regardless of the value of
`with_level`.
This commit updates the `Compact` formatter to properly check whether
levels should be formatted.
> subscriber: fix Compact formatter not honoring `with_level`

- README.md
- examples/README.md
- examples/examples/all-levels.rs
- examples/examples/async_fn.rs
- examples/examples/attrs-args.rs
- examples/examples/attrs-basic.rs
- examples/examples/custom_error.rs
- examples/examples/echo.rs
- examples/examples/fmt-custom-event.rs
- examples/examples/fmt-custom-field.rs
- examples/examples/fmt-stderr.rs
- examples/examples/fmt.rs
- examples/examples/futures-proxy-server.rs
- examples/examples/hyper-echo.rs
- examples/examples/instrumented_error.rs
- examples/examples/log.rs
- examples/examples/spawny_thing.rs
- examples/examples/tower-client.rs
- examples/examples/tower-load.rs
- examples/examples/tower-server.rs
- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/fmt/time.rs
- tracing-subscriber/src/lib.rs
- tracing-subscriber/src/prelude.rs
- tracing-subscriber/src/util.rs
- tracing-subscriber/tests/utils.rs
Users have said fairly frequently that configuring new subscribers in an
application is unnecessarily verbose and confusing. We should try to
make this nicer, especially as it's a common "on ramp" for new `tracing`
users.
This branch adds new APIs, inspired by `tonic` and `warp`, that should
make setting up a subscriber a little less verbose. This includes:
- Many modules in `tracing-subscriber` now expose free functions 
that construct default instances of various types. This makes 
configuring subscribers using these types more concise, a la `warp`.
- An extension trait for adding `.set_default`, `.init`, and `.try_init` 
methods to subscribers. This generalizes the similar functions on
`fmt`'s `SubscriberBuilder` to work with other subscribers.
All the old APIs are still left as they …
> subscriber: add more ergonomic subscriber configuration APIs

- README.md
- examples/Cargo.toml
- tracing-error/Cargo.toml
- tracing-error/src/layer.rs
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
This release includes several API ergonomics improvements, including shorthand
constructors for many types, and an extension trait for initializing subscribers
using method-chaining style. Additionally, several bugs in less commonly used
`fmt` APIs were fixed.
- **fmt**: Shorthand free functions for constructing most types in `fmt`
(including `tracing_subscriber::fmt()` to return a `SubscriberBuilder`,
`tracing_subscriber::fmt::layer()` to return a format `Layer`, etc) (#660)
- **registry**: Shorthand free function `tracing_subscriber::registry()` to
construct a new registry (#660)
- Added `SubscriberInitExt` extension trait for more ergonomic subscriber
initialization (#660)
- **fmt**: Moved `LayerBuilder` methods to `Layer` (#655)
- **fmt**: `LayerBuilder`, as `Layer` now implements all …
> subscriber: prepare to release 0.2.4

- tracing-subscriber/src/fmt/time.rs
This removes the trailing space from the end of the ChronoUtc FormatTime impl.
I'm pretty sure this is accidental? None of the other FormatTime impls have this there. Not sure if this is considered a breaking change. Hopefully not.
> Remove trailing space in ChronoUtc format_time

- tracing-subscriber/Cargo.toml
Cargo doesn't want to resolve 0.0.9 for tracing-subscriber :(
> subscriber: Bump sharded-slab dependency

- tracing-futures/CHANGELOG.md
- tracing-futures/Cargo.toml
With any luck, this should resolve the docs.rs build failures.
> futures: prepare to release 0.2.4

- tracing/src/subscriber.rs
This makes the user aware of if the guard is dropped immediately and
thus, the tracing does not work.
> Add `must_use` attribute to `set_default`

- tracing-appender/src/lib.rs
- tracing-appender/src/non_blocking.rs
- tracing-appender/src/rolling.rs
Adds documentation for tracing-appender that was added in PR #673 
I still need to fix the way links to structs/methods looks. But the rest of the content is reviewable.
> Add documentation to tracing appender crate

- examples/examples/all-levels.rs
- examples/examples/async_fn.rs
- examples/examples/echo.rs
- examples/examples/fmt-custom-event.rs
- examples/examples/fmt-custom-field.rs
- examples/examples/fmt.rs
- examples/examples/sloggish/sloggish_subscriber.rs
- examples/examples/spawny_thing.rs
- tracing-log/src/env_logger.rs
- tracing-log/src/log_tracer.rs
- tracing-macros/examples/factorial.rs
- tracing-subscriber/benches/fmt.rs
- tracing-subscriber/src/fmt/time.rs
- tracing-tower/src/http.rs
- tracing/src/lib.rs
It looks like Rust 1.43's version of clippy added a new lint for
redundant `use` statements with just a crate name. These are unnecessary
because the root module of an external crate is always available without
imports. Apparently, `tracing-log`, `tracing-subscriber`, `tracing`, and 
`tracing-tower` all had some redundant `use` statements, which clippy now 
warns us about.
This PR removes them.
> chore: remove redundant imports

- tracing-core/src/dispatcher.rs
Follow up of: https://github.com/tokio-rs/tracing/pull/685
> Add `must_use` to `dispatcher::set_default`

- .github/CODEOWNERS
This branch adds a CODEOWNERS file to configure Github to automatically
assign reviewers for pull requests. In general, when a crate or large
subsystem of a crate was contributed by an individual person, we should
use this file to ensure that that person is assigned to review future
changes to that code.
The @tokio-rs/tracing team should still be tagged to approve all pull
requests, in addition to the person who originally contributed the code,
so the CODEOWNERS file ensures this as well.
> chore: Add preliminary CODEOWNERS file

- tracing-appender/Cargo.toml
- tracing-appender/src/non_blocking.rs
- tracing-appender/src/rolling.rs
> Tracing appender tests

- tracing-core/src/field.rs
Currently, the only way to interact with `Value`s is to record them with
a visitor. In the most common case, where typed data is not needed,
`Value`s are recorded with their `fmt::Debug` implementations — a
visitor which does not implement the `record_${TYPE}` traits will
automatically fall back to recording all primitive value types with
`Debug`. However, implementing a visitor requires a bit of boilerplate:
an entire trait implementation has to be written, and a visitor object 
passed to `record`.
This branch hopes to simplify this common case by adding a `Debug` 
implementation to _all_ `dyn Value` trait objects. This is equivalent
to a visitor that only implements `record_debug`, but requiring less
boilerplate.
> core: add `fmt::Debug` impl to `dyn Value`s

- tracing-appender/CHANGELOG.md
- tracing-appender/Cargo.toml
- tracing-appender/src/lib.rs
Following the release process for https://github.com/tokio-rs/tracing/blob/master/CONTRIBUTING.md and these changes are the only things left to commit before release.
I'd like to hopefully get this released today so we can start using this crate internally.
Note:
I need to get PR #703 and PR #678 merged before release.
> Prepare tracing-appender for release

- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/format/json.rs
- tracing-subscriber/src/fmt/format/mod.rs
An issue (#707) currently exists where calling `record` on a span will cause the
JSON formatter in `tracing_subscriber::fmt` to not log any further events that
occur within that span.
This issue results from a combination of two factors:
*  Currently, when formatting the fields on a parent span as JSON, we
return a `fmt::Error`. In this case, we bail from the `format_event`
function, causing us to skip formatting that event entirely. We
don't print anything or panic when this occurs.
* The implementation of `on_record` for `fmt::Layer` simply formats the
new fields and appends them to the previous fields. This doesn't work 
with JSON! The  previous fields will have been recorded as a JSON 
object, like:
```json 
{ "field_1": "value_1" }
```
Appending the new fields will result in a string …
> subscriber: fix `Span::record` resulting in malformed JSON

- tracing-subscriber/tests/filter.rs
This removes the test `field_filter_events` in `tracing-subscriber/tests/filter.rs` as it appears to be a duplicate of `field_filter_events` in `tracing-subscriber/tests/field_filter.rs` (see discussion at https://github.com/tokio-rs/tracing/pull/711#issuecomment-626365124).
> [tracing-subscriber] remove the duplicated test 'field_filter_events'

- examples/Cargo.toml
- examples/examples/opentelemetry.rs
- examples/examples/opentelemetry_remote_context.rs
- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/lib.rs
- tracing-opentelemetry/src/span_ext.rs
The [OpenTelemetry Propagation Spec](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/context/api-propagators.md) has been changed from operating primarily on `SpanContext`s to a more generic `Context` struct which is a propagation mechanism that carries execution-scoped values across API boundaries and between logically associated execution units.
The following APIs are updated to facilitate this change:
* OpenTelemetrySpanExt's `set_parent` now accepts a reference to an  extracted parent context.
* OpenTelemetrySpanExt's `context` now returns a context.
Additionally the need to sample spans before their context can be injected into `Carrier`s necessitates that a `Sampler` is stored in the `OpenTelemetryLayer`. Accordingly:
* …
> tracing_opentelemetry: Switch to `Context` propagation

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
- Support for using `#[instrument]` on methods that are part of
[`async-trait`] trait implementations (#711)
- Optional `#[instrument(err)]` argument to automatically emit an event
if an instrumented function returns `Err` (#637)
Thanks to @ilana and @nightmared for contributing to this release!
[`async-trait`]: https://crates.io/crates/async-trait
> attributes: prepare to release v0.1.8

- tracing-subscriber/src/util.rs
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- **log**: When using the [`log`] compatibility feature alongside a 
`tracing` `Subscriber`, log records for spans now include span IDs
(#613)
- **attributes**: Support for using `#[instrument]` on methods that are
part of [`async-trait`] trait implementations (#711)
- **attributes**: Optional `#[instrument(err)]` argument to 
automatically emit an event if an instrumented function returns 
`Err` (#637) 
- Added `#[must_use]` attribute to the guard returned by
`subscriber::set_default` (#685)
- **log**: Made [`log`] records emitted by spans much less noisy when
span IDs are not available (#613)
- Several typos in the documentation (#656, #710, #715)
Thanks to @FintanH, @shepmaster, @inanna-malick, @zekisharif, @bkchr,
@majecty, @ilana and @nightmared for contributing to this release! …
> tracing: prepare to release 0.1.14

- tracing-core/src/lazy_static/mod.rs
- tracing-core/src/lib.rs
- tracing-macros/examples/factorial.rs
- tracing-macros/src/lib.rs
If it doesn't support pre-1.30 compilers, it's preferable to use `$crate` (it's more simple and powerful): https://doc.rust-lang.org/edition-guide/rust-2018/macros/macro-changes.html#macros-with-crate-prefix
> Replace local_inner_macros with $crate

- README.md
- tracing/src/lib.rs
Adding the crate to the list of community-related crates for `tracing`. 
Happy to provide additional details if needed.
> Add tracing-bunyan-formatter to the list of related crates.

- tracing/src/span.rs
When working with `tracing` I was caught by surprise when trying to record a new field on a span to later find out that the field was completely ignored.
Add a more explicit reference to this behaviour in the documentation of `Span::record` as well as an example.
> [Documentation] Clarify `record` behaviour for new fields

- tracing-opentelemetry/src/layer.rs
Support for translating calls to `Span::follows_from` to OpenTelemetry Links.
> Add on_follows_from to OpenTelemetryLayer

- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/lib.rs
The OpenTelemetry [spec for HTTP server request](https://github.com/open-telemetry/opentelemetry-specification/blob/master/specification/trace/semantic_conventions/http.md#http-server-semantic-conventions) span names states that:
> Given an inbound request for a route (e.g. "/users/:userID?") the name
> attribute of the span SHOULD be set to this route. If the route does not
> include the application root, it SHOULD be prepended to the span name.
However, `tracing` span names must be `'static`, so it is currently not always possible to add this dynamic information.
This patch adds support for setting OpenTelemetry span names by specifying a field named `otel.name` for a given span.
Resolves #720
> opentelemetry: Add dynamic span name field

- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/src/layer.rs
Currently, when converting `log::Record`s to `tracing::Event`s using `tracing-log`, data from `log`'s metadata is converted to special fields prefixed with `log.`, rather than being recorded as `tracing` metadata. In order to properly display this data from `log`, the `tracing-log` crate provides the [`NormalizeMetadata` trait](https://docs.rs/tracing-log/0.1.1/tracing_log/trait.NormalizeEvent.html). `tracing-opentelemetry` does not currently use this, however, and location data from `log` events is treated as a regular field rather than a source code location in OpenTelemetry logs.
Update `tracing-opentelemetry`'s `on_event` implementation to format recorded logs similarly to how `tracing-subscriber::fmt` does. Event metadata is normalized and intermediate `log.` prefixed values are …
> opentelemetry: support `tracing-log` special values

- tracing-opentelemetry/Cargo.toml
Fix broken `homepage` and `repository` links.
> opentelemetry: Fix crate url metadata

- tracing-opentelemetry/src/layer.rs
I use B3Propagator with opentelemetry and when there isn't any headers for B3 propagation it return an empty context and then the `set_parent` method doesn't really check if the context is valid or not. 
I just check if the context is valid. If not I don't put it as parent context for the current span.
> do not add parent context if the context is invalid

- tracing/src/macros.rs
Hello 👋  ! I had some issues playing with tracing and event! macro due to a call to a macro prefixed by `tracing::` so I fixed with `$crate::` like it's done for all other macros :)
> fix macro path

- examples/Cargo.toml
- examples/examples/opentelemetry_remote_context.rs
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/src/layer.rs
Upgrade `opentelemetry` to latest release version
> opentelemetry: Upgrade to opentelemetry v0.6.0

- tracing-subscriber/src/util.rs
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- **macros**: Replaced use of legacy `local_inner_macros` with
`$crate::` (#740)
- Docs fixes and improvements (#742, #731, #730)
Thanks to @bnjjj, @blaenk, and @LukeMathWalker for contributing to this
release!
> tracing: prepare to release 0.1.15

- tracing-appender/src/non_blocking.rs
I was able to reproduce the failures for `logs_dropped_if_lossy` on my machine when usnig loom.
Realized that the Worker calls `recv` and the only time we actually will increment the error_counter is when we have a write blocking on the call to `write_all` (called by the worker) and a messege buffered in NonBlocking crossbeam sender.
I added some sleeps after writes to avoid some races I saw.
For `multi_threaded_writes`, what likely is happening is that sometimes the last thread hasn't had a chance write to the queue, hence we now use recv_timeout instead of try_recv, to ensure  there's more than enough time for the a message to be visible in the channel.
> Fix races in tracing-appender unit tests

- tracing-core/src/callsite.rs
Clippy [now warns us][1] that comparing trait object pointers with
`ptr::eq` is bad, because vtable addresses are not guaranteed to be
unique due to the compiler merging vtables, and vtables for the same
trait impl may have different addresses in different compilation units.
In practice, I don't believe this actually effects `tracing-core`'s use
case for this comparison. Because callsites must be static, the data
component of the trait object wide pointer will always be unique, even
if the compiler merges the vtables for all the identical generated
`Callsite` impls (which it may very well do!).
Although this is probably not an issue in practice, I still thought it
was good to fix the clippy warning, and to be more explicit that it's
the data pointer comparison that's load-bearing here. …
> core: compare `callsite::Identifier` data pointers only

- tracing-appender/src/non_blocking.rs
See #751.
This is a temporary stop-gap solution until we get a better
understanding of what's going on here. I don't want it to block
unrelated changes to other crates in the meantime.
> appender: temporarily ignore flaky test

- tracing-appender/src/non_blocking.rs
- tracing-appender/src/rolling.rs
- tracing-core/src/callsite.rs
* RollingFile currently only supports hourly, daily, and never rotation schedules.
* With services with high TPS (transactions per second), logs fill up quicker and take longer to search through. For this reason, it is helpful to have logs on a more granular level, which is what this change introduces
* Updated documentation to reflect date-time format (yyyy-MM-dd-HH-mm) for clarity since we now have months and minutes
* Added minutely rotation, following the same pattern as other rotation schedules
testing:
* cargo test
> Add Minutely rotation to RollingFile

- examples/examples/tower-load.rs
This fixes a new compiler warning in the `tower-load` example.
> style: fix warning in examples

- tracing/src/macros.rs
- tracing/src/span.rs
This commit fixes up a few new Clippy lints and rustc warnings that
occur with the `log`/`log-always` features enabled.
> tracing: fix warnings with `log`/`log-always` features

- README.md
- examples/Cargo.toml
- tracing-appender/Cargo.toml
- tracing-error/Cargo.toml
- tracing-error/src/layer.rs
- tracing-flame/README.md
- tracing-futures/Cargo.toml
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **fmt**: Fixed an issue in the JSON formatter where using
`Span::record` would result in malformed spans (#709)
> subscriber: prepare to release 0.2.6

- tracing-subscriber/src/lib.rs
The "registry" crate feature is enabled by default but the top-level
documentation implies that it is not.
Minor docs fix to clarify that the registry feature is enabled by default.  The docs are not "wrong" per se, but other crate features indicate that they are enabled by default and the registry feature does not say that, which may lead to confusion (it did for me).
Fix the docs
> docs: update top-level documentation of crate features

- tracing-core/src/lazy_static/core_lazy.rs
- tracing-core/src/lib.rs
- tracing-core/src/spin/mod.rs
- tracing/src/lib.rs
When the following dependencies and their features were specified:
```toml
tracing-core = { version = "0.1", default-features = false, features = ["std"] }
tracing = { version = "0.1", default-features = false }
```
The build would fail with the following error:
```
error[E0412]: cannot find type `Once` in crate `tracing_core`
--> tracing/src/lib.rs:840:35
|
840 |     pub type Once = tracing_core::Once<()>;
|                                   ^^^^ not found in `tracing_core`
|
```
This happened because `tracing-core` exports `Once` only if its `std`
feature is disabled. And the depending `tracing` crate assumed that if
its `std` feature was disabled, so would be the `std` feature in
`tracing-core`.
This is a violation of the [undocumented "features must be additive"
guideline][ag]. In …
> Adjust Once to not violate feature additivity principle

- tracing-flame/src/lib.rs
These ended up being useful when trialing `tracing-flame` on `zebra`. By default most of the traces were coming from idle code where no spans were open, and because the codebase is all async the graph was basically split into 8ths, one for each thread, with the work evenly distributed across all threads.
With the collapse threads config setting you can combine all the events into a single flamegraph which gives a better picture of whats happening overall, and with the filter-empty you can remove a large amount of useless information that can shrink the size of the rest of the flame graph causing otherwise important spans to be hidden.
> add support for filtering and collapsing flamegraphs

- tracing-opentelemetry/src/layer.rs
Perform read-only operations before getting write-access to avoid a deadlock when recording an object that holds a SpanTrace on the event.
Mitigation for https://github.com/tokio-rs/tracing/issues/763
> Prevent deadlock panic when using OpenTelemetryLayer with SpanTrace

- examples/examples/tower-client.rs
- examples/examples/tower-load.rs
- examples/examples/tower-server.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/time.rs
Currently, the default formatter implementations in
`tracing-subscriber`'s `fmt` module do not handle explicitly set parent
spans for events, such as
```rust
let span = tracing::info_span!("some_interesting_span");
tracing::info!(parent: &span, "something is happening!");
```
Instead, when formatting the span context of an event, the context is
_always_ generated from the current span, even when the event has an
overridden parent. This is not correct.
This branch changes the default context formatters to use the explicit
parent ID, if it is present. Otherwise, the contexual parent is used, as
it was previously.
I've also added tests ensuring that this works correctly, and removed
some workarounds for the previous incorrect behavior from the examples.
Fixes #766 …
> subscriber: handle explicit event parents properly in formatters

- tracing-core/src/span.rs
Consumers of the crate should be able to handle the 0 case separately and avoiding panicking within `Id::from_u64`.
Expose direct conversion between the inner type.
> Add conversion between `span::Id` and `NonZeroU64`

- Cargo.toml
- README.md
- examples/Cargo.toml
- examples/README.md
- examples/examples/journald.rs
- tracing-journald/Cargo.toml
- tracing-journald/README.md
- tracing-journald/src/lib.rs
Support for writing tracing-based logs directly to their standard destination while preserving both standard and custom metadata on Linux systems. Improves usability of Linux services and for Linux applications executing outside of a terminal.
It turns out [journald's native protocol](https://www.freedesktop.org/wiki/Software/systemd/export/) is very simple and spoken over a Unix datagram socket at a fixed location (see [discussion of stability of these interfaces](https://systemd-devel.freedesktop.narkive.com/i5tlUyjz/client-logging-to-journald-without-libsystemd-journal-so#post6)), allowing high quality native support with ~100LoC.
I'm particularly interested in feedback on a few of the compromises made in this draft:
- [The documentation for the upstream …
> journald: add `tracing-journald` crate implementing a simple journald layer

- tracing-core/src/dispatcher.rs
- tracing-core/src/field.rs
- tracing-core/src/span.rs
- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/registry/mod.rs
PR #769 was merged with some incorrect docs formatting due to
incorrect HTML that resulted from overzealous find-and-replace
misuse. See https://github.com/tokio-rs/tracing/pull/769#pullrequestreview-439416330
This PR un-splodes it.
> docs: fix "sploded" formatting

- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/mod.rs
EDIT: thanks to @hawkw’s help this now actually is a pull request :-)
This is not really a pull request, more a hack that demonstrates the question I’d like to ask. Currently there is no subscriber that comes out of the box that will print information about spans. I find the concept quite useful and instrumented some code that does database queries in order to print out how long things take as well as tracing the execution (i.e. each span is doubling as a log statement of the same level). Example output looks like the following:
There is an ugly hack in the code to get the fields of the recently closed span into the output, and the output is generated using an even uglier hack by faking an event, but I hope that this still makes it sufficiently clear what I am trying to do.
There has been …
> print spans on close

- examples/Cargo.toml
- tracing-appender/Cargo.toml
- tracing-error/Cargo.toml
- tracing-error/src/layer.rs
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **parking_lot**: Updated the optional `parking_lot` dependency to
accept the latest `parking_lot` version (#774)
- **fmt**: Fixed events with explicitly overridden parent spans being
formatted  as though they were children of the current span (#767)
- **fmt**: Added the option to print synthesized events when spans are
created, entered, exited, and closed, including span durations (#761)
- Documentation clarification and improvement (#762, #769)
Thanks to @rkuhn, @greenwoodcm, and @Ralith for contributing to this
release!
> subscriber: prepare to release 0.2.7 (July 1, 2020)

- tracing-appender/Cargo.toml
This resolves https://github.com/tokio-rs/tracing/issues/777.
> appender: reduce tracing-subscriber's required features to `fmt`

- tracing/src/lib.rs
- tracing/src/macros.rs
Resolves https://github.com/tokio-rs/tracing/issues/783.
> tracing: attempt to monomorphize is_enabled call

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
- Support for arbitrary expressions as fields in `#[instrument]` (#672)
- `#[instrument]` now emits a compiler warning when ignoring 
unrecognized input (#672, #786)
Fixes #785
> attributes: prepare to release 0.1.9

- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/lib.rs
- tracing/Cargo.toml
- Replaced use of `inner_local_macros` with `$crate::` (#729)
- `must_use` warning to guards returned by `dispatcher::set_default`
(#686)
- `fmt::Debug` impl to `dyn Value`s (#696)
- Functions to convert between `span::Id` and `NonZeroU64` (#770)
- More obvious warnings in documentation (#769)
- Compiler error when `tracing-core/std` feature is enabled but
`tracing/std` is not (#760)
- Clippy warning on vtable address comparison in `callsite::Identifier`
(#749)
- Documentation formatting issues (#715, #771)
Thanks to @bkchr, @majecty, @taiki-e, @nagisa, and @nvzqz for
> core: prepare to release 0.1.11

- tracing-subscriber/src/util.rs
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- **attributes**: Support for arbitrary expressions as fields in
`#[instrument]` (#672)
- **attributes**: `#[instrument]` now emits a compiler warning when
ignoring unrecognized input (#672, #786)
- Improved documentation on using `tracing` in async code (#769)
- Updated `tracing-core` dependency to 0.1.11
- **macros**: Excessive monomorphization in macros, which could lead to
longer compilation times (#787)
- **log**: Compiler warnings in macros when `log` or `log-always` features
are enabled (#753)
- Compiler error when `tracing-core/std` feature is enabled but
`tracing/std` is not (#760)
Thanks to @nagisa, and everyone who contributed to the new `tracing-core`
and `tracing-attributes` versions, for contributing to this release!
> tracing: prepare to release 0.1.16

- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/format/json.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/mod.rs
Fixes: #704
Nested spans are not available in json formatter
I added a field `spans` in the json, with an array of the nested spans. I reused the span representation from the existing `span`, and pushed all the span representation in a `vec` using `ctx.visit_spans`. I didn't remove the `span` field as it can be useful to have direct access to the current span
> subscriber: add nested spans in json formatter

- examples/Cargo.toml
- tracing-log/Cargo.toml
The usage of the older version prevents crates from using newer `env_logger` versions, as they aren't compatible with each other during compilation.
Move to `env_logger@0.7`
> chore(deps): update env_logger dependency

- examples/Cargo.toml
`examples` is actually not a valid crate identifier. This prevents dependabot from working correctly.
> chore(crates): rename examples crate

- tracing/src/macros.rs
This commit fixes name clashes that occurred inside of tracing macros when values with the names `display, Value and debug` have been used.
This allows library users to trace variables that have the same name as imported types inside the `tracing::field` module.
Use fully qualified type names for types used inside the `tracing::field` module.
Fixes #805.
> tracing: fix name clash inside of tracing macros

- examples/Cargo.toml
These deps have been unused since the tracing-flame / inferno example removed the custom error handling logic in favor of unwraps.
> remove unused dependencies

- examples/examples/thread-info.rs
- examples/examples/thread_info.rs
- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/format/json.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/mod.rs
Fixes #809 
This PR adds two new methods i.e `with_thread_ids` and
`with_thread_names` to the fmt Layer which passed till
the pre-configured Format type, where the check is performed
and these the above values are formatted based on the flags.
The formatting is done by creating to new Types that impl Display
for Id and Name. For Thread Name, we keep track of the max length
of the thread name that occured till now using a thread safe static
type and pad accordingly. For Thread Id, we pad directly with 2
as in most cases we would see a double digit number of threads.
Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>
> Allow thread name and id to be displayed in traces

- examples/Cargo.toml
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **fmt**: When the `chrono` dependency is enabled, the `SystemTime`
timestamp now emits human-readable timestamps rather than using
`SystemTime`'s fmt::Debug`implementation (`chrono` is still required
for customized timestamp formatting) (#807)
- **ansi**: Updated `ansi_term` dependency to 0.12 (#816)
- **json**: `with_span_list` method to configure the JSON formatter to
include a list of all spans in the current trace in formatting events
(similarly to the text formatter) (#741)
- **json**: `with_current_span` method to configure the JSON formatter
to include a field for the _current_ span (the leaf of the trace) in
formatted events (#741)
- **fmt**: `with_thread_names` and `with_thread_ids` methods to
configure `fmt::Subscriber`s and `fmt::Layer`s to include the thread
name and/or …
> subscriber: prepare to release 0.2.8

- tracing-appender/CHANGELOG.md
- tracing-appender/Cargo.toml
- tracing-appender/README.md
- tracing-appender/src/lib.rs
- **rolling**: `minutely` rotation schedule to rotate the log file once
every minute (#748)
- Fixed broken links in docs (#718)
- `tracing-appender` now only enables the necessary
`tracing-subscriber`'s feature flags, rather than all of them (#779)
Thanks to new contributors @ericjheinz and @sourcefrog for contributing
> appender: prepare to release 0.1.1

- tracing/src/macros.rs
This reverts commit e3b3a3acb14141c3f5b72dad6dc45080fdfa0d5d.
This change was accidentally semver-incompatible, as user code was able
to use the imported `debug` and `display` functions without adding an
import outside the macro. Although this was not documented, downstream
code relied on these names being available, so this resulted in a
breaking change in a point release.
Fixes #820
> tracing: Revert "tracing: fix name clash inside of tracing macros (#806)"

- tracing/src/lib.rs
- tracing/src/span.rs
- tracing/test-log-support/tests/span_activity_filtered_separately.rs
- tracing/test-log-support/tests/span_lifecycle_can_be_enabled.rs
- tracing/test-log-support/tests/span_lifecycle_is_trace.rs
Currently, `tracing`'s `log` feature emits log records for creating,
entering, exiting, and dropping a `Span` at the `log` equivalent of that
span's `tracing` level. If the span has any fields, the span creation
logs are sent to the same target that the span would have, since the
fields provide high-value information that users enabling that target
will probably want to see. However, the other events for entering,
exiting, and dropping a span do not include fields, and are much more
verbose, so they are sent to a special `tracing::span` target. This
allows them to be filtered independently, and only enabled when needed.
However, some `log` users have noted that when using _blanket_ `log`
filters, like setting the level to `info` globally, the more verbose
activity logs will still be …
> log: make span enter/exit targets always TRACE

- tracing-subscriber/src/fmt/fmt_layer.rs
Currently, `fmt::FmtContext` _only_ exposes a way to iterate over all
spans in the current context. It doesn't publicly expose any of the
other `layer::Context` methods, although they provide more useful
querying functionality.
The in-crate implementations of the default formatters _do_ use some of
these other methods on `Context`, by accessing the private `Context`
field on `FmtContext`. Not having access to these methods externally
makes many `FormatEvent` implementations in other crates more difficult,
if not impossible.
This branch adds forwarding impls of the missing methods.
> subscriber: add missing `Context` methods to `FmtContext`

- tracing/src/macros.rs
- tracing/test-log-support/tests/log_no_trace.rs
When the `log` feature is enabled, the expressions provided for field
values are passed into two separate macros: one which prepares the
`tracing` structured value set that is used to construct the `tracing`
event, and another which formats a textual message to send to `log`, if
emitting a `log` record for the event is enabled. The issue is that the
macro that generates the `tracing` value set generates a block
containing an import for `tracing::field::debug` and
`tracing::field::display`, while the block generated by the `log`
message formatting macro does not import those functions. Therefore, the
block where the `log` message is formatted fails to compile, since the
functions are not present in the scope it expands to.
It turns out this is not, in fact, an accidental breaking change in …
> tracing: fix missing `debug`/`display` with `log`

- tracing-subscriber/src/util.rs
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- **log**: Moved verbose span enter/exit log records to
"tracing::span::active" target, allowing them to be filtered
separately (#833)
- **log**: All span lifecycle log records without fields now have the
`Trace` log filter, to guard against `log` users enabling them by
default with blanket level filtering (#833)
- **log**/**macros**: Fixed missing implicit imports of the
`tracing::field::debug` and `tracing::field::display` functions inside
the macros when the "log" feature is enabled (#835)
> tracing: prepare to release 0.1.17

- tracing-subscriber/src/fmt/time/datetime.rs
The datetime implementation added in 0.2.8 uses `i64::MAX` and
`i32::MAX`, which were added in Rust 1.43.0. This is not compliant with
our current MSRV, 1.39.
This PR fixes this by switching to `std::i64::MAX` and `std::i32::MAX`.
Fixes #840
> subscriber: use MSRV-compliant forms of `{integer}::MAX`

- tracing-appender/LICENSE
- tracing-attributes/LICENSE
- tracing-error/LICENSE
- tracing-flame/LICENSE
- tracing-futures/LICENSE
- tracing-journald/LICENSE
- tracing-log/LICENSE
- tracing-macros/LICENSE
- tracing-opentelemetry/LICENSE
- tracing-serde/LICENSE
- tracing-subscriber/LICENSE
- tracing-tower/LICENSE
- tracing/LICENSE
The MIT license states:
> The above copyright notice and this permission notice
> shall be included in all copies or substantial portions
> of the Software.
Therefore the LICENSE files should be present in each crate directory,
so they are included with `cargo publish`.
> Include the LICENSE in every crate

- examples/Cargo.toml
- tracing-error/src/layer.rs
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **fmt**: Fixed compilation failure on MSRV when the `chrono` feature
is disabled (#844)
- **fmt**: Span lookup methods defined by `layer::Context` are now also
provided by `FmtContext` (#834)
> subscriber: prepare to release 0.2.9

- CONTRIBUTING.md
The pull request template link was not pointing to the pull request template.
Give the issue template and pull request template links different names.
> docs: fix broken link in `CONTRIBUTING.md`

- README.md
some of the links in the readme don't work or go to the wrong targets
* the `closing` link needs another `tracing/` in the path
* the `#[instrument]` link apparently can't have `#[ ]`
* `tracing-core` shouldn't be another link to `tracing`
* avoid duplicate link targets for contained crates
> tracing: fix doc links in README

- tracing-core/src/dispatcher.rs
- tracing/src/dispatcher.rs
The `experimental-tracing` feature flag only existed in tokio 0.1.x and is no longer necessary in tokio 0.2.x
> docs: Remove reference to old tokio feature flag `experimental-tracing`

- tracing-subscriber/src/filter/mod.rs
- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/writer.rs
- tracing-subscriber/src/layer.rs
- tracing-subscriber/src/registry/mod.rs
- tracing-subscriber/src/registry/sharded.rs
This PR resolves two issues.
Here are a few examples:
- https://docs.rs/tracing-subscriber/0.2.9/tracing_subscriber/layer/trait.Layer.html
- https://docs.rs/tracing-subscriber/0.2.9/tracing_subscriber/layer/struct.Context.html#method.scope
- https://docs.rs/tracing-subscriber/0.2.9/tracing_subscriber/registry/trait.LookupSpan.html
Most of the incorrectly rendered document occurred due to a missing closing tag.
I think I've gotten _most_ of them, but I'm not entirely sure. This is due to two reasons:
- `cargo-deadlinks` returns false positives.
- `MakeWriter` [appears twice](https://docs.rs/tracing-subscriber/0.2.9/tracing_subscriber/?search=MakeWriter) due to  `#[doc(inline)]` in [`tracing_subscriber/fmt/mod.rs`](https://github.com/tokio-rs/tracing/blob/master/tracing-subscriber/src/fmt/mo …
> subscriber: Fix Incorrectly Rendered Documenation and Broken Links

- README.md
- examples/README.md
- examples/examples/attrs-literal-field-names.rs
- tracing/src/lib.rs
- tracing/src/macros.rs
- tracing/tests/macros.rs
This permits : in field names but also potentially anything
stringifiable, which may be overly liberal.
Signed-off-by: Robert Collins <robert.collins@cognite.com>
Some opentracing systems use fields with : in the names, which are not legal rust identifiers. We could special case :, but then we have complicated double-nested patterns (repeated idents separated by : and a nested repeat separated by .), and this may by a case of always being one-step-behind as more cases turn up; so this patch instead just gets in front and lets users put in whatever they want: as they are not rust identifiers, they miss out on some niceness.
> Support literals for field names.

- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/src/callsite.rs
- tracing-core/src/dispatcher.rs
- tracing-core/src/lib.rs
- tracing-core/src/metadata.rs
- tracing-core/src/subscriber.rs
- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/filter/env/mod.rs
- tracing-subscriber/src/filter/level.rs
- tracing-subscriber/src/layer.rs
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/src/level_filters.rs
- tracing/src/macros.rs
- tracing/test_static_max_level_features/tests/test.rs
Tracing currently stores cached filter evaluations in a per-callsite
cache. Once filters have been evaluated, this allows us to skip disabled
callsites with a single load and compare, which is a nice fast path for
skipping. However, determining the value to store in the callsite cache
is expensive: it requires acquiring a lock to register the callsite, and
asking the subscriber for an `Interest` value to cache.
In long-running applications, such as servers, daemons, and interactive
applications that are used for a long period of time, this cost is not
very visible; it's amortized over the rest of the application's
lifetime. However, in batch-oriented programs and CLI tools that run to
completion, the cost of building the initial cached value has a much
bigger impact. If a given callsite …
> core: add faster fast path for level filtering

- examples/Cargo.toml
- examples/examples/opentelemetry-remote-context.rs
- examples/examples/opentelemetry.rs
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/span_ext.rs
Upgrade `opentelemetry` to latest release version, updating some names in accordance with spec changes.
Resolves #797
> opentelemetry: Upgrade to opentelemetry v0.7.0

- tracing/src/macros.rs
This PR removes the `dispatcher::has_been_set` check from the
`level_enabled!` macro. We now check the static max level prior to
checking anything else, which avoids any atomic loads for callsites
disabled by the static max level. Also, checking the value of
`LevelFilter::current` should now be essentially equivalent to the
`dispatcher::has_been_set` check, since the default global max
`LevelFilter` is `OFF` when no dispatcher has been set. This means that
rather than doing *two* memory accesses if a callsite is disabled by the
global max level (one for the dispatcher set flag, and one for the max
level), we only do one memory access.
The `has_been_set` flag is also consumed by the `log` integration, for
determining whether to emit `log` records if "log-always" is not
enabled. We *could* …
> tracing: remove `dispatcher::has_been_set` check in macros

- tracing/src/macros.rs
- tracing/src/span.rs
In `tracing/macros.rs` `tracing_log!()` computes whether to log
differently from the log crate.
While the log crate checks for `lvl <= log::STATIC_MAX_LEVEL && lvl <=
log::max_level()`, tracing instead checks for `lvl <=
log::STATIC_MAX_LEVEL` and later the output of `logger.enabled()`. This
causes differences in what is being logged including unexpected log
output.
Since most of our testing has been with `env_logger`, we missed this
issue, since `env_logger` will also return `false` from its `enabled`
method for any records below the max level. However, other loggers may
not. Also, `enabled` is more expensive than checking the max level, so
this should result in better filtering performance for `log` records
emitted by tracing.
This commit...fixes that.
Fixes #856 …
> tracing: make the "log" feature honor `log`'s max level

- README.md
- tracing-core/CHANGELOG.md
- tracing-core/README.md
- tracing-core/src/lib.rs
- `LevelFilter` type and `LevelFilter::current()` for returning the
highest level that any subscriber will enable (#853)
- `Subscriber::max_level_hint` optional trait method, for setting the
value returned by `LevelFilter::current()` (#853)
- **docs**: Removed outdated reference to a Tokio API that no longer exists
(#857)
Thanks to new contributor @dignati for contributing to this release!
> core: prepare to release 0.1.12

- tracing/src/lib.rs
- tracing/src/macros.rs
Currently, every `tracing` macro generates a _new implementation_ of the
`Callsite` trait for a zero-sized struct created for that particular
callsite. This callsite accesses several statics defined in the macro
expansion.
This means that each tracing macro expands to a _lot_ of code — check
out the `cargo expand` output:
```
eliza on butterfly in tracing/examples on  master [$?] is v0.0.0 via ⚙️ v1.44.0
:; cargo expand --example all-levels | wc -l
Checking tracing-examples v0.0.0 (/home/eliza/code/tracing/examples)
Finished check [unoptimized + debuginfo] target(s) in 0.20s
463
```
More code in the macro expansion means more code in the function
*invoking* the macro, which may make that function harder for `rustc` to
optimize. This effects the performance of *other* code in the …
> tracing: move macro callsite impls out of macro expansion

- examples/Cargo.toml
- tracing-error/src/layer.rs
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
Fixed
- **docs**: Incorrect formatting (#862)
Changed
- **filter**: `LevelFilter` is now a re-export of the
`tracing_core::LevelFilter` type, it can now be used interchangably
with the versions in `tracing` and `tracing-core` (#853)
- **filter**: Significant performance improvements when comparing
`LevelFilter`s  and `Level`s (#853)
- Updated the minimum `tracing-core` dependency to 0.1.12 (#853)
Added
- **filter**: `LevelFilter` and `EnvFilter` now participate in
`tracing-core`'s max level hinting, improving performance
significantly in some use cases where levels are disabled globally
(#853)
> subscriber: prepare to release 0.2.10

- tracing-macros/Cargo.toml
- tracing-macros/src/lib.rs
The `tracing-macros` crate uses internal `tracing` APIs that are
unstable. These APIs changed in 0.1.18 (not a breaking change, since
they are explicitly not stable API). `tracing-macros` needed to be
updated to use the new versions of the internal APIs.
As a side note, I'm surprised this wasn't caught before merging the
branch, and only happened on `master`. Are we not checking all crates
for PR builds? If so, we should probably fix that.
> macros: fix breakage in experimental `tracing-macros` crate

- tracing/src/lib.rs
I wasn't able to reproduce the exact formatting issues seen on docs.rs locally, though from some source inspection, this extra `</div>` appears to be the culprit.
(hopefully) fixes #880
> Fix broken tracing documentation formatting

- tracing-opentelemetry/src/lib.rs
This branch adds crate-level docs for the otel trace semantic conventions and their usage as well as notes on stability status.
Resolves #747
> opentelemetry: Add semantic convention docs

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
Changelog: 
- Upgrade to `v0.7.0` of `opentelemetry` (#867) 
For list of breaking changes in OpenTelemetry, see the [v0.7.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/master/CHANGELOG.md#v070).
> opentelemetry: prepare for v0.6.0 release

- tracing-core/src/field.rs
Fix #874 by implementing `std::fmt::Display` for `DisplayValue`.
Fixes: #874
> core: Implement Display for DisplayValue

- README.md
- tracing-core/CHANGELOG.md
- tracing-core/README.md
- tracing-core/src/lib.rs
- Missing `fmt::Display` impl for `field::DisplayValue` causing a
compilation failure when the "log" feature is enabled (#887)
Thanks to @d-e-s-o for contributing to this release!
> core: prepare to release 0.1.13

- README.md
I spent quite a large portion of my talk at Rusty days discussing logging/structured logging/distributed tracing, covering our usage of `tracing`. 
If you think it's relevant I'd be happy to add it to the list :grin: 
P.S. there were some trailing whitespaces that my VIM setup ruthlessly eliminated. Let me know if you want me to leave them there.
> Add Rusty Days talk

- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/lib.rs
Some distributed tracing providers use information such as the span kind to enrich their UIs. The issue https://github.com/frigus02/opentelemetry-application-insights/issues/5 shows an example with Azure Application Insights, which builds an application map based on client/server spans sent from multiple applications.
In order to make use of this with a combination of this `tracing` crate, together with OpenTelemetry exporters, we need a way of setting the span kind through the OpenTelemetry layer.
This solves the issue by adding support for the special attribute `otel.kind` to the OpenTelemetry layer. If set to `SERVER`, `CLIENT`, `PRODUCER`, `CONSUMER` or `INTERNAL` it sets the span kind of the internal OpenTelemetry span.
This follows the convention introduced with the `otel.name` …
> opentelemetry: set span kind through otel.kind

- tracing-attributes/src/lib.rs
Not found in documentation how to change generated span name name, only in sources, then i found issue #725 
Documentation added
> Docs for instrument(name)

- tracing/src/lib.rs
Fix docs typo surrounding 'log-always' usage
> Fix docs typo surrounding 'log-always' usage

- tracing-subscriber/Cargo.toml
The regex dependency is used only to parse configuration directives, and
therefore is not performance critical.  This change turns off all default
features (except 'std') from regex in order to optimize for compile times for
this non-performance-critical code.
Note that due to the presence of the 'criterion' dependency (which has its own
default-features dependency on regex), the tests do not normally run with only
the minimal set of regex features. I did remove the criterion dependency to
verify that tests build, but I'm not sure how to test that we're not using
disabled regex features on an ongoing basis.
> subscriber: disable regex dependency default features

- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/mod.rs
This fixes an issue with `EnvFilter`'s `max_level_hint` not considering
that span field value filters may enable *any* span, regardless of the
level enabled inside that span. This is because the field value must be
recorded to be known.
We may wish to change this behavior to only check spans up to the
selected level, but this isn't what it does currently. This branch fixes
the wrong max level hint.
This bug was not caught due to an issue where hinting was too permissive
(#906), but fixing that bug uncovers this issue. A subsequent PR fixing
hint calculation introduces new test failures without this change.
> subscriber: fix level hint not considering value filters

- tracing-core/src/callsite.rs
- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/mod.rs
- tracing/tests/max_level_hint.rs
- tracing/tests/multiple_max_level_hints.rs
- tracing/tests/support/subscriber.rs
Currently, when rebuilding the interest cache, the max level is
calculated by tracking a max level, and comparing it with each active
`Subscriber`'s max level hint, and setting the max value to the hint if
the hint is higher than the current value.
This is correct. However, the max level in this calculation starts at
`TRACE`. This means that regardless of what any subscriber returns for
its hint, after rebuilding the interest cache, the max level will
*always* be `TRACE`. This is wrong — it means that the fast path will
not be taken in may cases where it *should* be.
The max level calculation was started at `TRACE` rather than `OFF`,
because when this code was written with it starting at `OFF`, all the
tests broke, because the test subscribers don't provide hints. This was
the incorrect …
> core: fix incorrect max level filter calculation

- README.md
- tracing-appender/README.md
- tracing-attributes/README.md
- tracing-core/README.md
- tracing-error/README.md
- tracing-flame/README.md
- tracing-futures/README.md
- tracing-journald/README.md
- tracing-log/README.md
- tracing-opentelemetry/README.md
- tracing-serde/README.md
- tracing/README.md
This puts the splash SVG in every crate's README, so
that it will be rendered on crates.io.
I also changed the link to an absolute URL, to ensure that
it works even outside of the repo.
> docs: put splash graphic in all READMEs

- README.md
- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/lib.rs
- Incorrect calculation of global max level filter which could result in
fast filtering paths not being taken (#908)
> core: prepare to release 0.1.14

- README.md
- tracing-appender/README.md
- tracing-attributes/README.md
- tracing-core/README.md
- tracing-error/README.md
- tracing-flame/README.md
- tracing-futures/README.md
- tracing-journald/README.md
- tracing-log/README.md
- tracing-opentelemetry/README.md
- tracing-serde/README.md
- tracing-subscriber/README.md
- tracing/README.md
Somehow a single line of whitespace is load-bearing I guess? MARKDOWN!
> docs: fix broken splash graphic link

- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/registry/sharded.rs
- tracing-subscriber/src/registry/stack.rs
- tracing-subscriber/tests/registry_with_subscriber.rs
Fixes part of #898 where creating multiple registries made them fight over the thread_local-stored span stacks.
Use the `thread_local` crate which has a tighter scope.
I believe @hawkw has a test that fails without this PR.
> Use the thread_local crate allowing multiple registries

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
- tracing/Cargo.toml
Added
- Support for using `self` in field expressions when instrumenting
`async-trait` functions (#875)
- Several documentation improvements (#832, #897, #911, #913)
Thanks to @anton-dutov and @nightmared for contributing to this release!
> attributes: prepare to release 0.1.10

- tracing-macros/Cargo.toml
- tracing-subscriber/src/util.rs
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- Updated `tracing-core` to fix incorrect calculation of the global max
level filter (#908)
- **attributes**: Support for using `self` in field expressions when
instrumenting `async-trait` functions (#875)
- Several documentation improvements (#832, #881, #896, #897, #911,
#913)
Thanks to @anton-dutov, @nightmared, @mystor, and @toshokan for
contributing to  this release!
> tracing: prepare to release 0.1.19

- examples/Cargo.toml
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **env-filter**: Incorrect max level hint when filters involving span
field values are in use (#907)
- **registry**: Fixed inconsistent span stacks when multiple registries
are in use on the same thread (#901)
- **env-filter**: `regex` dependency enables fewer unused feature flags
(#899)
Thanks to @bdonlan and @jeromegn for contributing to this release!
> subscriber: prepare to release 0.2.11

- tracing/src/dispatcher.rs
Newlines in `<code>` blocks are displayed, resulting in a newline before the closing parentheses.
> Docs: Fix newline in dispatcher note

- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/mod.rs
If you have a `Level` and want to set a directive for `EnvFilter` you need to do the mechanical transformation of: `     .add_directive(LevelFilter::from_level(log_lvl).into())`. To me, it wasn't obvious initially that this was even possible, I had to look through the docs for two different tracing repos to find that the pathway would work. 
If this implementation is added, the definition will be shown on the `Directive` docs page, and you can write `.add_directive(Level::INFO.into())` and skip the intermediate transformation
There was some discussion on discord about this, if it's not desirable because of other reasons feel free to close
> subscriber: adds From<Level> for Directive

- tracing/tests/multiple_max_level_hints.rs
- tracing/tests/support/subscriber.rs
The test-support mock subscribers currently `println!` a bunch of
debugging output. The debugging output is displayed if the test panics,
or if the test is run with `--nocapture`. This can be useful for
figuring out what went wrong if a test fails.
In some cases, tests involve multiple subscribers, to test behavior that
results from interactions between subscribers. In this case, there's no
way to tell which subscriber in the test the debug output came from.
Similarly, if a bunch of tests are run at the same time with
`--nocapture`, output from different test threads are interleaved,
making it impossible to interpret.
This branch adds names to the mock subscribers, which are prepended to
their debugging output.
By default, the mock subscriber's name is the  name of the test …
> test: add nicer debug output to mock subscribers

- tracing-core/src/callsite.rs
- tracing-core/src/subscriber.rs
- tracing-subscriber/src/filter/env/mod.rs
- tracing/tests/filters_dont_leak.rs
Currently, when multiple subscribers are in use, the way that `Interest`
values are combined results in surprising behavior. 
If _any_ subscriber returns `Interest::always` for a callsite, that
interest currently takes priority over any other `Interest`s. This means
that if two threads have separate subscribers, one of which enables a
callsite `always`, and the other `never`, _both_ subscribers will always
record that callsite, without the option to disable it. This is not
quite right. Instead, we should check whether the current subscriber
will enable that callsite in this case.
This branch changes the rules for combining `Interest`s so that `always`
is only returned if _both_ `Interest`s are `always`. If only _one_ is
`always`, the combined interest is now `sometimes`, instead. This …
> core: change `Interest`-combining to play nicer with multiple subscribers

- tracing-core/src/callsite.rs
- tracing-core/src/subscriber.rs
- tracing-subscriber/src/filter/env/mod.rs
- tracing/tests/filters_dont_leak.rs
Currently, when multiple subscribers are in use, the way that `Interest`
values are combined results in surprising behavior. 
If _any_ subscriber returns `Interest::always` for a callsite, that
interest currently takes priority over any other `Interest`s. This means
that if two threads have separate subscribers, one of which enables a
callsite `always`, and the other `never`, _both_ subscribers will always
record that callsite, without the option to disable it. This is not
quite right. Instead, we should check whether the current subscriber
will enable that callsite in this case.
This issue is described in #902. 
This branch changes the rules for combining `Interest`s so that `always`
is only returned if _both_ `Interest`s are `always`. If only _one_ is
`always`, the combined interest is …
> core: change `Interest`-combining to play nicer with multiple subscribers 

- examples/README.md
- examples/examples/toggle-layers.rs
- tracing-subscriber/src/layer.rs
Fixes #894
This PR implements Layer for Option, allowing users to wrap a Layer with
an Option, allowing it to be passed internally wherever Layer is used
there by allowing by allowing layers to be enabled or disabled.
Using this with `reload` further allows a Layer to be dynamically
toggled based by using `handle.modify`
This PR also consists of a basic example.
Signed-off-by: Tarun Pothulapati <tarunpothulapati@outlook.com>
> Impl `Layer` for `Option<T:Layer>`

- tracing-attributes/Cargo.toml
This PR removes the "derive" feature, which is not used.
The "extra-traits" flag could be eliminated, but at the cost of removing `Debug` implementations for a few structs.
> attributes: remove unnecessary syn features

- examples/Cargo.toml
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/src/layer.rs
I'm running into version conflicts in a project of mine, and changes are minor. Some traits/enums were moved into the `sdk` module. See https://github.com/open-telemetry/opentelemetry-rust/blob/master/CHANGELOG.md#v080 for more info.
Bump the versions and rename the traits/enums.
> Bump to opentelemetry:0.8, opentelemetry-jaeger:0.7

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
Changelog:
- Upgrade to `v0.8.0` of `opentelemetry` (#932)
For list of breaking changes in OpenTelemetry, see the [v0.8.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/master/CHANGELOG.md#v080).
> opentelemetry: prepare for v0.7.0 release

- examples/Cargo.toml
- tracing-attributes/src/lib.rs
This branch contains two commits that fix MSRV issues.
* **attributes: remove use of non-MSRV-compliant `Option::flatten`**
PR #875 added code to `tracing-attributes` that uses
`Option::flatten`, which was only added to the standard library in
Rust 1.40. This broke our MSRV, but we missed it because the MSRV CI
checks weren't working correctly (fixed in #934).
This commit removes the use of `Option::flatten`, and replaces it with
a manual implementation. It's a little less pretty, but it builds on
our MSRV (1.39.0).
Once this merges, we'll publish a new `tracing-attributes` version,
and yank 0.1.10.
* **examples: disable `opentelemetry`'s default features**
The `opentelemetry` crate depends on `prometheus`, which depends on
`protobuf`, a crate which doesn't compile on our MSRV (Rust …
> chore: fix MSRV breakage

- .github/workflows/CI.yml
The current MSRV check is lazybones, it's meaningless unless we override toolchain. Actually, we cannot compile tracing crates with 1.39.0, it should work with 1.44.0 or later because of the `protobuf` crate and others.
This enforces to override toolchain and updates MSRV to 1.44.0, this should compile all the crates fine.
And replaces `actions/checkout@master` with `main` as they've renamed the default branch name to `main`.
> chore: correct the MSRV check

- README.md
- tracing-appender/README.md
- tracing-appender/src/lib.rs
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
- tracing-core/README.md
- tracing-core/src/lib.rs
- tracing-error/README.md
- tracing-error/src/lib.rs
- tracing-flame/README.md
- tracing-flame/src/lib.rs
- tracing-futures/README.md
- tracing-futures/src/lib.rs
- tracing-journald/README.md
- tracing-journald/src/lib.rs
- tracing-log/README.md
- tracing-log/src/lib.rs
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
- tracing-serde/Cargo.toml
- tracing-serde/README.md
- tracing-serde/src/lib.rs
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- tracing/README.md
- tracing/src/lib.rs
PR #934 fixed a bug in the CI configuration where MSRV checks were not
being run correctly. After this was fixed, it was necessary to bump the
MSRV to 1.40.0, as the tests were no longer actually passing on 1.39,
because some dependencies no longer support it.
While updating the documentation to indicate that the new MSRV is 1.40,
I noticed that the note on the MSRV was located inconsistently in the
READMEs and `lib.rs` documentation of various crates, and missing
entirely in some cases. Additionally, there have been some questions on
what our MSRV _policies_ are, and whether MSRV bumps are considered
breaking changes (see e.g. #936). 
I've updated all the MSRV notes in the documentation and READMEs to
indicate that the MSRV is 1.40. I've also ensured that the MSRV note is
in the same …
> docs: consistent MSRV docs & policy explanation

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
- Corrected wrong minimum supported Rust version note in docs (#941)
- Removed unused `syn` features (#928)
Thanks to new contributor @jhpratt for contributing to this release!
> attributes: prepare to release 0.1.11

- README.md
- tracing/README.md
- tracing/src/lib.rs
The test-env-log crate comes in useful when testing tracing based
applications/libraries. With this change we mention it in the Related
Crates section of the README.
> docs: Mention test-env-log as "related crate"

- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/fmt/writer.rs
Using `cargo test` doesn't correctly capture stdout. This is due to the difference between the `print!` macros and writing directly to the output stream. The result is messy output during testing.
A `TestWriter` was created that implements the `MakeWriter` and `std::io::Write` traits to wrap around the `print!` macro.
Closes #638
> subscriber: Impl TestWriter for correct capturing of logs by cargo test

- README.md
- tracing/README.md
- tracing/src/lib.rs
This PR adds [`tracing-unwrap`](https://docs.rs/tracing-unwrap) to the list of related crates in the readme.
`tracing-unwrap` provides convenience methods to unwrap `Result` and `Option` types and automatically report failures via `tracing` before panicking.
Feel free to edit the description I wrote as you see fit. Thanks!
> Add tracing-unwrap to the Related Crates

- tracing-serde/src/lib.rs
- tracing-subscriber/src/fmt/format/json.rs
JSON is a structured format, so the order of the fields should be
unimportant.
However, sometimes the JSON output is read in non-structured or
semi-structured contexts, and sometimes the output is truncated. In
those situations, when the spans and the current span are serialized
before the fields and the message, it makes it very difficult to see
what is going on.
By serializing the "fields" key before the "spans" and "span" keys, this
information is more likely visible when the payload is shown raw and
gets truncated.
Systems that parse the JSON as structured data should be unaffected
because of the nature of JSON.
Fixes #891
> subscriber: Reorder JSON fields

- tracing-opentelemetry/src/layer.rs
There are cases where an `opentelemetry` span will be created before a `tracing` span (e.g. some server middleware). In this case it would be helpful for `tracing-opentelemetry` to connect generated spans to the existing trace rather than starting a new trace.
If a parent trace id does not exist, check the current otel context and only generate a new trace id if no valid id is found.
> opentelemetry: Connect external traces

- .github/workflows/CI.yml
- tracing/Cargo.toml
- tracing/test-log-support/tests/log_no_trace.rs
- tracing/test-log-support/tests/log_with_trace.rs
- tracing/test-log-support/tests/span_activity_filtered_separately.rs
- tracing/test-log-support/tests/span_lifecycle_can_be_enabled.rs
- tracing/test-log-support/tests/span_lifecycle_defaults_off.rs
- tracing/test-log-support/tests/span_lifecycle_is_trace.rs
- tracing/test_static_max_level_features/tests/test.rs
- tracing/tests/event.rs
- tracing/tests/filter_caching_is_lexically_scoped.rs
- tracing/tests/filters_are_not_reevaluated_for_the_same_span.rs
- tracing/tests/filters_are_reevaluated_for_different_call_sites.rs
- tracing/tests/filters_dont_leak.rs
- tracing/tests/macro_imports.rs
- tracing/tests/macros.rs
- tracing/tests/max_level_hint.rs
- tracing/tests/multiple_max_level_hints.rs
- tracing/tests/span.rs
- tracing/tests/subscriber.rs
refs #642 
Start Testing the core crate in a wasm environment. This requires a special runner, and an extra dev-dependency.
All tests have been ported over except for `span::spans_always_go_to_the_subscriber_that_tagged_them_even_across_threads` because that spins up a thread, and wasm has no concept of threads being spun up.
Add a wasm-pack tester, and properly tag all tests.
> tracing: wasm test running

- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/lib.rs
- tracing-opentelemetry/src/span_ext.rs
- tracing-opentelemetry/src/tracer.rs
Currently the `OpenTelemetryLayer` is coupled to the opentelemetry SDK in a way that makes using alternate API implementations difficult (they would have to use the SDK's sampler and id generator) as well as causing duplication when specifying sampler configuration (it must currently be set on both the tracer provider configuration as well as the layer configuration, which is difficult to remember to keep in sync).
This change creates an interface for working with pre-sampled tracers, and implements it for the current opentelemetry SDK. This simplifies the layer as it no longer needs to track an id generator or sampler, and allows other otel API implementations to implement the trait rather than rely on the current SDK.
> opentelemetry: Add PreSampledTracer interface

- tracing-attributes/src/lib.rs
Fixes #963 
Document the default span level in documentation for the attribute.
> Document the default span level

- README.md
- tracing/README.md
- tracing/src/lib.rs
tracing-tracy has become tested enough that I’m comfortable with suggesting it to
people at least to try out.
List the crate among other related crates.
> Add tracing-tracy to related crates

- tracing-core/src/metadata.rs
This PR resolves a previously unreported regression where `Option<Level>`  was no longer a valid `LevelFilter`. Below is a minimal reproduction of the issue:
```rust
tracing_subscriber::fmt().with_max_level(Some(tracing::Level::WARN)).init();
```
I've added an `From<Option<Level>> for LevelFilter` implementation which _might_ require an MSRV version bump to 1.41 to support the [rebalanced coherence changes](https://blog.rust-lang.org/2020/01/30/Rust-1.41.0.html).
> core: add conversion from `Option<Level>` to `LevelFilter`

- tracing-appender/src/lib.rs
- tracing-subscriber/src/fmt/writer.rs
Add an new implementation of `MakeWriter` called `BoxMakeWriter` that wraps another instance of
`MakeWriter` and erases its concrete type, as well as the concrete type of its `io::Write`.
See context from https://github.com/tokio-rs/tracing/pull/776#discussion_r468056925. This should unblock the effort to land an appender that can write the same log line to multiple writers.
Implement `BoxMakeWriter` as suggested by @hawkw in the above thread.
> appender: Added BoxMakeWriter.

- tracing-core/CHANGELOG.md
- tracing-core/Cargo.toml
- tracing-core/README.md
- tracing-core/src/lib.rs
Preparing a release containing changes #966.
> chore: prepare to release tracing-core 0.1.16

- examples/Cargo.toml
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **env-filter**: Fixed a regression where `Option<Level>` lost its
`Into<LevelFilter>` impl ([#966])
- **env-filter**: Fixed `EnvFilter` enabling spans that should not be enabled
when multiple subscribers are in use ([#927])
- **json**: `format::Json` now outputs fields in a more readable order ([#892])
- Updated `tracing-core` dependency to 0.1.16
- **fmt**: Add `BoxMakeWriter` for erasing the type of a `MakeWriter`
implementation ([#958])
- **fmt**: Add `TestWriter` `MakeWriter` implementation to support libtest
output capturing ([#938])
- **layer**: Add `Layer` impl for `Option<T> where T: Layer` ([#910])
- **env-filter**: Add `From<Level>` impl for `Directive` ([#918])
- Multiple documentation fixes and improvements
Thanks to @Pothulapati, @samrg472, @bryanburgers, @keetonian, 
and …
> subscriber: prepare to release 0.2.12

- tracing-serde/Cargo.toml
- tracing-serde/src/lib.rs
- `SerdeMapVisitor::finish` to complete serializing the visited objects
(#892)
- `SerdeMapVisitor::take_serializer` to return the serializer wrapped by
a `SerdeMapVisitor` (#892)
Thanks to @bryanburgers for contributing to this release!
> serde: prepare to release 0.1.2

- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
`tracing-subscriber` depended on unreleased `tracing-serde` APIs and
thus couldn't be released earlier (I forgot to publish the
`tracing-serde` changes).
Now that they're published, we can bump `tracing-subscriber`'s
dependency and _actually_ publish a new version.
> subscriber: bump serde dep, update release date

- tracing-attributes/src/lib.rs
`instrument` removes the visibility of function that looks like its from `async-trait` even if its not inside a trait `impl` block.
Add back the function visibility (`input.vis`) for when its reconstructed in `quote`.
Fixes: #976
> attributes: add visibility to async-trait output

- tracing/src/lib.rs
- tracing/src/macros.rs
- tracing/tests/macros.rs
In PR #943, the construction of `ValueSet`s for events and spans was
moved out of the code expanded at the callsite and into a closure, in
order to reduce the amount of assembly generated in functions containing
tracing macros. However, this introduced an accidental breaking change
for some dependent crates. Borrowing values inside a closure meant that
when a field of a struct, array, or tuple was used as a field value, the
closure must borrow the _entire_ struct, array, or tuple, rather than
the individual field. This broke code where another unrelated field of
that struct, array, or tuple would then be mutably borrowed or moved
elsewhere. 
This branch fixes the breaking change by moving `ValueSet` construction
back out of a closure and into the code expanded at the callsite. This
_does_ …
> tracing: move `ValueSet` construction out of closures

- tracing-core/Cargo.toml
- tracing-core/src/metadata.rs
- tracing-log/Cargo.toml
- tracing-log/src/lib.rs
- tracing-log/tests/log_tracer.rs
- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/field.rs
- tracing/Cargo.toml
- tracing/src/macros.rs
- tracing/src/span.rs
- tracing/tests/support/subscriber.rs
This makes both structs easier to use because you no longer have to
worry about borrow errors while working with them. There's no downside
to making them `Copy` since both are wrappers around a `usize`.
Ideally, this would make `Metadata::Level` return `Level` instead of
`&Level`. However that's a breaking change, so I didn't make it here.
Derive `Copy` for both structs and fix various warnings that popped up as a result.
> Make `Level` and `LevelFilter` `Copy`

- tracing-core/src/event.rs
- tracing/src/span.rs
Presently, functions for recording new spans and events that can get the
current dispatcher (`Event::dispatch`, `Event::child_of`, `Span::new`,
and `Span::new_root`) are marked as `#[inline]`. This results in these
methods getting inlined in most cases, and `dispatcher::get_default` is
sometimes inlined into *those* methods. This, then, inlines all of
`dispatcher::get_default` into the callsites of the `span!` and `event!`
macros, generating *way* too much code (including thread local accesses)
inline. Since there's an `expect` in `get_default`, this also means that 
unwinding code is inlined into functions that wouldn't otherwise panic,
which is also not great. Inlining too much code this results in code that
optimizes poorly in many cases.
This PR removes `#[inline]` attributes from …
> core, tracing: don't inline dispatcher::get_default

- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/field.rs
Currently, there are some minor issues with `Ord` and `PartialOrd` impls
in `tracing_subscriber::filter::env`:
- The `Directive` and `StaticDirective` types implement `PartialOrd`
with an implementation that never returns `None`, and then have `Ord`
implementations that call `partial_cmp` and `expect` that the returned
value is `Some`. This isn't necessary.
- `field::Match` implements `PartialOrd` manually but derives `Ord`.
Since these traits must agree, using the derived implementation for
one but manually implementing the other is potentially incorrect (see
#991).
This branch fixes these issues. I've moved actual comparison code from
`PartialOrd` impls for `Directive` and `StaticDirective` to their `Ord`
impls, and changed `PartialOrd::partial_cmp` for those types to call
`Ord::cmp` …
> subscriber: make `PartialOrd` & `Ord` impls more correct

- tracing-core/CHANGELOG.md
- tracing-core/README.md
- tracing-core/src/lib.rs
- Incorrect inlining of `Event::dispatch` and `Event::child_of`, which
could result in `dispatcher::get_default` being inlined at the
callsite (#994)
- `Copy` implementations for `Level` and `LevelFilter` (#992)
Thanks to new contributors @jyn514 and @TaKO8Ki for contributing 
> core: prepare to release 0.1.17

- tracing-subscriber/src/util.rs
- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- Incorrect inlining of `Span::new`, `Span::new_root`, and
`Span::new_child_of`, which could result in `dispatcher::get_default`
being  inlined at the callsite ([#994])
- Regression where using a struct field as a span or event field when
other fields on that struct are borrowed mutably would fail to compile
([#987])
- Updated `tracing-core` to 0.1.17 ([#992])
- `Instrument` trait and `Instrumented` type for attaching a `Span` to a
`Future` ([#808])
- `Copy` implementations for `Level` and `LevelFilter` ([#992])
- Multiple documentation fixes and improvements ([#964], [#980], [#981])
Thanks to @nagisa, and new contributors @SecurityInsanity, @froydnj,
@jyn514 and @TaKO8Ki for contributing to this release!
[#994]: https://github.com/tokio-rs/tracing/pull/994
[#992]: …
> tracing: prepare to release 0.1.21

- tracing-macros/src/lib.rs
The `tracing-macros` crate doesn't currently compile with the latest
`tracing` release, because it uses internal private API that changed.
We need to fix this so CI isn't broken.
I changed the `dbg!` macro so it no longer uses internal APIs. Ideally,
we would implement `dbg!` using the support for string-literal field
names that was recently added to `tracing`, but I couldn't actually get
it to work --- I think the `event!` macros may not handle string literal
field names properly (we only test them with the `span!` macros >_>).
Will try to fix that later, but for now, this fixes CI and I don't think
anyone actually uses the experimental, unreleased `tracing-macros` 
crate.
> macros: fix the `tracing-macros` crate not compiling

- .vscode/tasks.json
- examples/Cargo.toml
- examples/examples/all-levels.rs
- tracing-appender/Cargo.toml
- tracing-attributes/Cargo.toml
- tracing-core/Cargo.toml
- tracing-error/Cargo.toml
- tracing-flame/Cargo.toml
- tracing-futures/Cargo.toml
- tracing-journald/Cargo.toml
- tracing-log/Cargo.toml
- tracing-opentelemetry/Cargo.toml
- tracing-serde/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-tower/Cargo.toml
- tracing/Cargo.toml
This branch updates all crate versions to 0.2.x. After this PR merges,
we can now develop `tracing`/`tracing-core` v0.2.x on `master`. 
There is now a separate, protected `v0.1.x` branch. Changes backported
to 0.1 versions of `tracing` crates can be merged to that branch. 
> update all crate versions for v0.2.x

- examples/examples/hyper-echo.rs
- tracing-macros/src/lib.rs
- tracing/src/span.rs
The `Entered` guard returned by `Span::enter` represents entering and
exiting a span _on the current thread_. Calling `Span::enter` enters the
span, returning an `Entered`, and dropping the `Entered` ensures that
the span is exited. This ensures that all spans, once entered, are
eventually exited.
However, `Entered` has an auto-impl of `Send`, because it doesn't
contain any `!Send` types. This means that the `Entered` guard _could_
be sent to another thread and dropped. This would cause the original
thread to never exit the span,. and the thread to which the `Entered`
guard was sent would exit a span that it never observed an enter for.
This is incorrect.
This PR adds a `*mut ()` field to `Entered` so that it no longer
implements `Send`. There's now a manual `Sync` impl so structs holding …
> tracing: make `Entered` `!Send`

- tracing/src/span.rs
This doesn't work correctly, since the span is dropped when the function
returns, calling `try_close` on that span. We could remove the inner
value in this case, but then `try_close` will _never_ be called on that
ID, leaking the parent. If the span is dropped *after* the new span is
created, instead, everything will work correctly, because the subscriber
will have already increased its reference count (as it now has a
child). Thus, only `&Span` is valid here.
Fixes #688
> tracing: remove `Into<Option<Id>>` impl for `Span`

- tracing-opentelemetry/src/layer.rs
While using `tracing-opentelemetry` I noticed all the data gets sent to the collector as a string. This implements the additional data types and (possibly) saves bandwidth.
I just implemented additional `fn record_$type(...)` methods of the `field::Visit` trait to `SpanEventVisitor` and `SpanAttributeVisitor`.
PSA: I don't really know what I'm doing :)
> tracing-opentelemetry: implement additional record types (bool, i64, u64)

- tracing-core/src/callsite.rs
- tracing-core/src/dispatcher.rs
- tracing-core/src/event.rs
- tracing-core/src/field.rs
- tracing-core/src/lib.rs
- tracing-core/src/metadata.rs
- tracing-core/src/span.rs
- tracing-core/src/subscriber.rs
This caught multiple broken links in the documentation. Partially addresses https://github.com/tokio-rs/tracing/issues/940.
Use intra-doc links so rustdoc will give a loud warning if the documentation has errors.
> Switch to intra-doc links in tracing-core

- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/mod.rs
This adds support for having dashes in log target names, like:
`target-name=info`
We are using log targets with dashes in our project.
Extend the target parsing regex to support dashes.
> Support dash in target names

- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/mod.rs
Backports: https://github.com/tokio-rs/tracing/pull/1012
@hawkw should I directly bump the crate version?
> Backport #1012

- tracing-opentelemetry/src/layer.rs
This is a backport of #1007, done by simply cherry-picking 04bbb15.
> Backport #1007

- tracing-core/src/callsite.rs
Currently, the tests for the linked list implementation in
`tracing_core::callsite` declare two static `Registration`s in the test
module, which are used in multiple tests. Since these tests are all run
in one binary, in separate threads, these statics are shared across all
tests. This means that --- depending on the order in which tests are run
--- these `Registration`s may already have values for their `next`
pointers. In particular, there's a potential issue where the `for_each`
in the test `linked_list_push` can loop repeatedly, if one of the
`Registration`s already had a next pointer from a previous test. See:
https://github.com/tokio-rs/tracing/pull/1008#issuecomment-703041964
This branch declares separate `Registration` statics for each test.
These are not shared between multiple …
> core: fix linked list tests reusing `Registration`s

- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/mod.rs
Fixes https://github.com/tokio-rs/tracing/issues/975.
This implements the warning in `tracing-subscriber` only, as mentioned in https://github.com/tokio-rs/tracing/issues/975#issuecomment-692903469. It warns whenever directives are parsed, including programmatically and through environment variables. It does not include the suggested new API which returns the filters that wouldn't be parsed.
- List filters that would be ignored
- Mention 'static max level'
- Describe how to enable the logging
Example output:
```
$ RUST_LOG=off,debug,silenced[x]=trace cargo run -q
warning: some trace filter directives would enable traces that are disabled statically
| `debug` would enable the DEBUG level for all targets
| `silenced[x]=trace` would enable the TRACE level for the `silenced` target
= note: …
```
> subscriber: warn if trying to enable a statically disabled level

- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/filter/env/directive.rs
- tracing-subscriber/src/filter/env/mod.rs
This backports #990 so it can be used in rustc without having to upgrade to a new breaking version.
> Backport #990 (subscriber: warn if trying to enable a statically disabled level)

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/err.rs
For the non-async case, early returns could escape the block so that the
error handling was skipped.
I was wondering for quite some time now what was going on here 😆 
Just put the block into the all-mighty "try-catch-closure" construct.  I'm unsure whether this will negatively impact the quality of error messages in case of type checking issues.  Maybe, we should add some type annotations to the closure?
> attributes:  fix `#[instrument(err)]` in case of early returns

- examples/Cargo.toml
- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- Updated `tracing-core` to 0.1.17 ([#992])
- **env-filter**: Added support for filtering on targets which contain
dashes ([#1014])
- **env-filter**: Added a warning when creating an `EnvFilter` that
contains directives that would enable a level disabled by the
`tracing` crate's `static_max_level` features ([#1021])
Thanks to @jyn514 and @bkchr for contributing to this release!
[#992]: https://github.com/tokio-rs/tracing/pull/992
[#1014]: https://github.com/tokio-rs/tracing/pull/1014
[#1021]: https://github.com/tokio-rs/tracing/pull/1021
> subscriber: prepare to release 0.2.13

- .github/workflows/CI.yml
This PR just removes the use of the deprecated `add-path` from the CI workflow. See [here](https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/) for details. Specifically, note:
> Starting today runner version 2.273.5 will begin to warn you if you use the add-path or set-env commands. We are monitoring telemetry for the usage of these commands and plan to fully disable them in the future.
> Remove deprecated add-path from CI

- tracing-opentelemetry/src/tracer.rs
It is currently possible to create a span graph which includes a span that has both an invalid parent otel context _and_ a missing trace id by assigning an invalid extracted parent context to a non-root span. Constructing this particular graph will currently cause a panic.
Explicitly assign default trace / span ids when sampling using the otel SDK if the span builder does not contain these values.
> opentelemetry: Assign default ids if missing

- tracing-opentelemetry/src/tracer.rs
> opentelemetry: Backport Assign default ids if missing

- examples/examples/tower-load.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/reload.rs
Currently, the `reload` layer is generic over both the type of the layer
being reloaded, *and* the type of the subscriber that the layer is
layered onto. This means that the `reload::Handle` type that's used to
reload the value of the layer *also* is parameterized over the
subscriber's type.
The subscriber type parameter makes the `reload` API significantly
harder to use. Any time a `reload::Handle` is returned by a function,
taken as an argument, or stored in a struct, the full type of the
subscriber under the layer must be written out --- and often, it is
quite long. What makes this worse is that sometimes the type of the
subscriber may vary at runtime based on some configuration, while the
type of the layer that's reloaded remains the same. For example, in
Linkerd, we've had to do …
> subscriber: fix `reload` ergonomics

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
The intention is to backport this and release against v0.1.x branch. Changelog:
- Implement additional record types (bool, i64, u64) (#1007)
- Add `PreSampledTracer` interface, removes need to specify sampler (#962)
- Connect external traces (#956)
- Assign default ids if missing (#1027)
> opentelemetry: prepare for 0.8.0 release

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
> opentelemetry: Backport #1036 - prepare for 0.8.0 release

- tracing-subscriber/Cargo.toml
- tracing-subscriber/benches/enter.rs
- tracing-subscriber/src/registry/sharded.rs
- tracing-subscriber/src/registry/stack.rs
We've tried very hard to make sure that entering and exiting spans is
lightweight...in the `tracing-core` core machinery. Unfortunately, we
haven't done any benchmarking of how subscriber implementations actually
handle enter/exit events. It turns out that in `tracing-subscriber`'s
`Registry`, there's actually significant overhead for entering a span:
calling `span.enter()` may take as long as 69 ns (on my machine).
I've written some microbenchmarks for entering and exiting enabled spans
using `tracing-subscriber::fmt`, comparing them with the overhead of
calling `enter` on an enabled span. Based on this, I've made some
performance improvements. These optimizations include:
- Removing the `HashSet` that's used for tracking previously entered
span IDs, in favor of linear search. Span …
> subscriber: make Registry::enter/exit much faster

- tracing-subscriber/src/fmt/format/json.rs
I've been seeing this warning from `tracing-subscriber` for quite a long time.
Running `cargo doc` gives this:
```
warning: could not parse code block as Rust code
--> /home/veetaha/.cargo/registry/src/github.com-1ecc6299db9ec823/tracing-subscriber-0.2.13/src/fmt/format/json.rs:30:5
|
30 |   /// ```ignore,json
|  _____^
31 | | /// {
32 | | ///     "timestamp":"Feb 20 11:28:15.096",
33 | | ///     "level":"INFO",
...  |
38 | | /// }
39 | | /// ```
| |_______^
|
= note: error from rustc: unterminated double quote string
```
I guess it's me who dares fix this then :D
> Fix rustdoc warning

- tracing-subscriber/Cargo.toml
- tracing-subscriber/benches/enter.rs
- tracing-subscriber/src/registry/sharded.rs
- tracing-subscriber/src/registry/stack.rs
This backports #1058 to v0.1.x. This was already approved on master.
We've tried very hard to make sure that entering and exiting spans is
lightweight...in the `tracing-core` core machinery. Unfortunately, we
haven't done any benchmarking of how subscriber implementations actually
handle enter/exit events. It turns out that in `tracing-subscriber`'s
`Registry`, there's actually significant overhead for entering a span:
calling `span.enter()` may take as long as 69 ns (on my machine).
I've written some microbenchmarks for entering and exiting enabled spans
using `tracing-subscriber::fmt`, comparing them with the overhead of
calling `enter` on an enabled span. Based on this, I've made some
performance improvements. These optimizations include:
- Removing the `HashSet` that's used for …
> subscriber: make Registry::enter/exit much faster (backport #1058)

- tracing-subscriber/src/fmt/fmt_subscriber.rs
- tracing-subscriber/src/fmt/mod.rs
This PR removes the deprecated items in `tracing-subscriber`. It _does not_ remove `Collector::drop_span` as that will happen in a separate PR. Note that branch builds atop of #1015, which means:
- #1015 needs to be merged first
- This PR will be rebased against the master branch containing #1015.
- _Then_ this can safely be merged.
> subscriber: Remove Deprecated Type, Structs, and Methods

- tracing-subscriber/Cargo.toml
- tracing-subscriber/benches/fmt.rs
- tracing-subscriber/src/registry/extensions.rs
- tracing-subscriber/src/registry/sharded.rs
- tracing-subscriber/src/sync.rs
This backports #1062 to v0.1.6. This has already been approved on
master.
hawkw/sharded-slab#45 changes `sharded-slab` so that the per-shard
metadata is allocated only when a new shard is created, rather than all
up front when the slab is created. This fixes the very large amount of
memory allocated by simply creating a new `Registry` without actually
collecting any traces.
This branch updates `tracing-subscriber` to depend on `sharded-slab`
0.1.0, which includes the upstream fix.
In addition, this branch the registry from using `sharded_slab::Slab` to
`sharded_slab::Pool`. This allows us to clear hashmap allocations for
extensions in-place, retaining the already allocated maps. This should
improve `new_span` performance a bit.
Fixes #1005
> subscriber: update sharded-slab, pool hashmaps

- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **registry**: Fixed `Registry::new` allocating an excessively large
amount of memory, most of which would never be used ([#1064])
- **registry**: Improved `new_span` performance by reusing `HashMap`
allocations for `Extensions` ([#1064])
- **registry**: Significantly improved the performance of
`Registry::enter` and `Registry::exit` ([#1058])
[#1064]: https://github.com/tokio-rs/tracing/pull/1064
[#1058]: https://github.com/tokio-rs/tracing/pull/1058
> subscriber: prepare to release 0.2.14

- examples/examples/fmt-json.rs
- examples/examples/fmt-pretty.rs
- examples/examples/fmt.rs
- examples/examples/fmt/yak_shave.rs
- tracing-subscriber/src/fmt/fmt_subscriber.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/format/pretty.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/lib.rs
Currently, the `tracing_subscriber::fmt` module contains only
single-line event formatters. Some users have requested a
human-readable, pretty-printing event formatter optimized for
aesthetics.
This branch adds a new `Pretty` formatter which uses an _excessively_
pretty output format. It's neither compact, single-line oriented, nor
easily machine-readable, but it looks _quite_ nice, in my opinion. This
is well suited for local development or potentially for user-facing logs
in a CLI application.
Additionally, I tried to improve the docs for the different formatters
currently provided, including example output. Check out [the Netlify
preview][1]!
[1]: https://deploy-preview-1067--tracing-rs.netlify.app/tracing_subscriber/fmt/index.html#formatters
> subscriber: add `Pretty` formatter

- examples/examples/fmt-compact.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/mod.rs
Depends on #1067 
Currently, the `Compact` event formatter in `tracing-subscriber`
is...kind of bad, and nobody seems to use it. It outputs the names of
all the spans in the current context, and (inexplicably) the _names_ of
all the fields on the current span, but not their values. This isn't
very useful.
This branch rewrites the `Compact` formatter to be a little less bad.
Now, we output all the fields from the current span context, but skip
span names, and we shorten the level to a single character when it's
enabled. Additionally, using the `compact` formatter disables targets by
default. Now, the lines are nicely short, but maybe still useful.
Example output before this change:
...and after:
> subscriber: make `Compact` event formatter not terrible

- examples/examples/fmt-compact.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/mod.rs
Depends on #1067 
Currently, the `Compact` event formatter in `tracing-subscriber`
is...kind of bad, and nobody seems to use it. It outputs the names of
all the spans in the current context, and (inexplicably) the _names_ of
all the fields on the current span, but not their values. This isn't
very useful.
This branch rewrites the `Compact` formatter to be a little less bad.
Now, we output all the fields from the current span context, but skip
span names, and we shorten the level to a single character when it's
enabled. Additionally, using the `compact` formatter disables targets by
default. Now, the lines are nicely short, but maybe still useful.
Example output before this change:
...and after:
> subscriber: make `Compact` formatter not be useless

- examples/examples/custom-error.rs
- examples/examples/instrumented-error.rs
- tracing-error/README.md
- tracing-error/src/backtrace.rs
- tracing-error/src/layer.rs
- tracing-error/src/lib.rs
- tracing-subscriber/tests/reload.rs
- tracing/benches/subscriber.rs
- tracing/tests/collector.rs
A few minor things left over from #1015. There are possibly a few more (`ErrorLayer` in `tracing-error`?).
> Fix a few renames missed in #1015

- tracing-subscriber/src/fmt/fmt_subscriber.rs
Currently, the `FmtContext` type implements `FormatFields` using the
subscriber's field formatter. However, this is difficult to use. The
`FmtContext` may _not_ be passed to functions expecting a `for<'writer>
FormatFields<'writer>`, because it only implements `FormatFields` for
its _own_ lifetime. This means the writer must have the same lifetime as
the context, which is not correct.
This branch fixes this by changing the impl of `FormatFields` for
`FmtContext` to be generic over both the vontext's lifetime _and_ the
field formatter's lifetime. Additionally, I've added a method for
borrowing the actual field formatter as its concrete type, in case the
`FormatEvent` impl puts additional constraints on its type or is only
implemented for a specific named type, and wants to actually _use_ …
> subscriber: fix accessing the field formatter from `FmtContext`

- examples/examples/fmt-json.rs
- examples/examples/fmt-pretty.rs
- examples/examples/fmt/yak_shave.rs
- tracing-subscriber/src/fmt/fmt_layer.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/format/pretty.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/lib.rs
This backports PR #1067 to v0.1.x. Since this has already been approved
on master, I'm just going to go ahead and merge it when CI passes.
Currently, the `tracing_subscriber::fmt` module contains only
single-line event formatters. Some users have requested a
human-readable, pretty-printing event formatter optimized for
aesthetics.
This branch adds a new `Pretty` formatter which uses an _excessively_
pretty output format. It's neither compact, single-line oriented, nor
easily machine-readable, but it looks _quite_ nice, in my opinion. This
is well suited for local development or potentially for user-facing logs
in a CLI application.
Additionally, I tried to improve the docs for the different formatters
currently provided, including example output. Check out [the Netlify
preview][1]!
[1]: …
> subscriber: add `Pretty` formatter (backports #1067)

- tracing-subscriber/CHANGELOG.md
- tracing-subscriber/Cargo.toml
- tracing-subscriber/README.md
- tracing-subscriber/src/lib.rs
- **fmt**: Fixed wrong lifetime parameters on `FormatFields` impl for
`FmtContext` ([#1082])
- **fmt**: `format::Pretty`, an aesthetically pleasing, human-readable
event formatter for local development and user-facing CLIs ([#1080])
- **fmt**: `FmtContext::field_format`, which returns the subscriber's
field formatter ([#1082])
[#1082]: https://github.com/tokio-rs/tracing/pull/1082
[#1080]: https://github.com/tokio-rs/tracing/pull/1080
> subscriber: prepare to release 0.2.15

- tracing-subscriber/src/registry/mod.rs
- tracing-subscriber/src/registry/sharded.rs
ref: https://github.com/tokio-rs/tracing/pull/1009
This is code refactoring. Currently, there is a lot of code that declares modules as follows:
```rust
#[cfg(feature = "registry")]
#[cfg_attr(docsrs, doc(cfg(feature = "registry")))]
pub use registry::Registry;
#[cfg(feature = "registry")]
#[cfg_attr(docsrs, doc(cfg(feature = "registry")))]
pub fn registry() -> Registry {
Registry::default()
}
```
It is verbose to write a module declaration multiple times using the feature attribute. Also, if the definition for the same feature spans multiple places, it will be a little harder to read the code.
You can combine features attributes in one place by writing as follows. It also eliminates the need to write the same code over and over again.
```rust
cfg_feature!("feature" ,{
pub use …
```
> Use macros for module declarations on registry

- tracing-subscriber/src/fmt/fmt_subscriber.rs
- tracing-subscriber/src/fmt/mod.rs
`format::Format` already has [default values for the log forma](https://github.com/dvdplm/tracing/blob/95463b8ac2fe43f51f89ae3f98006930bbfd2874/tracing-subscriber/src/fmt/format/mod.rs#L177)t (`Full`) as well as time measuring gizmo (`SystemTime`) so no need to plug those in.
> Format has default value for all type params

- tracing-subscriber/src/fmt/fmt_subscriber.rs
- tracing-subscriber/src/fmt/mod.rs
There were two different doc strings for `with_ansi` this PR changes all of them to match the doc string I felt was best (the one that mentioned color) :smile:
> Make with_ansi docs consistent

- .github/workflows/CI.yml
Closes #648
Install cargo-hack from GitHub release instead of using cache.
See also https://github.com/taiki-e/cargo-hack/pull/89 and https://github.com/taiki-e/cargo-hack/pull/91.
> ci: install cargo-hack from GitHub release instead of using cache

- tracing-opentelemetry/src/layer.rs
Hi friends! I found the timing metrics captured in the fmt::Subscriber quite useful and thought it would be nice to send this data to the provider. Here I'm measuring the busy and idle time by pretty much the same way it's implemented in https://github.com/tokio-rs/tracing/blob/c10c8d2bd9ff3980d231b84d6fa1770756522f19/tracing-subscriber/src/fmt/fmt_subscriber.rs#L611-L615
Let me know what you think! 🙏 
Add `busy_ns` and `idle_ns` attributes to the open telemetry subscriber.
> Add busy/idle timings to the opentelemetry subscriber

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
Changelog:
- Track busy/idle timings as attributes via `with_tracked_inactivity` (#1096)
- Upgrade to `v0.10.0` of `opentelemetry` (#1049)
For list of breaking changes in OpenTelemetry, see the [v0.10.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry/CHANGELOG.md#v0100).
> opentelemetry: prepare for 0.9.0 release

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
> opentelemetry: backport prepare for 0.9.0 release

- examples/examples/echo.rs
In #808, I've added an `.await?` to an instrumented `tokio::task::JoinHandle` since the `Instrument` future now has a `#[must_use]`. However, this caused the echo example to no longer accept multiple netcat connections but was only reported in #1097. This PR resolves this bug by instrumenting the spawned future, _not_ the `JoinHandle`.
More broadly, I think the interaction between `tokio::task::JoinHandle` (which _does not_ have the `#[must_use]` annotation) and the `tracing::Instrument` future (which _does_ have the `#[must_use]` annotation) is confusing and introduces performance footguns in refactors that even advanced users missed in code review.
Resolves #1097.
> examples: Fix echo by Reintroducing Concurrency

- tracing-appender/src/rolling.rs
The list introduced by:
"To use a Rotation, pick one of the following options:"
had en entry for all variations of Rotation except for Rotation::MINUTELY. This PR completes this list, with the doc test structured the same as the others in the list.
The newly added entry heading is "Minutely Rotation".
**Side-note:** I had to look up "minutely" in several dictionaries to convince myself that it is actually a legit English word that means "minute by minute" (in addition to the more familiar definition meaning "careful examination"), and was not just a cute symbol name in the code. It turns out that that usage of the word *is* legit!  (But you folks already knew that)  :-)
I performed both positive and negative tests to ensure that `'cargo test --doc'` is correctly testing the change.
> appender(docs): add missing entry for Rotation::MINUTELY

- tracing-appender/src/non_blocking.rs
Remove duplication in "...at capacity. capacity." in doc comment for:
tracing_appender::non_blocking::DEFAULT_BUFFERED_LINES_LIMIT
> appender(docs): fix minor typo for DEFAULT_BUFFERED_LINES_LIMIT

- tracing-subscriber/src/fmt/time/mod.rs
I recon this is a bug, and @samschlegel  fixed this for ChronoUtc in #677, but not for ChronoLocal.
> Remove trailing space from ChronoLocal time formatter.

- tracing-appender/src/lib.rs
- tracing-appender/src/rolling.rs
- tracing-attributes/src/lib.rs
- tracing-core/src/collect.rs
- tracing-core/src/event.rs
- tracing-core/src/lib.rs
- tracing-error/src/backtrace.rs
- tracing-error/src/lib.rs
- tracing-flame/src/lib.rs
- tracing-log/src/lib.rs
- tracing-log/src/log_tracer.rs
- tracing-serde/src/lib.rs
- tracing-subscriber/src/filter/env/mod.rs
- tracing-subscriber/src/fmt/fmt_subscriber.rs
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-subscriber/src/fmt/mod.rs
- tracing-subscriber/src/fmt/writer.rs
- tracing-subscriber/src/lib.rs
- tracing-subscriber/src/registry/extensions.rs
- tracing-subscriber/src/registry/mod.rs
- tracing-subscriber/src/subscribe.rs
- tracing/src/dispatch.rs
- tracing/src/field.rs
- tracing/src/instrument.rs
- tracing/src/level_filters.rs
- tracing/src/lib.rs
- tracing/src/span.rs
- tracing/src/subscribe.rs
#940 
This converts some more links found while trying to debug the link failures in https://github.com/tokio-rs/tracing/pull/1078. Unfortunately it didn't fix the failures, but it's a useful change so I split it out into a separate PR.
> Switch to even more intra-doc links

- tracing-appender/src/lib.rs
- tracing-attributes/src/lib.rs
- tracing-core/src/lib.rs
- tracing-error/src/lib.rs
- tracing-flame/src/lib.rs
- tracing-futures/src/lib.rs
- tracing-journald/src/lib.rs
- tracing-log/src/lib.rs
- tracing-macros/src/lib.rs
- tracing-opentelemetry/src/lib.rs
- tracing-serde/src/lib.rs
- tracing-subscriber/src/lib.rs
- tracing-tower/src/lib.rs
- tracing/src/lib.rs
As of Rust 1.48, these are stable and the warnings are enabled by default :tada: :tada: .
Remove the unnecessary `deny`.
> Remove deny(broken_intra_doc_links)

- README.md
The blogpost is about the usage of tracing and some of it's complementary modules.
Related [Reddit comment]( https://www.reddit.com/r/rust/comments/jv6a5j/productiongrade_logging_in_rust_applications/gcrjoa6?utm_source=share&utm_medium=web2x&context=3).
> Adds a blogpost link in External Resources section

- tracing-subscriber/Cargo.toml
> Remove json support from tracing-subscriber's default features #653

- .github/workflows/CI.yml
- .github/workflows/audit.yml
Currently, we are building and caching `cargo-audit` on CI. The GitHub
Actions configuration we use for caching the `cargo-audit` binary is now
deprecated and is [breaking our CI builds][2].
This PR switches to the [`actions-rs/audit-check` action][3]. This ought
to fix CI.
[1]: https://github.blog/changelog/2020-10-01-github-actions-deprecating-set-env-and-add-path-commands/
[2]: https://github.com/tokio-rs/tracing/pull/1116/checks?check_run_id=1444562432
[3]: https://github.com/actions-rs/audit-check
> ci: switch to `audit-check` GitHub Action for `cargo audit`

- .github/workflows/CI.yml
- .github/workflows/audit.yml
This backports #1100 and #1117 to v0.1.x. This should hopefully fix the build.
> chore: backport CI fixes to v0.1.x

- tracing/Cargo.toml
This backports #1108 to v0.1.x. This was already approved on `master`,
so I'll just merge it pending CI.
Updates the requirements on [pin-project-lite](https://github.com/taiki-e/pin-project-lite) to permit the latest version.
- [Release notes](https://github.com/taiki-e/pin-project-lite/releases)
- [Changelog](https://github.com/taiki-e/pin-project-lite/blob/master/CHANGELOG.md)
- [Commits](https://github.com/taiki-e/pin-project-lite/compare/v0.1.0...v0.2.0)
Signed-off-by: dependabot-preview[bot] <support@dependabot.com>
Co-authored-by: dependabot-preview[bot] <27856297+dependabot-preview[bot]@users.noreply.github.com>
> chore(deps): update pin-project-lite requirement from 0.1 to 0.2

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- Updated `pin-project-lite` dependency to 0.2 ([#1108])
[#1108]: https://github.com/tokio-rs/tracing/pull/1108
> tracing: prepare to release v0.1.22

- .github/workflows/CI.yml
Tracing's examples depend on a number of external crates that the core
`tracing` crates don't depend on. Sometimes, crates that we only depend
on for examples will break compatibility with our MSRV. It's not ideal
to bump our supported MSRV just for an example, since the actual
`tracing` crates will still build fine.
Instead, this PR updates the CI config to exclude examples from the
MSRV check. This way, we don't have to bump MSRV for examples-only
dependencies.
> chore: don't check examples on MSRV

- netlify.toml
At Netlify we recently introduced native Rust support in the build system: https://github.com/netlify/build-image/pull/477
This PR cleans up the Netlify build config to use a more straight-forward way of building rust docs.
This also introduces a workaround for https://github.com/netlify/build-image/issues/505
We're big fans of the `tracing` crate at Netlify and using it for many new systems recently. Very happy we can give something back!
> Fix netlify build

- tracing-subscriber/src/filter/env/directive.rs
Hi Folks,
This PR is about behavior compatibility with the `env_logger` and `log` crates. There are references in the `tracing-subscriber` docs noting some level of partial compatibility with `env_logger`, but it is not clear to me the extent to which that is a priority.
If the intention is to keep the projects close in behavior where there is overlap in the representations of logging directive strings, then this PR is a step toward better compatibility.
On the other hand, if such compatibility is more of a short-term nice-to-have than a long-term objective, then this PR might be a step in the wrong direction. If so, please feel free to reject it. I happened to notice the behavior difference (described below) while working on something else, and just thought I'd bring it up for …
> subscriber: directives: accept legit log level names in mixed case (env_logger compat)

- tracing-subscriber/src/fmt/writer.rs
I noticed complaints in the doc checks upon CI deployments, and at first misread them as being the cause of some "Deployment failed" errors. It turns out that they were not the cause, but this PR does fix the doc check error.
There are several separate "Deploy failed" errors, all the same. From the deploy logs of one of them:
```console
$   curl https://sh.rustup.rs -sSf | sh -s -- -y --default-toolchain nightly --profile minimal && source $HOME/.cargo/env && RUSTDOCFLAGS="--cfg docsrs" cargo +nightly doc --no-deps
...
11:46:24 PM: warning: unresolved link to `Makewriter`
11:46:24 PM:    --> tracing-subscriber/src/fmt/writer.rs:153:58
11:46:24 PM:     |
11:46:24 PM: 153 | /// A writer that erases the specific [`io::Write`] and [`Makewriter`] types being used.
11:46:24 PM:     | …
```
> docs: fix typo causing CI doc check warnings

- tracing-appender/src/non_blocking.rs
- tracing-appender/src/worker.rs
Fixes the race condition outlined in #1120 . 
`Worker` now uses a 2 stage shutdown approach. The first shutdown signal is sent through the main message channel to the `Worker` from `WorkerGuard` when it is dropped. Then `WorkerGuard` sends a second signal on a second channel that is zero-capacity. This means It will only succeed a `send()` when a `recv()` is called on the other end. This guarantees that the `Worker` has flushed all it's messages before the `WorkerGuard` can continue with its drop.
With this solution I'm not able to reproduce the race anymore using the provided code sample from #1120
> tracing_apender: Fix race condition for logging on shutdown

- tracing-flame/src/lib.rs
We should allow config whether or not display module_path or file/line in output.
> tracing-flame: add module_path and file_and_line into Config

- .github/workflows/CI.yml
- README.md
- netlify.toml
- tracing-appender/src/non_blocking.rs
- tracing-appender/src/worker.rs
- tracing-flame/src/lib.rs
- tracing-subscriber/src/filter/env/directive.rs
This branch backports a number of non-breaking changes from `master` to
`v0.1.x`:
* 27b28773 tracing-flame: add module_path and file_and_line configs (#1134)
* 4f93a6e0 docs: update README.md (#1133)
* ade54898 appender: fix race condition when logging on shutdown (#1125)
* aa2bae09 subscriber: directives: accept legit log level names in mixed case (env_logger compat) (#1126)
* d59f4bc4 chore: fix netlify build (#1131)
* 2e81818f chore: don't check examples on MSRV (#1128)
These changes have already been approved on `master`, so I'll just go
ahead and merge this once CI passes.
I'll rebase merge this so all the commits land individually.
> backport several non-breaking changes to v0.1.x

- tracing-core/src/dispatch.rs
- tracing/src/dispatch.rs
Two minor documenation tweaks:
1. One typo in a (hidden) doc comment
2. Spell-out discarding behavior of the default collector
> two minor doc tweaks

- tracing-error/Cargo.toml
- tracing-flame/Cargo.toml
- tracing-opentelemetry/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-tower/Cargo.toml
This avoids relatively heavy dependencies (tracing-attributes, syn, etc.) in some cases.
> Disable default features of tracing dependency

- README.md
- tracing/src/lib.rs
From the readme
> (if you're the maintainer of a tracing ecosystem crate not in this list, please let us know!)
Added links to tracing-elastic-apm.
> docs: add tracing-elastic-apm to related crates

- tracing-appender/Cargo.toml
- tracing-appender/src/non_blocking.rs
- tracing-appender/src/rolling.rs
- tracing-appender/src/worker.rs
This backports a bunch of `tracing-appender` changes from v0.2.x.
This has all been approved already so I'll go ahead and merge it when CI passes.
> appender: backport a bunch of changes

- tracing-appender/CHANGELOG.md
- tracing-appender/Cargo.toml
- tracing-appender/README.md
- tracing-appender/src/lib.rs
Changed
- **non_blocking**: Updated `crossbeam-channel` dependency to 0.5
(#1031)
Fixed
- **non_blocking**: Fixed a race condition when logging on shutdown
(#1125)
- Several documentation improvements (#1109, #1110, #941, #953)
> appender: prepare to release v0.1.2

- examples/Cargo.toml
- examples/examples/opentelemetry-remote-context.rs
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/lib.rs
- tracing-opentelemetry/src/span_ext.rs
- tracing-opentelemetry/src/tracer.rs
- tracing-opentelemetry/tests/trace_state_propagation.rs
Support the latest OpenTelemetry specification
In order to support the latest spec, this patch makes the following breaking API changes:
* Update `opentelemetry` to 0.11.x
* Update `OpenTelemetrySpanExt::set_parent` to take a context by value as it is now stored and propagated.
* Rename `PreSampledTracer::sampled_span_context` to `PreSampledTracer::sampled_context` as it now returns a full otel context
Additionally the following doc and example changes:
* Show w3c trace context propagator as recommendation in examples
> opentelemetry: update to otel v0.11.x

- examples/Cargo.toml
- examples/examples/opentelemetry-remote-context.rs
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/lib.rs
- tracing-opentelemetry/src/span_ext.rs
- tracing-opentelemetry/src/tracer.rs
- tracing-opentelemetry/tests/trace_state_propagation.rs
> opentelemetry: Backport update to otel v0.11.x (#1161)

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
Changelog: 
- Upgrade to `v0.11.0` of `opentelemetry` (#1161)
For list of breaking changes in OpenTelemetry, see the [v0.11.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry/CHANGELOG.md#v0110).
- Update `OpenTelemetrySpanExt::set_parent` to take a context by value as it is now stored and propagated. (#1161)
- Rename `PreSampledTracer::sampled_span_context` to `PreSampledTracer::sampled_context` as it now returns a full otel context. (#1161)
> opentelemetry: prepare for v0.10.0 release

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
> opentelemetry: Backport prepare for v0.10.0 release (#1166)

- examples/Cargo.toml
- examples/README.md
- examples/examples/fmt-multiple-writers.rs
It turns out that this example never existed on v0.1.x, which is my bad.
Resolves https://github.com/tokio-rs/tracing/issues/1179.
> examples: backport `fmt-multiple-writers.rs` example to v0.1.0

- tracing-core/src/callsite.rs
- tracing-core/src/dispatch.rs
- tracing/tests/support/collector.rs
This branch fixes two known warnings.
The first fixed warning was in `tracing-core/src/callsite.rs`, where clippy suggested using `std::ptr::eq` to compare addresses instead of casting `&T` to a `*const T`, which `&T` coerces to _anyways_. Below is the warning:
```
error: use `std::ptr::eq` when comparing raw pointers
--> tracing-core/src/callsite.rs:238:9
|
238 |         self.0 as *const _ as *const () == other.0 as *const _ as *const ()
|         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: try: `std::ptr::eq(self.0 as *const _, other.0 as *const _)`
|
= note: `-D clippy::ptr-eq` implied by `-D warnings`
= help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#ptr_eq
```
The second fixed warning is a bit more complex. …
> chore: fix deprecation and clippy warnings

- examples/Cargo.toml
- tracing-opentelemetry/Cargo.toml
No additional changes needed to support the latest release, the changes on the otel side can be seen in [the changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/master/opentelemetry/CHANGELOG.md#v0120).
> opentelemetry: update to otel v0.12.x

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
Changelog:
- Upgrade to `v0.12.0` of `opentelemetry` (#1200)
For list of breaking changes in OpenTelemetry, see the [v0.12.0 changelog](https://github.com/open-telemetry/opentelemetry-rust/blob/main/opentelemetry/CHANGELOG.md#v0120).
> opentelemetry: prepare for v0.11.0 release

- tracing-core/src/callsite.rs
- tracing-core/src/dispatcher.rs
- tracing/tests/support/subscriber.rs
Backports #1195 to v0.1.x; unblocks #1205 and #1207.
> chore: backport "fix deprecation and clippy warnings"

- examples/Cargo.toml
- tracing-opentelemetry/Cargo.toml
> opentelemetry: Backport update to otel v0.12.x (#1200)

- tracing-opentelemetry/CHANGELOG.md
- tracing-opentelemetry/Cargo.toml
- tracing-opentelemetry/README.md
- tracing-opentelemetry/src/lib.rs
> opentelemetry: Backport prepare for v0.11.0 release (#1206)

- tracing/src/macros.rs
It was renamed everywhere in #1015, but until #1190 it wasn't possible to enter this macro branch. Now it fails with the following:
```
Compiling tracing v0.2.0 (/Users/ivan/projects/tracing/tracing)
error[E0433]: failed to resolve: maybe a missing crate `dispatcher`?
--> /Users/ivan/projects/tracing/tracing/src/macros.rs:2351:21
|
2351 |           if !$crate::dispatcher::has_been_set() {
|                       ^^^^^^^^^^ maybe a missing crate `dispatcher`?
```
> tracing: rename the last dispatch -> dispatcher

- tracing-macros/Cargo.toml
- tracing-macros/examples/factorial.rs
factorial dbg! example doesn't produce any stdout & is referencing tracing 0.1 crate
update to path reference & set fmt max level DEBUG:
```
$ cargo run --example factorial
Jan 10 21:17:47.574 DEBUG factorial: n <= 1 value=false
Jan 10 21:17:47.575 DEBUG factorial: n <= 1 value=false
...
```
> examples: tracing-macros - updates factorial example to tracing 0.2

- tracing/src/level_filters.rs
- tracing/src/macros.rs
- tracing/src/span.rs
Currently, when the `log` feature is enabled but the `log-always`
feature is not, we check the (dynamic, but inexpensive)
`dispatch::has_been_set` variable **before** checking if the event's
level would be enabled by `log`'s static max level features.
Although this check is not terribly costly in terms of performance, it
*does* result in code being generated even when the `log` crate disables
some levels statically. This means that we will always generate *some*
code when the `log` feature is disabled. This isn't ideal --- the static
max level features should result in us generating *no* code whatsoever
for disabled trace points.
This commit moves the static max level check outside of the dispatch
check. Now, we should generate 0 bytes of assembly when both `log` and
`tracing` disable an …
> tracing: check `log` max level prior to dispatch check

- tracing-subscriber/src/fmt/format/mod.rs
I recently had to write a custom `FormatEvent` implementation. Most things were straight forward but I struggled with how to print the values of fields on the span. Through the context you can get `SpanRef`s but those don't include field values, only field names. I had to dig around in the code to discover `FormattedFields` which made things easy. I think an example implementation in the docs would be helpful to others.
A sample implementation of `FormatEvent` in the docs that prints level, span name and fields, and event.
> Add sample implementation of `FormatEvent`

- README.md
- tracing-error/Cargo.toml
- tracing-flame/Cargo.toml
- tracing-futures/Cargo.toml
- tracing-opentelemetry/Cargo.toml
- tracing-subscriber/Cargo.toml
- tracing-subscriber/src/fmt/format/mod.rs
- tracing-tower/Cargo.toml
- tracing/src/level_filters.rs
- tracing/src/lib.rs
- tracing/src/macros.rs
- tracing/src/span.rs
This backports several changes from `master` to `v0.1.x`:
* 3b020ea2 chore(deps): update pin-project requirement from 0.4 to 1.0 (#1038)
* a0e9275a Add sample implementation of `FormatEvent` (#1189)
* e038d561 tracing: check `log` max level prior to dispatch check (#1175)
* ab631219 docs: add tracing-elastic-apm to related crates (#1146)
* cd7561e3 chore: disable default features of tracing dependencies (#1144)
Since these have all been approved on master, I'm going to just go ahead
and merge this when CI passes.
> chore: big pile of backports

- tracing-appender/Cargo.toml
- tracing-subscriber/Cargo.toml
- this allows dropping the old time 0.1 dependency (see https://github.com/chronotope/chrono/blob/main/CHANGELOG.md#0416)
Transitive dependency reduction. Only 1 but they all count right?
Require Chrono 0.4.16 & set features to not include the 'oldtime' compatibility.
> chore(deps): update chrono dependency to 0.4.16

- tracing-appender/Cargo.toml
- tracing-subscriber/Cargo.toml
- this allows dropping the old time 0.1 dependency (see https://github.com/chronotope/chrono/blob/main/CHANGELOG.md#0416)
Co-authored-by: Eliza Weisman <eliza@buoyant.io>
> chore: backport #1173

- examples/Cargo.toml
- examples/examples/echo.rs
- examples/examples/futures-proxy-server.rs
- examples/examples/tower-load.rs
Not sure that there's a issue tracking this, but anyways. Here's an
update to Tokio 1.0!
This closes the various Dependabot dependency update PRs that we can't
just merge due to breaking changes.
Closes #1149
Closes #1164
Closes #1177
> examples: update Tokio to 1.0

- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/lib.rs
This patch resolves the field value capitalization ambiguity currently in `otel.kind` by instead recommending an enum value. This also brings type safety to the value, further reducing the risk of typos and other misuse.
Resolves #1209
> opentelemetry: clarify otel.kind field usage in docs

- tracing-attributes/src/lib.rs
The `tracing-attributes` documentation for `instrument` is out of date
and could use some improvement. In particular, it doesn't mention that
empty fields can be created in `instrument`'s `fields` argument, and
states that dotted fields are forbidden and that field values must be
literals, both of which are no longer the case. See also #1210 and
#1211.
This branch updates the docs to correct the false statements, and also
fleshes out the usage examples a bit.
I wasn't sure what to do with the old examples --- some of them are now
redundant, but it's also useful to have a big list of examples for every
allowed form. Any thoughts?
> attributes: update & improve docs

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/err.rs
The closure generated by `#[instrument(err)]` for non-async functions is
not mutable, preventing any captured variables from being mutated. If a
function has any mutable parameters that are modified within the
function, adding the `#[instrument(err)]` attribute will result in a
compiler error.
This change makes it so the closure is executed directly as a temporary
variable instead of storing it in a named variable prior to its use,
avoiding the need to explicitly declare it as mutable altogether or to
add an `#[allow(unused_mut)]` annotation on the closure declaration to
silence lint warnings for closures that do not need to be mutable.
> attributes: fix #[instrument(err)] with mutable parameters

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/err.rs
- tracing-opentelemetry/src/layer.rs
- tracing-opentelemetry/src/lib.rs
this backports #1218  and #1167 to v0.1.x
> more backports

- tracing-attributes/CHANGELOG.md
- tracing-attributes/Cargo.toml
- tracing-attributes/README.md
- tracing-attributes/src/lib.rs
- Compiler error when using `#[instrument(err)]` on functions with
mutable parameters ([#1167])
- Missing function visibility modifier when using `#[instrument]` with
`async-trait` ([#977])
- Multiple documentation fixes and improvements ([#965], [#981],
[#1215])
- `tracing-futures` dependency is no longer required when using
`#[instrument]` on async functions ([#808])
Thanks to @nagisa, @Txuritan, @TaKO8Ki, and @okready for contributing to
this release!
[#1167]: https://github.com/tokio-rs/tracing/pull/1167
[#977]: https://github.com/tokio-rs/tracing/pull/977
[#965]: https://github.com/tokio-rs/tracing/pull/965
[#981]: https://github.com/tokio-rs/tracing/pull/981
[#1215]: https://github.com/tokio-rs/tracing/pull/1215
[#808]: https://github.com/tokio-rs/tracing/pull/808
> attributes: prepare to release v0.1.12

- tracing/Cargo.toml
This branch updates the minimum `tracing-attributes` dependency from
v0.1.10 to v0.1.12. v0.1.12 includes a number of significant changes:
* Support for arbitrary field expressions in `#[instrument]` was added
in v0.1.11. This means that users who read the crates.io docs for
`tracing-attributes` will see that arbitrary field expressions are
permitted, but if `tracing` reexports an older version, this won't
actually work.
* v0.1.12 updates `#[instrument]` to use the `Instrumented` type from
`tracing` rather than from `tracing-futures`. This means async/await
will now work without an additional dependency on `tracing-futures`.
* Also, a few bugs were fixed in v0.1.11 and v0.1.12.
> tracing: update minimum `tracing-attributes` to 0.1.12

- tracing/CHANGELOG.md
- tracing/Cargo.toml
- tracing/README.md
- tracing/src/lib.rs
- **attributes**: Compiler error when using `#[instrument(err)]` on
functions with mutable parameters ([#1167])
- **attributes**: Missing function visibility modifier when using
`#[instrument]` with `async-trait` ([#977])
- **attributes** Removed unused `syn` features ([#928])
- **log**: Fixed an issue where the `tracing` macros would generate code
for events whose levels are disabled statically by the `log` crate's
`static_max_level_XXX` features ([#1175])
- Fixed deprecations and clippy lints ([#1195])
- Several documentation fixes and improvements ([#941], [#965], [#981],
[#1146], [#1215])
- **attributes**: `tracing-futures` dependency is no longer required
when using `#[instrument]` on async functions ([#808])
- **attributes**: Updated `tracing-attributes` minimum dependency to …
> tracing: prepare to release v0.1.23

- tracing/CHANGELOG.md
The `:` breaks the last three links in the changelog
> tracing: fix some links in changelog

- tracing/src/macros.rs
Line [747 to 753](https://github.com/tokio-rs/tracing/blob/70ee64a96f84b90fb50aaf4a44af241df5ce284e/tracing/src/macros.rs#L747-L753) is identical with line [754 to 760](https://github.com/tokio-rs/tracing/blob/70ee64a96f84b90fb50aaf4a44af241df5ce284e/tracing/src/macros.rs#L754-L760) in `tracing/src/macros.rs`. 
This PR simply removes one of the duplicated patterns.
> tracing: remove the duplicated pattern of event macro

- tracing-attributes/src/lib.rs
- tracing-attributes/tests/err.rs
- tracing-attributes/tests/instrument.rs
Currently, using `#[instrument(err)]` on a function returning a `Result`
with an `impl Trait` in it results in a compiler error. This is because
we generate a type annotation on the closure in the function body that
contains the user function's actual body, and `impl Trait` isn't allowed
on types in local bindings, only on function parameters and return
types.
This branch fixes the issue by simply removing the return type
annotation from the closure. I've also added tests that break on master
for functions returning `impl Trait`, both with and without the `err`
argument.
Fixes #1227
> attributes: remove closure type annotation in `#[instrument(err)]`
