tokio-trace-fmt/src/default.rs
tokio-trace-fmt/src/filter.rs
tokio-trace-fmt/src/lib.rs
tokio-trace-fmt/src/span.rs

This adds the ability to pass a `NewVisitor` to record events. I've verified this works with my custom visitor.

fmt: Add new_visitor to span::Context

---

Cargo.toml
tokio-trace-env-logger/Cargo.toml
tokio-trace-fmt/Cargo.toml
tokio-trace-futures/Cargo.toml
tokio-trace-log/Cargo.toml
tokio-trace-macros/Cargo.toml
tokio-trace-proc-macros/Cargo.toml
tokio-trace-slog/Cargo.toml
tokio-trace-subscriber/Cargo.toml
tokio-trace-tower-http/Cargo.toml
tokio-trace-tower/Cargo.toml

chore: Remove problematic cargo patches

---

tokio-trace-serde/Cargo.toml
tokio-trace-serde/README.md
tokio-trace-serde/examples/serde_shaved_yak.rs

This PR adds a README and an example to the `tokio-trace-serde` crate.

Add an example and README

---

tokio-trace-fmt/src/filter/env.rs

It can sometimes be useful to display the current state of a trace
filter, such as when debugging the filter, or if the filter can change
dynamically. In these cases, it may be necessary to record the filter's
state textually.
This branch adds a `fmt::Display` implementation to `filter::EnvFilter`.
`EnvFilter`s are formatted in the same form they are specified in.

fmt: add fmt::Display impls for EnvFilter

---

tracing-fmt/src/filter/reload.rs

The `reload_handle` test in `tracing-fmt` is flakey. This is because
reloading a filter now triggers a callsite registry rebuild; and using
functions as filters means that the call counters are incremented when
the registry is rebuilt.
This branch replaces the functions with an enum implementing `Filter`,
which doesn't increment the call counters when `register_callsite` is
called. This should make the tests no longer be flakey.

fmt: fix flakey test

---

tracing-core/src/field.rs
tracing-core/src/subscriber.rs
tracing-fmt/src/filter/env.rs

This fixes some of the clippy warnings.

Clippy fixes

---

tracing-serde/Cargo.toml
tracing-serde/examples/serde_shaved_yak.rs

This addresses a TODO in the `Cargo.toml`.

tracing-serde: Use path deps to tracing-core and tracing.

---

CONTRIBUTING.md
tracing-core/src/subscriber.rs
tracing-core/tests/macros.rs
tracing/examples/sloggish/main.rs
tracing/examples/sloggish/sloggish_subscriber.rs
tracing/tests/filter_caching_is_lexically_scoped.rs
tracing/tests/filters_are_not_reevaluated_for_the_same_span.rs
tracing/tests/filters_are_reevaluated_for_different_call_sites.rs
tracing/tests/macros.rs

Fix typos.

---

tracing-env-logger/Cargo.toml
tracing-fmt/Cargo.toml
tracing-futures/Cargo.toml
tracing-proc-macros/Cargo.toml
tracing-tower-http/Cargo.toml
tracing-tower/Cargo.toml

fmt,futures,tower,tower-http: Use crates.io instead of local path deps

---

tracing-proc-macros/src/lib.rs

proc-macors: fix recursion bug from extra comma

---

tracing-core/src/metadata.rs

As mentioned in #189, having a `FromStr` implementation for `Level` could be useful for various cases (the first one being level parsing for `fmt` filters).
We will be able to use it in the filter parser once it is released, with something like:
```rust
fn parse_level(from: &str) -> Option<LevelFilter> {
from.parse::<Level>()
.ok()
.map(LevelFilter::Level)
.or_else(|| match from {
// Handle special values that are not levels but make sense as filters
"0" | "off" => Some(LevelFilter::Off),
"" => Some(LevelFilter::Level(Level::ERROR)),
_ => None,
})
}
```

Add a FromStr implementation for Level

---

tracing-fmt/Cargo.toml
tracing-fmt/README.md

fmt: Prepare 0.0.1-alpha.1 release

---

tracing-proc-macros/src/lib.rs

remove `traced_function`

---

tracing-futures/src/executor.rs

The `tokio::executor::TypedExecutor` trait is not implemented for the
`tracing_futures::Instrumented` and `tracing_futures::WithDispatch`
types wrapping executors. This branch adds implementations of
`TypedExecutor` for those types when the `tokio` feature flag is
enabled.

futures: add `TypedExecutor` impls

---

tracing-subscriber/tests/field_filter.rs

This adds a test that when a field value is recorded after a span is
created, and the new value changes the filter level for the span, the
filter updates accordingly.

subscriber: add filter test for recording after creation

---

tracing-subscriber/Cargo.toml
tracing-subscriber/src/filter/directive.rs
tracing-subscriber/src/filter/field.rs
tracing-subscriber/src/filter/level.rs
tracing-subscriber/src/filter/mod.rs
tracing-subscriber/src/layer.rs
tracing-subscriber/src/lib.rs
tracing-subscriber/src/reload.rs

Prepare a 0.0.1-alpha.2 release with the changes in #223. Let me know if I should bundle any other changes.

subscriber: prepare 0.0.1-alpha.2 release

---

tracing/Cargo.toml
tracing/src/lib.rs

tracing: add `tracing-attributes` re-export

---

README.md

docs: link to published crates in readme

---

tracing-tower/examples/load.rs

This commit tweaks the `tracing-tower` load-generator example a little
to better simulate a real application under load. In particular, there
are now three load generators rather than a single one, and there is a
small amount of random jitter to when each load generator sends a
request. This has the effect of making events more likely to be
interleaved, so filtering becomes much more necessary.

tower: make the load generator example more fun

---

.github/workflows/CI.yml

this adds a rough CI action. I'm going to merge this because it might fix the other actions; we can delete it later
please ignore this

[WIP] start experimenting with github actions

---

tracing-core/src/event.rs

Now that `tracing-subscriber` supports `Layer`ing subscribers, there is
a compelling use-case for constructing events without immediately
dispatching them to the default subscriber. In particular, this can be
used by a layer that aggregates or rolls up events and forwards those
aggregates to the root subscriber.
This branch adds `new` and `new_child_of` functions to `Event`.
Fixes: #90 

core: allow manually constructing events

---

tracing-subscriber/src/layer.rs

In some cases, `Layer` implementations may wish to trigger new events on
the inner subscriber. Potential use cases include layers that aggregate
or roll up events. Now that PR #281 allows events to be constructed
without implicitly dispatching them to a `Subscriber`, we can add
support for this to the `Layer` trait.
This commit adds a `Context::event` method to the `layer::Context` type
in `tracing-subscriber`. This takes an `&Event` and calls
`Subscriber::event` on the wrapped subscriber.

subscriber: add function to send an event to the inner subscriber

---

tracing-fmt/Cargo.toml

Usage of `tracing-fmt` with `tokio` 0.2 results in duplicate dependencies because of mismatched versions of `parking_lot`.
Update `parking_lot` to 0.9, the latest version and the version used by `tokio`.

fmt: update parking_lot

---

tracing-subscriber/Cargo.toml
tracing-subscriber/src/fmt/writer.rs
tracing-subscriber/src/lib.rs

subscriber: prepare to release 0.0.1-alpha.4

---

tracing-subscriber/src/fmt/span.rs

The `tracing-subscriber` `FmtSubscriber` currently has a subtle bug in
span reference counting that prevents spans from ever closing. The
`clone_span` function, which is supposed to increment a span's reference
count, actually _decrements_ it. Because we detect that a span has
closed when the reference count is _equal to_ 1, we don't free these
spans with inconsistent reference counts; instead, the reference count
overflows and the span is then never closed.
This branch fixes the bug by turning the incorrect `fetch_sub` into a
`fetch_add`, like it's supposed to be.
This is difficult to write tests for, since we don't currently expose
any way for an external component to be notified that a `FmtSubscriber`
has closed a span; but I've added some additional debug assertions that
catch …

subscriber: fix incorrect reference counting in fmt

---

tracing-subscriber/src/fmt/format.rs
tracing-subscriber/src/fmt/mod.rs
tracing-subscriber/src/fmt/time.rs

Resolves https://github.com/tokio-rs/tracing/issues/379

Add ChronoUtc and ChronoLocal timers

---

examples/README.md
examples/examples/attrs-basic.rs
nightly-examples/examples/echo.rs
nightly-examples/examples/proxy_server.rs
tracing-log/src/lib.rs
tracing-subscriber/src/field/debug.rs
tracing-subscriber/src/field/display.rs
tracing-subscriber/src/filter/env/mod.rs
tracing-subscriber/src/layer.rs
tracing-subscriber/src/reload.rs
tracing/src/lib.rs
tracing/src/macros.rs
tracing/src/span.rs
tracing/tests/macros.rs

Really excited to see this project progressing! Thought I'd fix a few small typos as I was reading through it ❤️

Fix small typos

---

tracing/src/span.rs

tracing: fix incorrect `follows_from` bounds

---

tracing-attributes/README.md
tracing-attributes/src/lib.rs
tracing-core/README.md
tracing-core/src/lib.rs
tracing-serde/README.md
tracing-subscriber/src/fmt/mod.rs
tracing/README.md
tracing/src/level_filters.rs
tracing/src/lib.rs

tracing: document MSRV in README / rustdocs

---

tracing-attributes/CHANGELOG.md
tracing-attributes/Cargo.toml
tracing-attributes/README.md
tracing-attributes/src/lib.rs

Added
-  Updated documentation (#468)

attributes: prepare to release 0.1.6

---

tracing-subscriber/src/fmt/fmt_layer.rs
tracing-subscriber/src/fmt/mod.rs

Add examples for layers

---

tracing-core/src/dispatcher.rs

With this change we replace DefaultGuard's drop implementation with a
version that no longer drops the previous dispatch object while the
comprising RefCell is borrowed mutably. In issue #521 we have seen how
this can back fire and result in a panic.
This patch is based on a suggestion by @hawkw (thanks for the quick
feedback!).
Fixes: #521

core: drop dispatch object outside of mutable borrow section

---

tracing-subscriber/src/registry/sharded.rs

This branch updates the `tracing-subscriber` tests for
span closure and removal from the registry. The test layer
used to make assertions about close orders is made more
flexible, so we can write more tests in the future, and the
tests are now a bit simpler.

subscriber: nicer assertions for span close tests

---

tracing-core/src/dispatcher.rs
tracing-core/src/field.rs
tracing-core/src/metadata.rs
tracing-futures/src/lib.rs

Get the last bits of tracing-core

---

tracing-futures/src/lib.rs
tracing-subscriber/src/filter/env/mod.rs
tracing-subscriber/src/filter/mod.rs
tracing-subscriber/src/fmt/fmt_layer.rs
tracing-subscriber/src/fmt/format/mod.rs
tracing-subscriber/src/fmt/mod.rs
tracing-subscriber/src/fmt/time.rs
tracing-subscriber/src/layer.rs
tracing-subscriber/src/lib.rs

I thought this branch was merged to master in #525, but it turns out that PR was actually against my branch. Whoops!

docs: finish doc_cfg for tracing-futures and tracing-subscriber (#525)

---

.github/workflows/CI.yml

ci: fix CI builds not running on PRs

---

tracing-subscriber/src/fmt/fmt_layer.rs

This fixes two bugs. One where the formatted fields were incorrectly parameterized over Self instead of the formatter that generated the formatted fields. The second bug is to check if another layer has already inserted formatted fields and to avoid inserting if so, which would cause a panic.

subscriber: fix incorrect use of `FormattedFields` extension in fmt layer

---

tracing-serde/CHANGELOG.md
tracing-serde/Cargo.toml
tracing-serde/README.md
tracing-subscriber/Cargo.toml

blocked by #599
Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

serde: Prepare `0.1.1` release

---

README.md
examples/Cargo.toml
tracing-error/Cargo.toml
tracing-error/src/layer.rs
tracing-subscriber/CHANGELOG.md
tracing-subscriber/Cargo.toml
tracing-subscriber/README.md
tracing-subscriber/src/lib.rs

Requires a `tracing-serde` release as well.
Signed-off-by: Lucio Franco <luciofranco14@gmail.com>

subscriber: Prepare `0.2.2` release

---

tracing/src/span.rs

Just a quick fix to your docs :)

Remove "describing" since it's unnecessary.

---

tracing-appender/README.md
tracing-appender/src/lib.rs
tracing-appender/src/non_blocking.rs
tracing-appender/src/rolling.rs

Add top level docs for tracing appender

---

README.md
tracing/README.md
tracing/src/lib.rs

update to add/fix links for my related crates per https://twitter.com/mycoliza/status/1255672523426951170

update related crates to include tracing-distributed

---

README.md
tracing/src/lib.rs

Add tracing-appender to Project Layout section.

Add tracing-appender to project layout list in README

---

tracing/src/lib.rs

Fix tiny typo

---

tracing-subscriber/Cargo.toml

Cleans up some duplication in my dependency graph.

Update to latest parking_lot

---

tracing-subscriber/src/layer.rs

Test error message was incorrect.
This PR makes a 1-character change to a test error message.

subscriber: fix layer test error message

---

tracing-macros/examples/factorial.rs

fix compilation

---

.github/CODEOWNERS

Adding myself to contributors list so I get tagged on tracing-appender PRs
Update CODEOWNERS file

Add @zekisherif to codeowners for tracing-appender

---

README.md
tracing/src/lib.rs

From the readme
> (if you're the maintainer of a tracing ecosystem crate not in this list, please let us know!)
Added link to tide-tracing on readme and doc comment.

docs: Add tide-tracing to "Related Crates"

---

README.md
tracing/src/lib.rs

I'd like to get more feedback on our [`tracing-wasm` crate](https://crates.io/crates/tracing-wasm), as well as improve its discoverability.
Add a link to the crate to the "Related Crates" section of the readme file.

readme: Add tracing-wasm to "Related Crates"

---

README.md

Example code in README was missing a semicolon.
Added semicolon 😛

Fix small code issue in README

---

README.md

Fix install global subscriber example in README.md

---

tracing/src/lib.rs

This seems extraneous.
If I should fix this in some other way, please let me know!

Fix documentation

---

tracing/README.md

Hello, thanks for the awesome lib ecosystem! :D
I was reading the initial documentation on https://crates.io/crates/tracing and one of the sections was duplicated.

remove duplicated section from README.md

---

examples/Cargo.toml
examples/examples/opentelemetry-remote-context.rs
examples/examples/opentelemetry.rs
tracing-opentelemetry/Cargo.toml
tracing-opentelemetry/README.md
tracing-opentelemetry/src/layer.rs
tracing-opentelemetry/src/lib.rs
tracing-opentelemetry/src/span_ext.rs
tracing-opentelemetry/src/tracer.rs

opentelemetry: Backport update to latest otel release version

---

tracing-subscriber/src/registry/sharded.rs

It's a typo in docs.
Replacing  `whicb` with `which`.

docs: fix typo in document

---

.github/CODEOWNERS

chore: add @carllerche as a tracing-core owner

---

.github/CODEOWNERS

Feel free to close this, but I'm happy to be an additional assigned reviewer.

chore: add @davidbarsky as a backup reviewer

---

.github/workflows/CI.yml
tracing/Cargo.toml

https://github.com/tokio-rs/tracing/blob/e3bd8af3ce0090922b5d9795cc5e33083246fc93/tracing/Cargo.toml#L65-L66
Context: #264

tracing: remove async-await feature

---

tracing/src/macros.rs

It happened again: https://github.com/tokio-rs/tracing/pull/1175/files#r566572698

tracing: rename new dispatcher -> dispatch

---

tracing-subscriber/src/fmt/mod.rs
tracing-subscriber/src/registry/extensions.rs
tracing-subscriber/src/subscribe.rs

This PR fixes some typos and trivial issues.

chore: fix some trivial typos

---

examples/examples/async-fn.rs
examples/examples/futures-proxy-server.rs

Fixes some comments in the tracing examples, making it easier to copy/paste into a terminal.

[skip ci] fix some comments in the examples

---

tracing-subscriber/src/fmt/format/json.rs

Fix typo in tracing-subscriber Json doc

---

examples/examples/attrs-args.rs
examples/examples/attrs-basic.rs
examples/examples/attrs-literal-field-names.rs
examples/examples/fmt-stderr.rs
examples/examples/futures-proxy-server.rs
examples/examples/hyper-echo.rs
examples/examples/inferno-flame.rs
examples/examples/serde-yak-shave.rs
examples/examples/sloggish/main.rs
examples/examples/sloggish/sloggish_collector.rs
examples/examples/subscriber-filter.rs

Yeah, another renaming PR. Hahaha ^-^

examples: rename the rest legacy `subscriber`s to `collector`s

---

examples/Cargo.toml
examples/examples/opentelemetry.rs
tracing-opentelemetry/Cargo.toml
tracing-opentelemetry/src/layer.rs
tracing-opentelemetry/src/lib.rs
tracing-opentelemetry/src/tracer.rs

Backports https://github.com/tokio-rs/tracing/pull/1322 to the v0.1.X branch.

Backport jtescher/update-otel to v0.1.X

---

tracing-subscriber/src/subscribe.rs

chore: fix lints for testings

---

tracing-flame/README.md

Fix a typo in the README code sample.

---

examples/Cargo.toml
tracing-opentelemetry/Cargo.toml
tracing-opentelemetry/src/layer.rs
tracing-opentelemetry/src/span_ext.rs
tracing-opentelemetry/src/tracer.rs
tracing-opentelemetry/tests/trace_state_propagation.rs

Backport #1394 in to `v0.1.x` branch

opentelemetry: backport update to otel 0.14.x

---

tracing-subscriber/src/subscribe.rs

This PR:
- Rename `Context`'s field `subscriber` to `collector`.
- Make the `Clone` implementation for `Context` more idiomatic.

subscriber: rename Context's field `subscriber` to `collector`

---

examples/examples/sloggish/sloggish_collector.rs
tracing-core/src/metadata.rs
tracing-subscriber/src/filter/env/mod.rs
tracing-subscriber/src/filter/level.rs
tracing-subscriber/src/fmt/format/mod.rs

This fixes a handful of new clippy lints. Should fix CI.

chore: fix new clippy warnings

---

examples/examples/tower-load.rs
tracing-appender/src/worker.rs
tracing-attributes/tests/fields.rs
tracing-core/src/dispatcher.rs
tracing-core/src/field.rs
tracing-core/src/span.rs
tracing-flame/src/lib.rs
tracing-log/src/trace_logger.rs
tracing-opentelemetry/src/tracer.rs
tracing-subscriber/src/field/mod.rs
tracing-subscriber/src/filter/env/directive.rs
tracing-subscriber/src/filter/env/mod.rs
tracing-subscriber/src/fmt/format/json.rs
tracing-subscriber/src/fmt/format/mod.rs
tracing-subscriber/src/fmt/format/pretty.rs
tracing-subscriber/src/layer.rs
tracing-subscriber/src/lib.rs
tracing-subscriber/src/registry/mod.rs
tracing-subscriber/src/registry/sharded.rs
tracing-subscriber/src/sync.rs
tracing/src/lib.rs
tracing/src/span.rs

Fix warnings introduced by Rustc 1.54

---

README.md

docs: fixup rust meetup date

---

examples/Cargo.toml
tracing-opentelemetry/Cargo.toml
tracing-opentelemetry/benches/trace.rs
tracing-opentelemetry/src/layer.rs
tracing-opentelemetry/src/tracer.rs
tracing-opentelemetry/tests/trace_state_propagation.rs

opentelemetry: backport update to otel v0.16.x

---

tracing-subscriber/src/registry/mod.rs
tracing-subscriber/src/subscribe.rs
tracing-subscriber/tests/duplicate_spans.rs
tracing-subscriber/tests/field_filter.rs
tracing-subscriber/tests/filter.rs
tracing-subscriber/tests/filter_log.rs
tracing-subscriber/tests/fmt_max_level_hint.rs
tracing-subscriber/tests/registry_max_level_hint.rs
tracing-subscriber/tests/registry_with_subscriber.rs
tracing-subscriber/tests/reload.rs
tracing-subscriber/tests/reload_max_log_level.rs
tracing-subscriber/tests/same_len_filters.rs
tracing-subscriber/tests/utils.rs

chore: port #1532 to master

---

tracing-core/src/subscriber.rs
tracing-subscriber/src/fmt/writer.rs
tracing-subscriber/src/layer/tests.rs
tracing/src/lib.rs
tracing/src/span.rs

Cleanups 0.1.x

---

examples/Cargo.toml
tracing-appender/Cargo.toml
tracing-attributes/Cargo.toml
tracing-core/Cargo.toml
tracing-error/Cargo.toml
tracing-flame/Cargo.toml
tracing-futures/Cargo.toml
tracing-journald/Cargo.toml
tracing-log/Cargo.toml
tracing-macros/Cargo.toml
tracing-opentelemetry/Cargo.toml
tracing-serde/Cargo.toml
tracing-subscriber/Cargo.toml
tracing-subscriber/src/fmt/fmt_layer.rs
tracing-subscriber/src/fmt/format/mod.rs
tracing-subscriber/src/fmt/format/pretty.rs
tracing-subscriber/src/fmt/mod.rs
tracing-subscriber/src/fmt/time/datetime.rs
tracing-subscriber/src/fmt/time/time_crate.rs
tracing-subscriber/src/lib.rs
tracing-tower/Cargo.toml
tracing/Cargo.toml

pile of tracing-subscriber packborts

---

examples/Cargo.toml
tracing-appender/Cargo.toml
tracing-attributes/Cargo.toml
tracing-core/Cargo.toml
tracing-error/Cargo.toml
tracing-flame/Cargo.toml
tracing-futures/Cargo.toml
tracing-journald/Cargo.toml
tracing-log/Cargo.toml
tracing-macros/Cargo.toml
tracing-opentelemetry/Cargo.toml
tracing-serde/Cargo.toml
tracing-subscriber/Cargo.toml
tracing-tower/Cargo.toml
tracing/Cargo.toml

backport #1742

---

tracing-subscriber/src/fmt/format/pretty.rs

chore: backport #1747

---

tracing-appender/README.md

Small mistake in README

---

tracing-opentelemetry/src/span_ext.rs

chore: Backport #1770

---

.github/workflows/release.yml

It is currently failing: https://github.com/tokio-rs/tracing/runs/4622678819?check_suite_focus=true
See also: https://github.com/tokio-rs/tracing/pull/1795#discussion_r775153856

chore(CI): fix release workflow

---

netlify.toml
tracing-appender/src/rolling.rs
tracing-core/src/collect.rs
tracing-subscriber/src/fmt/fmt_subscriber.rs
tracing/src/lib.rs

This fixes a bunch of broken documentation links

debreak various docs links

---

README.md
examples/README.md
examples/examples/fmt-source-locations.rs
tracing-journald/src/lib.rs
tracing-subscriber/src/fmt/fmt_layer.rs
tracing-subscriber/src/fmt/format/json.rs
tracing-subscriber/src/fmt/format/mod.rs
tracing-subscriber/src/fmt/format/pretty.rs
tracing-subscriber/src/fmt/mod.rs
tracing/README.md

this backports a few things from master to v0.1.x

backport changes from master

---

tracing-opentelemetry/src/layer.rs

this backports #1917 and #1911 from master

backport tracing-otel changes

---

tracing-appender/README.md

Found a typo as code didn't work as is.
Fixed the typo :)

Fixed typo in tracing-appender README

---

tracing-appender/src/rolling.rs

This branch backports #1989. Once merged, I'll create a release PR to fix it.

chore: backport #1989

---

tracing/Cargo.toml
tracing/src/span.rs

Remove unused dev-dependencies

chore: remove unused dev-dependencies

---

tracing-appender/README.md

update version of tracing appender in docs.

update tracing appender readme

---

tracing-subscriber/src/fmt/fmt_layer.rs
tracing-subscriber/src/fmt/format/mod.rs
tracing-subscriber/src/fmt/mod.rs

chore: backport 2126

---

tracing-attributes/Cargo.toml
tracing-attributes/src/expand.rs
tracing-attributes/src/lib.rs
tracing-attributes/tests/err.rs
tracing-attributes/tests/ret.rs
tracing-subscriber/src/layer/mod.rs
tracing-subscriber/tests/layer_filters/vec.rs
tracing-subscriber/tests/option.rs
tracing-subscriber/tests/vec.rs

this backports tracing-subscriber bugfixes from `master`

backport tracing-subscriber fixes

---

tracing/README.md

When a user clicks they they may accidentally get an old version of the crate. Its also out of sync with the current main readme.
removed the hard coded links

Readme remove hard coded version link

---

README.md
tracing/src/lib.rs

Add [tracing-cloudwatch](https://crates.io/crates/tracing-cloudwatch) crate to the list of related crates.

tracing: add tracing-cloudwatch to related crates in README

---

README.md

As invited in https://twitter.com/mycoliza/status/1689341745572753409
Added links to article and talk. :)

Add article and talk by hoverbear

---

README.md
tracing/README.md
tracing/src/lib.rs

Adding a relevant library to the list of `tracing`-enabled crates.
Added to READMEs and documentation.

Add `axum-insights` to relevant crates.

---

tracing-core/src/callsite.rs

This should fix the CI in #2751.

docs: remove mention of `Registration` on v0.1.x

---

tracing-log/Cargo.toml

Backporting #2750, see that PR for details.

chore: backport #2750

---

README.md

This also has to be backported to v0.1.x!
Fixes:  #3140

docs: update README.md docs link

---

tracing-subscriber/src/filter/env/mod.rs
tracing-subscriber/src/sync.rs

Reopening #2956 against the `main` branch. See https://github.com/tokio-rs/tracing/pull/2956#issuecomment-3189825307

subscriber: impl Clone for EnvFilter
